### ISSUE TITLE
jx preview - Values for depending chart are not used?

### ISSUE THREAD

**Issue by beerkeeper** [jenkins-x/jx#1069]
I'm trying to make a PR environment for a Spring Boot application with a MariaDB next to it.
The spinning up of it works and it waits nicely for the pods to be ready, and the application runs.

Though, MariaDB helm chart runs defaultly in replication mode and with persistent volumes. See https://github.com/kubernetes/charts/tree/master/stable/mariadb .
You can specify values to disable replication mode, remove the persistent storage and other options which are nice for the PR environment.

In my testproject, I have specified the values in charts/preview/values.yaml to disable replication mode and disabled persistent storage.

```
values.yaml

replication:
  enabled: false

slave:
  replicas: 0
  persistence:
    enabled: false

master:
  persistence:
    enabled: false
```

But this isn't picked up when deploying the new PR environment.

```
requirements.yaml

dependencies:
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.56
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.56
- alias: project-name-mariadb
  name: mariadb
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 4.2.2
- alias: preview
  name: project-name
  repository: file://../project-name
```

It runs the command
```
[preview] Running shell script
+ jx preview --app project-name --dir ../..
```
And I think this command doesn't use the values.yaml.
Am I correct? And is there a way to fix this?

**Comment by ccojocar** [comment]
@beerkeeper Are these values for `mariadb` chart? Do you place them in the preview of the spring boot project? I think you should reference them when you deploy the `mariadb` chart in order to be effective.

**Comment by rawlingsj** [comment]
yeah when using composable helm charts you need to provide the chartname or alias in the values.yaml so helm knows which chart to apply them to.  I.e. in your `charts/preview/values.yaml ` use:

```
project-name-mariadb:
  replication:
  enabled: false

  slave:
  replicas: 0
  persistence:
      enabled: false

  master:
  persistence:
      enabled: false
```
