### ISSUE TITLE
Supporting values folder in default environment git repo

### ISSUE THREAD

**Issue by ysaakpr** [jenkins-x/jx#1105]
Jenkins X is a fantastic product in the CI CD world. Great thanks for the contributors
@jstrachan

I would like to know what is the right way to tackle the environment configurations in the git ops way.

Basically I am having around 50 apps running n my environment and every application has a big config files to be applied differently for every env. If i start updating the values file...it becoming more than 3k lines of configuration in the values.yaml and which is difficult to manage.

How about building a seperate directory for all apps values overrides and in the build process of the env build the big yaml from the values sub folder and commit back to the env.

https://github.com/jenkins-x/default-environment-charts may include a directory named values as explained below.

```
values/
     - app1.yaml
     - expose.yaml
     - cleanup.yaml
     - mycustomapp.yaml
```

And in the process of build, we can Generate values.yaml by combining all of them

```
#values.yaml

GlobalValues: blahs

expose:
   expose: values

cleanup:
   cleanup: overrides

mycustomapp:
    ovirride: values.
```

I would like to know the best way to handle this and so that i can make changes.
