### ISSUE TITLE
jx should have its own context instead of changing local context

### ISSUE THREAD

**Issue by 123batman** [jenkins-x/jx#1129]
Hi
JenkinsX changed my kubectl local context to:

```
contexts:
- context:
    cluster: default-cluster
    namespace: jx
    user: default-admin
  name: local
current-context: local
```

Now kubectl tries to create everything in the jx namespace. This is quite unexpected because the documentation gave me the impression that jx's behavior is limited to the jx managed project-folders and not system-wide.
It should be made explicit and/or jx should have its own context instead of changing the local context.

I am not yet familiar with jx and might have missed something. What do you think?
