### ISSUE TITLE
Can the certificate for domain be manually modified and not just using certs for ingress.local?

### ISSUE THREAD

**Issue by isaron** [jenkins-x/jx#1153]
Hi, all.

I'm installing jx on local k8s cluster as this:
> jx install --provider='kubernetes' --default-admin-password='admin123' --domain='rdp.dev' --http='false' --tls-acme='true'

The install progress is all well. 

But i cannot browse the domains correctly. When i open `https://jenkins.jx.rdp.dev/blue`, the browser gives me the message: `Your connection is not secure`, and about the certificate:
> jenkins.jx.rdp.dev uses an invalid security certificate. 
The certificate is not trusted because it is self-signed. 
The certificate is only valid for **ingress.local**.

Before install jx, i have modified the DNS server with wildcard dns record for `*.jx.rdp.dev`.
> $ORIGIN jx.rdp.dev.
\*	IN	A	172.30.80.100

And the local k8s cluster has been deployed:
- k8s version: 1.10.5 (using kubeadm)
- storage: nfs (using nfs-client)
- lb: metallb
- cert-manager (using http01 challenge)
  - the issuer config:
> apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: kube-system
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: admin@rdp.dev
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    # Enable the HTTP-01 challenge provider
    http01: {}

  - the certificate config:
> apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: jx-ingress-certs
  namespace: jx
spec:
  secretName: jx-ingress-certs
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: jx.rdp.dev
  dnsNames:
  \- chartmuseum.jx.rdp.dev
  \- docker-registry.jx.rdp.dev
  \- gitea-gitea.jx.rdp.dev
  \- jenkins.jx.rdp.dev
  \- monocular.jx.rdp.dev
  \- nexus.jx.rdp.dev
  acme:
    config:
    \- http01:
        ingressClass: nginx
      domains:
      \- chartmuseum.jx.rdp.dev
      \- docker-registry.jx.rdp.dev
      \- gitea-gitea.jx.rdp.dev
      \- jenkins.jx.rdp.dev
      \- monocular.jx.rdp.dev
      \- nexus.jx.rdp.dev
    #- http01:
    #     ingress: chartmuseum
    #   domains:
    #   - chartmuseum.jx.rdp.dev
    # - http01:
    #     ingress: docker-registry
    #   domains:
    #   - docker-registry.jx.rdp.dev
    # - http01:
    #     ingress: gitea-gitea
    #   domains:
    #   - gitea-gitea.jx.rdp.dev
    # - http01:
    #     ingress: jenkins
    #   domains:
    #   - jenkins.jx.rdp.dev
    # - http01:
    #     ingress: monocular
    #   domains:
    #   - monocular.jx.rdp.dev
    # - http01:
    #     ingress: nexus
    #   domains:
    #   - nexus.jx.rdp.dev

Maybe i made the configs incorretly?
 
And, my questions are:
1.Can the certificate for domain be manually modified and not just using certs for ingress.local?
2.If can, how should i modify it?

Thanks you all.

**Comment by rawlingsj** [comment]
We should have this automated soon when we move to terraform (that's WIP right now).  But incase it helps this is what we've done on the Jenkins X own infra to setup TLS with signed certs using Certmanager...

```
helm install --name cert-manager --namespace kube-system stable/cert-manager --set rbac.create=false --set ingressShim.extraArgs='{--default-issuer-name=letsencrypt-staging,--default-issuer-kind=ClusterIssuer}'

apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme-v01.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: foo@acme.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    http01: {}

apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: foo@acme.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    # Enable the HTTP-01 challenge provider
    http01: {}

apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: jenkinsxio-cert
spec:
  secretName: tls-jx-jenkinsxio
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: foo.jenkins-x.io
  dnsNames:
  - foo.jenkins-x.io
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - foo.jenkins-x.io
```

**Comment by isaron** [comment]
@rawlingsj Thanks for your response.

I've try again with new config like you guided, but result as usual.

And `kubectl describe certificate jx-ingress-certs-acme -n jx` gives me:
```
Events:
  Type     Reason          Age                   From          Message
  ----     ------          ----                  ----          -------
  Warning  IssuerNotReady  39s (x1221 over 20h)  cert-manager  Issuer letsencrypt-staging not ready
```
I think the question is not from config files of cert-manager and issuers, but from other, such as domains?
The domains i deal with are all for INTRANET, not that like foo.jenkins-x.io.

So, i try to deploy cert-manager using its CA based issuer, and manually update ingress config, add annotations, add tls statement for related services. It works.

This issue could be closed.

Thank you all.

**Comment by rawlingsj** [comment]
Ok great, glad you got it working and thanks for explaining on this issue incase it helps others.

**Comment by isaron** [comment]
BTW i think it could not be the best solution.

Seems like Jenkins-X now support hosted cloud well then local cloud, like GKE/AWS etc. Could you have plan to open more options for local cloud, such as manually modifying domains, ingress annotations?
If i issue a new PR for more local cloud supporting options, which can i start first?

Thanks again.

**Comment by almerico** [comment]
> So, i try to deploy cert-manager using its CA based issuer, and manually update ingress config, add annotations, add tls statement for related services. It works.
Can you please add more details.

**Comment by rawlingsj** [comment]
We have a new CLI `jx upgrade ingress` which will hopefully be merged today which will regenerate ingress rules and optionally install certmanager + configure TLS.

**Comment by rawlingsj** [comment]
We only annotate services with the external URL. Are you asking if we can annotate the deployments too?  Just wondering what the usecase might be, if a deployment has multiple services we wouldn't know which external URL to add to deployment.

**Comment by isaron** [comment]
@almerico 

I do a patch for ingress like this:
```
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: ClusterIssuer
spec:
  tls:
  - hosts:
    - chartmuseum.jx.rdp.dev
    secretName: jx-ingress-certs
```
and cert-manager Certificate config:
```
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: jx-ingress-certs
  namespace: jx
spec:
  secretName: jx-ingress-certs
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  commonName: jx.rdp.dev
  dnsNames:
  - chartmuseum.jx.rdp.dev
```
cert-manager issuer config:
```
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: ca-issuer
spec:
  ca:
    secretName: ca-key-pair
```
Note: `.rdp.dev` is my internal domain.
