### ISSUE TITLE
jx create quickstart golang-http ImagePullBackOff error

### ISSUE THREAD

**Issue by shaicoleman** [jenkins-x/jx#1226]
When I run
`jx create quickstart --filter=golang-http --project-name=myprojectname --batch-mode`

The build gets stuck. Upon inspecting the pod, it tries to pull the image, but it doesn't seem to exist.
```
  containerStatuses:
    state:
      waiting:
        message: Back-off pulling image "jenkinsxio/builder-go:0.0.344"
        reason: ImagePullBackOff
```

Trying to do `docker pull jenkinsxio/builder-go:0.0.344` I get the following error:
`Error response from daemon: manifest for jenkinsxio/builder-go:0.0.344 not found`

Newer versions seem to work, e.g. `docker pull jenkinsxio/builder-go:0.0.347`, but I don't know how to make the build use the newer image.

Running on jx 1.3.69
