### ISSUE TITLE
Connect a new member to jx cluster

### ISSUE THREAD

**Issue by mordf** [jenkins-x/jx#1239]
Connect a new team member to the jx cluster (not GKE) by adding all the necessary certifications clusterrolebinding and etc.. to setup the kubectl to point to the jx cluster

JX Version 1.3.74

**Comment by gabeduke** [comment]
# Kops add user

Usage: 
1) First edit the user-rbac.yaml file to fill the correct permissions you would like to hand out
2) `chmod +x kops-user.sh && ./kops-user.sh [new-user]`

----

user-rbac.yaml
```yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: developer
  namespace: default
subjects:
  - kind: User
    name: %KUBEUSER%
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: kube-system
  name: user-role-dashboard
rules:
  - apiGroups: [""]
    resources:
      - services
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - services/proxy
    verbs: ["get", "list", "watch", "create"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: kube-system
  name: user-binding-dashboard
subjects:
- kind: User
  name: %KUBEUSER%
  apiGroup: ""
roleRef:
  kind: Role
  name: user-role-dashboard
  apiGroup: ""
````

kops-user.sh
```bash
#!/bin/bash

KUBEUSER=${1:-default-user}
DIR="${HOME}/.kube/${NAME}"
CONF="${KUBEUSER}-${NAME}.kubeconfig"
CONF_PATH="~/.kube/${CONF}"

mkdir -p ${DIR}/tmp && cd ${DIR}

sed -i /%KUBEUSER%/${KUBEUSER}/ user-rbac.yaml | kubectl apply -f -

pushd tmp

    # set certs
    aws s3 cp ${KOPS_STATE_STORE}/${NAME}/pki/private/ca . --recursive --include "*.ca"
    aws s3 cp ${KOPS_STATE_STORE}/${NAME}/pki/issued/ca . --recursive --include "*.ca"
    mv $(find . -name '*.crt' -print) ca.crt
    mv $(find . -name '*.key' -print) ca.key

    # generate client key
    openssl genrsa -out user.key 4096
    openssl req -new -key user.key -out user.csr -subj "/CN=${KUBEUSER}/O=cluster-admin"
    openssl x509 -req -in user.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out user.crt -days 365

    # gen kubeconfig for user
    KUBECONFIG=${CONF} \
        kops export kubecfg ${NAME}

    kubectl config \
        --kubeconfig=${CONF} \
        unset users

    kubectl config \
        --kubeconfig=${CONF} \
        --client-key=user.key \
        --client-certificate=user.crt \
        --embed-certs=true \
        set-credentials ${KUBEUSER} \

    kubectl config \
        --kubeconfig=${CONF} \
        set-context ${NAME} \
        --user ${KUBEUSER}

    kubectl config \
        --kubeconfig=${CONF} \
        use-context ${NAME}
popd

# cleanup
cp tmp/${CONF} . && rm -r tmp
```
