### ISSUE TITLE
setting up AWS wildcard DNS for an ELB?

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#1256]
We're super close to great EKS support in Jenkins X but we're stuck right now on setting up wildcard DNS on an AWS ELB so that:

`myapp.myns.elbid.us-west-2.elb.amazonaws.com` can map to the IP address of `dualstack.elbid.us-west-2.elb.amazonaws.com` so that it can be served up by an `Ingress` that points to the ELB along these lines:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
  name: jenkins
  namespace: jx
spec:
  rules:
  - host: jenkins.jx.elbid.us-west-2.elb.amazonaws.com
    http:
      paths:
      - backend:
          serviceName: jenkins
          servicePort: 8080
```

So far I've tried creating an A or CNAME of `*` on the ELB host name using Alias `Yes` - then when that failed, with `No` and could never `nslookup / dig` any wildcard DNS names (e.g. looking up `foo.elbid.us-west-2.elb.amazonaws.com` or `foo.bar.elbid.us-west-2.elb.amazonaws.com`)

There must be some way to do this - anyone know how?

As a fallback we could switch to using path based ingress; so using host `elbid.us-west-2.elb.amazonaws.com` and then specifying a path in each `Ingress` resource - the downside is this then means every microservice deployed in kubernetes typically needs custom configuration to specify the path its deployed within - which adds lots of complexity and generally breaks most apps OOTB without lots of manual tweaks which would make AWS a much worse place to develop on k8s than AKS / GKE
