### ISSUE TITLE
How to pass value to helm 

### ISSUE THREAD

**Issue by iamonkara** [jenkins-x/jx#1667]
Is there any way to override helm chart `values.yaml` when promoting a build? 

e.g. in dev environment I want to pass

`--set env.rails=development`
and in production
`--set env.rails=production`

I don't see `jx promote` or `jx environment` supporting any `--set` options and `jx options` returns nothing
```
~|⇒ jx options 
~|⇒ 
~|⇒ jx version
NAME               VERSION
jx                 1.3.260
jenkins x platform 0.0.2328
kubernetes cluster v1.10.3
kubectl            v1.11.3
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 2.17.1
```
the following piece of code means addOns can accept `--set` arguments, but that's not the same thing as `jx promote` or `jx environment`

https://github.com/jenkins-x/jx/blob/d85e2cb4366f94f72b2839183a3a2550a3ff004d/pkg/helm/helm.go#L31

Any ideas?

**Comment by jstrachan** [comment]
the `env/values.yaml` file in each environments git repository can be used to override any helm values.
https://github.com/jenkins-x/default-environment-charts/blob/master/env/values.yaml

**Comment by duffn** [comment]
I cannot get this to work as described.

Sample `deployment.yaml` file.

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "fullname" . }}
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
{{/*
Here's the section in question.
*/}}
{{- if .Values.env }}
        env:
{{- if .Values.prBranch }}
          - name: MY_ENV
            value: "some_value"
{{- else }}
{{ toYaml .Values.env | indent 10 }}
{{- end }}
{{- end }}
        livenessProbe:
          httpGet:
            path: {{ .Values.probePath }}
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.probePath }}
            port: {{ .Values.service.internalPort }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
```

Sample project `values.yaml` contains this:

```yaml
env:
  - name: MY_ENV
    value: "some_staging_value"
```

Sample `environment-xxxx-production` `values.yaml` contains this:

```yaml
env:
- name: MY_ENV
  value: some_production_value
```

I can certainly get the preview and staging environment variables working.
However, when I promote the application to the production environment, the `env` 
list in `environment-xxxx-production` does not override the `env`
list in the `values.yaml` file inside of the project itself.

**Comment by duffn** [comment]
Ahh, I see now that I need to include the project name as a key in the `environment-xxxx-production` `values.yaml` file for it to be recognized. https://stackoverflow.com/a/54773078/1753891

```yaml
myprojectname:
  env:
  - name: MY_ENV
    value: some_production_value
```
