### ISSUE TITLE
jx import not setting user for API token correctly

### ISSUE THREAD

**Issue by ryandawsonuk** [jenkins-x/jx#1731]
My gitAuth.yaml contains:

```
servers:
- url: https://github.com
  users:
  - username: ryandawsonuk
    apitoken: xxxxxxxxxxxx
    bearertoken: ""
  - username: jx-activiti-cloud@alfresco.com
    apitoken: xxxxxxxxxxxxx
    bearertoken: ""
  name: GitHub
  kind: github
  currentuser: jx-activiti-cloud@alfresco.com
defaultusername: jx-activiti-cloud@alfresco.com
pipelineusername: jx-activiti-cloud@alfresco.com
currentserver: https://github.com
pipelineserver: https://github.com
```
So I want `jx-activiti-cloud@alfresco.com` to be used. When I do `jx import` to import an app then I get the choice in the cli and I choose the `jx-activiti-cloud@alfresco.com` user. But if I step into a build job and view the full log then I see:

`10:27:55 Connecting to https://api.github.com using ryandawsonuk/****** (API Token for acccessing https://github.com git service inside pipelines)`
