### ISSUE TITLE
Environment git repos created in users github account not pipeline bot user

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#1782]
I have three git user accounts in my local `~/.jx/gitAuth.yaml` file, here's the file with the tokens personal access tokens removed:

```
servers:
- url: https://github.com
  users:
  - username: jenkins-x-bot
    apitoken: foo
    bearertoken: ""
  - username: rawlingsj
    apitoken: bar
    bearertoken: ""
  - username: jenkins-x-bot-test
    apitoken: wine
    bearertoken: ""
  name: GitHub
  kind: github
  currentuser: rawlingsj
- url: https://github.beescloud.com
  users: []
  name: GHE
  kind: github
  currentuser: ""
defaultusername: rawlingsj
pipelineusername: jenkins-x-bot-test
currentserver: https://github.com
pipelineserver: https://github.com
```

I ran `jx create cluster gke --prow` and selected the `jenkins-x-bot-test` user to use as the pipeline user.  However the environments git repos were created in my `rawlingsj` user.  I guess the `defaultusername` is being used from above rather than the chosen test bot user?
