### ISSUE TITLE
Add --ingress-class flag to jx install to ingress resource to work on existing ingress controllers

### ISSUE THREAD

**Issue by edalford11** [jenkins-x/jx#1973]
Any chance we could allow this functionality? Some users like myself have an `nginx-internal` and `nginx-external` ingress controllers and I'd like to install on the internal ingress. As of right now I'm going in a manually changing the ingress class after install so I can access the resources in the browser.

**Comment by beebird** [comment]
We can just use a local ``cloud-environments`` repo and override the default annotation of services  in ``myvalues.yaml`` like this:
```yaml
jenkins:
  Master:
    ServiceAnnotations:
      #   service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
      fabric8.io/expose: "true"
      fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx-internal\nnginx.ingress.kubernetes.io/proxy-body-size: 500m"

```
