### ISSUE TITLE
Setup failed

### ISSUE THREAD

**Issue by agentgonzo** [jenkins-x/jx#2019]
### Summary 
At the end of the setup, the jx installer tried to create a git repo in the wrong org

### Steps to reproduce the behavior
Run `jx install terraform blah blah`

### Jx version

The output of `jx version` is:

Same as my other tickets

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
GKE, jx install

### Operating system / Environment
Windows

### Expected behavior
It didn't fail

### Actual behavior
```
Creating Git repository [32mjenkinsx-dev[0m/[32menvironment-goosesage-steve-dev-staging[0m
error: failed to create staging environment in namespace jx: Failed to create repository jenkinsx-dev/environment-goosesage-steve-dev-staging due to: POST https://api.github.com/orgs/jenkinsx-dev/repos: 404 Not Found []
```

The org `jenkinsx-dev` that it is trying to use is not a valid github org (it is the gke project name). 

output of .jx/gitAuth.yaml
```
servers:
- url: https://github.com
  users:
  - username: agentgonzo
    apitoken: REDACTED
    bearertoken: ""
  - username: jenkins-x-bot-test
    apitoken: REDACTED
    bearertoken: ""
  name: GitHub
  kind: github
  currentuser: jenkins-x-bot-test
defaultusername: jenkins-x-bot-test
currentserver: https://github.com
pipelineusername: agentgonzo
pipelineserver: https://github.com
```
