### ISSUE TITLE
jx upgrade platform --always-upgrade resets password

### ISSUE THREAD

**Issue by bryanlarsen** [jenkins-x/jx#2164]
### Summary 

I wanted to update my `myvalues.yaml` so I ran `jx upgrade platform --always-upgrade` and it destroyed my installation.   All passwords in ~/.jx/adminSecrets.yaml were reset to be empty, and I'm unable to log in using the old password.

### Steps to reproduce the behavior

jx upgrade platform --always-upgrade

### Jx version

The output of `jx version` is:

```
Using helmBinary helm with feature flag: none
NAME               VERSION
jx                 1.3.498
jenkins x platform 0.0.2806
Kubernetes cluster v1.9.7-gke.6
kubectl            v1.12.2
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.17.1
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

` jx create cluster gke`

### Operating system / Environment

Ubuntu 18.04

### Expected behavior

password not changed when upgrading platform

### Actual behavior

`jx upgrade platform --always-upgrade` resets password

**Comment by bryanlarsen** [comment]
Here's the first part of `adminSecrets.yaml` that I have after the upgrade:

```
chartmuseum:
  env:
    secret:
      BASIC_AUTH_USER: admin
      BASIC_AUTH_PASS: ""
grafana:
  server:
    adminUser: admin
    adminPassword: ""
jenkins:
  Master:
    AdminPassword: ""
```
