### ISSUE TITLE
jx import --no-draft creates an invalid config

### ISSUE THREAD

**Issue by carlossg** [jenkins-x/jx#2348]
### Steps to reproduce the behavior

Clone https://github.com/carlossg/croc-hunter-jenkinsx-serverless

`jx import --no-draft`

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.599
jenkins x platform 0.0.2940
Kubernetes cluster v1.11.2-gke.18
kubectl            v1.12.2
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.19.1
Operating System   Mac OS X 10.14.1 build 18B75
```

### Kubernetes cluster

GKE

### Expected behavior

Template name is set to something valid or user is asked about what template to use

### Actual behavior

Template name is set to `jenkins-` which is invalid

`configmap/config`

```
      carlossg/croc-hunter-jenkinsx-serverless:
      - agent: knative-build
        branches:
        - master
        build_spec:
          serviceAccountName: knative-build-bot
          template:
            name: jenkins-
        name: release
...
      carlossg/croc-hunter-jenkinsx-serverless:
      - agent: knative-build
        always_run: true
        build_spec:
          serviceAccountName: helm
          template:
            name: jenkins-
        context: serverless-jenkins
        name: serverless-jenkins
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)

```

build-controller errors

```
E1127 19:24:02.586702       1 controller.go:277] build template "jx/jxz4z58" in namespace "jx" does not exist
E1127 19:24:02.586821       1 controller.go:209] error syncing 'jx/jxz4z58': buildtemplate.build.knative.dev "jenkins-" not found
```
