### ISSUE TITLE
Builds that time out are marked as successful

### ISSUE THREAD

**Issue by davidcurrie** [jenkins-x/jx#2633]
### Summary 

I have a knative build that timed out (at the end on a `jx preview` but anything that exceeds the 1 hour timeout would suffice for testing purproses). The knative build and the prowjob are both marked as unsuccessful but the pipelineactivity shows success:

```
- kind: Promote
    promote:
      environment: staging
      pullRequest:
        pullRequestURL: https://github.com/cloudbees/environment-graspred-staging/pull/1
        startedTimestamp: 2019-01-09T20:38:45Z
        status: Running
      startedTimestamp: 2019-01-09T20:38:45Z
      status: Running
```

yet:

```
status: Succeeded
```

The following logic that appears to set the status to successful if all of the init containers have terminated but none have failed:
https://github.com/jenkins-x/jx/blob/master/pkg/jx/cmd/controller_build.go#L296-L301

But the logic before that looks like it should change the status of the stage for the terminated init container from Running to Failed. Unfortunately, the pod has been removed so I cannot verify what the exit state of the init container was.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.699
jenkins x platform 0.0.3143
Kubernetes cluster v1.11.5-gke.4
kubectl            v1.12.0
helm client        v2.11.0+g2e55dbe
helm server        v2.12.1+g02a47c7
git                git version 2.18.0
Operating System   Mac OS X 10.14.2 build 18C54
```

### Kubernetes cluster

GKE cluster in prow mode.

### Operating system / Environment

MacOS

### Expected behavior

Build is marked as unsuccessful.

### Actual behavior

Build is marked as successful.
