### ISSUE TITLE
Devpod doesn't support pod template inheritence or raw yaml

### ISSUE THREAD

**Issue by ranginuitrot** [jenkins-x/jx#2647]
### Summary
Related to https://github.com/jenkins-x/jx/issues/2389

I'm working on a project that requires a GPU in its pod for both build and as a deployed service. I can confirm the repo builds, publishes, and deploys in preview, staging, and production.
I'd love to be able to use devpods for this project, but when I try to use the template below with `jx create devpod -l python-gpu`, `inheritFrom` and `yaml` (raw yaml) aren't supported.

### Steps to reproduce the behavior

Create `myvalues.yaml` with the following content:

```yaml
jenkins:
  Agent:
    PodTemplates:
      PythonGpu:
        Name: python-gpu
        Label: jenkins-python-gpu
        InheritFrom: python
        Yaml: |
          spec:
            containers:
              - name: python
                resources:
                  requests:
                    cpu: 400m
                    memory: 512Mi
                    nvidia.com/gpu: 1
                  limits:
                    cpu: 2
                    memory: 8Gi
                    nvidia.com/gpu: 1
```
2. In Jenkins console /configure, confirm that inheritance and raw yaml fields are blank. At this point I filled them in accordingly in order to support building (with `jenkins-python-gpu` as the agent in Jenkinsfile).
3. `jx create devpod -l python-gpu --sync`
4. Confirm that the devpod doesn't deploy.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.706
jenkins x platform 0.0.3143
Kubernetes cluster v1.11.5-eks-6bad6d
kubectl            v1.13.1
helm client        v2.12.1+g02a47c7
helm server        v2.12.1+g02a47c7
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.14.2 build 18C54
```

### Kubernetes cluster

EKS cluster via AWS Cloudformation.

### Operating system / Environment

Mac OS 10.14

### Expected behavior

Devpod should support pod inheritance and raw yaml.

### Actual behavior

Devpod doesn't support pod inheritance and raw yaml.
