### ISSUE TITLE
unable to access charts in monocular, maybe regression in exposecontroller

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#2798]
On a new `jx create cluster` the service annotations for that exposecontroller uses to add another backend to the monocular ingress are missing.  I.e. these https://github.com/jenkins-x/jenkins-x-platform/blob/4c258bb/values.yaml#L650-L654 monocular api service annotations are not updating the monucular ingress rule.  
Ingress looks like:
```
    http:
      paths:
      - backend:
          serviceName: jenkins-x-monocular-ui
          servicePort: 80
        path: /
```
but should be 
```
    http:
      paths:
      - backend:
          serviceName: jenkins-x-monocular-ui
          servicePort: 80
        path: /
      - backend:
          serviceName: jenkins-x-monocular-api
          servicePort: 80
        path: /api
```

/kind bug
/area install
/priority important-soon
