### ISSUE TITLE
have a PipelineActivity resource thats like a Stage view but more detailed

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#285]
It would be awesome to have a PipelineActivity kubernetes resource for each Pipeline Run that kept a high level metadata of what activities have happened on the Pipeline.

A simple version could be a list of the Stages as they start/complete.

However for Jenkins X we could add much more metadata and depth to the list of activity steps such as:
```yaml
apiVersion: jenkins.io/v1
kind: PipelineActivity
metadata:
  name: myapp-4
spec:
  pipeline: myapp
  build: 4    
  status: pending
  steps:
    - buildRelease
       version: "1.2.3"
      duration: 1h
      status: success
    - promotePullRequest
      environment: staging
      pullRequestURL: https://github.com/jstrachan/environment-staging/pull/3
      startTime: 12345
      buildURL: http://unconfigured-jenkins-location/job/jstrachan/job/environment-staging/job/PR-3/1/display/redirect
      duration: 1h
      status: success
      mergeCommit: https://github.com/jstrachan/environment-staging/commit/4064219469c3d27da20f2f61d0514664fe8c6061
    - promotePipeline
      environment: staging
      pullRequestURL: https://github.com/jstrachan/environment-staging/pull/3
      startTime: 45678
      buildURL: http://unconfigured-jenkins-location/job/jstrachan/job/environment-staging/job/master/5/display/redirect
      duration: 1h
      status: success
    - promotePullRequest
      environment: production
      pullRequestURL: https://github.com/jstrachan/environment-production/pull/2
      startTime: 780762
      status: watingForApproval
```

Then we can visualise whats been happening in fairly course grained steps (not quite the pipeline `low level steps` but higher level semantics than 'Stages' in that we'd link to data like status, PRs, merges, environments, versions and whatnot so we can deep link to the underlying commits/issues/PRs/resources/namespaces/apps etc

Am still not 100% sure if we should have lots of immutable steps added to the list (e.g. start PR, PR building, PR built) versus just a more course grained PR activity that one activity row starts, the status changes to `building` then is marked later as completed etc
