### ISSUE TITLE
Knative doesn’t react properly to pods getting deleted

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#3155]
### Summary 

Knative doesn’t react properly to pods getting deleted
Prow relies on knative builds to detect build state. When we loose nodes knative seems to not react, here is the except from a build where the pod was lost due to node restart - as you can see it’s still showing as running:

```
  status:
    builder: Cluster
    cluster:
      namespace: jx
      podName: 820d6d00-303f-11e9-8759-0a580a305309-pod-4bc4d8
    conditions:
    - lastTransitionTime: 2019-02-14T10:48:47Z
      message: 'pod status "Initialized":"False"; message: "containers with incomplete
        status: [build-step-jenkins]"'
      reason: Pending
      status: Unknown
      type: Succeeded
    startTime: 2019-02-14T10:01:37Z
    stepStates:
    - running:
        startedAt: 2019-02-14T10:01:47Z
    stepsCompleted: null
```
Solution: fix knative build or write a controller than does the reconciling properly. Ideally in this case we would have prow retrigger the job automatically
