### ISSUE TITLE
Next gen pipeline - error with spaces in stage name 

### ISSUE THREAD

**Issue by warrenbailey** [jenkins-x/jx#3209]
### Summary 

I'm using `jx step create task` to process a jenkins-x.yml and utilise the new tekton pipelines. However I've just upgraded to the latest jx binary and notice my jenkins-x.yml file no longer works.

Basically it doesn't like spaces in the stage name anymore. An easy workaround is to rename it with a '_' or '-' 

### Steps to reproduce the behavior

Create a jenkins-x.yaml with a space in the stage name. e.g.

```
pipelineConfig:
  pipelines:
    release:
      pipeline:
          stages:
          - name: next version
            steps:
              - agent:
                  image: jenkinsxio/jx:1.3.925
                command: jx
                args:
                  - step
                  - next-version
                  - -t
                  - --use-git-tag-only
```

### Expected behavior

Build should succeed.

### Actual behavior

error: failed to generate Task for build pack pipeline YAML: /Users/warrenbailey/dev/jenkins-x-serverless/jenkins-x.yml: failed to apply generated Pipeline: failed to create/update the task warrenbailey-jenkins-x-serverless-m-next-version in namespace jx: failed to get PipelineResource warrenbailey-jenkins-x-serverless-m-next-version with tasks.tekton.dev "warrenbailey-jenkins-x-serverless-m-next-version" not found after failing to create a new one: Task.tekton.dev "warrenbailey-jenkins-x-serverless-m-next-version" is invalid: metadata.labels: Invalid value: "next version": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')

### Jx version

The output of `jx version` is:

NAME               VERSION
jx                 1.3.925
jenkins x platform 0.0.3432
Kubernetes cluster v1.11.7-gke.4
kubectl            v1.13.2
helm client        v2.12.1+g02a47c7
helm server        v2.12.1+g02a47c7
git                git version 2.20.1
Operating System   Mac OS X 10.13.6 build 17G5019
### Jenkins type

- [ ] Classic Jenkins
- [ ] Serverless Jenkins
