### ISSUE TITLE
Use different default Jenkins username

### ISSUE THREAD

**Issue by mdiez19** [jenkins-x/jx#3350]
### Summary 
Currently, we can overwrite the admin-password with `--default-admin-password` when running `jx install` with a static jenkins server. 

Currently we piggy back on CASC to use LDAP as an Active Directory for jenkins users. Therefore I need to overwrite the default admin username as well i.e. `--default-admin-username`
### Steps to reproduce the behavior
Add the following to your myvalues.yaml
```
jenkins:
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: true
  securityRealm:
    ldap:
      configurations:
      - <LDAP config>
```
### Expected behavior
Not Applicable

### Actual behavior
JX Installs but fails in the API section because the admin credentials are not valid

### Jx version

The output of `jx version` is: 

```
jx                 1.3.974
jenkins x platform 0.0.3535
Kubernetes cluster v1.10.12
kubectl            v1.13.0
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.13.6 build 17G5019
```

### Jenkins type

- [x] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster

Kops
