### ISSUE TITLE
extraValues.yaml overrides helm values in preview environment.

### ISSUE THREAD

**Issue by tejesh-unbxd** [jenkins-x/jx#3362]
I'm using ECR to store docker images. In a preview environment, I'm making a few changes in values.yaml so that image gets pulled from ECR. 

`cat pim/dam/preview/values.yaml`

```
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  config:
    exposer: Ingress
    http: true
    tlsacme: false

cleanup:
  Args:
    - --cleanup
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded

preview:
  image:
    repository: abc.dkr.ecr.us-east-1.amazonaws.com/pim-dam
    tag:
    pullPolicy: IfNotPresent
```

When i run `jx preview --app pim-dam --dir ../..`  i can see `extraValues.yaml` file is getting created which overrides my `values.yaml `file.The problem with `extraValues.preview.image.repository` is it adds organisation after registry name which is not the case with ECR.
How do I override `extraValues.yaml` ? or How do I tell Jenkinsx not to include $ORG in `extraValues .yaml`?

current:
```
extraValues.preview.image.repository: $DOCKER_REGISTRY/$ORG/$APPNAME
```

required:
```
extraValues.preview.image.repository: $DOCKER_REGISTRY/$APPNAME
```

cat extraValues.yaml
```
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  config:
    domain: 54.183.236.166.nip.io
    exposer: Ingress
    http: "true"
preview:
  image:
    repository: abcd.dkr.ecr.us-east-1.amazonaws.com/tejesh-unbxd/pim-dam
    tag: 0.0.0-SNAPSHOT-PR-11-2
```

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.980
jenkins x platform 0.0.3513
Kubernetes cluster v1.10.6
kubectl            v1.12.1
helm client        v2.11.0+g2e55dbe
helm server        v2.12.2+g7d2b0c7
git                git version 2.14.4
Operating System   Unkown Linux distribution Linux version 4.14.72-73.55.amzn2.x86_64 (mockbuild@ip-10-0-1-219) (gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC)) #1 SMP Thu Sep 27 23:37:24 UTC 2018
```

**Comment by martin-patsov** [comment]
Did you have any progress on this? I think I have the same issue.

**Comment by tejesh-unbxd** [comment]
I found workaround not to get overridden by Extravalues.yaml.
changed preview name in requirements.yaml
``` 
- alias: preview-pim-dam
  name: pim-dam
  repository: file://../pim-dam
```
renamed same in values.yaml
```
preview-pim-dam:
  image:
    repository: abc.dkr.ecr.us-east-1.amazonaws.com/jenkinsx
    tag:
    pullPolicy: IfNotPresent
```
