### ISSUE TITLE
Pipeline endless loop due to error in jenkins-x.yaml

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#3450]
### Summary 
Pipeline gets stuck in error retry loop if jenkins-x.yml contains errors.

`jx log pipeline` shows:
```
E0327 19:34:41.572752       1 controller.go:259] failed to reconcile default/jx/92847db7-50a7-11e9-ac04-0a580a380112/ProwJob: posting pipeline: got unexpected response from pipelinerunner: 400 Bad Request, failed to load project config in dir /tmp/git502955350: Failed to unmarshal YAML file /tmp/git502955350/jenkins-x.yml due to error converting YAML to JSON: yaml: line 16: did not find expected key
E0327 19:34:42.813924       1 controller.go:259] failed to reconcile default/jx/7853bdfe-50ba-11e9-ae92-0a580a380009/ProwJob: posting pipeline: got unexpected response from pipelinerunner: 400 Bad Request, failed to load project config in dir /tmp/git821593277: Failed to unmarshal YAML file /tmp/git821593277/jenkins-x.yml due to error converting YAML to JSON: yaml: line 13: did not find expected key
```
### Steps to reproduce the behavior
Edited jenkins-x.yml with incorrect key structure:
```
buildPack: python
pipelineConfig:
  pipelines:
    pullRequest:
      build:
        steps:
        - sh: python -m pip install pytest
        - sh: pytest
    release:
      setVersion:
        steps:
        - sh: echo \$(jx-release-version) > VERSION
          comment: so we can retrieve the version in later steps
        - sh: jx step tag --version \$(cat VERSION)
      build:
        steps:
      - sh: python -m pip install pytest
      - sh: pytest
```
(Indentation wrong at end.)

### Expected behavior
Build to complete with new tests or error out due to incorrect YAML.

### Actual behavior
Pipeline retries endlessly every 15 mins. Checking in subsequent fixes fails to trigger new build with updated file.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.1035
jenkins x platform 0.0.3657
Kubernetes cluster v1.11.7-gke.12
kubectl            v1.13.4
helm client        Client: v2.13.0+g79d0794
git                git version 2.21.0
Operating System   Mac OS X 10.13.6 build 17G4015E
```

### Jenkins type

- [ ] Classic Jenkins
- [x] Serverless Jenkins

### Kubernetes cluster
```
jx create cluster gke \
--cluster-name='d29' \
--default-admin-password='xxxxx' \
--environment-git-owner='tdcox' \
--enhanced-apis=true \
--enhanced-scopes=true \
--git-username='tdcox' \
--git-private=false \
--kaniko=true \
--labels='demo=true' \
--machine-type='n1-standard-4' \
--max-num-nodes='3' \
--min-num-nodes='2' \
--no-tiller=true \
--preemptible=true \
--project-id='jx-mar19' \
--prow=true \
--skip-login=true \
--tekton=true \
--vault=false \
--zone='europe-west1-d'
```
