### ISSUE TITLE
Couldn't find key docker.registry in ConfigMap jx/jenkins-x-docker-registry

### ISSUE THREAD

**Issue by dimmel82** [jenkins-x/jx#3494]
### Summary 
When upgrading the jenkins-x-platform to **0.0.3698** the jenkins pod fails to start with following error displayed in `kubectl describe pods jenkins-7b997fb8c9-z5mpj -n jx` :

> Couldn't find key docker.registry in ConfigMap jx/jenkins-x-docker-registry

The **jenkins-x-docker-registry** config map is missing the following part
```
data:
  docker.registry: "myhost:5000"
```
When  executing `helm upgrade --dry-run --debug --version 0.0.3698 ..... jenkins-x/jenkins-x-platform` the output for the **jenkins-x-docker-registry** cm is the following, both when the **dockerRegistry** key has a value or not in myvalues.yaml (the **jenkins.Servers.Global.EnvVars.DOCKER_REGISTRY** has a non-empty value as well):
```
---
# Source: jenkins-x-platform/templates/jenkins-x-docker-registry.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-x-docker-registry
  annotations:
    expose.config.fabric8.io/clusterip-port-if-empty-key: docker.registry
data:docker.registry: myhost:5000
```

It seems that the relevant change in the **jenkins-x-platformtemplates/jenkins-x-docker-registry.yaml** file is 
the addition of an `if-else` condition which does not add the necessary indentation:

```
data:
{{- if .Values.jenkins.Servers.Global.EnvVars.DOCKER_REGISTRY -}}
  docker.registry: {{ .Values.jenkins.Servers.Global.EnvVars.DOCKER_REGISTRY }}
{{- else -}}
  docker.registry: {{ .Values.dockerRegistry }}
{{- end }}
```

The issue is bypassed by manually adding the missing **data** key in the cm and deleting the jenkins pod

### Steps to reproduce the behavior
Execute `jx upgrade platform` while having the jenkins-x-platform 0.0.3588 version installed

### Expected behavior
The **jenkins-x-docker-registry** cm has the "data" key, and the jenkins pod is running

### Actual behavior
The **jenkins-x-docker-registry** cm does not have the "data" key, and the jenkins pod fails with error

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.992
jenkins x platform 0.0.3698
Kubernetes cluster v1.11.5-docker-4
kubectl            v1.10.3
helm client        v2.12.3+geecf22f
helm server        v2.12.2+g7d2b0c7
git                git version 2.18.0.windows.1
Operating System   Windows 10 Pro 1703 build 15063
```

### Jenkins type

- [x] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster

On-premise Kubernetes, created manually
### Operating system / Environment

Windows 10
