### ISSUE TITLE
secrets/jx-sso-dex-dex didn't contain the connector organization name

### ISSUE THREAD

**Issue by carlosrodlop** [jenkins-x/jx#3536]
### Summary 

I managed to install the cluster by this [Installation Process](https://go.cloudbees.com/docs/cloudbees-core/kubernetes-cd-install-guide/install-product/). Try to login into the `cloudbees`  the `sso` component is giving the following message `user carlosrodlop not in required orgs or teams`

Looking at the `kubectl logs jx-sso-dex-dex-64fd954699-5hlc7 -n=sso` we see that

```
time="2019-04-04T09:47:52Z" level=info msg="github: user \"example.user\" not in org \"\" or application not authorized to read org data" connector=GitHub 
time="2019-04-04T09:47:52Z" level=error msg="Failed to authenticate: github: user \"example.user\" not in required orgs or teams" 
```

Then `kubectl get secrets/jx-sso-dex-dex -o yaml -n=sso | ksd` 

```
 connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: redacted
        clientSecret: redacted
        redirectURI: https://dex.sso.jx.my-domain.com/callback
        orgs:
          - name: 
        useLoginAsID: true

```

Finally, I tried to workaround the issue by deleting the faulty secret and create it back with the right name of the organization but now the behavior of the sso is odd, it is logging me into the cloudbees addon but it is not working correctly.

### Steps to reproduce the behavior

```
jx create terraform --environment-git-owner my-org -o my-org -default-admin-password=***** --verbose
```

### Jx version

```
NAME               VERSION
jx                 1.3.1073
jenkins x platform 0.0.3734
Kubernetes cluster v1.11.7-gke.12
kubectl            v1.13.4
helm client        v2.13.0+g79d0794
helm server        v2.13.0+g79d0794
git                git version 2.7.4
Operating System   Ubuntu 16.04.6 LT
```

### Jenkins type

- [ ] Classic Jenkins
- [x ] Serverless Jenkins

### Kubernetes cluster

GKE

### Operating system / Environment

Ubuntu 16.04.6 LT
