### ISSUE TITLE
Using path-mode:path option is not supported for preview environment applications

### ISSUE THREAD

**Issue by chenfli** [jenkins-x/jx#3564]
### Summary 

Installing JX with the following parameters

jx install  --install-dependencies=true --provider=kubernetes --on-premise  --log-level='debug'   --namespace='jx' --exposecontroller-pathmode='path' --prow=true --no-tiller=true

Using my personal Github account
### Steps to reproduce the behavior

After a succesfull install, I do the following:
1. Create a quickstart nodejs application by the name nodejs
 jx create quickstart
2. Login to github create a change in the index.html and opens a PR
3. The Pull request build succed, the preview environment ingress is http://nodejs.jx-[my  github user]-nodejs-pr-1.[The domain I selected]
### Expected behavior
The preview environment should be
http://[The domain I selected]/nodejs-pr-1/nodejs
### Actual behavior
http://nodejs.jx-[my  github user]-nodejs-pr-1.[The domain I selected]

### More details How I debugged it
Looking at the logs, it appears no traces of the *path-mode: path* on the exposecontroller configuration

Found commit author match for: chenfli with email address: <my mail address>
```yaml
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  config:
    domain: <the domain I selected>
    exposer: Ingress
    http: "true"
preview:
  image:
    repository: 10.3.0.167:5000/<my user>/nodejs
    tag: 0.0.0-SNAPSHOT-PR-1-2
```
Applying generated chart . YAML via kubectl in dir: /tmp/helm-template-workdir-521416723/preview/output

### Things I did but didn't change the result or the build log details
1. Change the nodejs/charts/preview/values.yaml to include path-mode:path
``` yaml
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
config:
  path-mode: path
```
2. Change the buildpacks to have a nodejs version with the above change allready inside
3. Change the jx/ingress-config config map to include path-mode:path

The result is still the same, what is the way to enforce exposecontroller to use path-mode:path configuration ?

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.1096
jenkins x platform 0.0.3832
Kubernetes cluster v1.13.4
kubectl            v1.13.3
helm client        Client: v2.13.0+g79d0794
git                git version 2.17.1
Operating System   Ubuntu 18.04.2 LTS
```

### Jenkins type

- [ ] Classic Jenkins
- [x] Serverless Jenkins

### Kubernetes cluster

On premise, Using Azure as backbone

### Operating system / Environment
3 Master/3 Workers 
Machines are Ubuntu 
Network layer is weave

From the master

**Comment by lgg42** [comment]
Hey! try to update your file app-name/charts/preview/values.yaml
I found that if I set expose options like the following:
```
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  config:
    exposer: Ingress
    http: true
    tlsacme: false
    pathMode: "path"
```
Just putting the pathMode in there, the preview environments switch to path based ingress.
