### ISSUE TITLE
how to switch from http://chartmuseum.jenkins-x.io/ to my custom mirror ?

### ISSUE THREAD

**Issue by LeoQuote** [jenkins-x/jx#3607]
### Summary 
It's kinda hard and slow to get to the default chartmuseum http://chartmuseum.jenkins-x.io/  in our network environment. I'm considering make a whole mirror of the chartmuseum . 
I wonder how to edit the configuration so the jx will use my mirror instead ? 

I tried to edit my environment repo directly , including the ``Makefile`` and ``env/requirements.yaml``

but still , it will
```
Adding missing Helm repo: jenkins-x http://chartmuseum.jenkins-x.io
```
during ``jx step helm build``.

Is there a way to use my local mirror completely ? 

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.1103
jenkins x platform 0.0.3832
Kubernetes cluster v1.13.3
kubectl            v1.13.3
helm client        Client: v2.12.2+g7d2b0c7
git                git version 1.8.3.1
Operating System   CentOS Linux release 7.2.1511 (Core)
```

### Jenkins type

- [x] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster
kubeadm

### Operating system / Environment
linux

possible related issue: #2340

**Comment by LeoQuote** [comment]
here's my environment Makefile :
```make
CHART_REPO := http://jenkins-x-chartmuseum:8080
DIR := "env"
NAMESPACE := "jx-production"
OS := $(shell uname)

build: clean
	rm -rf requirements.lock
	helm version
	helm init
	helm repo add releases ${CHART_REPO}
	helm repo add jenkins-x http://192.168.109.241:30415
	helm dependency build ${DIR}
	helm lint ${DIR}

install: 
	helm upgrade ${NAMESPACE} ${DIR} --install --namespace ${NAMESPACE} --debug

delete:
	helm delete --purge ${NAMESPACE}  --namespace ${NAMESPACE}

clean:
```

and requirements.yaml:
```yaml
dependencies:
- name: exposecontroller
  version: 2.3.89
  repository: http://192.168.109.241:30415
  alias: expose
- name: exposecontroller
  version: 2.3.89
  repository: http://192.168.109.241:30415
  alias: cleanup
```
