### ISSUE TITLE
GetLifecycle always returns Setup

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/jx#3717]
### Summary 

GetLifecycle (https://github.com/jenkins-x/jx/blob/master/pkg/jenkinsfile/pipeline.go#L214) returns Setup no matter which Lifecycle name is passed as the argument.

### Steps to reproduce the behavior

```bash
jx create step -l prebuild -m post -p release -c 'echo "hello"'
cat jenkins-x.yml
```

```
buildPack: go
pipelineConfig:
  agent: {}
  pipelines:
    release:
      setup:
        steps:
        - sh: echo "hello"
```

### Expected behavior

The lifecycle in jenkins-x.yml should be `prebuild`

### Actual behavior

The lifecycle in jenkins-x.yml is `setup`

### Jx version

The output of `jx version` is:

```
NAME             VERSION
jx               2.0.26
git              git version 2.20.1 (Apple Git-117)
Operating System Mac OS X 10.14.4 build 18E226
```

### Jenkins type

- [X] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

Any

### Operating system / Environment

macOS
