### ISSUE TITLE
Allow the execution of multiple commands within a single pipeline step

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx#3767]
### Summary 

Right now one cannot execute multiple commands in a single pipeline step. The best workaround is using '&&':

```yaml
- name: copy
  image: busybox
  command: mkdir
  args:
  - -p
  - /workspace/go/src/github.com/jenkins-x/exposecontroller
  - "&&"
  - cp
  - -R
  - "./"
  - /workspace/go/src/github.com/jenkins-x/exposecontroller
```

### Expected behavior

It would be nice to have a syntax which allows executing multiple commands, eg by using/adding a _script_ key.
