### ISSUE TITLE
jx create spring does not take --docker-registry-org into account

### ISSUE THREAD

**Issue by ascheman** [jenkins-x/jx#3835]
### Summary 

Found this problem in the course of investigating #3834.

Creating a new Spring application and setting `--docker-registry-org=jxtest-199909` does not use the provided org.

### Steps to reproduce the behavior

```bash
: ${JX_ARTIFACT:="jx-demo-`date +%y%m%d-%H%M%S`"}

jx create spring \
    --name ${JX_ARTIFACT} \
    --git-username ascheman \
    --org ascheman \
    -l java \
    -g net.aschemann.demos.jx \
    -a ${JX_ARTIFACT} \
    -d actuator \
     --docker-registry-org=jxtest-199909 -b
```

### Expected behavior

The Docker project/org is `jxtest-199909`, e.g, in `skaffold.yml`:

```yaml
apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/jxtest-199909/jx-demo-190502-102623:{{.VERSION}}'
...
```

### Actual behavior

Several files contain the github org (which should only be the default, if the Docker registry org is not provided by param), e.g., `skaffold.yaml`:

```yaml
apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/ascheman/jx-demo-190502-102300:{{.VERSION}}'
  local: {}
```

### Jx version

The output of `jx version` is:

```
jx                 2.0.72
jenkins x platform 2.0.177
Kubernetes cluster v1.12.7-gke.10
kubectl            v1.14.1
helm client        Client: v2.13.1+g618447c
git                git version 2.21.0
Operating System   Mac OS X 10.14.4 build 18E226
```

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [x] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)
