### ISSUE TITLE
Steps are not ordered in activities

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/jx#4016]
### Summary 

Steps in `jx get activities` seem to be ordered alphabetically, not by the order of execution.

### Steps to reproduce the behavior

Create a `jenkins-x.yml` file with the following content.

```yaml
buildPack: go
pipelineConfig:
  pipelines:
    pullRequest:
      build:
        preSteps:
        - name: unit-tests
          command: make unittest
      promote:
        steps:
        - name: rollout
          command: |
            NS=$(echo cd-$REPO_OWNER-go-demo-6-$BRANCH_NAME | tr '[:upper:]' '[:lower:]')
            kubectl -n $NS rollout status deployment preview-preview
        - name: functional-tests
          command: ADDRESS=`jx get preview --current 2>&1` make functest
```

Push the change and execute `jx get activities`.

### Expected behavior

The output, limited to the `Promote` lifecycle, should be:

```
    Promote Make Preview                                   3m48s      52s Succeeded
    Promote Jx Preview                                     3m48s    1m11s Succeeded
    Promote Rollout                                        3m48s    1m52s Succeeded
    Promote Functional Tests                               3m47s    1m55s Succeeded
```

### Actual behavior

The output, limited to the `Promote` lifecycle, is:

```
    Promote Functional Tests                               3m47s    1m55s Succeeded
    Promote Jx Preview                                     3m48s    1m11s Succeeded
    Promote Make Preview                                   3m48s      52s Succeeded
    Promote Rollout                                        3m48s    1m52s Succeeded
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.122
jenkins x platform 2.0.276
Kubernetes cluster v1.12.7-gke.10
kubectl            v1.14.0
helm client        Client: v2.13.1+g618447c
git                git version 2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.4 build 18E226
WARNING:
A new jx version is available: 2.0.139
```

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [X] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

GKE

### Operating system / Environment

macOS
