### ISSUE TITLE
Environment controller's ELB can't pass health checks

### ISSUE THREAD

**Issue by lgg42** [jenkins-x/jx#4081]
### Summary 

Helm install of environment controller can't register webhook because the ELB exposing the service never marks the EKS nodes as healthy.

### Steps to reproduce the behavior

`helm install jenkins-x/environment-controller -n environment-controller -f environment-controller-values.yml --debug --wait`

 environment-controller-values.yml:
```
hmacToken: ""
dockerRegistry: "registry.domain.tld"
projectId: ""
dockerRegistryOrg: "organisation-name"


source:
  owner: "organisation-name"
  repo: "environment-eks-qa"
  serverUrl: "https://bitbucket.com"
  gitKind: "bitbucketcloud"
  user: "bot-user-name"
  token: "XXXXtokenXXXX"

service:
  name: environment-controller
  type: LoadBalancer
  externalPort: 80
  internalPort: 8080
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: |-
      kubernetes.io/ingress.class: nginx
```
Helm Charts tried: 
- environment-controller-0.0.52
- environment-controller-0.0.54

### Expected behavior

Environment-controller registers webhook in Bitbucket's environment repo and triggers actions when changes get merged to such repo's master branch.

### Actual behavior

Pods for environment controller and tekton pipelines are created and in running state.
Log of environment-controller is:

> using require GitHub headers: true
waiting for the external IP on the service environment-controller in namespace jx ...

Service for environment controller is created and a new ELB is provisioned.
Such ELB never marks the EKS nodes instances as healthy thus it never forwards traffic to the environment-controller pod.

### Remarks

If I create the following test pod:

```
kind: Deployment
metadata:
  name: hello-kubernetes
  namespace: jx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-kubernetes
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.5
        ports:
        - containerPort: 8080
```

And then run `kubectl edit svc environment-controller`

Changing 
```
  selector:
    app: environment-controller
```
for
```
  selector:
    app: hello-kubernetes
```

The ELB instantly mark the nodes as healthy and forwards traffic to the pod's app.

### Solutions tried

1. Adding `fabric8.io/exposeUrl=_ELB_ADDRESS_` to the environment-controller service.
Results in environment-controller pod in *CrashLoopBackOff* state.

2. Adding the ports.containerPort key (to port 8080) in environment-controller deployment manifest with `kubectl edit deployments environment-controller`
Results in no change.

3. Using Github instead of Bitbucket.
Resutls in no change.

### Jx version

The output of `jx version` is:

```
jx                 2.0.119
Kubernetes cluster v1.10.13-eks-g484b8
kubectl            v1.13.3
helm client        v2.13.1+g618447c
helm server        v2.13.1+g618447c
git                git version 2.7.4
Operating System   Ubuntu 16.04.6 LTS
```

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [x] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

EKS v1.10.13
AWS Dashboard for EKS and AWS's Cloudformation templates for nodes.
CNI: AWS-VPC

### Operating system / Environment

Ubuntu 16.04.6 LTS
Bash shell.

### Discussion
https://kubernetes.slack.com/archives/C9MBGQJRH/p1558708179022400
https://kubernetes.slack.com/archives/C9MBGQJRH/p1558711256027600
https://kubernetes.slack.com/archives/C9MBGQJRH/p1558729095041400
