### ISSUE TITLE
feature: Lifecycle of Previews

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#420]
Just some thoughts on preview behaviour.

- Is it intended that a preview environment be automatically removed after the PR is merged? If not, could we perhaps issue a reminder to delete the preview?

- At the moment, the only way to remove a preview seems to be `jx delete environment`. This isn't obvious to devs who are still learning the platform. Also, there is a real risk that a slip of a finger could delete a production environment if this command is used regularly. Although they are environments, it would probably be safer to have a distinct delete preview command if it is intended to be used regularly.

- Not checked yet, but are we generating the relevant k8s voodoo to allow services in the preview to access services deployed in staging? I think this can be done by mapping them locally as follows:
```
kind: Service
apiVersion: v1
metadata:
  name: service-y
  namespace: namespace-a
spec:
  type: ExternalName
  externalName: service-x.namespace-b.svc.cluster.local
  ports:
  - port: 80
```
