### ISSUE TITLE
Name is not supported in the loop

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/jx#4228]
### Summary 

I have the following pipeline.

```yaml
buildPack: go
pipelineConfig:
  pipelines:
    pullRequest:
      build:
        preSteps:
        - loop:
            variable: ARCH
            values:
            - arch-1
            - arch-2
            - arch-3
            steps:
            - command: echo ${ARCH}
              name: my-loop
```

With that YAML, pipeline fails to run (tekton Pod is not even created). If I remove the `name` instruction it works correctly. `jx step syntax validate pipeline` claims that the syntax is correct.

### Steps to reproduce the behavior

Run the above-mentioned pipeline.

### Expected behavior

Pipeline run is started

### Actual behavior

Pipeline does not run

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.253
jenkins x platform 2.0.330
Kubernetes cluster v1.12.8-gke.6
kubectl            v1.14.3
helm client        Client: v2.14.1+g5270352
git                git version 2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.5 build 18F203
```

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [X] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

GKE

### Operating system / Environment

macOS
