### ISSUE TITLE
race condition breaking 2 deploys at the same time due to merge conflicts in environment repos

### ISSUE THREAD

**Issue by michaelneale** [jenkins-x/jx#428]
It is possible to have merge conflict when deploying 2 apps close together. 

To reproduce: 

* start with a clean cluster (probably, maybe just 2 new apps)
* jx create quickstart
* jx create spring (in quick succession to above)
* Note that the environment-xyz-staging environment will end up with a pull request open that is not mergable
* Note that the master pipeline job for the spring app (likely) is stuck (it won't finish, it is usualy the one that takes longer). 

The conflict will look something like: 

```
dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.55
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.55
<<<<<<< promote-demo-0.0.1
- name: demo
=======
- name: node-http
>>>>>>> master
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
```

Not sure how best to avoid this - this is not an uncommon thing, adding 2 apps close together, and they have the same repo, and same version number so git can easily get confused here.
