### ISSUE TITLE
containerOptions not working on buildpack level

### ISSUE THREAD

**Issue by shahnewazrifat** [jenkins-x/jx#4369]
### Summary 
This works fine when I put it on the `jenkins-x.yml` inside the repo

```
# If a build pack is specified, the `pipeline` in `release`, `pullRequest`, and `feature` will be ignored.
buildPack: none

pipelineConfig:
  pipelines:
    release:
      pipeline:
        agent:
          image: "rifatshahnewaz/builder-maven-js:latest" # or "maven" - this means "use the maven pod template"
        options:
          containerOptions:
            volumeMounts:
            - name: jenkins-maven-settings
              mountPath: /root/.m2/
```

As specified in https://jenkins-x.io/architecture/pipeline-syntax-reference/#full-pipeline-definition-in-jenkins-x-yml

But when I put it inside my buildpack:

```
extends:
  file: ../maven/pipeline.yaml
agent:
  image: rifatshahnewaz/builder-maven-js:latest

containerOptions:
  volumeMounts:
  - name: jenkins-maven-settings
    mountPath: /root/.m2/
```

### Steps to reproduce the behavior
1. Start the pipeline
2. `kubectl get tasks -n jx` followed by `kubectl describe task TASK_NAME` 
3. You'll notice the volume mounts didn't work.
### Expected behavior
containerOptions works in buildpack level
### Actual behavior
containerOptions does not work in buildpack level
### Jx version
2.0.312
The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.312
jenkins x platform 2.0.634
Kubernetes cluster v1.11.8-eks-7c34c0
kubectl            v1.14.2
helm client        Client: v2.14.0+g05811b8
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.14.3 build 18D109
```

### Jenkins type

- [x] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster
EKS.

### Operating system / Environment
MacOs 10.14
