### ISSUE TITLE
Unkown image 'go' when using go build pack

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx#4458]
When creating/importing a Golang project and just using the go build pack:
```yaml
buildPack: go
```
One ends up with the following warning level log messages in the pipeline controller:
```
{"level":"warning","msg":"could not find a stable version of docker image: go from /root/.jx/jenkins-x-versions\nFor background see: https://jenkins-x.io/architecture/version-stream/","time":"2019-06-27T10:48:03Z"}
```

I believe the root cause is in jenkins-x-classic go pack:
```yaml
agent:
  label: jenkins-go
  container: go
  dir: /home/jenkins/go/src/REPLACE_ME_GIT_PROVIDER/REPLACE_ME_ORG/REPLACE_ME_APP_NAME
```

I think container `go` is interpreted as an image at some stage and we attempt to resolve it against the version stream where nothing is recorded for this "image".

Should we add an entry to the version stream? What image do we actually want to use at this point? 

@abayer WDYT?
