### ISSUE TITLE
`jx create quickstart` fails with "error: No quickstarts match filter"

### ISSUE THREAD

**Issue by jody-frankowski** [jenkins-x/jx#448]
On a fresh install of jenkins-x, `jx create quickstart` fails:

```sh
jx create quickstart
error: No quickstarts match filter
```

`jx` is from master and jenkins-x is installed on a fresh GKE cluster.

**Comment by rawlingsj** [comment]
@jody-frankowski what version of jx are you running?

`jx version`

**Comment by jody-frankowski** [comment]
```
NAME        VERSION
jx
Jenkins X   0.0.364
Kubernetes  v1.9.3-gke.0
Helm Client v2.8.2+ga802316
Helm Server v2.8.2+ga802316
Git         git version 2.16.2
```

**Comment by jody-frankowski** [comment]
And the same happens with jx `1.1.12`:

```
~/jx create quickstart
error: No quickstarts match filter

~/jx version
NAME        VERSION
jx          1.1.12
Jenkins X   0.0.364
Kubernetes  v1.9.3-gke.0
Helm Client v2.8.2+ga802316
Helm Server v2.8.2+ga802316
Git         git version 2.16.2
```

**Comment by rawlingsj** [comment]
Ah I think I know what this is, did you run the jx create cluster or was that done by someone else?

When we create the cluster jx sets up a few yaml files under ~/.jx, in particular one called `.jx/gitAuth.yaml`.  I just renamed this and got your error.

So we need to have jx prompt to enter users git token and setup that file.  Sounds like a bug we can fix.  For now if you create a file `.jx/gitAuth.yaml` and have it like this placing GITHUB_USERNAME and GITHUB_PERSONAL_ACCESS_TOKEN:

```yaml
servers:
- url: github.com
  users:
  - username: GITHUB_USERNAME
    apitoken: GITHUB_PERSONAL_ACCESS_TOKEN
    bearertoken: ""
  name: GitHub
  kind: ""
  currentuser: GITHUB_USERNAME
defaultusername: GITHUB_USERNAME
currentserver: github.com
```
