### ISSUE TITLE
`jx step helm apply` mishandles .Files.Get?

### ISSUE THREAD

**Issue by sdoxsee** [jenkins-x/jx#4540]
### Summary
https://kubernetes.slack.com/archives/C9MBGQJRH/p1561661149431700

Facing a problem when releasing an application to an environment even though it works perfectly in a preview environment. I have a template in my application for a Secret that is supposed to add three base64-encoded secrets to the "data" section of the Secret. What I experience is that, depending on their order, it only puts 1 secret or 0. I think that `jx step helm apply` isn't working correctly...possibly choking on encoding.
```
apiVersion: v1
kind: Secret
metadata:
  name: realm-secret
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  "master-realm.json": {{ tpl (.Files.Get "files/master-realm.json") . | b64enc | quote}}
  "bbd-realm.json": {{ tpl (.Files.Get "files/bbd-realm.json") . | b64enc | quote }}
  "external-realm.json": {{ tpl (.Files.Get "files/external-realm.json") . | b64enc | quote }}
```
The result, only in environments other than preview (since preview is using `jx preview` rather than `jx step helm apply`, looks like the following (note that only `master-realm.json` appears)
```
apiVersion: v1
data:
  master-realm.json: <base64-encoded json file>
kind: Secret
metadata:
  annotations:
    jenkins.io/chart: env
  creationTimestamp: 2019-06-27T17:55:13Z
  labels:
    app: keycloak-http
    chart: keycloak-http-0.0.15
    heritage: Tiller
    jenkins.io/chart-release: jx
    jenkins.io/namespace: jx-staging
    jenkins.io/version: "73"
    release: jx
  name: realm-secret
  namespace: jx-staging
  resourceVersion: "5573336"
  selfLink: /api/v1/namespaces/jx-staging/secrets/realm-secret
  uid: b6c9c313-9904-11e9-a364-42010aa2006e
type: Opaque
```
It's also worth noting that if I change the order of my data keys, that data get's a `null` with 0 keys.

### Steps to reproduce the behavior

You have to trigger `jx step helm apply`. An example would be with the following directory structure:
```
+-- Chart.yaml
+-- files
| .   +-- bbd-realm.json
| .   +-- external-realm.json   
| .   +-- master-realm.json
+-- templates
| .   +-- realm-secret.yaml
```
### Expected behavior
`helm template` processes the files properly and inserts all 3 into the secret. `jx step helm apply` should do the same.

### Actual behavior

`jx step helm apply` seems to either add one data key for master.json or none whatsover depending on if master.json is first in the template. bbd.json first yields zero data keys in the resulting secret.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.258
Kubernetes cluster v1.12.8-gke.10
kubectl            v1.14.3
helm client        Client: v2.14.0+g05811b8
git                git version 2.21.0
Operating System   Mac OS X 10.14.5 build 18F132
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GKE using `jx create cluster gke`

### Operating system / Environment

MacOS
