### ISSUE TITLE
Using `type: after` in the `overrides:` section of jenkins-x.yml does not work

### ISSUE THREAD

**Issue by ajp-lqx** [jenkins-x/jx#4545]
### Summary 
Using `type: after` results in steps with duplicate names in the pipeline.

### Steps to reproduce the behavior
Here is a sample `jenkins-x.yml` to place in a javascript project which adds an after step to the npmrc step:
```
pipelineConfig:
  extends:
    import: kubernetes
    file: javascript/pipeline.yaml
  pipelines:
    overrides:
    - pipeline: pullRequest
      stage: build
      name: npmrc
      type: after
      step:
        sh: cp /builder/home/.npmrc /workspace/source/.npmrc
        name: npmrc-copy
        image: jenkinsxio/jx:2.0.119
```

### Expected behavior
It should copy the npmrc file after the npmrc step has completed.

### Actual behavior
Log from pipelinerunner:
```
{"level":"error","msg":"failed to create effective project configuration: effective pipeline creation failed: failed to create effective pipeline for pull request: validation failed for Pipeline: step names within a stage must be unique: stages[0].steps\nThe following step names in the stage from-build-pack are used more than once: build-npmrc","time":"2019-07-02T19:17:11Z"}
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.381-dev+799c1f2f2
Kubernetes cluster v1.13.5
kubectl            v1.14.1
helm client        Client: v2.13.1+g618447c
git                git version 2.20.1
Operating System   Ubuntu 19.04
```

### Jenkins type
- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster
AKS

### Operating system / Environment
Ubuntu 19.04
