### ISSUE TITLE
jx boot fails to install correctly using secretStorage: vault

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#4684]
### Summary 
When attempting to install with external-dns and vault for secret storage, the pipeline runs very slowly and eventually starts to report:

```
failed to create system vault in namespace jx due to wait for vault to be initialized and unsealed: reading vault health: Get http://jx-vault-d55.jx.kill-9.uk/v1/sys/health?drsecondarycode=299&performancestandbycode=299&sealedcode=299&standbycode=299&uninitcode=299: dial tcp: lookup jx-vault-d55.jx.kill-9.uk on 192.168.50.1:53: no such host
```
### Steps to reproduce the behavior
```
cluster:
  clusterName: d56
  environmentGitOwner: bootstrap-labs
  project: jx-mar19
  provider: gke
  zone: europe-west1-d
environments:
- key: dev
- key: staging
- key: production
ingress:
  domain: kill-9.uk
  externalDNS: true
  tls:
    email: ""
    enabled: false
    production: false
kaniko: true
secretStorage: local
storage:
  logs:
    enabled: true
    url: ""
  reports:
    enabled: true
    url: ""
  repository:
    enabled: true
    url: ""
```

This looks like it may be the old chestnut that vault needs a domain name but external-dns hasn't created any yet.

**Comment by pmuir** [comment]
@daveconde is this one working now?

**Comment by renatoaraujoc** [comment]
I can confirm this bug. Has anyone been able to successfully install JX Boot with Vault?

**Comment by sharepointoscar** [comment]
It worked for me only when I used a custom domain, set `externalDNS:true` and enabled TLS as follows

```
ingress:
  domain: jx.sharepointoscar.com
  externalDNS: true
  namespaceSubDomain: -jx.
  tls:
    email: me@sharepointoscar.com
    enabled: true
    production: true
kaniko: true
secretStorage: vault
```
