### ISSUE TITLE
Make Tekton Pipeline YAML Required Items

### ISSUE THREAD

**Issue by sharepointoscar** [jenkins-x/jx#4786]
### Summary 
When working with the `jenkins-x.yml` and defining a custom step to execute prior or after named steps, one *must* have the `type:after` (in this case).  Otherwise the entire *release/build* is overridden.

```
    - pipeline: release
      stage: build
      steps:
      - name: release-honeycomb-build-name-concat
        sh: echo the build is "${APP_NAME}-${PULL_NUMBER}-${VERSION}-${BUILD_NUMBER}" and HONEYCOMB_BUILD_START=$(cat release_start)
      - name: release-honeycomb-build-send-success
        sh: ./buildevents build "${APP_NAME}-${PULL_NUMBER}-${VERSION}-${BUILD_NUMBER}" $(cat release_start) success
      type: after

```

### Steps to reproduce the behavior
Simply remove the `type:after` from the snippet above and insert it into your `jenkins-x.yml`

### Expected behavior
We should get an error, saying that the `type:` is required, to prevent users from overriding the entire pipeline stage.

### Actual behavior
No error message and pipeline executes but does not finish.

### Jx version
```
NAME               VERSION
jx                 2.0.294
jenkins x platform 2.0.768
Kubernetes cluster v1.12.8-gke.10
kubectl            v1.14.0
helm client        Client: v2.13.1+g618447c
git                git version 2.21.0
Operating System   Mac OS X 10.14.3 build 18D42
```

### Jenkins type

- [x ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

Created using `jx create cluster gke`

### Operating system / Environment

Running the CLI on my MacBook Pro (OS X)
