### ISSUE TITLE
Instructions on getting started are invalid for kops-based cluster

### ISSUE THREAD

**Issue by arun-gupta** [jenkins-x/jx#482]
Instructions at http://jenkins-x.io/getting-started/install-on-cluster/ show how to enable insecure registries. The suggested code fragment is:

```
...
spec:
  docker:
    insecureRegistry: 100.64.0.0/10
```

This should instead be:

```
spec:
  docker:
    insecureRegistry: 100.64.0.0/10
    logDriver: ""
```

This is also mentioned at https://github.com/kubernetes/kops/issues/42#issuecomment-375382118.
