### ISSUE TITLE
jx boot not creating valid tls certificates

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#4865]
### Summary 
Installing with jx boot and tls enabled results in wildcard certificates with an invalid issuer.

Inspecting the certificates shows an issuer of `cert-manager.local`

The cert-manager log contains many entries of the form:
```
E0726 11:43:44.078591       1 controller.go:200] cert-manager/controller/orders "msg"="re-queuing item  due to error processing" "error"="error creating new order: acme: urn:ietf:params:acme:error:malformed: Error creating new order :: Domain name \"hook-jx.kill-9.uk\" is redundant with a wildcard domain in the same request. Remove one or the other from the certificate request." "key"="jx/tls-kill-9-uk-p-1880648896"
```

### Jx version

The output of `jx version` is:

```
jx                 2.0.513
Kubernetes cluster v1.12.8-gke.10
kubectl            v1.14.2
helm client        Client: v2.14.0+g05811b8
git                git version 2.21.0
Operating System   Mac OS X 10.13.6 build 17G6030
```

**Comment by renatoaraujoc** [comment]
I confirm this issue, happening to me as well.

**Comment by renatoaraujoc** [comment]
For some very unknown and random reason, these wildcard certs **started working for me**... All I remember doing is changing the list order for the DNS on the issuers declaration, this is my `git diff` on env/templates/cert-manager-{prod/staging}-issuer.yaml i.e:

```yaml
solvers:
     - selector:
         dnsNames:
-        - "*.{{ .Values.cluster.domain }}"
         - "{{ .Values.cluster.domain }}"
-      # ACME DNS-01 provider configurations
+        - "*.{{ .Values.cluster.domain }}"
```

I was having Google Cloud DNS challenging issues because I use subdomain delegation for my cluster and I was getting that the root domain was not registered into GCloud DNS. The problem presented by @tdcox was also happening in the same cert-manager log.

What really happened...
The TLS certificate was being generated with

```yaml
dnsNames:
  - 'hook-jx.example.com'
```
Now is being generated correctly with:
```yaml
dnsNames:
  - '*.k8s.example.com
```

Hope I have helped.

Renato
