### ISSUE TITLE
Jenkins X 'dir' pipeline option doesn't work correctly

### ISSUE THREAD

**Issue by alexvolsh** [jenkins-x/jx#4966]
### Summary 
Option 'dir' in jenkins-x.yml configuration works incorrectly.

With the following configuration - build fails.
```
      promote:
        steps:
        - dir: ./charts/preview
          steps:
          - sh: make preview
            name: make-preview
```

But if I change configuration for the following - build executed successfully.
```
      promote:
        steps:
        - sh: cd ./charts/preview && make preview
          name: make-preview
```

### Steps to reproduce the behavior
Make changes and create pull request

### Expected behavior
Script executed successfully
```
sed -i -e "s/version:.*/version: 0.0.0-SNAPSHOT-PR-3-16/" Chart.yaml
sed -i -e "s/version:.*/version: 0.0.0-SNAPSHOT-PR-3-16/" ../*/Chart.yaml
sed -i -e "s|repository:.*|repository: dr.geeoz.com\/razomer\/razomer-web|" values.yaml
sed -i -e "s/tag:.*/tag: 0.0.0-SNAPSHOT-PR-3-16/" values.yaml
echo "  version: 0.0.0-SNAPSHOT-PR-3-16" >> requirements.yaml
jx step helm build
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Adding missing Helm repo: storage.googleapis.com https://storage.googleapis.com/chartmuseum.jenkins-x.io
Successfully added Helm repository storage.googleapis.com.
Adding missing Helm repo: jenkins-x-chartmuseum http://jenkins-x-chartmuseum:8080
Successfully added Helm repository jenkins-x-chartmuseum.
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Adding missing Helm repo: chartmuseum.jenkins-x.io http://chartmuseum.jenkins-x.io
Successfully added Helm repository chartmuseum.jenkins-x.io.
```

### Actual behavior
Command `make preview` failed with:
```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
make: getcwd: No such file or directory
make: *** No rule to make target `preview'.  Stop.
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.550
jenkins x platform 2.0.892
Kubernetes cluster v1.14.3
kubectl            v1.15.1
helm client        Client: v2.14.3+g0e7f3b6
git                git version 2.22.0
Operating System   Mac OS X 10.15 build 19A526h
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

Self-created with kubespray

### Operating system / Environment

Running the CLI on my MacBook Pro (OS X)
