### ISSUE TITLE
Error when running the dev environment master pipeline on a fresh boot cluster

### ISSUE THREAD

**Issue by dgozalo** [jenkins-x/jx#4984]
### Summary 
The result of running the master pipeline of the dev environment on a fresh GitOps `boot` install fails on the `kube-system` step with the following error:

```
Error from server (Forbidden): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"rbac.authorization.k8s.io/v1beta1\",\"kind\":\"ClusterRole\",\"metadata\":{\"annotations\":{\"jenkins.io/chart\":\"jxing\"},\"labels\":{\"app\":\"nginx-ingress\",\"chart\":\"nginx-ingress-1.11.4\",\"heritage\":\"Tiller\",\"jenkins.io/chart-release\":\"jxing\",\"jenkins.io/version\":\"2\",\"release\":\"jxing\"},\"name\":\"jxing-nginx-ingress\"},\"rules\":[{\"apiGroups\":[\"\"],\"resources\":[\"configmaps\",\"endpoints\",\"nodes\",\"pods\",\"secrets\"],\"verbs\":[\"list\",\"watch\"]},{\"apiGroups\":[\"\"],\"resources\":[\"nodes\"],\"verbs\":[\"get\"]},{\"apiGroups\":[\"\"],\"resources\":[\"services\"],\"verbs\":[\"get\",\"list\",\"update\",\"watch\"]},{\"apiGroups\":[\"extensions\",\"networking.k8s.io\"],\"resources\":[\"ingresses\"],\"verbs\":[\"get\",\"list\",\"watch\"]},{\"apiGroups\":[\"\"],\"resources\":[\"events\"],\"verbs\":[\"create\",\"patch\"]},{\"apiGroups\":[\"extensions\",\"networking.k8s.io\"],\"resources\":[\"ingresses/status\"],\"verbs\":[\"update\"]}]}\n"},"labels":{"jenkins.io/version":"2"}}}
to:
Resource: "rbac.authorization.k8s.io/v1beta1, Resource=clusterroles", GroupVersionKind: "rbac.authorization.k8s.io/v1beta1, Kind=ClusterRole"
Name: "jxing-nginx-ingress", Namespace: ""
```
The step is currently defined like this in the environment's `jenkins-x.yml` file:
```
name: kube-system
                dir: /workspace/source/systems/jxing
                command: jx
                args: ['step','helm','apply', '--boot', '--remote', '--no-vault', '--name', 'jxing']
                env:
                  - name: DEPLOY_NAMESPACE
                    value: kube-system
```

### Steps to reproduce the behavior
Create a fresh jx boot cluster, run the master pipeline for the dev environment, somehow get past the `Validate Git` step.

### Expected behavior

The pipeline should pass and apply the environment repository chart into the cluster.

### Actual behavior
Fails on the `kube-system` step.

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by pmuir** [comment]
Can be worked around by deleting ingress before running

**Comment by deanesmith** [comment]
Likely the template is incorrect.

**Comment by hferentschik** [comment]
@dgozalo:

> run the master pipeline for the dev environment

How exactly do you want me to do that?

I have a working cluster (created cluster manually using GKE console, cloned latest jenkins-x-boot-config (sha a5bef54de735), ran `jx boot` in checkout). What's next?

```
$ jx start pipeline
? Which pipeline do you want to start:   [Use arrows to move, space to select, type to filter]
> hf-bee/environment-hardy-boot-4984-production/master
  hf-bee/environment-hardy-boot-4984-staging/master
```

**Comment by hferentschik** [comment]
I guess the missing part was to enable `gitops: true` in `jx-requirements.yml`.

**Comment by dgozalo** [comment]
@hferentschik Yes, sorry, this was an error when running it GitOps mode. The master pipeline for the environment should be executed when adding an app, for example.

**Comment by hferentschik** [comment]
So here are the fully rendered templates this step tries to apply:

```yaml
---
# Source: jxing/charts/nginx-ingress/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: nginx-ingress
    chart: nginx-ingress-1.15.0
    heritage: Tiller
    release: release-name
  name: release-name-nginx-ingress
---
# Source: jxing/charts/nginx-ingress/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: nginx-ingress
    chart: nginx-ingress-1.15.0
    heritage: Tiller
    release: release-name
  name: release-name-nginx-ingress
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - nodes
      - pods
      - secrets
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - update
      - watch
  - apiGroups:
      - extensions
      - "networking.k8s.io" # k8s 1.14+
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - extensions
      - "networking.k8s.io" # k8s 1.14+
    resources:
      - ingresses/status
    verbs:
      - update
---
# Source: jxing/charts/nginx-ingress/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: nginx-ingress
    chart: nginx-ingress-1.15.0
    heritage: Tiller
    release: release-name
  name: release-name-nginx-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-name-nginx-ingress
subjects:
  - kind: ServiceAccount
    name: release-name-nginx-ingress
    namespace: jx
---
# Source: jxing/charts/nginx-ingress/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
    app: nginx-ingress
    chart: nginx-ingress-1.15.0
    heritage: Tiller
    release: release-name
  name: release-name-nginx-ingress
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - secrets
      - endpoints
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - update
      - watch
  - apiGroups:
      - extensions
      - "networking.k8s.io" # k8s 1.14+
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
      - "networking.k8s.io" # k8s 1.14+
    resources:
      - ingresses/status
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - ingress-controller-leader-nginx
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - create
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
# Source: jxing/charts/nginx-ingress/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    app: nginx-ingress
    chart: nginx-ingress-1.15.0
    heritage: Tiller
    release: release-name
  name: release-name-nginx-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-name-nginx-ingress
subjects:
  - kind: ServiceAccount
    name: release-name-nginx-ingress
    namespace: jx
---
# Source: jxing/charts/nginx-ingress/templates/controller-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-ingress
    chart: nginx-ingress-1.15.0
    component: "controller"
    heritage: Tiller
    release: release-name
  name: release-name-nginx-ingress-controller
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    app: nginx-ingress
    component: "controller"
    release: release-name
  type: "LoadBalancer"

---
# Source: jxing/charts/nginx-ingress/templates/default-backend-service.yaml

apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-ingress
    chart: nginx-ingress-1.15.0
    component: "default-backend"
    heritage: Tiller
    release: release-name
  name: release-name-nginx-ingress-default-backend
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: nginx-ingress
    component: "default-backend"
    release: release-name
  type: "ClusterIP"

---
# Source: jxing/charts/nginx-ingress/templates/controller-deployment.yaml

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx-ingress
    chart: nginx-ingress-1.15.0
    component: "controller"
    heritage: Tiller
    release: release-name
  name: release-name-nginx-ingress-controller
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    {}

  minReadySeconds: 0
  template:
    metadata:
      labels:
        app: nginx-ingress
        component: "controller"
        release: release-name
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - name: nginx-ingress-controller
          image: "quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.25.0"
          imagePullPolicy: "IfNotPresent"
          args:
            - /nginx-ingress-controller
            - --default-backend-service=jx/release-name-nginx-ingress-default-backend
            - --election-id=ingress-controller-leader
            - --ingress-class=nginx
            - --configmap=jx/release-name-nginx-ingress-controller
            - --publish-service=kube-system/jxing-nginx-ingress-controller
          securityContext:
            capabilities:
                drop:
                - ALL
                add:
                - NET_BIND_SERVICE
            runAsUser: 33
            allowPrivilegeEscalation: true
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          livenessProbe:
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          resources:
            {}

      hostNetwork: false
      serviceAccountName: release-name-nginx-ingress
      terminationGracePeriodSeconds: 60

---
# Source: jxing/charts/nginx-ingress/templates/default-backend-deployment.yaml

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx-ingress
    chart: nginx-ingress-1.15.0
    component: "default-backend"
    heritage: Tiller
    release: release-name
  name: release-name-nginx-ingress-default-backend
spec:
  replicas: 1
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: nginx-ingress
        component: "default-backend"
        release: release-name
    spec:
      containers:
        - name: nginx-ingress-default-backend
          image: "k8s.gcr.io/defaultbackend-amd64:1.5"
          imagePullPolicy: "IfNotPresent"
          args:
          securityContext:
            runAsUser: 65534
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {}

      terminationGracePeriodSeconds: 60

---
# Source: jxing/charts/nginx-ingress/templates/addheaders-configmap.yaml


---
# Source: jxing/charts/nginx-ingress/templates/controller-configmap.yaml


---
# Source: jxing/charts/nginx-ingress/templates/controller-daemonset.yaml


---
# Source: jxing/charts/nginx-ingress/templates/controller-hpa.yaml


---
# Source: jxing/charts/nginx-ingress/templates/controller-metrics-service.yaml


---
# Source: jxing/charts/nginx-ingress/templates/controller-poddisruptionbudget.yaml


---
# Source: jxing/charts/nginx-ingress/templates/controller-servicemonitor.yaml


---
# Source: jxing/charts/nginx-ingress/templates/default-backend-poddisruptionbudget.yaml


---
# Source: jxing/charts/nginx-ingress/templates/podsecuritypolicy.yaml


---
# Source: jxing/charts/nginx-ingress/templates/proxyheaders-configmap.yaml


---
# Source: jxing/charts/nginx-ingress/templates/tcp-configmap.yaml


---
# Source: jxing/charts/nginx-ingress/templates/udp-configmap.yaml
```
