### ISSUE TITLE
how to take effect nexus server?

### ISSUE THREAD

**Issue by blademainer** [jenkins-x/jx#4990]
### Summary 
How to change nexus server after install jenkins-x? There is a way to change nexus server url during installing, but there is no way to effect nexus config after installed platform.

### Steps to reproduce the behavior
kubectl edit cm jenkins-x-team-controller
```yaml
  myvalues.yaml: |-
    # disable stuff
    controllerteam:
      enabled: false
    pipelinecontroller:
      enabled: false
    monocular:
      enabled: false

    # service link nexus
    nexus:
      enabled: false
    nexusServiceLink:
      enabled: true
      externalName: "maven.hosted.com"

    # service link chartmuseum
    chartmuseum:
      enabled: false
    chartmuseumServiceLink:
      enabled: true
      externalName: "jenkins-x-chartmuseum.jx.svc.cluster.local"
```
after that, I deleted the pod: jenkins-x-controllerteam and jenkins, but this step not effect.

### Expected behavior
Nexus server config effect.

### Actual behavior
Still `nexus` pod

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.520
jenkins x platform 2.0.718
Kubernetes cluster v1.11.5
kubectl            v1.14.2
helm client        Client: v2.14.1+g5270352
git                git version 2.21.0
Operating System   Mac OS X 10.14.5 build 18F132
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [x] Classic Jenkins

### Kubernetes cluster

v1.11.5

### Operating system / Environment

macOS
