### ISSUE TITLE
jx boot ignores namespace

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/jx#5034]
### Summary 

I changed the `namespace` entry in `jx-requirements.yml` but the process ignored it and used the default `jx` Namespace.

```bash
cat jx-requirements.yml
```

```
cluster:
  clusterName: jx-rocks
  environmentGitOwner: vfarcic
  gitKind: github
  gitName: github
  gitServer: https://github.com
  namespace: jx-boot
  project: devops26
  provider: gke
  zone: us-east1
environments:
- key: dev
- key: staging
- key: production
gitops: true
ingress:
  domain: 35.231.148.184.nip.io
  externalDNS: false
  namespaceSubDomain: -jx-boot.
  tls:
    email: ""
    enabled: false
    production: false
kaniko: true
secretStorage: local
storage:
  logs:
    enabled: false
    url: ""
  reports:
    enabled: false
    url: ""
  repository:
    enabled: false
    url: ""
versionStream:
  ref: master
  url: https://github.com/cloudbees/cloudbees-jenkins-x-versions.git
webhook: prow
```

The end of the output of `jx boot`

```
...
verifying the git Secrets
verifying git Secret jx-pipeline-git-github-github
verifying git server github at https://github.com
found 11 organisations in git server https://github.com: TechnologyConversations, cloudbees, docker-captains, docker-flow, jenkins-x, jenkins-x-buildpacks, jenkins-x-quickstarts, jenkinsci, nuxeo, scbcn, serverless-quickstarts
git tokens seem to be setup correctly
valid: there is a Secret: kaniko-secret in namespace: jx
installation is currently looking: GOOD
switching to the namespace jx so that you can use jx commands on the installation
Using namespace 'jx' from context named 'gke_devops26_us-east1_jx-rocks' on server 'https://35.243.252.242'.
```

As can be seen from the output, it is using `jx` as the Namespace instead of `jx-boot` specified in `jx-requirements.yml`. To be sure...

```bash
kubectl get ns
```

The output...

```
NAME           STATUS   AGE
cert-manager   Active   14m
default        Active   20m
jx             Active   16m
kube-public    Active   20m
kube-system    Active   20m
```

### Steps to reproduce the behavior

Specified above.

### Expected behavior

`jx` is running in the specified Namespace.

### Actual behavior

`jx` is running in the default Namespace `jx`.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.558
Kubernetes cluster v1.12.8-gke.10
kubectl            v1.15.2
helm client        Client: v2.14.1+g5270352
git                git version 2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.6 build 18G87
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GKE

### Operating system / Environment

macOS

needs #5340
