### ISSUE TITLE
Jenkins-x YAML configuration for monorepo across internal folders

### ISSUE THREAD

**Issue by axsaucedo** [jenkins-x/jx#5042]
### Summary 
We have a monorepo with multiple microservices. It currently gets built using old Jenkins through a `Jenkinsfile` in each of the sub-folders containing the respective microservice, and a simple Jenkins job configured through the UI. For explicitness, the repository is something like:

```
monorepo/
- microservice1:
    - Jenkinsfile
    - ...other files
- microservice2:
    - Jenkinsfile
    - ...other files
```

Currently we are trying to explore having this project built using Jenkins X, and the idea would be to have a `jenkins-x.yml` file on each of each of the respective sub-folders containing the microservices. 

I have seen that there was functionality added to handle a "push folder to new repo" step through the `jx step split monorepo` step as per https://github.com/jenkins-x/jx/issues/822, however it seems that at least how we've attempted using it, it's not implemented as a core step that could be triggered through a jx base file.

The ideal way atm could be having a monorepo `jenkins-x.yml` file with contents similar to the following:
``` yaml
buildPack: monorepo
pipelineConfig:
  pipelines:
    release:
      build:
        steps:
          split: 
          - microservice1
          - microservice2
          - ...
```

### Edit: [Added extra thoughts]
It's worth mentioning that one of the main benefits we see by using a monorepo is the centralisation and alignment with PRs and Issues, which means that we would want to make sure that all the PROW notifications are provided in the monorepo, instead of the sub-repos. 

Given we have this constraint, ideally it would be possible to handle the steps without having to create a whole new monorepo for each of these microservices.

Is there a way to do this through the YAML? Alternatively how could it be triggered?

**Comment by axsaucedo** [comment]
It's worth mentioning that one of the main benefits we see by using a monorepo is the centralisation and alignment with PRs and Issues, which means that we would want to make sure that all the PROW notifications are provided in the monorepo, instead of the sub-repos. 

Given we have this constraint, ideally it would be possible to handle the steps without having to create a whole new monorepo for each of these microservices.

**Comment by l3m** [comment]
A monorepo is simply a pattern that often exists in the wide world, so support for it seems valuable as it opens up many additional potential users. 

Splitting the repo in many smaller repos is certainly a nice and quick way to handle it, but one of the benefits of a monorepo is that it's much easier to split and merge microservices as the code base grows. It seems to me that over time one quickly ends up with a ton of similarly named repos where it's unclear which ones are still used, which ones are relics etc. Hard to maintain... 

Initial support might be just allowing to specify a subdirectory into a monorepo and treating the subdir as root.

**Comment by valdestron** [comment]
Can we make this happen? Monorepos is very important in microservices world.

**Comment by valdestron** [comment]
I think we should make this topic alive and publish more approaches to monorepos using jx. As much as a I hate the ideology of service per repository, I am still willing to use Jenkins X and I still believe this might be very good tool.

Would be great to get help from Jenkins X developers on how to build more less generic jenkins-x.yaml, skaffold.yaml files for our monorepos.

I am starting by sharing my approaches and what issues I am having right now, correct me if my approaches are nonsense.

**Approach #1**
1. My monorepo structure (Nodejs/Typescript) looks something liek this
```markdown
├── OWNERS
├── OWNERS_ALIASES
├── README.md
├── aws-ecr.sh
├── charts
├── docker-compose.integration.yml
├── docker-compose.yml
├── docker-entrypoint-initdb.d
|  └── init.sh
├── identify_services.sh
├── jenkins-x.yml
├── jest.config.base.js
├── jest.config.js
├── lerna.json
├── microservices
|  ├── api-gateway
|  ├── api-gateway-deprecated
|  ├── api-gateway-reverse-proxy
|  ├── api-testsuite
|  ├── api-workers
|  ├── auth
|  ├── buyback
|  ├── devices
|  ├── frontend-admin
|  ├── integrations
|  ├── subscriptions
|  └── workflow-engine
├── package.json
├── skaffold.yaml
├── tmp
|  ├── cache
|  ├── localstack
|  └── postgres-data
├── tsconfig.json
├── tsconfig.spec.json
├── wait-for-service.sh
└── yarn.lock
```
2. Each service/subfolder has Dockerfile that has multistages. Looks something like this:
```Dokerfile
# First stage
# - installing dependencies and devDependencies
# - building dist
# ----------------------------------------------------------
FROM node:10-alpine as build

LABEL authors="Valdas Mazrimas <valdas.mazrimas@gmail.com>"

WORKDIR /srv/apigateway

COPY microservices/api-gateway ./microservices/api-gateway
COPY package.json yarn.lock tsconfig*.json jest.config*.js .eslintrc ./

RUN yarn install --pure-lockfile --non-interactive --cache-folder ./ycache; rm -rf ./ycache

WORKDIR /srv/apigateway/microservices/api-gateway

RUN yarn prod:build


# Second stage - unit tests
# - copying files from build stage
# - running unit tests against it
# - running lint
# ----------------------------------------------------------
FROM node:10-alpine as validate

WORKDIR /srv/apigateway

COPY --from=build /srv/apigateway .
WORKDIR /srv/apigateway/microservices/api-gateway

RUN yarn validate:test


# Third stage - start
# - install only dependencies
# - start app process
# ----------------------------------------------------------
FROM node:10-alpine as start

WORKDIR /srv/apigateway

COPY --from=build /root/.npmrc /root/.npmrc 
COPY --from=build /srv/apigateway/package.json /srv/apigateway/package.json
COPY --from=build /srv/apigateway/yarn.lock /srv/apigateway/yarn.lock
COPY --from=build /srv/apigateway/microservices/api-gateway/dist /srv/apigateway/microservices/api-gateway/dist
COPY --from=build /srv/apigateway/microservices/api-gateway/package.json /srv/apigateway/microservices/api-gateway/package.json
COPY --from=build /srv/apigateway/microservices/api-gateway/yarn.lock /srv/apigateway/microservices/api-gateway/yarn.lock

RUN yarn install --prod --pure-lockfile --non-interactive --cache-folder ./ycache; rm -rf ./ycache

WORKDIR /srv/apigateway/microservices/api-gateway

USER node

EXPOSE 3001

CMD ["yarn", "prod:run"]
```

Build command: `docker build . -f microservices/api-gateway/Dockerfile -t api-gateway`

3. jenkins-x.yaml looks something like this:
```yaml
buildPack: typescript
pipelineConfig:
  pipelines:
    pullRequest:
      build:
        replace: true
        steps:
          - name: container-build
            sh: export VERSION=$PREVIEW_VERSION && skaffold build -f skaffold.yaml
          - name: npmrc
            sh: echo 0
          - name: npm-install
            sh: echo 0
          - name: npm-test
            sh: echo 0
```

4. skaffold.yaml looks like this:
```yaml
apiVersion: skaffold/v1beta9
kind: Config
build:
  artifacts: 
    - image: api-gateway
      context: .
      kaniko:
        dockerfile: microservices/api-gateway/Dockerfile
        buildArgs:
           ... destination ecr repo
deploy: 
  kubectl: {}

Problems:
1. Kaniko executor is unable to run child dockerfile with the context as root.
2. I have identify_services.sh bash script which returns what services are changed, how to use it ?
3. I can use jenkins-x.yaml and build images with kaniko executor there and skaffold for deployment only, but then I do not know how to identify buildable services.

Problem with skaffold: https://github.com/GoogleContainerTools/skaffold/issues/3822

**Comment by hervelemeur** [comment]
@valdestron can you share the content of your identify_services.sh script?

In your approach you're building everything via Docker instead of tekton, not sure it"s the best way.

I'm intending to create a custom pipeline looping around all modified projects in the monorepo, and execute the different steps on each of them, but I'm just starting, nothing to show yet.

**Comment by valdestron** [comment]
> @valdestron can you share the content of your identify_services.sh script?
> 
> In your approach you're building everything via Docker instead of tekton, not sure it"s the best way.
> 
> I'm intending to create a custom pipeline looping around all modified projects in the monorepo, and execute the different steps on each of them, but I'm just starting, nothing to show yet.

Hmm, thats because I am not very familiar with tekton, Ill look at it. Completely agree that my aproach is not correct, looks too hard.

**Comment by valdestron** [comment]
Ok I succeeded to build CICD for monorepo using nothing more than jx. Ill prepare an example repository later after I finish the manifests part with helm.

Infra:
- AWS EKS
- 3 nodes x.large
- jx version 2.0.1243
- git provider: github
- file and folder structure the same as in previos comments

1. jenkins-x.yaml
```yaml
pipelineConfig:
  pipelines:
    pullRequest:
      pipeline:
        options:
          distributeParallelAcrossNodes: true
        agent:
          image: gcr.io/jenkinsxio/builder-nodejs12x:latest
        stages:
          - name: test-and-build-services
            options:
                volumes:
                  - name: docker-config
                    secret:
                      secretName: jenkins-docker-cfg
                  - name: aws-credentials
                    secret:
                      secretName: aws-creds
                containerOptions:
                  volumeMounts:
                    - name: docker-config
                      mountPath: /builder/home/.docker/
                    - name: aws-credentials
                      mountPath: /builder/home/.aws/
                      readOnly: false
            parallel:
              - name: batch-1-test-and-build
                steps:
                  - name: version
                    sh: export VERSION=$PREVIEW_VERSION
                  - name: setup-ecr
                    sh: ./scripts/aws-ecr.sh
                  - name: npmrc
                    sh: printf "@bit:registry=https://node.bit.dev%s\n//node.bit.dev/:_authToken=xxx" >> /builder/home/.npmrc
                  - name: npm-install
                    # sh: yarn install
                    sh: echo 0
                  - name: npm-test
                    # sh: CI=true DISPLAY=:99 yarn test
                    sh: echo 0
                  - name: build-images
                    sh: ./scripts/build.sh
```
Do not know if i need these parallels I might stick with just teckton tasks.

2. aws-ecr.sh script that creates ecr repositories of my monorepo services, kaniko unable to create them dynamically, does not matter..
```sh
#!/bin/bash

set -e

function setup_ecr() {
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    ./aws/install
    aws --version

}

function create_repos() {
  for D in `find microservices -maxdepth 1 -not -path microservices`
  do
    subdir=$(basename $D)
    region=eu-central-1
    access_key_id=$(cat ~/.aws/credentials | grep aws_access_key_id | awk 'BEGIN {FS="= "} {print $2}')
    secret_access_key=$(cat ~/.aws/credentials | grep aws_secret_access_key | awk 'BEGIN {FS="= "} {print $2}')
    AWS_ACCESS_KEY_ID=$access_key_id AWS_SECRET_ACCESS_KEY=$secret_access_key AWS_DEFAULT_REGION=$region aws ecr create-repository --repository-name sagahead-io/hector/${subdir} || true
  done
}


setup_ecr
create_repos
```

3. build.sh Script that helps to identify changed services
```sh
#!/bin/bash
set -e

service_name=${1:-'null'}

function upgrade_skaffold() {
    curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v1.6.0/skaffold-linux-amd64
    chmod +x skaffold
    mv skaffold /usr/local/bin
    skaffold version
}

function ok_to_build_service() {
    #$PULL_BASE_SHA
    changed_folders=`git diff --name-only $PULL_BASE_SHA..HEAD | grep microservices/ | awk 'BEGIN {FS="/"} {print $2}' | uniq`
    echo "$changed_folders"
}

function run_skaffold() {
    result=$(ok_to_build_service)
    services=""
    if [ ! -z "$result" ]; then
        echo $result | while read line; do
            for service in $line; do
                services+="$service,"
            done
            skaffold build -f skaffold.yaml --build-image=[$(echo ${services%$})] --cache-artifacts=false
        done
    fi
}

upgrade_skaffold
run_skaffold
```
