### ISSUE TITLE
Previews are not including changes from the PR

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#5064]
```
jx version
NAME               VERSION
jx                 2.0.586
Kubernetes cluster v1.12.8-gke.10
kubectl            v1.12.2
helm client        Client: v2.12.2+g7d2b0c7
git                2.21.0
Operating System   Mac OS X 10.12.6 build 16G1114
```

Just noticed that PR builds are cloning master and not the revision in the PR. To recreate 
- create a new cluster with `jx boot`
- `jx create quickstart` - I used nodejs and golang
- cd MY_NEW_APP
- `git checkout -b foo`
- [make code change and commit]
- `git push origin foo`
- create a pull request
- check preview link doesn't include change
- build logs show clone is for master and not the revision in the PR

Shout out to @abayer for helping disable meta pipeline in my cluster to work around the issue.

Workaround: `--use-meta-pipeline=false` on the `pipelinerunner` pod

/priority urgent-critical
/kind bug
/area pipeline

**Comment by abayer** [comment]
cc @hferentschik

**Comment by abayer** [comment]
Sounds like we really should have the quickstart and/or create spring BDD tests make a meaningful change in the PR phase and verify that the change actually showed up right.

**Comment by abayer** [comment]
Verification from a random PR's `tekton` context's run of the `create_spring` BDD test. Note that they're cloning the same ref in the metapipeline, and `master` is being checked out in the actual PR build.

Master build metapipeline: 

```
Showing logs for build cb-kubecd/bdd-spring-1565646118/master #1 stage app-extension and container step-git-source-meta-cb-kubecd-bdd-spring-15656-zvs2j
{"level":"warn","ts":1565646181.1916835,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/master\" is not a valid GitHub commit ID"}
{"level":"info","ts":1565646183.725724,"logger":"fallback-logger","caller":"git/git.go:102","msg":"Successfully cloned https://github.com/cb-kubecd/bdd-spring-1565646118.git @ 8bbbd664aa36fa560c39ea8adb765ce897ef9952 in path /workspace/source"}
```

PR build metapipeline:

```
Showing logs for build cb-kubecd/bdd-spring-1565646118/pr-1 #1 serverless-jenkins stage app-extension and container step-git-source-meta-cb-kubecd-bdd-spring-15656-xr286
{"level":"warn","ts":1565646547.4845898,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/master\" is not a valid GitHub commit ID"}
{"level":"info","ts":1565646548.8082955,"logger":"fallback-logger","caller":"git/git.go:102","msg":"Successfully cloned https://github.com/cb-kubecd/bdd-spring-1565646118.git @ 8bbbd664aa36fa560c39ea8adb765ce897ef9952 in path /workspace/source"}
```

PR build actual pipeline:
```
Showing logs for build cb-kubecd/bdd-spring-1565646118/pr-1 #1 serverless-jenkins stage from-build-pack and container step-git-source-cb-kubecd-bdd-spring-1565646118-vlw8l
{"level":"warn","ts":1565646569.5590947,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/master\" is not a valid GitHub commit ID"}
{"level":"info","ts":1565646570.8200197,"logger":"fallback-logger","caller":"git/git.go:102","msg":"Successfully cloned https://github.com/cb-kubecd/bdd-spring-1565646118.git @ master in path /workspace/source"}
```

**Comment by hferentschik** [comment]
I think this might be related or a duplicate of issue #5043. Looks like we are not passing along all required env variables.

**Comment by hferentschik** [comment]
This also relates to issue #4821. We really need imo a list of required variables we expect to be set for any pipeline run. This is also important in terms of Apps and extending a pipeline. These variables are really part of the contract for pipeline execution.

**Comment by hferentschik** [comment]
And there is a relation to issue #4641 as well. Once we have a meta pipeline setup where meta pipeline and build pipeline actually do share the same value, there is no need anymore to do a merge in the build pipeline. For now we still need it though.

**Comment by hferentschik** [comment]
Looking at the meta pipeline, it seems it tries to pass all the required information. For example the `step create task` step in the meta pipeline looking at the generated task CRD looks like:

```yaml
  - args:
    - jx step create task --clone-dir /workspace/source --kind pullrequest --pr-number
      1 --service-account tekton-bot --source source --branch PR-1 --build-number
      4 --context promotion-build --label created-by-prow=true --label prowJobName=590b0e8a-bda5-11e9-b8a0-62b0333a6472
      --env PULL_BASE_REF=master --env PULL_BASE_SHA=1af3d0da886939d3197677c768b39be145a9dea2
      --env PULL_NUMBER=1 --env JOB_NAME=promotion-build --env BUILD_ID= --env JOB_SPEC={"type":"presubmit","job":"promotion-build","refs":{"org":"hf-bee","repo":"go-test","base_ref":"master","base_sha":"1af3d0da886939d3197677c768b39be145a9dea2","pulls":[{"number":1,"author":"hferentschik","sha":"e94912afd0b4054f515cf5669e6aec422b47734a"}]}}
      --env REPO_OWNER=hf-bee --env PULL_PULL_SHA=e94912afd0b4054f515cf5669e6aec422b47734a
      --env PROW_JOB_ID= --env JOB_TYPE=presubmit --env REPO_NAME=go-test --env PULL_REFS=master:1af3d0da886939d3197677c768b39be145a9dea2,1:e94912afd0b4054f515cf5669e6aec422b47734a
    command:
    - /bin/sh
    - -c
```

All env variables specified via `--env` should be passed through to the generated step of the build Task CRD. When I run the above command locally this is the case, however, this is not the case for when this runs in the cluster. Not quite sure yet what's going on. @abayer, does any of this ring a bell?

**Comment by hferentschik** [comment]
Looking in the GKE console at the information for the _step-create-tekton-crds_ container, I only see the arguments:

```
-wait_file /builder/tools/3 -post_file /builder/tools/4 -entrypoint /bin/sh -- -c jx step create task --clone-dir /workspace/source --kind pullrequest --pr-number 1 --service-account tekton-bot --source source --branch PR-1 
```

So unless for some reason not the full command is displayed, it seems that Tekton chopped off parts of the command? @abayer, is that a possibility?

**Comment by hferentschik** [comment]
Actually looking at the actual pod running the meta pipeline I see:

```yaml
  - args:
    - -wait_file
    - /builder/tools/3
    - -post_file
    - /builder/tools/4
    - -entrypoint
    - /bin/sh
    - --
    - -c
    - jx step create task --clone-dir /workspace/source --kind pullrequest --pr-number
      1 --service-account tekton-bot --source source --branch PR-1 --build-number
      8 --context promotion-build --label created-by-prow=true --label prowJobName=67f2d22e-bddb-11e9-b341-4e8910d7f231
      --env PULL_NUMBER=1 --env PROW_JOB_ID= --env JOB_TYPE=presubmit --env JOB_SPEC={"type":"presubmit","job":"promotion-build","refs":{"org":"hf-bee","repo":"go-test","base_ref":"master","base_sha":"1af3d0da886939d3197677c768b39be145a9dea2","pulls":[{"number":1,"author":"hferentschik","sha":"e94912afd0b4054f515cf5669e6aec422b47734a"}]}}
      --env REPO_OWNER=hf-bee --env REPO_NAME=go-test --env PULL_BASE_SHA=1af3d0da886939d3197677c768b39be145a9dea2
      --env PULL_REFS=master:1af3d0da886939d3197677c768b39be145a9dea2,1:e94912afd0b4054f515cf5669e6aec422b47734a
      --env PULL_PULL_SHA=e94912afd0b4054f515cf5669e6aec422b47734a --env JOB_NAME=promotion-build
      --env BUILD_ID= --env PULL_BASE_REF=master
    command:
    - /builder/tools/entrypoint
    env:
    - name: HOME
      value: /builder/home
    - name: APP_NAME
      value: go-test
    - name: BRANCH_NAME
      value: PR-1
    - name: BUILD_ID
    - name: BUILD_NUMBER
      value: "8"
    - name: DOCKER_CONFIG
      value: /home/jenkins/.docker/
    - name: DOCKER_REGISTRY
      valueFrom:
        configMapKeyRef:
          key: docker.registry
          name: jenkins-x-docker-registry
    - name: GIT_AUTHOR_EMAIL
      value: jenkins-x@googlegroups.com
    - name: GIT_AUTHOR_NAME
      value: jenkins-x-bot
    - name: GIT_COMMITTER_EMAIL
      value: jenkins-x@googlegroups.com
    - name: GIT_COMMITTER_NAME
      value: jenkins-x-bot
    - name: JENKINS_URL
      value: http://jenkins:8080
    - name: JOB_NAME
      value: promotion-build
    - name: JOB_SPEC
      value: '{"type":"presubmit","job":"promotion-build","refs":{"org":"hf-bee","repo":"go-test","base_ref":"master","base_sha":"1af3d0da886939d3197677c768b39be145a9dea2","pulls":[{"number":1,"author":"hferentschik","sha":"e94912afd0b4054f515cf5669e6aec422b47734a"}]}}'
    - name: JOB_TYPE
      value: presubmit
    - name: JX_LOG_FORMAT
      value: json
    - name: MAVEN_OPTS
      value: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    - name: PIPELINE_CONTEXT
      value: promotion-build
    - name: PIPELINE_KIND
      value: pullrequest
    - name: PROW_JOB_ID
    - name: PULL_BASE_REF
      value: master
    - name: PULL_BASE_SHA
      value: 1af3d0da886939d3197677c768b39be145a9dea2
    - name: PULL_NUMBER
      value: "1"
    - name: PULL_PULL_SHA
      value: e94912afd0b4054f515cf5669e6aec422b47734a
    - name: PULL_REFS
      value: master:1af3d0da886939d3197677c768b39be145a9dea2,1:e94912afd0b4054f515cf5669e6aec422b47734a
    - name: REPO_NAME
      value: go-test
    - name: REPO_OWNER
      value: hf-bee
    - name: SOURCE_URL
      value: https://github.com/hf-bee/go-test.git
    - name: XDG_CONFIG_HOME
      value: /home/jenkins
    - name: _JAVA_OPTIONS
      value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true
        -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4
        -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx192m
    image: gcr.io/jenkinsxio/builder-maven:0.1.634
```

So `jx step create task` seems to get all the required information, but if I then look at the pod for the build pipeline I see:

```
 - args:
    - -wait_file
    - /builder/tools/0
    - -post_file
    - /builder/tools/1
    - -entrypoint
    - jx
    - --
    - step
    - git
    - merge
    - --verbose
    command:
    - /builder/tools/entrypoint
    env:
    - name: HOME
      value: /builder/home
    - name: DOCKER_REGISTRY
      valueFrom:
        configMapKeyRef:
          key: docker.registry
          name: jenkins-x-docker-registry
    - name: DOCKER_CONFIG
      value: /home/jenkins/.docker/
    - name: GIT_AUTHOR_EMAIL
      value: jenkins-x@googlegroups.com
    - name: GIT_AUTHOR_NAME
      value: jenkins-x-bot
    - name: GIT_COMMITTER_EMAIL
      value: jenkins-x@googlegroups.com
    - name: GIT_COMMITTER_NAME
      value: jenkins-x-bot
    - name: XDG_CONFIG_HOME
      value: /workspace/xdg_config
    - name: BUILD_NUMBER
      value: "9"
    - name: PIPELINE_KIND
      value: pullrequest
    - name: PIPELINE_CONTEXT
      value: promotion-build
    - name: REPO_OWNER
      value: hf-bee
    - name: REPO_NAME
      value: go-test
    - name: JOB_NAME
      value: hf-bee/go-test/PR-1
    - name: APP_NAME
      value: go-test
    - name: BRANCH_NAME
      value: PR-1
    - name: JX_BATCH_MODE
      value: "true"
    - name: VERSION
      value: 0.0.0-SNAPSHOT-PR-1-9
    - name: BUILD_ID
      value: "9"
    - name: PREVIEW_VERSION
      value: 0.0.0-SNAPSHOT-PR-1-9
    image: gcr.io/jenkinsxio/builder-jx:0.1.635
```

The env variables specified via `--env`, in particular PULL_REF in this case, are not there.
