### ISSUE TITLE
jx quickstart with On-Prem Github Enterprise Fails

### ISSUE THREAD

**Issue by chaseconey** [jenkins-x/jx#511]
It seems like the `jx create quickstart` does not work when trying to target a different git server that is not github.com. I have added the node-http quickstart to our org and still can't seem to get it to pick up.

**Command Run:** `jx create quickstart -g other-org`

**Expected Result:** node-http quickstart to show up

**Actual Result:** error: No quickstarts match filter

**Version Output:**

```
jx             1.1.32
Jenkins X      0.0.393
Kubernetes     v1.8.9
Helm Client    v2.8.1+g6af75a8
Helm Server    v2.8.1+g6af75a8
Kubectl Client v1.9.5
Git            git version 2.16.2
```

**Comment by rawlingsj** [comment]
Thanks for reporting, I think the current logic wont prompt for new git server auth details if it doesn't match the original git server that was used in the install.

Yes it definitely is a bug and one we should hopefully be able to fix very soon.

I you wanted to try something in the meantime I wonder if you edit your `~/.jx/gitAuth.yaml` file and add another `server` section, easier to copy an existing one assuming github was originally used during the install.

Then add the details of your github enterprise server, e.g.
```
- url: my.github.server.io
  users:
  - username: [login user]
    apitoken: [a personal access token]
  name: GitHubEnterprise
  kind: GitHub
  currentuser: [login user]
```

That may work but we'll try and get this fixed up this week.
