### ISSUE TITLE
Slack reporting through upgrading Crier image

### ISSUE THREAD

**Issue by axsaucedo** [jenkins-x/jx#5115]
### Expected behavior
Enable slack reporting by adding the `--slack-workers=n` and `--slack-token-file=/path/to/slack/token` flags to the Crier container.

### Actual behavior
Slack reporter flags are not supported, so Crier container crashes if they are provided.

### Potential Solution
Based on latest configuration in Prow repo, the changes would involve something similar to the following modifications in the configurations.

In regards to the crier deployment, the following configuration would be required (the image would be the updated jenkins-x version instead of the default Crier image):
``` yaml
...
        image: gcr.io/k8s-prow/crier:v20190814-9981dc3c5
...
      - args:
        - ...
        - -slack-workers=1
        - -slack-token-file=/etc/slack/slack-token
...
        volumeMounts:
        - mountPath: /etc/slack
          name: slack-token
          readOnly: true
...
      volumes:
      - name: slack-token
        secret:
          defaultMode: 420
          secretName: slack-token
...
```
Then adding the following in the `config` configmap in the `jx namespace`:
``` yaml
...
    slack_reporter:
      job_types_to_report:
      - presubmit
      - postsubmit
      - periodic
      - batch
      job_states_to_report:
      - triggered
      - pending
      - success
      - failure
      - aborted
      - error
      channel: tech
      report_template: 'Job {{.Spec.Job}} of type {{.Spec.Type}} ended with state {{.Status.State}}. <{{.Status.URL}}|View logs>'
```
