### ISSUE TITLE
Unable to use vault substitutions in user app

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#5141]
### Summary 
I don't seem to be able to use vault within a jx build in the same way that the platform utilises it.

### Steps to reproduce the behavior
Create KV pairs in default cluster vault using the vault CLI tool:
```
jx get vault-config
export VAULT_ADDR etc
vault login (with token from above)
vault kv put secret/admin/mysecret admin-username=zig admin-password=pass1  system-username=zag system-password=pass2
```
This works.

Add credential references to `values.yaml` in app chart:
```
credentials:
  admin:
    username: vault:secret/admin/mysecret:admin-username
    password: vault:secret/admin/mysecret:admin-password
  system:
    username: vault:secret/admin/mysecret:system-username
    password: vault:secret/admin/mysecret:system-password
``` 
and create a credential-secret.yaml in templates which includes the section:
```
data:
  admin-username: {{ .Values.credentials.admin.username | b64enc | quote }}
  admin-password: {{ .Values.credentials.admin.password | b64enc | quote }}
  system-username: {{ .Values.credentials.system.username | b64enc | quote }}
  system-password: {{ .Values.credentials.system.password | b64enc | quote }}
```

Modify the pod template to mount the secrets as files.

Commit, push and build.

### Expected behavior
jx would make the substitution so that the vault: references are replaced with the values from vault in the K8S secrets.

### Actual behavior
K8S secrets are created and mounted but contain the literals `vault:secret/admin/mysecret:system-username` etc.

No errors are reported.

### Jx version

The output of `jx version` is:

```
2.0.582
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GKE
