### ISSUE TITLE
Docker registry persistence

### ISSUE THREAD

**Issue by oleksiidzhulai** [jenkins-x/jx#518]
Hi Team,

Just noticed that docker registry data doesn't survive pod restart.

```
        volumeMounts:
        - mountPath: /var/lib/registry/
          name: data
        - mountPath: /etc/docker/registry
          name: jenkins-x-docker-registry-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: data
      - configMap:
          defaultMode: 420
          name: jenkins-x-docker-registry-config
        name: jenkins-x-docker-registry-config
```

This happens after initial `jx install `.
```
$ jx version
NAME           VERSION
jx             1.1.35
Jenkins X      0.0.393
Kubernetes     v1.8.8-gke.0
Helm Client    v2.8.2+ga802316
Helm Server    v2.8.2+ga802316
Kubectl Client v1.8.6
Git            git version 2.16.1
```

In order to fix I run
`jx upgrade platform`

```
jx version
NAME           VERSION
jx             1.1.35
Jenkins X      0.0.486
Kubernetes     v1.8.8-gke.0
Helm Client    v2.8.2+ga802316
Helm Server    v2.8.2+ga802316
Kubectl Client v1.8.6
Git            git version 2.16.1
```

Is it intentional ? 
If yes why an outdated "platform" is loaded from the beginning?

Thanks
