### ISSUE TITLE
Overriding entire pipeline fails

### ISSUE THREAD

**Issue by sharepointoscar** [jenkins-x/jx#5183]
### Summary 
I am trying to run a custom pipeline that worked previously with the `yaml` below.  Now I get an error as shown below.

**NOTE:**  I noticed if I remove the `buildPack: none` at the top of the yaml file, then it does not error out.

### Steps to reproduce the behavior
Simply add the `yaml` to your `jenkins-x.yml` file and do a pull request.

### Expected behavior
The pipeline runs and the logs shows the custom steps. Using the following definition

```yaml
buildPack: none
pipelineConfig:
  pipelines:
    release:
      pipeline:
        agent:
          image: sharepointoscar/node:8
        stages:
          - name: Oscar Build Stage
            steps:
              - name: Get Node Version
                command: node
                args:
                  - --version
              - name: NPM Installar Por Favor
                command: npm
                args: 
                  - install               
            options:
              containerOptions:
                resources:
                  limits:
                    cpu: 0.4
                    memory: 256Mi
                  requests:
                    cpu: 0.2
                    memory: 128Mi
          - name: Oscar Test Stage
            steps:
              - name: Run MochaJS Tests
                command: npm
                args:
                  - test
            options:
              containerOptions:
                resources:
                  limits:
                    cpu: 0.4
                    memory: 256Mi
                  requests:
                    cpu: 0.2
                    memory: 128Mi
```

### Actual behavior
I get the error listed below.

```
Showing logs for build jenkins-oscar/sp-webpart/pr-1 #14 serverless-jenkins stage app-extension and container step-create-effective-pipeline
{"level":"info","msg":"Deleting and cloning the Jenkins X versions repo","time":"2019-08-22T23:26:27Z"}
{"level":"info","msg":"Cloning the Jenkins X versions repo https://github.com/jenkins-x/jenkins-x-versions.git with ref refs/heads/master to /builder/home/.jx/jenkins-x-versions","time":"2019-08-22T23:26:27Z"}
{"level":"info","msg":"Effective pipeline written to jenkins-x-serverless-jenkins-effective.yml","time":"2019-08-22T23:26:29Z"}

Showing logs for build jenkins-oscar/sp-webpart/pr-1 #14 serverless-jenkins stage app-extension and container step-create-tekton-crds
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x11dcb4a]

goroutine 1 [running]:
github.com/jenkins-x/jx/pkg/tekton/syntax.(*ParsedPipeline).GenerateCRDs(0x0, 0xc00050b1a0, 0x25, 0x7ffde6032651, 0x2, 0xc000dc2440, 0x1f, 0xc000645ddc, 0x2, 0xc0005461e0, ...)
	/workspace/source/pkg/tekton/syntax/pipeline.go:1523 +0x3a
github.com/jenkins-x/jx/pkg/cmd/step/create.(*StepCreateTaskOptions).generateTektonCRDs(0xc0003222c0, 0xc0006c0630, 0xc000645ddc, 0x2, 0xc00050b1a0, 0x25, 0xc000dc2440, 0x1f, 0x0, 0x53267c0, ...)
	/workspace/source/pkg/cmd/step/create/step_create_task.go:543 +0x18f
github.com/jenkins-x/jx/pkg/cmd/step/create.(*StepCreateTaskOptions).Run(0xc0003222c0, 0x0, 0x0)
	/workspace/source/pkg/cmd/step/create/step_create_task.go:323 +0x66a
github.com/jenkins-x/jx/pkg/cmd/step/create.NewCmdStepCreateTaskAndOption.func1(0xc000624500, 0xc0000bc380, 0x8, 0x34)
	/workspace/source/pkg/cmd/step/create/step_create_task.go:146 +0x6f
github.com/spf13/cobra.(*Command).execute(0xc000624500, 0xc0000bc000, 0x34, 0x38, 0xc000624500, 0xc0000bc000)
	/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002ae280, 0xc00034c550, 0x530c2c0, 0xc00000e010)
	/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
	/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/jenkins-x/jx/cmd/jx/app.Run(0x0, 0x0, 0x0, 0xc0009eff88, 0xc0000a0058)
	/workspace/source/cmd/jx/app/jx.go:19 +0x147
main.main()
	/workspace/source/cmd/jx/jx.go:11 +0x32

Pipeline failed on stage 'app-extension' : container 'step-create-tekton-crds'. The execution of the pipeline has stopped.
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.598
jenkins x platform 2.0.951
Kubernetes cluster v1.12.8-gke.10
kubectl            v1.15.3
helm client        Client: v2.13.1+g618447c
git                2.21.0
Operating System   Mac OS X 10.14.3 build 18D42
```

### Jenkins type

- [ x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster
What kind of Kubernetes cluster are you using & how did you create it?
Using GKE, used the following command to create cluster:

```bash
jx create cluster -n mycluster --tekton --no-tiller --default-admin-password=mypassword
```

### Operating system / Environment

In which environment are you running the jx CLI?
OS X Mojave 10.14.3
