### ISSUE TITLE
How to specify eksctl cluster and node groups specific values if using `jx create cluster eks`?

### ISSUE THREAD

**Issue by stepanselyuk** [jenkins-x/jx#5357]
### Summary

How to specify eksctl cluster and node groups specific values if using `jx create cluster eks`? 

If I would create the cluster via `eksctl` itself, I would use like this config:

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev-cluster
  region: us-west-2

nodeGroups:
  - name: ng-default
    labels:
      purpose: mixed
    instanceType: m5.large
    amiFamily: Ubuntu1804
    desiredCapacity: 2
    volumeSize: 50
    volumeType: gp2
    volumeEncrypted: true
    ssh:
      publicKeyName: dev-cluster
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        xRay: true
        cloudWatch: true
    kubeletExtraConfig:
      kubeReserved:
        cpu: "300m"
        memory: "300Mi"
        ephemeral-storage: "1Gi"
      kubeReservedCgroup: "/kube-reserved"
      systemReserved:
        cpu: "300m"
        memory: "300Mi"
        ephemeral-storage: "1Gi"
      evictionHard:
        memory.available:  "200Mi"
        nodefs.available: "10%"
      featureGates:
        DynamicKubeletConfig: true
        RotateKubeletServerCertificate: true # has to be enabled, otherwise it will be disabled

cloudWatch:
  clusterLogging:
    # enable specific types of cluster control plane logs
    enableTypes: ["audit", "authenticator", "controllerManager"]
    # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
    # supported special values: "*" and "all"
```

In `jx create cluster eks` I can specify only a few related options and I did not find any example how to specify I want to use custom `eksctl` cluster configuration.
