### ISSUE TITLE
Add sonarqube addon

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#536]
So that pipelines invoke sonarqube - either via the SaaS service or a sonarqube chart

**Comment by yuntsewu** [comment]
Please add this

**Comment by amuniz** [comment]
There is a chart for SonarQube in https://github.com/helm/charts/tree/master/stable/sonarqube that could be useful for this task.

**Comment by icereed** [comment]
Super useful for us!

**Comment by ccojocar** [comment]
I think the SonarQube can be installed now as an application. 

cc @pmuir

**Comment by pmuir** [comment]
@deanesmith is still working on it

**Comment by Cervator** [comment]
@deanesmith: any update soonish? Inquiring minds wish to knew :-) Would be happy to help test and maybe tweak at it a bit

**Comment by deanesmith** [comment]
@Cervator we have been addressing other jx related matters specific to addons (we refer to them as apps), but I may have some bandwidth to pick this back up.  The case of invoking SonarQube from a pipeline is straightforward

**Comment by gazal-k** [comment]
I tried setting up sonarqube using helm. And it works quite well. Only problem I have is that Jenkins X sets up a network load balancer in AWS for itself and other apps like Nexus. But the helm chart for sonarqube sets up an additional load balancer; a classic load balancer. Is there any way to tweak the helm chart configuration for sonarqube to use the existing NLB?

**Comment by nukepuppy** [comment]
been avoiding doing this via helm due to the fact the load balancer stuff would come up as @gazal-k  mentioned.. but also on top of that.. the integration become a bit ad-hoc and require some possible manual nonsense to integrate automatically in a jxified way

**Comment by nukepuppy** [comment]
> I tried setting up sonarqube using helm. And it works quite well. Only problem I have is that Jenkins X sets up a network load balancer in AWS for itself and other apps like Nexus. But the helm chart for sonarqube sets up an additional load balancer; a classic load balancer. Is there any way to tweak the helm chart configuration for sonarqube to use the existing NLB?

Also curious about this too...   I know the helm sonarqube has some ingress options that could be passed/ignored

**Comment by nukepuppy** [comment]
ping

**Comment by gazal-k** [comment]
> > I tried setting up sonarqube using helm. And it works quite well. Only problem I have is that Jenkins X sets up a network load balancer in AWS for itself and other apps like Nexus. But the helm chart for sonarqube sets up an additional load balancer; a classic load balancer. Is there any way to tweak the helm chart configuration for sonarqube to use the existing NLB?
> 
> Also curious about this too... I know the helm sonarqube has some ingress options that could be passed/ignored

Sorry, I haven't tried tweaking it yet.

**Comment by afirth** [comment]
> I tried setting up sonarqube using helm. And it works quite well. Only problem I have is that Jenkins X sets up a network load balancer in AWS for itself and other apps like Nexus. But the helm chart for sonarqube sets up an additional load balancer; a classic load balancer. Is there any way to tweak the helm chart configuration for sonarqube to use the existing NLB?

It seems the helm chart supports setting `service.type`. If you set this to ClusterIP and make sure your ingress controller picks it up (by `ingress.class` for example) you should be able to add it to the existing LB.

**Comment by gazal-k** [comment]
> > I tried setting up sonarqube using helm. And it works quite well. Only problem I have is that Jenkins X sets up a network load balancer in AWS for itself and other apps like Nexus. But the helm chart for sonarqube sets up an additional load balancer; a classic load balancer. Is there any way to tweak the helm chart configuration for sonarqube to use the existing NLB?
> 
> It seems the helm chart supports setting `service.type`. If you set this to ClusterIP and make sure your ingress controller picks it up (by `ingress.class` for example) you should be able to add it to the existing LB.

Thanks for the tip. I'll give it a go

**Comment by gazal-k** [comment]
After a lot of fiddling, I finally got the ingress working with the existing NLB

Create custom values for `stable/sonarqube` in `sonarqube.yml`

```yml
service:
  type: ClusterIP
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
```

Install the chart using jx:

```sh
jx step helm install --set-file sonarqube.yml --name <releaseName> stable/sonarqube
```

Create the Ingress:

```yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sonarqube
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: sonarqube.jx.<customDomain>
    http:
      paths:
      - path: /
        backend:
          serviceName: <releaseName>-sonarqube
          servicePort: 9000
```
