### ISSUE TITLE
`jx boot` environmentGitPrivate key in jx-requirements.yaml

### ISSUE THREAD

**Issue by stepanselyuk** [jenkins-x/jx#5372]
### Summary 

I see the message: 
```
Will create public environment repos, if you want to create private environment repos, please set environmentGitPrivate to true jx-requirements.yaml
```

### Steps to reproduce the behavior

`jx boot`

### Expected behavior

Allow using `environmentGitPrivate` key in jx-requirements.yaml

### Actual behavior

Says there is no `environmentGitPrivate` key support in the structure and additional fields do not allowed.

### Jx version

The output of `jx version` is:

```
jx                 2.0.689
Kubernetes cluster v1.13.10-eks-5ac0f1
kubectl            v1.15.3
git                2.23.0
Operating System   Mac OS X 10.14.6 build 18G95
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

Created by `eksctl`

### Operating system / Environment

Operating System   Mac OS X 10.14.6 build 18G95

**Comment by cagiti** [comment]
@stepanselyuk are you able to share and example `jx-requirements.yml` showing the use of environmentGitPrivate? Thanks

**Comment by stepanselyuk** [comment]
I've added `environmentGitPrivate ` key on top-level:
```
cluster:
  clusterName: cdp-dev
  environmentGitOwner: redacted
  gitKind: github
  gitName: github
  gitServer: https://github.com
  namespace: jx
  project: cdp-dev
  provider: eks
  zone: us-west-2
environments:
- key: dev
- key: staging
- key: production
gitops: true
# here
environmentGitPrivate: true
ingress:
  domain: redacted-dev.com
  externalDNS: true
  namespaceSubDomain: -jx.
  tls:
    email: redacted@redacted.com
    enabled: true
    production: true
kaniko: true
secretStorage: vault
storage:
  logs:
    enabled: true
    url: s3://jx-cdp-dev/logs/
  reports:
    enabled: true
    url: s3://jx-cdp-dev/reports/
  repository:
    enabled: true
    url: s3://jx-cdp-dev/repository/
versionStream:
  ref: master
  url: https://github.com/jenkins-x/jenkins-x-versions.git
webhook: prow
```
