### ISSUE TITLE
Replace the use of step credentials command with volume mounts in all pipeline files

### ISSUE THREAD

**Issue by ccojocar** [jenkins-x/jx#5422]
### Summary 

Replace the use of `step credentials` command for setting secrets in environment variables or files in the build PODs with the use of volume mounts in all pipeline files. 

This is an example how to mount a secret into a volume:

```
buildPack: none
pipelineConfig:
  pipelines:
    pullRequest:
      pipeline:
        options:
        environment:
          - name: GKE_SA
            value: /secrets/bdd/sa.json
        agent:
          image: gcr.io/jenkinsxio/builder-go-maven
        stages:
          - name: ci
            options:
              volumes:
                - name: sa
                  secret:
                    secretName: bdd-secret
                    items:
                      - key: bdd-credentials.json
                        path: bdd/sa.json
              containerOptions:
                volumeMounts:
                  - mountPath: /secrets
                    name: sa
            steps:
              - name: run-script
                command: script.sh
```

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [x ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins
