### ISSUE TITLE
skaffold build -f skaffold.yaml doesn't translate skaffold.yaml modifications to jenkins-x.yaml

### ISSUE THREAD

**Issue by renatoaraujoc** [jenkins-x/jx#5447]
### Summary 
On `jenkins-x.yaml` pipeline ``sh: export VERSION=`cat VERSION` && skaffold build -f skaffold.yaml`` won't correctly translate any modification made on project's `skaffold.yaml`.

### Steps to reproduce the behavior
Modify anything on `skaffold.yaml` like: 
```yaml
apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
  - image: repo/app_name
    context: .
    docker:
      buildArgs:
        PROD: "true" # THIS IS NEW
...
```
### Expected behavior
`jx step syntax effective` **should** translate `build-container-build` step into:
```yaml
- args:
- --build-arg=PROD=true # <--- this should be included
- --cache=true
- --cache-dir=/workspace
- --context=/workspace/source
- --dockerfile=/workspace/source/Dockerfile
- --destination=gcr.io/repo/app_name:${inputs.params.version}
- --cache-repo=gcr.io/repo/cache
command: /kaniko/executor
dir: /workspace/source
image: gcr.io/kaniko-project/executor:9912ccbf8d22bbafbf971124600fbb0b13b9cbd6
name: build-container-build
```
### Actual behavior
`jx step syntax effective` simply does not read the local skaffold.yaml file and outputs this:
```yaml
- args:
- --cache=true
- --cache-dir=/workspace
- --context=/workspace/source
- --dockerfile=/workspace/source/Dockerfile
- --destination=gcr.io/repo/app_name:${inputs.params.version}
- --cache-repo=gcr.io/repo/cache
command: /kaniko/executor
dir: /workspace/source
image: gcr.io/kaniko-project/executor:9912ccbf8d22bbafbf971124600fbb0b13b9cbd6
name: build-container-build
```
**Important!** `jx step syntax effective` will output the **same thing** even if you make syntax errors or delete `skaffold.yaml` from your project.
### Jx version

The output of `jx version` is:

```
 ~ jx version
NAME               VERSION
jx                 2.0.712
Kubernetes cluster v1.13.7-gke.24
kubectl            v1.15.1
helm client        Client: v2.14.2+ga8b13cc
git                2.22.0
Operating System   Mac OS X 10.12.6 build 16G2128
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins
