### ISSUE TITLE
jx boot will purge ingress.domain before step create-install-values

### ISSUE THREAD

**Issue by dove-young** [jenkins-x/jx#5496]
### Summary 

`jx boot` will purge ingress.domain before step `create-install-values`

```
gitops: true
ingress:
  domain: ""
  externalDNS: false
  namespaceSubDomain: -jx.
  tls:
    email: ""
    enabled: false
    production: false
```

The step `create-install-values` will becomes `No domain flag provided so using default  to generate Ingress rules`

```
STEP: create-install-values command: /bin/sh -c jx step create install values -b in dir: env


Waiting to find the external host name of the ingress controller Service in namespace kube-system with name jxing-nginx-ingress-controller
No domain flag provided so using default  to generate Ingress rules
waiting for external Host on the ingress service jxing-nginx-ingress-controller in namespace kube-system ...
```

### Steps to reproduce the behavior
0. edit `jx-requirements.yml`, input `ingress.domain`
```
gitops: true
ingress:
  domain: <my-ip-addr>.nip.io
  externalDNS: false
  namespaceSubDomain: -jx.
```
1. `jx boot` 
2.  answer questions till step `create-install-values`

### Jx version

The output of `jx version` is:

```
jx version
NAME               VERSION
jx                 2.0.721
Kubernetes cluster v1.13.5+icp-ee
kubectl            v1.13.5+icp-ee
git                2.23.0
Operating System   Red Hat Enterprise Linux Server release 7.6 (Maipo)


verifying packages
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Operating system / Environment

IBM Cloud Private

RHEL 7.6

This can be workaround by 

1. kill `jx boot` at step `create-install-values`,  
2. fix `ingress.domain` in `jx-requirements.yml`
3. reinstall via command `jx boot --start-step create-install-values`
