### ISSUE TITLE
kaniko: false does not switch back to Skaffold on jx boot installations

### ISSUE THREAD

**Issue by renatoaraujoc** [jenkins-x/jx#5505]
### Summary 
I'm trying to use Skaffold as the builder for my images and, in respect for commit 684902d9fbbe5a4316da01a4bef2a3331150a505, setting `kaniko: false` should turn off the command substitution which does *not* happen in fact.

### Steps to reproduce the behavior
Issue a `jx boot` with `kaniko: false` on `jx-requirements.yaml` and then do a `jx step syntax effective` on a jx application.

### Expected behavior
We should not see any substitution and this should be printed:
```yaml
command: export VERSION=`cat VERSION` && skaffold build -f skaffold.yaml
```
### Actual behavior
Command substitution is still being applied on top of `skaffold build -f skaffold.yaml`
```yaml
- args:
  - --cache=true
  - --cache-dir=/workspace
  - --context=/workspace/source
  - --dockerfile=/workspace/source/Dockerfile
  - --destination=gcr.io/project_name/app:${inputs.params.version}
  - --cache-repo=gcr.io/project_name/cache
  command: /kaniko/executor
  dir: /workspace/source
  image: gcr.io/kaniko-project/executor:9912ccbf8d22bbafbf971124600fbb0b13b9cbd6
  name: build-container-build
```
### Jx version

The output of `jx version` is:
```
jx                 2.0.721
Kubernetes cluster v1.13.7-gke.24
kubectl            v1.15.1
helm client        Client: v2.14.2+ga8b13cc
git                2.22.0
Operating System   Mac OS X 10.12.6 build 16G2128
```
### Jenkins type
- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster
GKE cluster with JX Boot
