### ISSUE TITLE
jx boot adds ingress definitions into environments section in jx-requirements.yaml

### ISSUE THREAD

**Issue by sdoxsee** [jenkins-x/jx#5569]
### Summary 

Clone/fork the jenkins-x-boot-config github repo. Run `jx boot` and the `environments` node in jx-requirements.yaml gets a bunch of (unused?) ingress definitions.

Slack Reference: https://kubernetes.slack.com/archives/C9MBGQJRH/p1568110165241000?thread_ts=1568102025.228600&cid=C9MBGQJRH

example of corrupted jx-requirements.yaml section:

```
environments:
- ingress:
    domain: rhervas.info
    externalDNS: true
    namespaceSubDomain: ""
    tls:
      email: <user>@gmail.com
      enabled: true
      production: true
  key: dev
- ingress:
    domain: rhervas.info
    externalDNS: true
    namespaceSubDomain: ""
    tls:
      email: <user>@gmail.com
      enabled: true
      production: true
  key: staging
- ingress:
    domain: rhervas.info
    externalDNS: true
    namespaceSubDomain: ""
    tls:
      email: <user>@gmail.com
      enabled: true
      production: true
  key: production
```

### Expected behavior

should look more like this:

```
environments:
- key: dev
- key: staging
- key: production
```

### Jx version

2.0.758

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GKE (jx create cluster gke --skip-installation)

### Operating system / Environment

OSX
