### ISSUE TITLE
Feature branch not triggering pipeline

### ISSUE THREAD

**Issue by udbscience** [jenkins-x/jx#5586]
### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.780
Kubernetes cluster v1.14.3-gke.11
kubectl            v1.15.3
helm client        Client: v2.14.3+g0e7f3b6
git                2.22.0
Operating System   CentOS Linux release 7.7.1908 (Core)
```

### Jenkins type

- [+] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster
GKE

### Operating system / Environment

created a branch called feature-something, then added entry in the jenkins-x.yml
```
buildPack: maven-java11
pipelineConfig:
  pipelines:
    feature:
      build:
        steps:
        - command: echo hello world
```
after commit from the feature branch, no meta-pipeline and pipeline gets created.
lighthouse logs, shows the webhook was received, GHE also shows the webhook was successful.
