### ISSUE TITLE
Unable to switch from Let's Encrypt staging to production certificates

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx#5593]
### Summary 

Using `jx boot` with an ingress configuration of the form:

```
ingress:
  cloud_dns_secret_name: external-dns-gcp-sa
  domain: foo.bar.com
  externalDNS: true
  namespaceSubDomain: -jx.
  tls:
    email: foo@bar
    enabled: true
    production: false
```

is failing with:

```
Waiting for vault to be initialized and unsealed...
Waiting for vault to be initialized and unsealed...
Waiting for vault to be initialized and unsealed...
error: creating system vault URL client: wait for vault to be initialized and unsealed: reading vault health: Get https://vault-jx.dev.hardy.jenkins-x.rocks/v1/sys/health?drsecondarycode=299&performancestandbycode=299&sealedcode=299&standbycode=299&uninitcode=299: x509: certificate signed by unknown authority
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step create values --name parameters' command in directory 'env', output: ''
```

Vault requires non-staging certificates.

By enabling production certificates in the ingress, the problem should be solved:

```
ingress:
  cloud_dns_secret_name: external-dns-gcp-sa
  domain: foo.bar.com
  externalDNS: true
  namespaceSubDomain: -jx.
  tls:
    email: foo@bar
    enabled: true
    production: true
```

However, now before the changes to the certificates can be made, boot tries to access Valut which never was completely configured:

```
jx boot
booting up Jenkins X

STEP: validate-git command: /bin/sh -c jx step git validate in dir: env

Git configured for user: foo

STEP: verify-preinstall command: /bin/sh -c jx step verify preinstall in dir: env

Connecting to cluster hardy-jx-all-in
verifying the kubernetes cluster before we try to boot Jenkins X in namespace: jx
we will try to lazily create any missing resources to get the current cluster ready to boot Jenkins X
setting the local kubernetes context to the deploy namespace jx
Now using namespace 'jx' on server 'https://35.188.172.65'.
verifying the CLI packages
verifying the CLI package using version stream URL: https://github.com/jenkins-x/jenkins-x-versions.git and git ref: master

WARNING: A different jx version 2.0.780 is available in the version stream. We highly recommend you upgrade to it.

? Would you like to upgrade to the jx version? No

the CLI packages seem to be setup correctly kubectl, git, helm

NAME               VERSION
jx                 2.0.399-dev+1ef92b754
Kubernetes cluster v1.13.7-gke.8
kubectl            v1.15.1
helm client        v2.14.3+g0e7f3b6
git                2.20.1
WARNING: Your requirements have not enabled cloud storage for reports - we recommend enabling this for kubernetes provider gke
WARNING: Your requirements have not enabled cloud storage for repository - we recommend enabling this for kubernetes provider gke
WARNING: Your requirements have not enabled cloud storage for backup - we recommend enabling this for kubernetes provider gke
the storage looks good
helm installed and configured
helm client is setup
Waiting for vault to be initialized and unsealed...
```

At this stage it is not possible to recover and you need to delete the cluster.
