### ISSUE TITLE
Regression on `jx step create pr`

### ISSUE THREAD

**Issue by salaboy** [jenkins-x/jx#5615]
### Summary 

`jx step create pr chart` used inside a pipeline cause an error regarding GIT USER and GIT EMAIL

### Steps to reproduce the behavior

Upgrade to latest platform

### Expected behavior

The PR should be sent

### Actual behavior

The PR failed to be sent

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.757
jenkins x platform 2.0.1296
Kubernetes cluster v1.13.7-gke.8
kubectl            v1.15.2
helm client        Client: v2.14.3+g0e7f3b6
git                2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.6 build 18G95
```

### Jenkins type

- [ x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Operating system / Environment

Workaround shown in here: 

https://github.com/zeebe-io/zeebe-cluster-helm/blob/master/jenkins-x.yml
Which is adding to the pipeline configuration these env variables: 
```
buildPack: charts 
pipelineConfig:
  env:
  - name: GIT_COMMITTER_EMAIL
    value: jenkins-x@googlegroups.com
  - name: GIT_AUTHOR_EMAIL
    value: jenkins-x@googlegroups.com
  - name: GIT_AUTHOR_NAME
    value: jenkins-x-bot
  - name: GIT_COMMITTER_NAME
    value: jenkins-x-bot
```
