### ISSUE TITLE
jx boot ingress docs do not match generated jx-requirements.yml

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#5685]
### Summary 
The jx boot documentation shows example environment config with multiple keys but a single ingress, as below:
```
environments:
- key: dev
- key: staging
- key: production
ingress:
  domain: 1.2.3.4.nip.io
  externalDNS: false
  tls:
    email: ""
    enabled: false
    production: false
```
However, jx boot generates a config file with four keys and four ingress configs:
```
environments:
- ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: ""
    tls:
      email: ""
      enabled: false
      production: false
  key: dev
- ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: ""
    tls:
      email: ""
      enabled: false
      production: false
  key: staging
- ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: ""
    tls:
      email: ""
      enabled: false
      production: false
  key: production
ingress:
  domain: ""
  externalDNS: false
  namespaceSubDomain: -jx.
  tls:
    email: ""
    enabled: false
    production: false
```

No explanation is provided as to how these are expected to be configured and if they can share a domain or not.

### Jx version

The output of `jx version` is:

```
2.0.808
```
