### ISSUE TITLE
`jx boot`: `verify-jenkins-x-environment` step failing. Returning `404` when fetching the repository with a `GET` request 

### ISSUE THREAD

**Issue by KDvu** [jenkins-x/jx#5842]
### Summary 

I'm using Serverless Jenkins X with Gitlab. I tried `jx boot` on two of the more recent versions of JX (2.0.875 and 2.0.861) and the `verify-jenkins-x-environment` step is failing. A `404` is being returned when attempting to fetch the repository with a `GET` request.

I've resorted to using `jx boot` with JX version 2.0.827 (which works) to install Jenkins X onto my cluster and then updating my JX version afterwards (to the latest version 2.0.875) to make use of the latest JX features.

P.S. Feel free to let me know if I'm mis-using `jx boot` and/or the `https://github.com/jenkins-x/jenkins-x-boot-config` repository

### Steps to reproduce the behavior

Prerequisite: `https://GITLAB_DOMAIN/USER/environment-test-cluster-dev.git` does not exist (or it has been deleted)

1. Fork the `https://github.com/jenkins-x/jenkins-x-boot-config` project into a Gitlab repo
2. `git clone https://GITLAB_DOMAIN/group/jenkins-x-boot-config`
3. Customise `jx-requirements.yml` file to something like this

```
# jenkins-x-boot-config/jx-requirements.yml

cluster:
  clusterName: test-cluster
  environmentGitOwner: USER
  gitKind: gitlab
  gitName: gitlab
  gitServer: https://GITLAB_DOMAIN
  project: jx-next-gen-tests
  provider: gke
  zone: europe-west2-b
gitops: true
environments:
- key: dev
- key: staging
- key: production
ingress:
  domain: DOMAIN # SET DOMAIN
  externalDNS: true # SET to true
  tls:
    email: ""
    enabled: false
    production: false
kaniko: true
secretStorage: vault
storage:
  logs:
    enabled: false
    url: ""
  reports:
    enabled: false
    url: ""
  repository:
    enabled: false
    url: ""
versionStream:
  ref: "master"
  url: https://github.com/jenkins-x/jenkins-x-versions.git
webhook: lighthouse # CHANGED prow to Lighthouse

```

#### JX Version where it is working as intended
```
NAME               VERSION
jx                 2.0.827
Kubernetes cluster v1.13.7-gke.24
kubectl            v1.16.1
helm client        Client: v2.13.1+g618447c
git                2.17.1
Operating System   Ubuntu 18.04.3 LTS
```

#### Logs

```
STEP: verify-jenkins-x-environment command: /bin/sh -c jx step verify env in dir: .

validating git repository for dev at URL https://GITLAB_DOMAIN/USER/environment-test-cluster-dev.git
creating environment dev git repository for URL: https://GITLAB_DOMAIN/USER/environment-test-cluster-dev.git to namespace jx
Username for 'https://GITLAB_DOMAIN': USER
Password for 'https://USER@GITLAB_DOMAIN': 
Username for 'https://GITLAB_DOMAIN': USER
Password for 'https://USER@GITLAB_DOMAIN': 
Username for 'https://GITLAB_DOMAIN': USER
Password for 'https://USER@GITLAB_DOMAIN': 
Duplicated Git repository https://GITLAB_DOMAIN/USER/jenkins-x-boot-config to https://GITLAB_DOMAIN/USER/environment-test-cluster-dev
Setting upstream to https://GITLAB_DOMAIN/USER/environment-test-cluster-dev
Created Pull Request: https://GITLAB_DOMAIN/USER/environment-test-cluster-dev/merge_requests/1
WARNING: Adding labels not supported on gitlab yet for repo USER/environment-test-cluster-dev issue 1 labels [jx/boot]
Added label jx/boot to Pull Request https://GITLAB_DOMAIN/USER/environment-test-cluster-dev/merge_requests/1
validating git repository for production at URL https://GITLAB_DOMAIN/USER/environment-test-cluster-production.git
creating environment production git repository for URL: https://GITLAB_DOMAIN/USER/environment-test-cluster-production.git to namespace jx-production
Using Git provider gitlab at https://GITLAB_DOMAIN
? Using Git user name: USER
? Using organisation: USER
Creating repository USER/environment-test-cluster-production
Git repository USER/environment-test-cluster-production already exists
Pushed Git repository to https://GITLAB_DOMAIN/USER/environment-test-cluster-production

validating git repository for staging at URL https://GITLAB_DOMAIN/USER/environment-test-cluster-staging.git
creating environment staging git repository for URL: https://GITLAB_DOMAIN/USER/environment-test-cluster-staging.git to namespace jx-staging
Using Git provider gitlab at https://GITLAB_DOMAIN
? Using Git user name: USER
? Using organisation: USER
Creating repository USER/environment-test-cluster-staging
Git repository USER/environment-test-cluster-staging already exists
Pushed Git repository to https://GITLAB_DOMAIN/USER/environment-test-cluster-staging

the git repositories for the environments look good

STEP: install-repositories command: /bin/sh -c jx step helm apply --boot --name repos in dir: repositories

...

```

#### JX Versions where it is not working as intended

```
NAME               VERSION
jx                 2.0.861
Kubernetes cluster v1.13.7-gke.24
kubectl            v1.16.1
helm client        Client: v2.13.1+g618447c
git                2.17.1
Operating System   Ubuntu 18.04.3 LTS
```

```
NAME               VERSION
jx                 2.0.875
Kubernetes cluster v1.13.7-gke.24
kubectl            v1.16.1
helm client        Client: v2.13.1+g618447c
git                2.17.1
Operating System   Ubuntu 18.04.3 LTS
```

#### Logs

```
$ jx boot

STEP: verify-jenkins-x-environment command: /bin/sh -c jx step verify env in dir: .

Validating git repository for dev environment at URL https://GITLAB_DOMAIN/USER/environment-test-cluster-dev.git
Username for 'https://GITLAB_DOMAIN': 
Password for 'https://USER@GITLAB_DOMAIN': 
error: creating remote for dev environment environment-test-cluster-dev: duplicating https://GITLAB_DOMAIN/USER/jenkins-x-boot-config to USER/environment-test-cluster-dev: getting repo for https://GITLAB_DOMAIN/USER/jenkins-x-boot-config: failed to get repository USER/jenkins-x-boot-config due to: GET https://GITLAB_DOMAIN/api/v3/repos/USER/jenkins-x-boot-config: 404  []
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step verify env' command in directory '.', output: ''

```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

I'm using a GKE cluster. I created it manually using the GCP web GUI.
