### ISSUE TITLE
Assumes wrong format for EKS cluster context

### ISSUE THREAD

**Issue by andrewhertog** [jenkins-x/jx#5844]
So I'm trying to run `jx boot` on an EKS cluster we created via Terraform. We also set up our context file by running `aws eks update-kubeconfig`. 
This tool sets up the context to the cluster where the context name is the ARN of the eks cluster.
`jx boot` seems to expect the clusters context name to be in the format of `<cluster_name>.<region>.*` so i keep running into the following error:
```
error: there was a problem obtaining the current cluster name and region: parsing the current Kubeernetes context arn:aws:eks:us-east-1:account-id:cluster/andrew-test-dev: unable to parse arn:aws:eks:us-east-1:account-id:cluster/andrew-test-dev as <cluster_name>.<region>.*
```
I think the function in question is https://github.com/jenkins-x/jx/blob/874ec4a52a22e6147ef04365d6001d0ea7ed7790/pkg/cloud/amazon/common.go#L68

My jx-requirements.yaml has the following block in it:
```
cluster:
  azure: {}
  clusterName: andrew-test-dev
  gitKind: github
  gitName: github
  gitServer: https://github.com
  namespace: jx
  provider: eks
```

I'm running:
- jx 2.0.871
- kubectl client 1.16.1
- kubectl server 1.14.7

Note: Apologies for not following the standard Issues template, but Github never gave it to me when i used their "Create issue from code" feature.
