### ISSUE TITLE
Replace the GCP service accounts stored in secrets with Workload Identity

### ISSUE THREAD

**Issue by ccojocar** [jenkins-x/jx#5856]
### Summary 

We should replace all GCP service accounts stored in k8s secrets with Workload Identity, which is the recommended way to provision automatically a GCP service account in a POD.  

Service Accounts:
- tekton bot (add permissions for storage)
- vault 
- external dns
- kaniko
- velero

Setup example for pipeline service account which enables storage permissions required to push logs into GCS:

```
 gcloud iam service-accounts create jenkins-x-pipeline
```

```
gcloud iam service-accounts add-iam-policy-binding \
  --role roles/iam.workloadIdentityUser \
  --role roles/storage.objectAdmin \
  --role roles/editor \
  --member "serviceAccount:<project-id>.svc.id.goog[jx/tekton-bot]" \
  jenkins-x-pipeline@<project-id>iam.gserviceaccount.com
```

```
kubectl annotate serviceaccount --namespace jx tekton-bot iam.gke.io/gcp-service-account=jenkins-x-pipeline@<project-id>.iam.gserviceaccount.com
```

More details in https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity

### Expected behavior

Use WorkloadIdentity for all service accounts instead of storing the GCP service accounts in k8s secrets.

### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [ x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by garethjevans** [comment]
@ccojocar any suggestions on the best way to annotate the service accounts?

**Comment by ccojocar** [comment]
I would add the annotation via a helm value when possible to the service accounts created by helm charts:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: <gcp-sa>@<project-id>.iam.gserviceaccount.com
```

A few service accounts are created programatically, in that case maybe we can input somehow the annotation when they are created.

Probably, it would be also nice to have some command if none of the above are possible.  The command can get as inputs: gcp service account name, list of roles, k8s service account to annotated.  It can be helpful to get these inputs from a YAML file such that we can setup multiple service accounts in one go. 
```YAML
serviceAccounts:
  - name: k8s-sa-1
     gcpServiceAccount: gcp-sa-1
     roles:
       - role/editor
       - role/storage.objectAdmin
   - name: k8s-sa-2
      gcpServiceAccount: gcp-sa-2
      roles:
        - role/editor
        - role/storage.objectAdmin
```

I am not know if there is another alternative (e.g. using terraform) to achieve this.
