### ISSUE TITLE
Can we configure hooks plugins ?

### ISSUE THREAD

**Issue by eddycharly** [jenkins-x/jx#5890]
I have read a lot of the docs but failed to find something showing how to configure hooks plugins. 
Is the configuration static or can it be changed through `jx install` ?

**Comment by deanesmith** [comment]
`jx install` is soon to be deprecated, it is recommended to use `jx boot` and a scheduler config is available.  Will follow up with doc link.

**Comment by axsaucedo** [comment]
@eddycharly  I have been following the brief FAQ answer at https://jenkins-x.io/docs/using-jx/faq/chatops/#how-do-i-add-multiple-parallel-pipelines-to-a-project, with the objective of adding a new jenkins-x-{context}.yml files for linting and integration tests - it has been a good starting point for our usecase.

I haven't been able to make it work successfully yet tho, @deanesmith is there any resource I could dive deeper into? I've leveraged the `scheduler.yaml` files in [the jenkins-x/env../templates](https://github.com/jenkins-x/environment-tekton-weasel-dev/tree/f377a72498282de9ee49b807b4d5ba74321a4fab/env/templates) repo, but haven't managed to get it working successfully yet

**Comment by axsaucedo** [comment]
Just as a follow-up, I have managed to get this working thanks to @jstrachan ! Basically as a walkaround it can be done by just adding the entries into the configmap `config` in the `jx` namespace, in our case the entries look like follows:
```
      SeldonIO/seldon-core:
      - agent: tekton
        always_run: true
        context: pr-build
        name: pr-build
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
      - agent: tekton
        always_run: true
        context: lint
        name: lint
        rerun_command: /test lint
        trigger: (?m)^/test( all| lint),?(\s+|$)
      - agent: tekton
        always_run: false
        context: integration
        name: integration
        rerun_command: /test integration
```

And from that, we can now trigger the `lint` automatically and the `integration` with `/test integration`:
![image](https://user-images.githubusercontent.com/1447507/67853216-f710ea80-fb05-11e9-8bbf-df7203a950fc.png)
