### ISSUE TITLE
jx should annotate the deployed Ingress with `kubernetes.io/ingress.class: "nginx"` when the nginx ingresscontroller is used

### ISSUE THREAD

**Issue by jody-frankowski** [jenkins-x/jx#599]
The gce ingress controller only supports [NodePort services](https://github.com/kubernetes/ingress-gce/issues/75#issuecomment-344698434), however there is also a bug in the gce ingress controller which makes it stop evaluating Ingress objects when it fails for one.

Since jx doesn't annotate its Ingress object with `kubernetes.io/ingress.class: "nginx"`, and the backend services are of `ClusterIP` type, this effectively forbids us to use the gce ingress controller.

Note in the following example that the service is of type `NodePort` and should work with the gce ingress controller (the following works when I set `kubernetes.io/ingress.class: "nginx"` on all the ingress deployed by jenkins-x):

```
 ❯ kubectl get svc
NAME           TYPE       CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
hello-server   NodePort   10.15.242.10   <none>        8080:30489/TCP   3h
```

```
 ❯ kubectl get ingress hello-server -o yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: gce
[...]
spec:
  rules:
  - host: hello-server.jx.[...]
    http:
      paths:
      - backend:
          serviceName: hello-server
          servicePort: 8080
```

```
 ❯ kubectl describe ing hello-server
[...]
Events:
  Type     Reason  Age   From                     Message
  ----     ------  ----  ----                     -------
  Warning  GCE     4m    loadbalancer-controller  googleapi: Error 400: Invalid value for field 'namedPorts[0].port': '0'. Must be greater than or equal to 1, invalid
```

The annotation should also probably be set by default for any ingress deployed by jenkins-x when the nginx ingress controller is installed.

Ping @vgallissot
