### ISSUE TITLE
Cannot override the kaniko step in a pipeline: command merged with args

### ISSUE THREAD

**Issue by aure-olli** [jenkins-x/jx#6058]
### Summary 

I'm trying to override the kaniko step in the pipeline. However, when doing so, the kaniko step systematically fails with 
```
Showing logs for build aure-olli/test-pipeline/master #5 release stage from-build-pack and container step-build-container-build
2019/11/08 08:50:48 Error executing command: fork/exec /kaniko/executor --cache=true --cache-dir=/workspace --context=/workspace/source --dockerfile=/workspace/source/Dockerfile --destination=gcr.io/aure-olli/test-pipeline:0.0.7 --cache-repo=gcr.io/aure-olli/cache: no such file or directory
```

The reason seems to be that `command` and `args` are merged together when overriding a step:
```
- args:
  - --cache=true
  - --cache-dir=/workspace
  - --context=/workspace/source
  - --dockerfile=/workspace/source/Dockerfile
  - --destination=gcr.io/aure-olli/test-pipeline:${inputs.params.version}
  - --cache-repo=gcr.io/aure-olli/cache
  command: /kaniko/executor
  dir: /workspace/source
  image: gcr.io/kaniko-project/executor:9912ccbf8d22bbafbf971124600fbb0b13b9cbd6
  name: build-container-build
```
Is turned into
```
- command: /kaniko/executor --cache=true --cache-dir=/workspace --context=/workspace/source
    --dockerfile=/workspace/source/Dockerfile --destination=gcr.io/aure-olli/test-pipeline:${inputs.params.version}
    --cache-repo=gcr.io/aure-olli/cache
  dir: /workspace/source
  image: gcr.io/kaniko-project/executor:9912ccbf8d22bbafbf971124600fbb0b13b9cbd6
  name: build-container-build
```

### Steps to reproduce the behavior

- create a project and  check that everything went well
```
jx create quickstart --name=test-pipeline --language=go
cd test-pipeline
jx get build logs
```
- save the current pipeline
```
jx step syntax effective > old.yml
```
- replace the `release build container-build` step by itself
```
echo "buildPack: go
pipelineConfig:
  pipelines:
    overrides:
    - pipeline: release
      stage: build
      name: container-build
      steps:
      - args:
        - --cache=true
        - --cache-dir=/workspace
        - --context=/workspace/source
        - --dockerfile=/workspace/source/Dockerfile
        - --destination=gcr.io/aure-olli/test-pipeline:${inputs.params.version}
        - --cache-repo=gcr.io/aure-olli/cache
        command: /kaniko/executor
        dir: /workspace/source
        image: gcr.io/kaniko-project/executor:9912ccbf8d22bbafbf971124600fbb0b13b9cbd6
        name: container-build" | tee jenkins-x.yml
```
- save the new pipeline and look for the differences
```
jx step syntax effective > new.yml
diff old.yaml new.yaml
```
```
[...]
<           - args:
<             - --cache=true
<             - --cache-dir=/workspace
<             - --context=/workspace/source
<             - --dockerfile=/workspace/source/Dockerfile
<             - --destination=gcr.io/aure-olli/test-pipeline:${inputs.params.version}
<             - --cache-repo=gcr.io/aure-olli/cache
<             command: /kaniko/executor
---
>           - command: /kaniko/executor --cache=true --cache-dir=/workspace --context=/workspace/source
>               --dockerfile=/workspace/source/Dockerfile --destination=gcr.io/aure-olli/test-pipeline:${inputs.params.version}
>               --cache-repo=gcr.io/aure-olli/cache
```
- save it and watch for the error
```
git commit -am test
git push origin master
jx get build logs
```
```
[...]
Showing logs for build aure-olli/test-pipeline/master #5 release stage from-build-pack and container step-build-container-build
2019/11/08 08:50:48 Error executing command: fork/exec /kaniko/executor --cache=true --cache-dir=/workspace --context=/workspace/source --dockerfile=/workspace/source/Dockerfile --destination=gcr.io/aure-olli/test-pipeline:0.0.7 --cache-repo=gcr.io/aure-olli/cache: no such file or directory
```

From there, it's easy to check that the merging created the bug
- replace the full pipeline by itself
```
head -n6 old.yaml | tail -n+2 > jenkins-x.yml
tail -n+10 old.yaml > jenkins-x.yml
```
- save it and check that there is no error
```
git commit -am test
git push origin master
jx get build logs
```
- replace in the `release` pipeline the normal command
```
- args:
  - --cache=true
  - --cache-dir=/workspace
  - --context=/workspace/source
  - --dockerfile=/workspace/source/Dockerfile
  - --destination=gcr.io/aure-olli/test-pipeline:${inputs.params.version}
  - --cache-repo=gcr.io/aure-olli/cache
  command: /kaniko/executor
  dir: /workspace/source
  image: gcr.io/kaniko-project/executor:9912ccbf8d22bbafbf971124600fbb0b13b9cbd6
  name: build-container-build
```
by the merged one
```
- command: /kaniko/executor --cache=true --cache-dir=/workspace --context=/workspace/source
    --dockerfile=/workspace/source/Dockerfile --destination=gcr.io/aure-olli/test-pipeline:${inputs.params.version}
    --cache-repo=gcr.io/aure-olli/cache
  dir: /workspace/source
  image: gcr.io/kaniko-project/executor:9912ccbf8d22bbafbf971124600fbb0b13b9cbd6
  name: build-container-build
```
- save it and watch for the error
```
git commit -am test
git push origin master
jx get build logs
```
```
[...]
Showing logs for build aure-olli/test-pipeline/master #5 release stage from-build-pack and container step-build-container-build
2019/11/08 08:50:48 Error executing command: fork/exec /kaniko/executor --cache=true --cache-dir=/workspace --context=/workspace/source --dockerfile=/workspace/source/Dockerfile --destination=gcr.io/aure-olli/test-pipeline:0.0.7 --cache-repo=gcr.io/aure-olli/cache: no such file or directory
```

### Expected behavior

Replacing a step by itself should not create any error, and the result of `jx step syntax effective` should be unchanged.

### Actual behavior

Replacing the kaniko step by itself creates an error, due to merging command and args

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.954
jenkins x platform 2.0.1564
Kubernetes cluster v1.13.11-gke.9
kubectl            v1.13.11-dispatcher
helm client        Client: v2.15.1+gcf1de4f
git                2.17.1
Operating System   Ubuntu 18.04.3 LTS
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GKE cluster, created by `jx create cluster gke`

### Operating system / Environment

`Ubuntu 18.04.3 LTS`
