### ISSUE TITLE
jx create/import error with gitlab

### ISSUE THREAD

**Issue by vishveshv** [jenkins-x/jx#6064]
Summary : `jx create quickstart` or `jx import` failing with Gitlab:
error: json: cannot unmarshal array into Go value of type gitlab.ProjectHook

Steps to reproduce the behaviour: 
On a healthy Jx cluster run following command:
jx create quickstart --git-provider-kind 'gitlab' --git-provider-url 'http://GITLABURL' --git-username 'XXXX' --git-api-token 'GITLAB_TOKEN' -f go

Expected behavior: jx create quickstart should create a project

Actual behavior: jx create command is failed with error ```error: json: cannot unmarshal array into Go value of type gitlab.ProjectHook```

Jx version: 2.0.966

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.966
Kubernetes cluster v1.13.5
kubectl            v1.14.0
helm client        Client: v2.11.0+g2e55dbe
git                2.18.0
Operating System   Mac OS X 10.14.5 build 18F132
```

### Jenkins type

- [V] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

Operating system / Environment: Ubuntu-18.04

**Comment by deanesmith** [comment]
Hi @vishveshv, did you install using boot and are you using Lighthouse?

**Comment by vishveshv** [comment]
Hi @deanesmith Yes, I am using `jx boot` with using Lighthouse

**Comment by deanesmith** [comment]
Thanks @vishveshv

**Comment by vishveshv** [comment]
Same issue is observed during pipeline step `jx step verify env`.
Error message:
error: failed to create git repository for gitURL http://gitlab-XXXX.TLDR/<USER>/environment-jx-experiment-production.git: creating the repository: json: cannot unmarshal array into Go value of type gitlab.Project

 Here are some more information:
Gitlab Version: Gitlab Enterprise Edition v12.3.5-ee

jx-requirement.yaml:

```
cluster:
  clusterName: jx-experiment
  environmentGitOwner: <UserName>
  gitKind: gitlab
  gitName: gitlab
  gitServer: http://gitlab-XXX.domain.com
  namespace: jx
  provider: kubernetes
environments:
- key: dev
- key: staging
- key: production
gitops: true
ingress:
  domain: jenkins-x.domain.com
  externalDNS: false
  namespaceSubDomain: -jx.
  tls:
    email: ""
    enabled: false
    production: false
repository: nexus
secretStorage: local
storage:
  logs:
    enabled: false
    url: ""
  reports:
    enabled: false
    url: ""
  repository:
    enabled: false
    url: ""
versionStream:
  ref: v1.0.190
  url: https://github.com/jenkins-x/jenkins-x-versions.git
webhook: lighthouse
```
