### ISSUE TITLE
jx boot should not fail if missing provider

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#6131]
I tried running `jx boot -r jx-requirements.yml` with a minimal file...

```yaml
cluster:
  environmentGitOwner: jstrachan
  environmentGitPublic: true
repository: bucketrepo
webhook: lighthouse
```
it fails with:
```
error: missing property: provider in file /workspace/java/minikube/minikube-dev/jenkins-x-boot-config/jx-requirements.yml
```
it would be nicer to ask the user to pick a known value from a list
