### ISSUE TITLE
jx boot doesn't recognize gitKind: bitbucketserver as a Bitbucket git server

### ISSUE THREAD

**Issue by SmartassSkeleton** [jenkins-x/jx#6158]
### Summary 

When trying to install Jenkins-X on an existing EKS cluster using `jx boot` the process fails on creating a repository for the `dev` environment. From the error message it seems like the git server API the `jx` CLI is trying to use is GitHub API.   

### Steps to reproduce the behavior

Using `jx boot` with `jx-requirements.yml` file cloned from the [jenkins-x-boot-config](https://github.com/jenkins-x/jenkins-x-boot-config/) repository:

```
autoUpdate:
  enabled: false
  schedule: ""
bootConfigURL: https://github.com/jenkins-x/jenkins-x-boot-config
cluster:
  clusterName: my-cluster
  environmentGitOwner: cicd
  gitKind: bitbucketserver
  gitName: bs
  gitServer: https://bitbucket.example.com
  namespace: jx
  provider: eks
  region: eu-west-1
  registry: xxxxxxxxxxxx.dkr.ecr.eu-west-1.amazonaws.com
  zone: eu-west-1
environments:
- ingress:
    domain: staging.example.com
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: user@example.com
      enabled: true
      production: true
  key: dev
- ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: ""
    tls:
      email: ""
      enabled: false
      production: false
  key: staging
- ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: ""
    tls:
      email: ""
      enabled: false
      production: false
  key: production
gitops: true
ingress:
  domain: staging.example.com
  externalDNS: false
  namespaceSubDomain: -jx.
  tls:
    email: user@example.com
    enabled: true
    production: true
kaniko: true
repository: nexus
secretStorage: local
storage:
  backup:
    enabled: true
    url: s3://bucket
  logs:
    enabled: true
    url: s3://bucket
  reports:
    enabled: true
    url: s3://bucket
  repository:
    enabled: true
    url: s3://bucket
vault: {}
velero: {}
versionStream:
  ref: v1.0.201
  url: https://github.com/jenkins-x/jenkins-x-versions.git
webhook: lighthouse
```

### Expected behavior

I expected `jx boot` to successfully deploy Jenkins X on my Kubernetes cluster and create the appropriate git repositories and hooks. 

### Actual behavior

`jx boot` fails with this error message:

```
Validating git repository for dev environment at URL https://bitbucket.example.com/scm/cicd/environment-my-cluster-dev.git
error: creating remote for dev environment environment-my-cluster-dev: duplicating https://github.com/jenkins-x/jenkins-x-boot-config to cicd/environment-my-cluster-dev: getting repo for https://github.com/jenkins-x/jenkins-x-boot-config: failed to get repository jenkins-x/jenkins-x-boot-config due to: GET https://bitbucket.example.com/api/v3/repos/jenkins-x/jenkins-x-boot-config: 404  []
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step verify env' command in directory '.', output: ''
```

Going through the Bitbucket server API page there's no such endpoint as `/api/v3/repos`, but a bit of Googleing showed me that this API endpoint belongs to GitHub.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.976
Kubernetes cluster v1.13.12-eks-c500e1
kubectl            v1.15.3
helm client        Client: v2.14.3+g0e7f3b6
git                2.23.0
Operating System   Mac OS X 10.14.6 build 18G103


verifying packages
? A local Jenkins X versions repository already exists, pulling the latest: Yes
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

AWS EKS using `eksctl`

### Operating system / Environment

macOS Mojave
