### ISSUE TITLE
jx removes "environment" key in kubeconfig when using Azure Active Directory backed authentication

### ISSUE THREAD

**Issue by lcaille** [jenkins-x/jx#6194]
### Summary 
We have a similar issue like this [one](https://github.com/helm/helm/issues/5665).
Given a kubeconfig: 
```
users:
- name: azure-ad
  user:
    auth-provider:
      config:
        access-token: ....
        apiserver-id: ....
        client-id: ....
        environment: AzurePublicCloud <-- removed by jx
        expires-in: "3600"
        expires-on: "1556718695"
        refresh-token: ....
        tenant-id: ....
      name: azure
```
Whenever we run the `jx` command, it removes the **environment** key, forcing kubectl to prompt for new authentication. 

### Steps to reproduce the behavior
- using AKS with Azure Active Directory authentication
- run `az aks get-credentials --resource-group <group> --name <cluster-name>`
- run `kubectl get pods --namespace jx` should prompt Azure authentication
- run `jx --help` just that would mess the kubeconfig
- run `kubectl get pods --namespace jx`

### Expected behavior
The last command should show all the pods in jx namespace
```
$ kubectl get pods --namespace jx  
NAME                                         READY   STATUS    RESTARTS   AGE
jenkins-6c55f8d656-vf8f6                     1/1     Running   0          30m
jenkins-x-chartmuseum-d87cbb789-gpxwm        1/1     Running   0          30m
jenkins-x-controllerrole-5f7c8f798-xqhbd     1/1     Running   0          30m
jenkins-x-docker-registry-69d666d455-vgcdw   1/1     Running   0          30m
jenkins-x-heapster-75558b6cfb-5sldb          2/2     Running   0          30m
jenkins-x-nexus-6bc788447f-556d6             1/1     Running   0          30m
```

### Actual behavior
It prompts to a new Azure authentication
```
$ kubectl get pods --namespace jx                                                                                                                                                                                                                      
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code ... to authenticate.
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1014
Kubernetes cluster v1.14.8
kubectl            v1.16.1
git                2.23.0
Operating System   Mac OS X 10.15.1 build 19B88


verifying packages
? A local Jenkins X versions repository already exists, pulling the latest: Yes
```

### Jenkins type

<!--
Select which installation type are you using. 
-->
- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ x] Classic Jenkins

### Kubernetes cluster

<!--
What kind of Kubernetes cluster are you using & how did you create it?
-->
AKS 1.14.8 with Azure Active Directory authentication

### Operating system / Environment
```
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.15.1
BuildVersion:   19B88
```

<!--
In which environment are you running the jx CLI?
-->
