### ISSUE TITLE
Unable to override a command with args in a tekton pipeline

### ISSUE THREAD

**Issue by garethjevans** [jenkins-x/jx#6197]
### Summary 

I'm trying to override the default kaniko behaviour in the pipeline, 

### Steps to reproduce the behavior

My `jenkins-x.yaml` has:

```
buildPack: go
pipelineConfig:
 pipelines:
   overrides:
   - pipeline: pullRequest
     stage: build
     name: container-build
     steps:
     - name: container-build
       command: /kaniko/executor --cache=true --cache-dir=/workspace --context=/workspace/source --dockerfile=/workspace/source/Dockerfile --destination=gcr.io/cbjx-bellycurse/gevans-golang02:\${inputs.params.version} --cache-repo=gcr.io/cbjx-bellycurse/cache
       dir: /workspace/source
       image: gcr.io/kaniko-project/executor:9912ccbf8d22bbafbf971124600fbb0b13b9cbd6
   - pipeline: release
     stage: build
     name: container-build
     steps:
     - name: container-build
       command: /kaniko/executor --cache=true --cache-dir=/workspace --context=/workspace/source --dockerfile=/workspace/source/Dockerfile --destination=gcr.io/cbjx-bellycurse/gevans-golang02:\${inputs.params.version} --destination=gcr.io/cbjx-bellycurse/gevans-golang02:latest --cache-repo=gcr.io/cbjx-bellycurse/cache
       dir: /workspace/source
       image: gcr.io/kaniko-project/executor:9912ccbf8d22bbafbf971124600fbb0b13b9cbd6
```

### Expected behavior

I'd expect to be able to do this - pipeline should process

### Actual behavior

```
Showing logs for build cb-kubecd/gevans-golang02/pr-2 #3 pr-build stage from-build-pack and container step-build-container-build
2019/11/26 12:40:34 Error executing command: fork/exec /kaniko/executor --cache=true --cache-dir=/workspace --context=/workspace/source --dockerfile=/workspace/source/Dockerfile --destination=gcr.io/cbjx-bellycurse/gevans-golang02:0.0.0-SNAPSHOT-PR-2-3 --cache-repo=gcr.io/cbjx-bellycurse/cache: no such file or directory
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins
