### ISSUE TITLE
[SOLVED] Overriding the creation of changelog and tag upon for release pipeline

### ISSUE THREAD

**Issue by axsaucedo** [jenkins-x/jx#6230]
Currently our tag and changelog process is manual, so we want to override the automated changelog creation. We have tried overriding the setVersion but without success (it still creates the changelog). What would be the correct way to remove the step that creates a changelog and a tag on every release pipeline?

Edit:
Solved by the initial suggestion that @abayer provided on his first answer.

**Comment by abayer** [comment]
The tag is created by `setVersion`, so specifying `setVersion` explicitly on your `release` will fix that. The changelog is created in the `promote` stage's `changelog` step, like https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/blob/master/packs/go/pipeline.yaml#L34, so something like the following should let you change the both of them:
```
buildPack: go # or whatever
pipelineConfig:
  pipelines:
    overrides:
      - name: changelog
         pipeline: release
         stage: promote
         step:
           command: whatever-you-want-to-do-instead
    release:
      setVersion:
        steps:
          - name: next-version
             command: whatever-you-want-to-do-instead
```

**Comment by axsaucedo** [comment]
Thank you very much for your prompt response @abayer ! I've tried using your suggestion, but it seems it still creates a tag and a changelog. Here is the YAML I used:
```
buildPack: none
pipelineConfig:
  pipelines:
    overrides:
    - name: changelog
      pipeline: release
      stage: promote
      step:
        command: echo "skipping promote"
    release:
      setVersion:
        steps:
        - name: next-version
          command: echo "skipping tag"
    pullRequest:
      pipeline:
        agent:
          image: seldonio/core-builder:0.4
        stages:
        - name: build-and-test
          parallel:
          - name: test-python
            agent:
              image: seldonio/python-builder:0.2
            steps:
            - name: test-python
              command: make
              args:
              - -C python
              - update_package
              - install_dev
              - test
```
And here is the output where the tag was created:
```
Showing logs for build seldonio/jenkins-x-seldon-core-sandbox/master #3 release stage meta-pipeline and container step-create-tekton-crds
? A local Jenkins X versions repository already exists, pulling the latest: Yes
running command: jx step next-version --use-git-tag-only --tag
created new version: 0.0.22 and written to file: ./VERSION
Updating chart version in helm-charts/seldon-abtest/Chart.yaml to 0.0.22
Tag v0.0.22 created and pushed to remote origin
```
Is there something I may be missing in the override?
