### ISSUE TITLE
`kaniko-secret` not mounted if the step is not precisely called `build-container-build`

### ISSUE THREAD

**Issue by aure-olli** [jenkins-x/jx#6247]
### Summary 

I've tried to create my own pipeline from scratch for a particular project, inspiring myself from the buildPacks. However the build systematically ended  with:
```
error pushing image: failed to push to destination gcr.io/***/***:2.0.10: DENIED: Access denied.

Pipeline failed on stage 'build' : container 'step-container-build'. The execution of the pipeline has stopped
```
After looking around, finally discovered that my kaniko step `container-build` did not receive the `GOOGLE_APPLICATION_CREDENTIALS` header from the secret `kaniko-secret`. Looking in the source code, the condition for adding those credentials seems pretty restrictive: https://github.com/jenkins-x/jx/blob/master/pkg/cmd/step/create/step_create_task.go#L1043
```go
if container.Name == "build-container-build" && !o.NoKaniko {
```

This condition is problematic for 2 reasons:
- the step is originally called `container-build`, the name `build-container-build` is only generated by `jx step syntax effective` when importing the buildPack: https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/blob/master/packs/go/pipeline.yaml#L9
- the condition to turn a `skaffold` step into a `kaniko` step is much larger: https://github.com/jenkins-x/jx/blob/master/pkg/jenkinsfile/pipeline.go#L894
```go
if strings.HasPrefix(parsedStep.GetCommand(), "skaffold build") ||
	(len(parsedStep.Arguments) > 0 && strings.HasPrefix(strings.Join(parsedStep.Arguments[1:], " "), "skaffold build")) ||
	commandIsSkaffoldRegex.MatchString(parsedStep.GetCommand()) {
```

I suggest that the condition to detect a kaniko step to be similarly large as the one to detect a skaffold build. At least something like:
```go
if strings.HasPrefix(parsedStep.GetCommand(), "/kaniko/executor") ||
	(len(parsedStep.Arguments) > 0 && strings.HasPrefix(strings.Join(parsedStep.Arguments[1:], " "), "/kaniko/executor"))
```
the concerned lines are https://github.com/jenkins-x/jx/blob/master/pkg/cmd/step/create/step_create_task.go#L1015 and https://github.com/jenkins-x/jx/blob/master/pkg/cmd/step/create/step_create_task.go#L1043

### Steps to reproduce the behavior

- Create a pipeline without using the buildPack, and without naming the build step `build-container-build`
```yaml
buildPack: go
pipelineConfig:
  agent:
    image: go
  pipelines:
    release:
      pipeline:
        options:
          containerOptions:
            env:
            - name: DOCKER_REGISTRY
              valueFrom:
                configMapKeyRef:
                  key: docker.registry
                  name: jenkins-x-docker-registry
            - name: TILLER_NAMESPACE
              value: kube-system
            - name: DOCKER_CONFIG
              value: /home/jenkins/.docker/
            - name: GIT_AUTHOR_EMAIL
              value: jenkins-x@googlegroups.com
            - name: GIT_AUTHOR_NAME
              value: jenkins-x-bot
            - name: GIT_COMMITTER_EMAIL
              value: jenkins-x@googlegroups.com
            - name: GIT_COMMITTER_NAME
              value: jenkins-x-bot
            - name: JENKINS_URL
              value: http://jenkins:8080
            - name: XDG_CONFIG_HOME
              value: /home/jenkins
            name: ""
            securityContext:
              privileged: true
            volumeMounts:
            - mountPath: /home/jenkins
              name: workspace-volume
            - mountPath: /var/run/docker.sock
              name: docker-daemon
            - mountPath: /home/jenkins/.docker
              name: volume-0
        stages:
        - name: build
          agent:
            image: go
          steps:
          - command: jx step git credentials
            dir: /workspace/source
            name: setup-jx-git-credentials
          - args:
            - --cache=true
            - --cache-dir=/workspace
            - --context=/workspace/source
            - --dockerfile=/workspace/source/Dockerfile
            - --destination=gcr.io/***/***:${inputs.params.version}
            - --cache-repo=gcr.io/***/cache
            command: /kaniko/executor
            dir: /workspace/source
            image: gcr.io/kaniko-project/executor:9912ccbf8d22bbafbf971124600fbb0b13b9cbd6
            name: container-build
```
- Run the pipeline
```bash
git commit -am 'test pipeline'
git push
```
- Watch it failing
```bash
jx get build log
```
```
error pushing image: failed to push to destination gcr.io/***/***:2.0.10: DENIED: Access denied.

Pipeline failed on stage 'build' : container 'step-container-build'. The execution of the pipeline has stopped.
```

### Expected behavior

Should succeed and push the docker image

### Actual behavior

Fails pushing the docker image

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1003
Kubernetes cluster v1.14.8-gke.12
kubectl            v1.14.7
helm client        Client: v2.14.3+g0e7f3b6
git                2.17.1
Operating System   Ubuntu 18.04.3 LTS
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

Classic `jx create cluster gke --skip-installation` and `jx boot`

### Operating system / Environment

`Ubuntu 18.04.3 LTS`
