### ISSUE TITLE
Pipeline overrides not behaving as expected with build packs and effective syntax stage/step names

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#6256]
### Summary 
Overrides no longer seem to be working in the way I have previously used them and I am not sure if this is due to a regression or a change in behaviour that means I am not applying them correctly.

### Steps to reproduce the behavior
Create a go-http quickstart.
Branch.
Make the following changes to jenkins-x.yml:
```
buildPack: go
pipelineConfig:
  pipelines:
    overrides:
    - name: build-make-linux
      pipeline: pullRequest
      stage: from-build-pack
      step:
        command: echo 'This does not EXIST!!!'
      type: before
    pullRequest:
      build:
        preSteps:
        - command: echo 'This EXISTS!'
```
Commit / push / create PR and monitor build logs.

### Expected behavior
Both messages should appear in the logs.

### Actual behavior
The pipeline config parses correctly and builds but the 'This does not EXIST!!!' message never appears. The 'This EXISTS!' message appears as expected.

### Jx version

The output of `jx version` is:

```
jx                 2.0.1011
Kubernetes cluster v1.13.11-gke.14
kubectl            v1.16.2
helm client        Client: v2.14.0+g05811b8
git                2.21.0
Operating System   Mac OS X 10.14.6 build 18G1012
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

Created with `boot`.

**Comment by tdcox** [comment]
@abayer

**Comment by abayer** [comment]
Hrm, it's been a bit since I last changed behavior here, but lemme see.

**Comment by tdcox** [comment]
I think the problem may be related to `jx step syntax effective -s` reporting the name as `build-make-linux` but the actual name in the source is `make-linux`.

**Comment by tdcox** [comment]
Ok, I see the problem. `jx step syntax effective -s` is making up names for steps and stages that are only vaguely related to their true names and therefore you can't tell what the originals are called unless you go and dig recursively through the source, rendering `jx step syntax effective -s` redundant.

The actual pipeline should be:
```
buildPack: go
pipelineConfig:
  pipelines:
    overrides:
    - name: make-linux
      pipeline: pullRequest
      stage: build
      step:
        command: echo 'This does not EXIST!!!'
        name: myoverride
      type: before
    pullRequest:
      build:
        preSteps:
        - command: echo 'This EXISTS!'
```
The stage is actually called `build` and the step is actually called `make-linux`.

Also, you MUST name the steps you are injecting or the pipeline will create duplicate steps with the name of the step you are overriding before/after and then fail.
