### ISSUE TITLE
Cannot change pipeline image without loosing `containerOptions`

### ISSUE THREAD

**Issue by aure-olli** [jenkins-x/jx#6278]
### Summary 

I sometimes use my own images in the pipelines, mainly because the official images use an old version of jx (`2.0.1005` apparently), and sometimes I also want to do my own test. There should be an easy way to change the image:
```yaml
builPack: go
pipelineConfig:
  agent:
    image: gcr.io/***/builder-go:test
    label: jenkins-go
```
But when running `jx step syntax effective`, the `containerOptions` fields of the pipelines have disappeared.

Digging in the code, the `containerOptions` field actually comes from the `jenkins-x-pod-template-go` secret. To detect which secret to use, the `image` field is used. If it is called `xxx`, it will use `jenkins-x-pod-template-xxx`. Needless to say that when your image is called `gcr.io/***/builder-go:test`, there is no chance to use that pod template, neither to create your own.

I propose that either:

- another field is added to `agent` (`template` ? `podTemplate` ?) to indicate which pod template to use

- the pod template is related to the buildPack, not the image

- the field `label` is used to select the pod template, which will be named by its `metadata.name`. That second options is compatible with the way buildPacks and pod templates are written already (https://github.com/jenkins-x-buildpacks/jenkins-x-classic/blob/master/packs/go/pipeline.yaml#L2),. It will also fix some current problem: the build back `maven-java11` has the image `maven`, so is not using the pod template `jenkins-x-pod-template-maven-java11` but the pod template `jenkins-x-pod-template-maven` (https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/blob/master/packs/maven-java11/pipeline.yaml#L5). I've started to implement this (https://github.com/olli-ai/jx/commit/abbcee50bae9aa7f49f26adf6a4679d713ff2225) however tests needs to be updated too.

### Steps to reproduce the behavior

- check your project pipeline and acknowledge the presence of `containerOptions`
```bash
jx step syntax effective | grep containerOptions -C5
```
- change the image in the pipeline
```bash
builPack: go
pipelineConfig:
  agent:
    image: gcr.io/***/builder-go:test
    label: jenkins-go" > jenkins-x.yml
```
- check your project pipeline and acknowledge that `containerOptions` is gone
```bash
jx step syntax effective | grep containerOptions -C5
```

### Expected behavior

`containerOptions` field should survive a change of image, or there should at least be a way to do so.

### Actual behavior

`containerOptions` is gone

### Jx version

Current head 6e47e73fc2909aba33fe8ed7f6721cf67975a2e1

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Operating system / Environment

`Ubuntu 18.04.3 LTS`

**Comment by abayer** [comment]
So we’re theoretically trying to get away from using the pod templates at all. See #5498, #5212. This means that what we should ideally be doing is automatically populating the appropriate container configuration regardless of pod template. What configuration specifically is missing when you use the fully qualified image and tag that is there with just `go`?

**Comment by aure-olli** [comment]
The part missing is
```yaml
        options:
          containerOptions:
            env:
            - name: DOCKER_REGISTRY
              valueFrom:
                configMapKeyRef:
                  key: docker.registry
                  name: jenkins-x-docker-registry
            - name: DOCKER_CONFIG
              value: /home/jenkins/.docker/
            - name: GIT_AUTHOR_EMAIL
              value: jenkins-x@googlegroups.com
            - name: GIT_AUTHOR_NAME
              value: jenkins-x-bot
            - name: GIT_COMMITTER_EMAIL
              value: jenkins-x@googlegroups.com
            - name: GIT_COMMITTER_NAME
              value: jenkins-x-bot
            - name: JENKINS_URL
              value: http://jenkins:8080
            - name: XDG_CONFIG_HOME
              value: /home/jenkins
            name: ""
            resources:
              limits:
                cpu: "1"
                memory: 1448Mi
              requests:
                cpu: 400m
                memory: 600Mi
            securityContext:
              privileged: true
            volumeMounts:
            - mountPath: /home/jenkins
              name: workspace-volume
            - mountPath: /var/run/docker.sock
              name: docker-daemon
            - mountPath: /home/jenkins/.docker
              name: volume-0
```

This is the part obtained from the pod template `jenkins-x-pod-template-go`, and generated by `jenkinsfile.CreatePipelineForBuildPack` (https://github.com/jenkins-x/jx/blob/master/pkg/jenkinsfile/pipeline.go#L974). If this part is missing, I for instance get errors because the header `DOCKER_REGISTRY` is missing.

This can be solved by passing explicitly those options, or by changing the image step by step, so it's not urgent. I think getting rid of pod templates (and in general all of those stuffs silently generated by `jx`) will be a cleaner solution.

Currently, `jenkinsfile.CreatePipelineForBuildPack` is using the image (`agent.image` or `agent.container`: https://github.com/jenkins-x/jx/blob/master/pkg/tekton/syntax/pipeline.go#L441) to determine which pod template to use. Pod template keys are determined by the name of the secret (https://github.com/jenkins-x/jx/blob/master/pkg/kube/pod_templates.go#L15).

**Comment by aure-olli** [comment]
Apparently the `volume` field from the pod template is also retrieved. If missing, looks like the preview pipeline fails to start. This is much more tricky because it won't appear in `jx step syntax effective`. This seems to be added here: https://github.com/jenkins-x/jx/blob/master/pkg/tekton/syntax/pipeline.go#L1526

So the missing part is:
```yaml
        options:
          volumes:
          - name: workspace-volume
            emptyDir: {}
          - name: docker-daemon
            hostPath:
              path: /var/run/docker.sock
          - name: volume-0
            secret:
              secretName: jenkins-docker-cf
          containerOptions:
            env:
            - name: DOCKER_REGISTRY
              valueFrom:
                configMapKeyRef:
                  key: docker.registry
                  name: jenkins-x-docker-registry
            - name: DOCKER_CONFIG
              value: /home/jenkins/.docker/
            - name: GIT_AUTHOR_EMAIL
              value: jenkins-x@googlegroups.com
            - name: GIT_AUTHOR_NAME
              value: jenkins-x-bot
            - name: GIT_COMMITTER_EMAIL
              value: jenkins-x@googlegroups.com
            - name: GIT_COMMITTER_NAME
              value: jenkins-x-bot
            - name: JENKINS_URL
              value: http://jenkins:8080
            - name: XDG_CONFIG_HOME
              value: /home/jenkins
            name: ""
            resources:
              limits:
                cpu: "1"
                memory: 1448Mi
              requests:
                cpu: 400m
                memory: 600Mi
            securityContext:
              privileged: true
            volumeMounts:
            - mountPath: /home/jenkins
              name: workspace-volume
            - mountPath: /var/run/docker.sock
              name: docker-daemon
            - mountPath: /home/jenkins/.docker
              name: volume-0
```
