### ISSUE TITLE
jx create addon gloo fails

### ISSUE THREAD

**Issue by dmarzan** [jenkins-x/jx#6299]
```
$ jx create addon gloo
installing Knative CRDs...
installing Knative...
Error: installing knative components failed. options used: options.Knative{InstallKnativeVersion:"0.10.0", InstallKnative:true, SkipGlooInstall:false, InstallKnativeMonitoring:false, InstallKnativeEventing:false, InstallKnativeEventingVersion:"0.10.0"}: installing knative resources with kubectl apply: exit status 1
Usage:
  glooctl install knative [flags]
```

### Jx version

The output of `jx version` is:

```
jx version
NAME               VERSION
jx                 2.0.1063
Kubernetes cluster v1.13.11-gke.14
kubectl            v1.16.3
helm client        Client: v2.13.1+g618447c
git                2.21.0 (Apple Git-122.2)
Operating System   Mac OS X 10.15.1 build 19B8
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

```
$ jx create cluster gke --skip-installation
```

### Operating system / Environment

GKE

**Comment by dmarzan** [comment]
This is the error showing in the logs:
service/controller created
service/webhook created
error: error validating "STDIN": error validating data: ValidationError(MutatingWebhookConfiguration.webhooks[0]): unknown field "admissionReviewVersions" in io.k8s.api.admissionregistration.v1beta1.Webhook; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by hferentschik** [comment]
@dmarzan, thanks for creating this issue. We are currently in the process of phasing out the concepts of `addon`s. It will be replaced by another extension framework (`jx add app`).

For that reason, it is unlikely that we are going to look into this bug. If you want to get this fixed maybe you feel up for a contribution. If a pull request comes along we not opposed to merging it with the caveat, however, that `addon`s will be removed eventually.

A better long term solution would be to write an App which installs gloo. Maybe that is something which interests you?

**Comment by jstrachan** [comment]
fwiw if using the helm 3 based boot: https://jenkins-x.io/docs/labs/boot/

you can install gloo via a custom `jx-apps.yml` file something like this:

```yaml
apps:
- name: gloo/gloo
  phase: system
  namespace: gloo
- name: jenkins-x/jxboot-helmfile-resources
- name: jenkins-x/nexus
- name: jenkins-x/lighthouse
- name: jenkins-x/tekton
- name: jenkins-x/chartmuseum
- name: repositories
  repository: ".."
```
