### ISSUE TITLE
feat: Create helm tags and/or global variables for environments

### ISSUE THREAD

**Issue by aure-olli** [jenkins-x/jx#6312]
Currently, in charts, the only way to know which environment is being deployed is to read `.Release.Namespace`. `jx-<environment>` for staging or production, and `jx-<ownwe>-<repo>-pr-<n>` for a preview environment. 

This is quite limited for the following reasons:
- It cannot be used in dependencies conditions
- Extracting the PR number is quite empirical, as different owners can post their PR or namespaces could change in the future

If we pass those info as tags, they can easily be used to condition dependencies. And if we pass it as global, they can be easily used anywhere in the templates.

`helm` already makes it easy to pass those. A call to `helm` could be
```bash
helm template charts/my-project \
    --set tags.jx-production=true \
    --set global.jx-env=production \
    --set global.jx-env-production=true
```
or
```bash
helm template charts/preview \
    --set tags.jx-preview=true \
    --set global.jx-env=preview \
    --set global.jx-env-preview=true \
    --set global.jx-preview-owner=my-owner \
    --set global.jx-preview-project=my-project \
    --set global.jx-preview-pr=3
```

Dependencies could then be like
```yaml
dependencies:
- alias: local-test-redis
  name: redis
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 9.3.3
  tags:
  - jx-preview
```
and templates like
```
{{- template "myDatabase" -}}
  {{- if .Values.global.jx-env-preview -}}
    db-preview-{{ .Values.global.jx-preview-pr }}
  {{- else -}}
    db-{{ .Values.global.jx-env }}
  {{- end -}}
{{- end -}}
```
