### ISSUE TITLE
create effective pipeline fails if passing in DOCKER_REGISTRY

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#6313]
if we pass in the env var DOCKER_REGISTRY to creating the effective pipeline we've seen failures where the pod gets created with an env var of the form:

```yaml
    - name: DOCKER_REGISTRY
      value: gcr.io
      valueFrom:
        configMapKeyRef:
          key: docker.registry
          name: jenkins-x-docker-registry
```

which is invalid; either `value` or `valueFrom` should be used.

It looks like this is coming from logic of taking the `DOCKER_REGISTRY` from the pod templates and not detecting its being passed in to the meta pipeline client as a custom environment variable so should be discarded from the build pack. i.e. it should just generate this...

```yaml
    - name: DOCKER_REGISTRY
      value: gcr.io
```
