### ISSUE TITLE
improve the build packs for skaffold & to work better with different git providers

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#638]
we can remove this section from `Jenkinsfiles` as we can load all this data now from the Secrets/Credentials:
```
      GIT_CREDS         = credentials('jenkins-x-git')
      GIT_USERNAME      = "$GIT_CREDS_USR"
      GIT_API_TOKEN     = "$GIT_CREDS_PSW"
```

Also after the line:
```
sh "git config --global credential.helper store"
```
we can add this line:
```
            sh "jx step git credentials"
```
which ensures that the git CLI has creds to access all the git servers.

We can also add the line:
```
jx step validate --min-jx-version 1.1.71
```
to ensure the `jx` binary is new enough.

Finally to enable skaffold we need to:
* remove the `Dockerfile` from `.dockerignore`
* switch the `docker build / docker push` statements in the `Jenkinsfile` over to:
```
            sh 'export VERSION=`cat VERSION` && skaffold run -f skaffold.yaml'
```
* add a `skaffold.yaml` like this:
```yaml 
apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.JENKINS_X_DOCKER_REGISTRY_SERVICE_HOST}}:{{.JENKINS_X_DOCKER_REGISTRY_SERVICE_PORT}}/{{.ORG}}/{{.APP_NAME}}:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
```
