### ISSUE TITLE
Better jenkins-x.yml secrets syntax

### ISSUE THREAD

**Issue by abayer** [jenkins-x/jx#6380]
We now recommend mounting secret files into the pod directly, which is represented in the syntax currently like the below:
```
        volumes:
          - name: some-secret
            secret:
              secretName: some-secret-key
              items:
                - key: some-secret
                  path: some-path/some-secret.json
        containerOptions:
          volumeMounts:
            - mountPath: /secrets
              name: some-secret
```
That...is kinda crap. We should have some kind of syntactic sugar for that, allowing you to say "put the value for the key `foo` in secret `bar` in the file `/secrets/bar/foo.json`" or somesuch.
