### ISSUE TITLE
.m2 with settings.xml and settings-security.xml folder are not mounted into the container of the setVersion step

### ISSUE THREAD

**Issue by tycoonm** [jenkins-x/jx#6417]
### Summary 
I want that all the maven artifacts are being loaded from my custom nexus repository. For that I set settings.xml and settings-security.xml properties of the `jenkins-maven-settings` secret. Unfortunately this secret is not mounted into the container of setVersion step.  

### Steps to reproduce the behavior
1. Delete old and create new one `jenkins-maven-settings` secret
```
cat <<EOF > jenkins-maven-settings.secret.yaml
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  settings.xml: PHNldHRpbmdzPgogICAgPGxvY2FsUmVwb3NpdG9yeT4vaG9tZS9qZW5raW5zLy5tdm5yZXBvc2l0b3J5PC9sb2NhbFJlcG9zaXRvcnk+CiAgICA8IS0tVGhpcyBzZW5kcyBldmVyeXRoaW5nIHRvIC9tYXZlbi1wdWJsaWMgLS0+CiAgICA8bWlycm9ycz4KICAgICAgICA8bWlycm9yPgogICAgICAgICAgICA8aWQ+bmV4dXM8L2lkPgogICAgICAgICAgICA8bmFtZT5uZXh1cyBtaXJyb3I8L25hbWU+CiAgICAgICAgICAgIDxtaXJyb3JPZj5leHRlcm5hbDoqPC9taXJyb3JPZj4KICAgICAgICAgICAgPHVybD5odHRwOi8vbmV4dXMubG9jYWwvcmVwb3NpdG9yeS9tYXZlbi1wdWJsaWMvPC91cmw+CiAgICAgICAgPC9taXJyb3I+CiAgICA8L21pcnJvcnM+CgogICAgPCEtLSBsZXRzIGRpc2FibGUgdGhlIGRvd25sb2FkIHByb2dyZXNzIGluZGljYXRvciB0aGF0IGZpbGxzIHVwIGxvZ3MgLS0+CiAgICA8aW50ZXJhY3RpdmVNb2RlPmZhbHNlPC9pbnRlcmFjdGl2ZU1vZGU+CiAgICA8cHJvZmlsZXM+CiAgICAgICAgPHByb2ZpbGU+CiAgICAgICAgICAgIDxpZD5uZXh1czwvaWQ+CiAgICAgICAgICAgIDxwcm9wZXJ0aWVzPgogICAgICAgICAgICAgICAgPGFsdERlcGxveW1lbnRSZXBvc2l0b3J5PmxvY2FsLW5leHVzOjpkZWZhdWx0OjpodHRwOi8vbmV4dXMubG9jYWwvcmVwb3NpdG9yeS9tYXZlbi1zbmFwc2hvdHMvPC9hbHREZXBsb3ltZW50UmVwb3NpdG9yeT4KICAgICAgICAgICAgICAgIDxhbHRSZWxlYXNlRGVwbG95bWVudFJlcG9zaXRvcnk+bG9jYWwtbmV4dXM6OmRlZmF1bHQ6Omh0dHA6Ly9uZXh1cy5sb2NhbC9yZXBvc2l0b3J5L21hdmVuLXJlbGVhc2VzLzwvYWx0UmVsZWFzZURlcGxveW1lbnRSZXBvc2l0b3J5PgogICAgICAgICAgICAgICAgPGFsdFNuYXBzaG90RGVwbG95bWVudFJlcG9zaXRvcnk+bG9jYWwtbmV4dXM6OmRlZmF1bHQ6Omh0dHA6Ly9uZXh1cy5sb2NhbC9yZXBvc2l0b3J5L21hdmVuLXNuYXBzaG90cy88L2FsdFNuYXBzaG90RGVwbG95bWVudFJlcG9zaXRvcnk+CiAgICAgICAgICAgIDwvcHJvcGVydGllcz4KCiAgICAgICAgICAgIDwhLS1FbmFibGUgc25hcHNob3RzIGZvciB0aGUgYnVpbHQgaW4gY2VudHJhbCByZXBvIHRvIGRpcmVjdCAtLT4KICAgICAgICAgICAgPCEtLWFsbCByZXF1ZXN0cyB0byBuZXh1cyB2aWEgdGhlIG1pcnJvciAtLT4KICAgICAgICAgICAgPHJlcG9zaXRvcmllcz4KICAgICAgICAgICAgICA8cmVwb3NpdG9yeT4KICAgICAgICAgICAgICAgIDxpZD5jZW50cmFsPC9pZD4KICAgICAgICAgICAgICAgIDx1cmw+aHR0cDovL2NlbnRyYWw8L3VybD4KICAgICAgICAgICAgICAgIDxyZWxlYXNlcz48ZW5hYmxlZD50cnVlPC9lbmFibGVkPjwvcmVsZWFzZXM+CiAgICAgICAgICAgICAgICA8c25hcHNob3RzPjxlbmFibGVkPnRydWU8L2VuYWJsZWQ+PC9zbmFwc2hvdHM+CiAgICAgICAgICAgICA8L3JlcG9zaXRvcnk+CiAgICAgICAgICAgPC9yZXBvc2l0b3JpZXM+CiAgICAgICAgICAgPHBsdWdpblJlcG9zaXRvcmllcz4KICAgICAgICAgICAgICA8cGx1Z2luUmVwb3NpdG9yeT4KICAgICAgICAgICAgICAgIDxpZD5jZW50cmFsPC9pZD4KICAgICAgICAgICAgICAgIDx1cmw+aHR0cDovL2NlbnRyYWw8L3VybD4KICAgICAgICAgICAgICAgIDxyZWxlYXNlcz48ZW5hYmxlZD50cnVlPC9lbmFibGVkPjwvcmVsZWFzZXM+CiAgICAgICAgICAgICAgICA8c25hcHNob3RzPjxlbmFibGVkPnRydWU8L2VuYWJsZWQ+PC9zbmFwc2hvdHM+CiAgICAgICAgICAgICAgPC9wbHVnaW5SZXBvc2l0b3J5PgogICAgICAgICAgIDwvcGx1Z2luUmVwb3NpdG9yaWVzPgoKICAgICAgICA8L3Byb2ZpbGU+CiAgICAgICAgPHByb2ZpbGU+CiAgICAgICAgICAgIDxpZD5yZWxlYXNlPC9pZD4KICAgICAgICAgICAgPHByb3BlcnRpZXM+CiAgICAgICAgICAgICAgICA8Z3BnLmV4ZWN1dGFibGU+Z3BnPC9ncGcuZXhlY3V0YWJsZT4KICAgICAgICAgICAgICAgIDwhLS0gVE9ETyB1c2U6IC5QYXJhbWV0ZXJzLmdwZy5wYXNzcGhyYXNlIHdoZW4gaXQgaXMgYWx3YXlzIHBvcHVsYXRlZCAtLT4KICAgICAgICAgICAgICAgIDxncGcucGFzc3BocmFzZT48L2dwZy5wYXNzcGhyYXNlPgogICAgICAgICAgICA8L3Byb3BlcnRpZXM+CiAgICAgICAgPC9wcm9maWxlPgogICAgPC9wcm9maWxlcz4KICAgIDxhY3RpdmVQcm9maWxlcz4KICAgICAgICA8YWN0aXZlUHJvZmlsZT5uZXh1czwvYWN0aXZlUHJvZmlsZT4KICAgIDwvYWN0aXZlUHJvZmlsZXM+Cjwvc2V0dGluZ3M+Cg==
kind: Secret
metadata:
  annotations:
    jenkins.io/chart: env
  name: jenkins-maven-settings
  namespace: jx
type: Opaque
EOF
kubectl delete -f jenkins-maven-settings.secret.yaml
kubectl apply -f jenkins-maven-settings.secret.yaml
```
2. Create new maven quickstart Projekt
3. Check in the build log that maven in the step `setVersion` tries to download artifacts from nexus.local repository

### Expected behavior
Secret `jenkins-maven-settings` is mounted into the container of `setVersion` step and used by maven.

### Actual behavior
Secret is not mounted into the container of `setVersion` step and artifacts are being loaded from maven central repository instead of in settings.xml configured repository.

### Jx version

The output of `jx version` is:

```
$ jx version
NAME               VERSION
jx                 2.0.1102
Kubernetes cluster v1.17.0
kubectl            v1.17.0
helm client        Client: v2.16.1+gbbdfe5e
git                2.21.0 (Apple Git-122.2)
Operating System   Mac OS X 10.14.6 build 18G103


verifying packages
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

On-Premise

### Operating system / Environment

macOS Mojave
Version: 10.14.6
