### ISSUE TITLE
error: no pipeline user found for git server https://github.com from gitURL https://github.com/myorg/environment-app-test-dev.git

### ISSUE THREAD

**Issue by zadigus** [jenkins-x/jx#6456]
### Summary 

After a lot of struggling, I'm finally more or less able to finalize Jenkins X installation on my k8s cluster hosted on Jelastic. However, I am now stuck with the following issue:
```
error: no pipeline user found for git server https://github.com from gitURL https://github.com/...
```
I created a user for the pipelines with a git token which I provided to the `jx boot`. I don't understand what I could be missing here. The token has following rights:
```
repo,read:user,read:org,user:email,write:repo_hook,delete_repo
```
The user has write access to any repository in the organization.

### Steps to reproduce the behavior

1. Install the development kubernetes environment on jelastic from the marketplace
2. Install `jx`
3. Install the latest `git` from the github archives
4. Run `jx boot`

### Expected behavior

The `dev` environment can be created at the URL specified by the `jx` output.

### Actual behavior

I get the above mentioned error.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1107
Kubernetes cluster v1.15.6
kubectl            v1.15.6
helm client        Client: v2.16.1+gbbdfe5e
git                2.24.1
Operating System   CentOS Linux release 7.7.1908 (Core)
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

`kubectl version` gives:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"archive", BuildDate:"2019-11-19T09:00:01Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"li
nux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"archive", BuildDate:"2019-11-19T08:45:41Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"li
nux/amd64"}
```

As mentioned above, the cluster was created with marketplace installer on Jelastic.

### Operating system / Environment

```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

**Comment by zadigus** [comment]
I forgot to mention that this is my `jx-requirements.yml`: 

```
autoUpdate:
  enabled: false
  schedule: ""
bootConfigURL: https://github.com/jenkins-x/jenkins-x-boot-config
cluster:
  clusterName: shopozor-test
  environmentGitOwner: shopozor
  environmentGitPublic: true
  gitKind: github
  gitName: github
  gitServer: https://github.com
  namespace: jx
  provider: kubernetes
  registry: docker.io
environments:
- ingress:
    domain: env-8958284.hidora.com
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  key: dev
- ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: ""
    tls:
      email: ""
      enabled: false
      production: false
  key: staging
- ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: ""
    tls:
      email: ""
      enabled: false
      production: false
  key: production
gitops: true
ingress:
  domain: env-8958284.hidora.com
  externalDNS: false
  namespaceSubDomain: -jx.
  tls:
    email: ""
    enabled: false
    production: false
kaniko: true
repository: nexus
secretStorage: local
storage:
  backup:
    enabled: false
    url: ""
  logs:
    enabled: false
    url: ""
  reports:
    enabled: false
    url: ""
  repository:
    enabled: false
    url: ""
vault: {}
velero: {}
versionStream:
  ref: v1.0.289
  url: https://github.com/jenkins-x/jenkins-x-versions.git
webhook: prow
```
In particular, I configured the bootstrapping with public github repositories.
