### ISSUE TITLE
generated expose config tlsSecretName contains dots which does not match the secret name

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#6463]
Generated config:
```
expose:
  config:
    domain: jx.domain.tld
    exposer: Ingress
    http: "false"
    tlsSecretName: tls-jx.domain.tld-p
    tlsacme: "true"
    urltemplate: '{{.Service}}-{{.Namespace}}.{{.Domain}}'
  production: true
```
However the generated Kubernetes Secret is actually called `tls-jx-domain-tld-p`

/kind bug
/assign rawlingsj
