### ISSUE TITLE
Override is not selecting the correct agent

### ISSUE THREAD

**Issue by guitcastro** [jenkins-x/jx#6492]
### Summary 

I am overring two steps `gradle-build` and `gradle-build`, one should use `builder-gradle5-java11` image and the other `kaniko-project/executor` Although both steps are being executed in the `builder-gradle5-java11` image

### Steps to reproduce the behavior

Create the following pipeline:

```
buildPack: gradle
pipelineConfig:
  pipelines:
    overrides:
      - stage: build
        steps:
          - name: gradle-build
            sh:  gradle clean build
            agent:
              label: jenkins-gradle
              container: gcr.io/jenkinsxio/builder-gradle5-java11
          - name: container-build
            sh: /kaniko/executor --dockerfile=./Dockerfile --context=./ --insecure
            agent:
              label: kaniko
              container: gcr.io/kaniko-project/executor
```

### Expected behavior

The container-build step should be executed in kaniko container 

### Actual behavior

The container-build step is being executed using the builder-gradle5-java11 container. 

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1104
Kubernetes cluster v1.15.4-gke.22
kubectl            v1.14.8
helm client        Client: v2.16.1+gbbdfe5e
git                2.21.0 (Apple Git-122.2)
Operating System   Mac OS X 10.15.1 build 19B77a
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GKE using jx boot

### Operating system / Environment
MAC OS

**Comment by abayer** [comment]
Try this - it should work:
```
buildPack: gradle
pipelineConfig:
  pipelines:
    overrides:
      - stage: build
        steps:
          - name: gradle-build
            sh:  gradle clean build
            image: gcr.io/jenkinsxio/builder-gradle5-java11
          - name: container-build
            sh: /kaniko/executor --dockerfile=./Dockerfile --context=./ --insecure
            image: gcr.io/kaniko-project/executor
```

If that doesn't work, let me know and I'll change this to a bug and see what I can do.
