### ISSUE TITLE
jx boot install Jenkins Master in stateless mode

### ISSUE THREAD

**Issue by alexvolsh** [jenkins-x/jx#6512]
### Summary 
`jx boot` install prow and jenkins at the same time

### Steps to reproduce the behavior
set webhook in jx-requirements.yml with prow
```
...
versionStream:
  ref: v1.0.298
  url: https://github.com/jenkins-x/jenkins-x-versions.git
webhook: prow
```
and run
`jx boot`

### Expected behavior
Install stateless components

### Actual behavior
Install stateless and classic components

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1120
Kubernetes cluster v1.15.6
kubectl            v1.17.0
helm client        v2.16.1+gbbdfe5e
helm server        v2.16.1+gbbdfe5e
git                2.25.0
Operating System   Mac OS X 10.15.3 build 19D49f


verifying packages
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

Self-created with kubespray

### Operating system / Environment

Running the CLI on my MacBook Pro (OS X)

**Comment by hferentschik** [comment]
How do you see that there are any "classic" components installed?

**Comment by alexvolsh** [comment]
I see it in deployment section of the dev namespace.
<img width="1193" alt="Screenshot 2020-01-14 at 14 56 56" src="https://user-images.githubusercontent.com/183509/72346319-68604280-36de-11ea-9c58-7e4c201eb35b.png">

**Comment by alexvolsh** [comment]
@hferentschik also if I try manually add
```
jenkins:
  enabled: false
```
in values.yaml or values.tmpl.yaml files for `env/jenkins`, `env/jenkins-x-platform`, this configuration ignored.

**Comment by alexvolsh** [comment]
@hferentschik the same for 
```
versionStream:
  ref: v1.0.303
  url: https://github.com/jenkins-x/jenkins-x-versions.git
```
Also, I tried to change `kubeProviders/kubernetes/values.tmpl.yaml` with:
```
# Override configuration from https://github.com/jenkins-x/jenkins-x-platform/blob/master/jenkins-x-platform/values.yaml

jenkins:
  enabled: false
```
And `jenkins` still installing to dev namespace.
Maybe you need more info or something wrong with my understanding of the `jx boot` work behavior?

**Comment by daveconde** [comment]
Hi, could you please share your jx-requirements.yaml? Are you seeing that both prow and a static Jenkins master are being installed in to the same cluster?

**Comment by alexvolsh** [comment]
@daveconde yes, I seeing both prow and a static Jenkins master in the same namespace right after the first run of the `jx boot`.
Static Jenkins master doesn't install only in case if I add configuration in `kubeProviders/kubernetes/values.tmpl.yaml`:

```
jenkins-x-platform:
  jenkins:
    enabled: false
```

 jx-requirements.yaml
```
autoUpdate:
  enabled: false
  schedule: ""
bootConfigURL: https://github.com/geeoz/environment-razomer-dev
cluster:
  clusterName: geeoz
  devEnvApprovers:
  - alexvolsh
  - sergevoloshyn
  environmentGitOwner: geeoz
  gitKind: github
  gitName: github
  gitServer: https://github.com
  namespace: razomer
  provider: kubernetes
  registry: https://docker.geeoz.com
environments:
- ingress:
    domain: razomer.com
    externalDNS: false
    namespaceSubDomain: .
    tls:
      email: alex@geeoz.com
      enabled: true
      production: false
  key: dev
  repository: environment-razomer-dev
- ingress:
    domain: razomer.com
    externalDNS: false
    namespaceSubDomain: ""
    tls:
      email: alex@geeoz.com
      enabled: true
      production: false
  key: staging
  repository: environment-razomer-staging
- ingress:
    domain: razomer.com
    externalDNS: false
    namespaceSubDomain: ""
    tls:
      email: alex@geeoz.com
      enabled: true
      production: false
  key: production
  repository: environment-razomer-production
gitops: true
ingress:
  domain: razomer.com
  externalDNS: false
  namespaceSubDomain: .
  tls:
    email: alex@geeoz.com
    enabled: true
    production: false
kaniko: true
repository: none
secretStorage: local
storage:
  backup:
    enabled: false
    url: ""
  logs:
    enabled: false
    url: ""
  reports:
    enabled: false
    url: ""
  repository:
    enabled: false
    url: ""
vault: {}
velero:
  schedule: ""
  ttl: ""
versionStream:
  ref: v1.0.303
  url: https://github.com/jenkins-x/jenkins-x-versions.git
webhook: prow
```
