### ISSUE TITLE
Vault Secret Interpolation in Helm

### ISSUE THREAD

**Issue by sharepointoscar** [jenkins-x/jx#6527]
### Summary 
In the process of getting Vault secret values within my Helm app chart, it appears there are some changes in the staging env repo in order for it to work.

### Steps to reproduce the behavior
1. Create a `env/values.tmpl.yaml` in the Staging environment repo with the following sample content (assuming you have the Vault secret here).

```yaml
PipelineSecrets: {}
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: cjxd.sharepointoscar.com
    exposer: Ingress
    http: "true"
    tlsacme: "false"
jenkins:
  Servers:
    Global: {}
prow: {}

cars-rest-api: # this is my app
  env:
    MONGODB_USERNAME: vault:mongodb:mongodb-username
    MONGODB_PASSWORD: vault:mongodb:mongodb-password
    MONGODB_DATABASE: cars-rest-api
    MONGODB_ROOT_PASSWORD: vault:mongodb:mongodb-root-password
```

2. If I do not create a file called `env/values.yaml`, and run  `jx boot` , it fails with an error message stating that the `values.yaml` file is missing as the deployment is being built.

### Expected behavior
Since creating the `values.tmpl.yaml` file was unknown to me until recently, I am not sure if this is expected behavior or more of an enhancement.

### Actual behavior
Once I add the `env/values.yaml` to my staging env repo. all is good.
### Jx version

The output of `jx version` is:

```
jx                 2.0.1005+cjxd.5
Kubernetes cluster v1.13.11-gke.14
kubectl            v1.16.0
helm client        Client: v2.13.1+g618447c
git                2.21.0
Operating System   Mac OS X 10.14.6 build 18G103
```

### Jenkins type

- [ X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

NOTE: See Slack conversation for more context at https://kubernetes.slack.com/archives/C9LTHT2BB/p1578996276093400
