### ISSUE TITLE
Duplicated SourceRepository resources

### ISSUE THREAD

**Issue by vbehar** [jenkins-x/jx#6545]
### Summary 

I "manually" created sourcerepositories by adding files in `repositories/templates` in the git repo for the dev env. When the first pipeline ran, it created a duplicated resource for my repository, resulting in an invalid hook configuration.

### Steps to reproduce the behavior

- add a sourcerepository in the `repositories/templates` directory of the git repo for the dev env. name it after the repo. push/merge/...
- trigger a first pipeline run for your application repo. it will automatically create a new SourceRepository resource in the cluster, named `${owner}-${repo}`, which duplicates the existing one - but with a different name
- this generates an invalid configuration for `hook`, with duplicated entries in the `config` configmap:

```
owner/repo:
      - agent: tekton
        always_run: true
        context: pr-build
        name: pr-build
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
      - agent: tekton
        always_run: true
        context: pr-build
        name: pr-build
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
```
- hook is full of errors such as
```
{"component":"hook","error":"duplicated presubmit job: pr-build","jobConfig":"","level":"error","msg":"Error loading config.","prowConfig":"/etc/config/config.yaml"...}
```

### Expected behavior

- the second resource for the same repo should not have been created
- the invalid hook config should not have been generated

### Actual behavior

- duplicated SourceRepository resources - which in itself is not really the issue, just confusing
- invalid hook configuration

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1120
Kubernetes cluster v1.15.4-gke.22
kubectl            v1.15.7
helm client        Client: v2.14.3+g0e7f3b6
git                2.24.0
Operating System   Mac OS X 10.12.6 build 16G2136
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GKE, using jx boot

### Operating system / Environment

macos

### More informations

see this slack thread: https://kubernetes.slack.com/archives/C9MBGQJRH/p1579207114237400
