### ISSUE TITLE
`jx boot` failing on GHE with latest CLI due to failing GET request

### ISSUE THREAD

**Issue by tomfrenken** [jenkins-x/jx#6551]
### Summary 
With the latest CLI I receive the following errors on GitHub Enterprise:

```
error: handle dev environment repository: creating remote for dev environment environment-jx-eval-01-dev: duplicating https://github.com/tomfrenken/jenkins-x-boot-config to jx-test-org/environment-jx-eval-01-dev: getting repo for https://github.com/tomfrenken/jenkins-x-boot-config: failed to get repository tomfrenken/jenkins-x-boot-config due to: GET https://github.tools.sap/api/v3/repos/tomfrenken/jenkins-x-boot-config: 404 Not Found []
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step verify env' command in directory '.', output: ''
```
I previously forked the repo and changed the files, the `jx-requirements.yaml` looks like this:

```yaml
cluster:
  clusterName: ""
  environmentGitOwner: ""
  environmentGitPublic: false
  gitKind: github
  gitName: ghe
  gitServer: https://github.tools.sap
  project: ""
  provider: gke
  zone: ""
gitops: true
environments:
- key: dev
- key: staging
- key: production
ingress:
  domain: ""
  externalDNS: false
  tls:
    email: ""
    enabled: false
    production: false
kaniko: true
secretStorage: local
storage:
  logs:
    enabled: true
    url: ""
  reports:
    enabled: true
    url: ""
  repository:
    enabled: true
    url: ""
versionStream:
  ref: "master"
  url: https://github.com/jenkins-x/jenkins-x-versions.git
webhook: lighthouse
```

### Steps to reproduce the behavior
Fork the boot-config, change values to work with GHE, run `jx boot`

### Expected behavior
It works

### Actual behavior
It doesn't

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1133
Kubernetes cluster v1.13.11-gke.14
kubectl            v1.17.1
helm client        Client: v2.16.1+gbbdfe5e
git                2.25.0
Operating System   Mac OS X 10.15.2 build 19C57
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Lighthouse)
- [ ] Classic Jenkins
