### ISSUE TITLE
`tekton-pipelines-controller` conflict for the team environment

### ISSUE THREAD

**Issue by alexvolsh** [jenkins-x/jx#6560]
### Summary 
Dev/staging/production environment build fails with `jx boot` setup usage.

### Steps to reproduce the behavior
1. Create private clone of the `jenkins-x-boot-config` repo
2. Setup credentials by using `jx step verify preinstall`
3. Update `jx-requirements.yml` with additional configuration. The full version of the file:
```
autoUpdate:
  enabled: false
  schedule: ""
bootConfigURL: https://github.com/geeoz/environment-razomer-dev
cluster:
  clusterName: geeoz
  devEnvApprovers:
  - alexvolsh
  - sergevoloshyn
  environmentGitOwner: geeoz
  gitKind: github
  gitName: github
  gitServer: https://github.com
  namespace: razomer
  provider: kubernetes
  registry: https://docker.geeoz.com
environments:
- ingress:
    domain: razomer.com
    externalDNS: false
    namespaceSubDomain: .
    tls:
      email: alex@geeoz.com
      enabled: true
      production: false
  key: dev
  repository: environment-razomer-dev
- ingress:
    domain: razomer.com
    externalDNS: false
    namespaceSubDomain: ""
    tls:
      email: alex@geeoz.com
      enabled: true
      production: false
  key: staging
  repository: environment-razomer-staging
- ingress:
    domain: razomer.com
    externalDNS: false
    namespaceSubDomain: ""
    tls:
      email: alex@geeoz.com
      enabled: true
      production: false
  key: production
  repository: environment-razomer-production
gitops: true
ingress:
  domain: razomer.com
  externalDNS: false
  namespaceSubDomain: .
  tls:
    email: alex@geeoz.com
    enabled: true
    production: false
kaniko: true
repository: none
secretStorage: local
storage:
  backup:
    enabled: false
    url: ""
  logs:
    enabled: false
    url: ""
  reports:
    enabled: false
    url: ""
  repository:
    enabled: false
    url: ""
vault: {}
velero:
  schedule: ""
  ttl: ""
versionStream:
  ref: master
  url: https://github.com/jenkins-x/jenkins-x-versions.git
webhook: prow
```
4. Run `jx boot` command
Successful command result log:
```
Git tokens seem to be setup correctly
Installation is currently looking: GOOD
```

File `jx-requirements.yml` was updated with:
```
versionStream:
  ref: v1.0.307
```
5. Push changes of the `jx-requirements.yml` file to the GitHub private dev repo (https://github.com/geeoz/environment-razomer-dev). Example changes:
```
versionStream:
  ref: master
```

### Expected behavior

Build start and finish successfully.

### Actual behavior

Build creates multiple pods that are still running after building failure.

`kubectl get pod` returns:

```
NAME                                                                    READY   STATUS      RESTARTS   AGE
crier-76bb69cdcc-lrwlw                                                  1/1     Running     0          12m
deck-6d894bd6c-5p74w                                                    1/1     Running     0          12m
deck-6d894bd6c-mc5xk                                                    1/1     Running     0          12m
geeoz-environment-razomer-dev-m-7dp6m-1-release-2cwzj-pod-0380f9        19/19   Running     0          3m27s
geeoz-environment-razomer-dev-m-7dp6m-1-release-2cwzj-pod-322d4a        0/19    Completed   0          3m27s
geeoz-environment-razomer-dev-m-7dp6m-1-release-2cwzj-pod-783140        19/19   Running     0          3m27s
geeoz-environment-razomer-dev-m-7dp6m-1-release-5hgsq-pod-4a942d        19/19   Running     0          3m27s
geeoz-environment-razomer-dev-m-7dp6m-1-release-5hgsq-pod-660c08        0/19    Completed   0          3m26s
geeoz-environment-razomer-dev-m-7dp6m-1-release-5hgsq-pod-e5acc6        19/19   Running     0          3m27s
geeoz-environment-razomer-dev-m-7dp6m-1-release-h42q8-pod-44fad9        19/19   Running     0          3m27s
geeoz-environment-razomer-dev-m-7dp6m-1-release-h42q8-pod-d5983e        0/19    Completed   0          3m27s
geeoz-environment-razomer-dev-m-7dp6m-1-release-h42q8-pod-f29ad5        19/19   Running     0          3m27s
geeoz-environment-razomer-dev-m-gkt22-1-release-cccjk-pod-11fc5d        0/19    Completed   0          4m16s
geeoz-environment-razomer-dev-m-gkt22-1-release-cccjk-pod-5aea96        19/19   Running     0          4m17s
geeoz-environment-razomer-dev-m-gkt22-1-release-cccjk-pod-6254ed        19/19   Running     0          4m16s
geeoz-environment-razomer-dev-m-gkt22-1-release-hn9vb-pod-15f62d        19/19   Running     0          4m17s
geeoz-environment-razomer-dev-m-gkt22-1-release-hn9vb-pod-4f0b0d        19/19   Running     0          4m17s
geeoz-environment-razomer-dev-m-gkt22-1-release-hn9vb-pod-c2ca7a        6/19    Running     0          4m17s
geeoz-environment-razomer-dev-m-gkt22-1-release-tdzm9-pod-0e68a2        0/19    Completed   0          4m17s
geeoz-environment-razomer-dev-m-gkt22-1-release-tdzm9-pod-8f3f7b        19/19   Running     0          4m17s
geeoz-environment-razomer-dev-m-gkt22-1-release-tdzm9-pod-ef1472        19/19   Running     0          4m17s
hook-68777d88c7-9rxhn                                                   1/1     Running     0          12m
hook-68777d88c7-r784q                                                   1/1     Running     0          12m
horologium-7ffb6d7cfd-5cv4h                                             1/1     Running     0          12m
jenkins-x-chartmuseum-5459d54d46-mrzhr                                  1/1     Running     0          74s
jenkins-x-controllerbuild-84d8857865-589sn                              1/1     Running     0          72s
jenkins-x-controllerrole-7c545585cf-wr8gv                               1/1     Running     0          12m
jenkins-x-gcactivities-1579359600-25c7d                                 0/1     Completed   0          4m18s
jenkins-x-gcpods-1579359600-g9xsg                                       0/1     Completed   0          4m18s
jenkins-x-gcpreviews-1579359600-d8cxc                                   0/1     Completed   0          4m18s
jenkins-x-heapster-59ddd47fc9-bhlsh                                     2/2     Running     0          33s
meta-geeoz-environment-razomer-jtkdw-1-meta-pipeline-5s9sr-pod-021e27   5/5     Running     0          5m3s
meta-geeoz-environment-razomer-jtkdw-1-meta-pipeline-5s9sr-pod-022f4b   5/5     Running     0          5m3s
meta-geeoz-environment-razomer-jtkdw-1-meta-pipeline-5s9sr-pod-2db1ce   0/5     Completed   0          5m3s
meta-geeoz-environment-razomer-jtkdw-1-meta-pipeline-kwh7k-pod-45b128   0/5     Completed   0          5m3s
meta-geeoz-environment-razomer-jtkdw-1-meta-pipeline-kwh7k-pod-97a946   5/5     Running     0          5m3s
meta-geeoz-environment-razomer-jtkdw-1-meta-pipeline-kwh7k-pod-cbcf13   5/5     Running     0          5m3s
meta-geeoz-environment-razomer-jtkdw-1-meta-pipeline-p55pj-pod-022e8b   5/5     Running     0          5m2s
meta-geeoz-environment-razomer-jtkdw-1-meta-pipeline-p55pj-pod-abd9ff   5/5     Running     0          5m2s
meta-geeoz-environment-razomer-jtkdw-1-meta-pipeline-p55pj-pod-b368fd   0/5     Completed   0          5m2s
pipeline-599c968cc5-cnjhn                                               1/1     Running     0          12m
pipelinerunner-7b6dcb5956-8zstc                                         1/1     Running     0          12m
tekton-pipelines-controller-569d5f977d-kfxcv                            1/1     Running     0          12m
tide-5f6df69548-4hl9m                                                   1/1     Running     0          12m
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1139
Kubernetes cluster v1.15.6
kubectl            v1.17.1
helm client        v2.16.1+gbbdfe5e
helm server        v2.16.1+gbbdfe5e
git                2.25.0
Operating System   Mac OS X 10.15.3 build 19D62e


verifying packages
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

Self-created with kubespray

### Operating system / Environment

Running the CLI on my MacBook Pro (OS X)

**Comment by cagiti** [comment]
Hi @alexvolsh, do you happen to have more information on how the cluster was installed and how the boot process was initiated? Thank you in advance.

**Comment by alexvolsh** [comment]
@cagiti yes, I have. What exactly do you interested in?

1. Kubernetes cluster where I tried to use `jx boot` already has working Jenkins X environments that were installed by `jx install` earlier.

2. I had changed the `jenkins-x.yml` config to disable the installation of the nginx-ingress, cert-manager and acme (we already have all of this).
Current `jenkins-x.yml`:
```
buildPack: none
pipelineConfig:
  pipelines:
    pullRequest:
      pipeline:
        agent:
          image: gcr.io/jenkinsxio/builder-go
        stages:
        - name: pr-checks
          options:
            containerOptions:
              name: ""
              resources: {}
              volumeMounts:
              - mountPath: /builder/home/.jx/localSecrets/currentCluster
                name: local-secrets
                readOnly: true
            volumes:
            - name: local-secrets
              secret:
                optional: true
                secretName: local-param-secrets
          steps:
          - args:
            - step
            - verify
            - values
            - --values-file=parameters.yaml
            - --schema-file=parameters.tmpl.schema.json
            command: jx
            dir: /workspace/source/env
            name: verify-parameters
          - args:
            - build
            command: make
            dir: /workspace/source/env
            name: lint-env-helm
    release:
      pipeline:
        agent:
          image: gcr.io/jenkinsxio/builder-go
        environment:
        - name: DEPLOY_NAMESPACE
          value: razomer
        - name: GIT_AUTHOR_NAME
          value: alexvolsh
        - name: GIT_COMMITTER_NAME
          value: alexvolsh
        - name: GIT_AUTHOR_EMAIL
          value: alex@geeoz.com
        - name: GIT_COMMITTER_EMAIL
          value: alex@geeoz.com
        stages:
        - name: release
          options:
            containerOptions:
              name: ""
              resources: {}
              volumeMounts:
              - mountPath: /builder/home/.jx/localSecrets/currentCluster
                name: local-secrets
                readOnly: true
            volumes:
            - name: local-secrets
              secret:
                optional: true
                secretName: local-param-secrets
          steps:
          - args:
            - step
            - git
            - validate
            command: jx
            dir: /workspace/source/env
            name: validate-git
          - args:
            - step
            - verify
            - preinstall
            - --provider-values-dir="kubeProviders"
            command: jx
            dir: /workspace/source
            name: verify-preinstall
          - args:
            - upgrade
            - crd
            command: jx
            name: install-jx-crds
          - args:
            - step
            - helm
            - apply
            - --boot
            - --remote
            - --no-vault
            - --name
            - velero
            command: jx
            dir: /workspace/source/systems/velero
            env:
            - name: DEPLOY_NAMESPACE
              value: velero
            name: install-velero
          - args:
            - step
            - helm
            - apply
            - --boot
            - --remote
            - --no-vault
            - --name
            - velero-backups
            command: jx
            dir: /workspace/source/systems/velero-backups
            env:
            - name: DEPLOY_NAMESPACE
              value: velero
            name: install-velero-backups
          - args:
            - step
            - create
            - install
            - values
            - -b
            command: jx
            dir: /workspace/source/env
            name: create-install-values
          - args:
            - step
            - helm
            - apply
            - --boot
            - --remote
            - --no-vault
            - --name
            - exdns
            command: jx
            dir: /workspace/source/systems/external-dns
            name: install-external-dns
          - args:
            - step
            - boot
            - vault
            - --provider-values-dir
            - ../../kubeProviders
            command: jx
            dir: /workspace/source/systems/vault
            name: install-vault
          - args:
            - step
            - create
            - values
            - --name
            - parameters
            command: jx
            dir: /workspace/source/env
            name: create-helm-values
          - args:
            - step
            - create
            - templated
            - --parameters-file=../../env/parameters.yaml
            - --requirements-dir=../../
            - --template-file=jx-auth-configmap.tmpl.yaml
            - --config-file=templates/jx-auth-configmap.yaml
            command: jx
            dir: /workspace/source/systems/jx-auth
            name: create-jx-auth-config
          - args:
            - step
            - helm
            - apply
            - --boot
            - --remote
            - --no-vault
            - --name
            - jx-auth
            command: jx
            dir: /workspace/source/systems/jx-auth
            name: install-jx-auth-config
          - args:
            - step
            - helm
            - apply
            - --boot
            - --remote
            - --name
            - jenkins-x
            - --provider-values-dir
            - ../kubeProviders
            command: jx
            dir: /workspace/source/env
            name: install-jenkins-x
          - args:
            - step
            - verify
            - env
            command: jx
            dir: /workspace/source
            name: verify-jenkins-x-environment
          - args:
            - step
            - helm
            - apply
            - --boot
            - --name
            - repos
            command: jx
            dir: /workspace/source/repositories
            name: install-repositories
          - args:
            - step
            - scheduler
            - config
            - apply
            - --direct=true
            command: jx
            dir: /workspace/source/prowConfig
            name: install-pipelines
          - args:
            - update
            - webhooks
            - --verbose
            - --warn-on-fail
            command: jx
            dir: /workspace/source/repositories
            name: update-webhooks
          - args:
            - step
            - verify
            - install
            - --pod-wait-time
            - 30m
            command: jx
            dir: /workspace/source/env
            name: verify-installation
```

3. I had changed the `kubeProviders/kubernetes/values.tmpl.yaml`, because I also has an issue https://github.com/jenkins-x/jx/issues/6512 and I need to setup shared resources like Nexus, Chartmuseum.
Current `kubeProviders/kubernetes/values.tmpl.yaml`:
```
# Override configuration from https://github.com/jenkins-x/jenkins-x-platform/blob/master/jenkins-x-platform/values.yaml

jenkins-x-platform:
  chartmuseum:
    enabled: false

  chartmuseumServiceLink:
    enabled: true
    externalName: "jenkins-x-chartmuseum.jenkins-x-stack.svc.geeoz"

  jenkins:
    enabled: false

  docker-registry:
    enabled: false

  nexus:
    enabled: false

  nexusServiceLink:
    enabled: true
    externalName: "nexus.jenkins-x-stack.svc.geeoz"

jxboot-resources:
  cluster:
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging

  jenkins-x-platform:
    chartmuseum:
      enabled: false

  nexus:
    enabled: false
```

4. Log of the installation:
```
alex@Alex-MacBook-Pro razomer-dev % jx boot
Attempting to resolve version for boot config https://github.com/geeoz/environment-razomer-dev from https://github.com/jenkins-x/jenkins-x-versions.git
WARNING: could not find a stable version from git of https://github.com/geeoz/environment-razomer-dev from /Users/alex/.jx/jenkins-x-versions
For background see: https://jenkins-x.io/docs/concepts/version-stream/
Please lock this version down via the command: jx step create pr versions -k git -n https://github.com/geeoz/environment-razomer-dev
WARNING: could not find a stable version for git repository: https://github.com/geeoz/environment-razomer-dev in /Users/alex/.jx/jenkins-x-versions
WARNING: for background see: https://jenkins-x.io/docs/concepts/version-stream/
please lock this version down via the command: jx step create pr versions -k git -n github.com/geeoz/environment-razomer-dev -v 1.2.3
no version for https://github.com/geeoz/environment-razomer-dev found in version stream https://github.com/jenkins-x/jenkins-x-versions.git, defaulting to master
Local boot clone is out of date. It is based on HEAD, but the version stream is using origin/master. The clone will now be updated to origin/master.
Stashing any changes made in local boot clone.
Booting Jenkins X

STEP: validate-git command: /bin/sh -c jx step git validate in dir: /Users/alex/workspace/environment/razomer-dev/env

Git configured for user: Alex Voloshyn and email alex@geeoz.com

STEP: verify-preinstall command: /bin/sh -c jx step verify preinstall --provider-values-dir="kubeProviders" in dir: /Users/alex/workspace/environment/razomer-dev

jx boot has only been validated on GKE and EKS, we'd love feedback and contributions for other Kubernetes providers
? Continue execution anyway? Yes

writing the following to the OWNERS file for the development environment repository:
approvers:
- alexvolsh
- sergevoloshyn
reviewers:
- alexvolsh
- sergevoloshyn
Verifying the kubernetes cluster before we try to boot Jenkins X in namespace: razomer
Trying to lazily create any missing resources to get the current cluster ready to boot Jenkins X
Verifying Ingress...

Using namespace 'razomer' from context named 'alex@geeoz-km01' on server 'https://116.202.16.6:6443'.

Verifying the CLI packages using version stream URL: https://github.com/jenkins-x/jenkins-x-versions.git and git ref: v1.0.311
using version 2.0.1140 of jx
CLI packages kubectl, git, helm seem to be setup correctly
NAME               VERSION
jx                 2.0.1140
jenkins x platform 2.0.1847
Kubernetes cluster v1.15.6
kubectl            v1.17.1
helm client        v2.16.1+gbbdfe5e
git                2.25.0

Verifying Storage...
Storage configuration looks good

Helm installed and configured
Ensuring Helm chart repository https://storage.googleapis.com/chartmuseum.jenkins-x.io is configured
Cluster looks good, you are ready to 'jx boot' now!


STEP: install-jx-crds command: /bin/sh -c jx upgrade crd in dir: /Users/alex/workspace/environment/razomer-dev

Jenkins X CRDs upgraded with success

STEP: install-velero command: /bin/sh -c jx step helm apply --boot --remote --no-vault --name velero in dir: /Users/alex/workspace/environment/razomer-dev/systems/velero

Modified file /Users/alex/workspace/environment/razomer-dev/systems/velero/Chart.yaml to set the chart to version 1
Verifying the helm requirements versions in dir: . using version stream URL: https://github.com/jenkins-x/jenkins-x-versions.git and git ref: v1.0.311

STEP: install-velero-backups command: /bin/sh -c jx step helm apply --boot --remote --no-vault --name velero-backups in dir: /Users/alex/workspace/environment/razomer-dev/systems/velero-backups

Modified file /Users/alex/workspace/environment/razomer-dev/systems/velero-backups/Chart.yaml to set the chart to version 1
Ignoring templates/default-backup.yaml
No requirements file: /var/folders/l9/5z3r4hsn4gl_99q0nj3h_jjr0000gn/T/jx-helm-apply-989339554/velero-backups/requirements.yaml so not checking for missing versions

STEP: create-install-values command: /bin/sh -c jx step create install values -b in dir: /Users/alex/workspace/environment/razomer-dev/env

WARNING: Note that we have only tested TLS support on Google Container Engine with external-dns so far. This may not work!

STEP: install-external-dns command: /bin/sh -c jx step helm apply --boot --remote --no-vault --name exdns in dir: /Users/alex/workspace/environment/razomer-dev/systems/external-dns

Modified file /Users/alex/workspace/environment/razomer-dev/systems/external-dns/Chart.yaml to set the chart to version 1
Verifying the helm requirements versions in dir: . using version stream URL: https://github.com/jenkins-x/jenkins-x-versions.git and git ref: v1.0.311

STEP: install-vault command: /bin/sh -c jx step boot vault --provider-values-dir ../../kubeProviders in dir: /Users/alex/workspace/environment/razomer-dev/systems/vault

Not attempting to boot Vault as using secret storage: local

STEP: create-helm-values command: /bin/sh -c jx step create values --name parameters in dir: /Users/alex/workspace/environment/razomer-dev/env

defaulting to secret storage scheme local found from requirements file at /Users/alex/workspace/environment/razomer-dev/jx-requirements.yml
defaulting to secret base path to the cluster name geeoz found from requirements file at /Users/alex/workspace/environment/razomer-dev/jx-requirements.yml
generated schema file /Users/alex/workspace/environment/razomer-dev/env/parameters.schema.json from template /Users/alex/workspace/environment/razomer-dev/env/parameters.tmpl.schema.json

Jenkins X Admin Username admin [Automatically accepted existing value]
Jenkins X Admin Password *** [Automatically accepted existing value]
Pipeline bot Git username alexvolsh [Automatically accepted existing value]
Pipeline bot Git email address alex@geeoz.com [Automatically accepted existing value]
Pipeline bot Git token *** [Automatically accepted existing value]
HMAC token, used to validate incoming webhooks. Press enter to use the generated token *** [Automatically accepted existing value]
Do you want to configure an external Docker Registry?By default Jenkins X will use the docker registry from the cloud provider. If you want to configure an external docker registry such as Docker Hub or your own existing docker registry enter YDocker Registry Url https://docker.geeoz.com [Automatically accepted existing value]
Docker Registry username admin [Automatically accepted existing value]
Docker Registry password *** [Automatically accepted existing value]
Docker Registry email alex@geeoz.com [Automatically accepted existing value]
WARNING: Unexpected registry auth URL https://docker.geeoz.com - using it as registry push URL


STEP: create-jx-auth-config command: /bin/sh -c jx step create templated --parameters-file=../../env/parameters.yaml --requirements-dir=../../ --template-file=jx-auth-configmap.tmpl.yaml --config-file=templates/jx-auth-configmap.yaml in dir: /Users/alex/workspace/environment/razomer-dev/systems/jx-auth

Saved the rendered configuration into templates/jx-auth-configmap.yaml file

STEP: install-jx-auth-config command: /bin/sh -c jx step helm apply --boot --remote --no-vault --name jx-auth in dir: /Users/alex/workspace/environment/razomer-dev/systems/jx-auth

Modified file /Users/alex/workspace/environment/razomer-dev/systems/jx-auth/Chart.yaml to set the chart to version 1
Ignoring templates/jx-auth-configmap.yaml
No requirements file: /var/folders/l9/5z3r4hsn4gl_99q0nj3h_jjr0000gn/T/jx-helm-apply-857783764/jx-auth/requirements.yaml so not checking for missing versions

STEP: install-jenkins-x command: /bin/sh -c jx step helm apply --boot --remote --name jenkins-x --provider-values-dir ../kubeProviders in dir: /Users/alex/workspace/environment/razomer-dev/env

Modified file /Users/alex/workspace/environment/razomer-dev/env/Chart.yaml to set the chart to version 1
Ignoring templates/.gitignore
Applying the kubernetes overrides at ../kubeProviders/kubernetes/values.tmpl.yaml
Verifying the helm requirements versions in dir: . using version stream URL: https://github.com/jenkins-x/jenkins-x-versions.git and git ref: v1.0.311


STEP: verify-jenkins-x-environment command: /bin/sh -c jx step verify env in dir: /Users/alex/workspace/environment/razomer-dev

Storing the requirements in team settings in the dev environment
Validating git repository for dev environment at URL https://github.com/geeoz/environment-razomer-dev.git
Pushed Git repository to https://github.com/geeoz/environment-razomer-dev

Validating git repository for production environment at URL https://github.com/geeoz/environment-razomer-production.git
Using Git provider github at https://github.com
? Using Git user name: alexvolsh
? Using organisation: geeoz
Creating repository geeoz/environment-razomer-production
Creating Git repository geeoz/environment-razomer-production
Pushed Git repository to https://github.com/geeoz/environment-razomer-production

Validating git repository for staging environment at URL https://github.com/geeoz/environment-razomer-staging.git
Using Git provider github at https://github.com
? Using Git user name: alexvolsh
? Using organisation: geeoz
Creating repository geeoz/environment-razomer-staging
Creating Git repository geeoz/environment-razomer-staging
Pushed Git repository to https://github.com/geeoz/environment-razomer-staging

Environment git repositories look good


STEP: install-repositories command: /bin/sh -c jx step helm apply --boot --name repos in dir: /Users/alex/workspace/environment/razomer-dev/repositories

Modified file /Users/alex/workspace/environment/razomer-dev/repositories/Chart.yaml to set the chart to version 1
Ignoring templates/default-group.yaml
No requirements file: /var/folders/l9/5z3r4hsn4gl_99q0nj3h_jjr0000gn/T/jx-helm-apply-299437991/repositories/requirements.yaml so not checking for missing versions


STEP: install-pipelines command: /bin/sh -c jx step scheduler config apply --direct=true in dir: /Users/alex/workspace/environment/razomer-dev/prowConfig


STEP: update-webhooks command: /bin/sh -c jx update webhooks --verbose --warn-on-fail in dir: /Users/alex/workspace/environment/razomer-dev/repositories

Updating webhooks for Owner: geeoz and Repository: environment-razomer-dev in git server: https://github.com
Checking hooks for repository geeoz/environment-razomer-dev with user alexvolsh
Found matching hook for url https://hook.razomer.com/hook
Updating GitHub webhook for geeoz/environment-razomer-dev for url https://hook.razomer.com/hook
Updating webhooks for Owner: geeoz and Repository: environment-razomer-production in git server: https://github.com
Checking hooks for repository geeoz/environment-razomer-production with user alexvolsh
Creating GitHub webhook for geeoz/environment-razomer-production for url https://hook.razomer.com/hook
Updating webhooks for Owner: geeoz and Repository: environment-razomer-staging in git server: https://github.com
Checking hooks for repository geeoz/environment-razomer-staging with user alexvolsh
Creating GitHub webhook for geeoz/environment-razomer-staging for url https://hook.razomer.com/hook

STEP: verify-installation command: /bin/sh -c jx step verify install --pod-wait-time 30m in dir: /Users/alex/workspace/environment/razomer-dev/env

verifying the Jenkins X installation in namespace razomer
verifying pods
Checking pod statuses
POD                                          STATUS
crier-76bb69cdcc-dqr4l                       Pending
deck-6d894bd6c-4h6sh                         Pending
deck-6d894bd6c-cnfdj                         Pending
hook-68777d88c7-b4cdc                        Pending
hook-68777d88c7-fsfjl                        Pending
horologium-7ffb6d7cfd-pwj5c                  Pending
jenkins-x-controllerrole-5bf85fcd88-87wdc    Running
jenkins-x-heapster-59ddd47fc9-756z4          Running
pipeline-599c968cc5-2w88s                    Pending
pipelinerunner-6d4655df47-mftrd              Running
tekton-pipelines-controller-569d5f977d-kpnkf Running
tide-5f6df69548-7hwsr                        Pending
WARNING: the following pods are not ready:
Pending: crier-76bb69cdcc-dqr4l, deck-6d894bd6c-4h6sh, deck-6d894bd6c-cnfdj, hook-68777d88c7-b4cdc, hook-68777d88c7-fsfjl, horologium-7ffb6d7cfd-pwj5c, pipeline-599c968cc5-2w88s, tide-5f6df69548-7hwsr

Waiting 30m0s for the pods to become ready...

WARNING: retrying after error: the following pods are not ready:
Pending: crier-76bb69cdcc-dqr4l, deck-6d894bd6c-4h6sh, deck-6d894bd6c-cnfdj, hook-68777d88c7-b4cdc, hook-68777d88c7-fsfjl, horologium-7ffb6d7cfd-pwj5c, pipeline-599c968cc5-2w88s, tide-5f6df69548-7hwsr
WARNING: retrying after error: the following pods are not ready:
Running: deck-6d894bd6c-4h6sh, deck-6d894bd6c-cnfdj, hook-68777d88c7-fsfjl, tide-5f6df69548-7hwsr
WARNING: retrying after error: the following pods are not ready:
Running: deck-6d894bd6c-4h6sh, deck-6d894bd6c-cnfdj
.

WARNING: retrying after error: the following pods are not ready:
Running: deck-6d894bd6c-cnfdj
POD                                          STATUS
crier-76bb69cdcc-dqr4l                       Running
deck-6d894bd6c-4h6sh                         Running
deck-6d894bd6c-cnfdj                         Running
hook-68777d88c7-b4cdc                        Running
hook-68777d88c7-fsfjl                        Running
horologium-7ffb6d7cfd-pwj5c                  Running
jenkins-x-controllerrole-5bf85fcd88-87wdc    Running
jenkins-x-heapster-59ddd47fc9-756z4          Running
pipeline-599c968cc5-2w88s                    Running
pipelinerunner-6d4655df47-mftrd              Running
tekton-pipelines-controller-569d5f977d-kpnkf Running
tide-5f6df69548-7hwsr                        Running
Verifying the git config
Verifying username alexvolsh at git server github at https://github.com
Found 1 organisations in git server https://github.com: geeoz
Validated pipeline user alexvolsh on git server https://github.com
Git tokens seem to be setup correctly
Installation is currently looking: GOOD
Using namespace 'razomer' from context named 'alex@geeoz-km01' on server.
```

Do you need some additional information?
