### ISSUE TITLE
Feature Request: Splitting up the build-pack lifecycles in stages

### ISSUE THREAD

**Issue by tomfrenken** [jenkins-x/jx#6564]
### Summary 
Today I wanted to extend the default maven build-pack and noticed that I can only add steps, but not stages to the build-pack, which becomes an issue as soon as I want to utilize parallelization.

In my case I wanted to use different testing tools before and after the build stage, which would be running in parallel, but couldn't do so with the current extension model of the default build-pack.

I propose adding the possibility to add stages in-between the lifecycles (especially `parallel`), to the extensibility model of build-packs.

The best way to do so I have in mind is splitting up the build-pack lifecycles in separated stages.

Here is an example for the maven build-pack:

```yaml
buildPack: none
pipelineConfig:
  agent:
    image: maven
    label: jenkins-maven
  env:
  - name: _JAVA_OPTIONS
    value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true
      -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4
      -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx1024m
  pipelines:
    post: {}
    pullRequest:
      pipeline:
        options:
          containerOptions:
            env:
            - name: DOCKER_CONFIG
              value: /home/jenkins/.docker/
            - name: DOCKER_REGISTRY
              valueFrom:
                configMapKeyRef:
                  key: docker.registry
                  name: jenkins-x-docker-registry
            - name: GIT_AUTHOR_EMAIL
              value: jenkins-x@googlegroups.com
            - name: GIT_AUTHOR_NAME
              value: jenkins-x-bot
            - name: GIT_COMMITTER_EMAIL
              value: jenkins-x@googlegroups.com
            - name: GIT_COMMITTER_NAME
              value: jenkins-x-bot
            - name: JENKINS_URL
              value: http://jenkins:8080
            - name: MAVEN_OPTS
              value: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
            - name: XDG_CONFIG_HOME
              value: /home/jenkins
            name: ""
            resources:
              limits:
                cpu: "1"
                memory: 1Gi
              requests:
                cpu: 400m
                memory: 512Mi
            securityContext:
              privileged: true
            volumeMounts:
            - mountPath: /home/jenkins
              name: workspace-volume
            - mountPath: /var/run/docker.sock
              name: docker-daemon
            - mountPath: /root/.m2/
              name: volume-0
            - mountPath: /home/jenkins/.docker
              name: volume-1
            - mountPath: /home/jenkins/.gnupg
              name: volume-2
          volumes:
          - emptyDir: {}
            name: workspace-volume
          - hostPath:
              path: /var/run/docker.sock
            name: docker-daemon
          - name: volume-0
            secret:
              secretName: jenkins-maven-settings
          - name: volume-1
            secret:
              secretName: jenkins-docker-cfg
          - name: volume-2
            secret:
              secretName: jenkins-release-gpg
        agent:
          image: maven
        stages:
        - name: from-build-pack-build
          steps:
            - command: mvn versions:set -DnewVersion=$PREVIEW_VERSION
              dir: /workspace/source
              name: build-set-version
            - command: mvn install
              dir: /workspace/source
              name: build-mvn-install
            - command: skaffold version
              dir: /workspace/source
              name: build-skaffold-version
            - command: /kaniko/executor --cache=true --cache-dir=/workspace --context=/workspace/source
                --dockerfile=/workspace/source/Dockerfile --destination=gcr.io/sap-cpe-cloudpot-dev/cloud-s4-sdk-book:${inputs.params.version}
                --cache-repo=gcr.io/sap-cpe-cloudpot-dev/cache
              dir: /workspace/source
              image: gcr.io/kaniko-project/executor:9912ccbf8d22bbafbf971124600fbb0b13b9cbd6
              name: build-container-build
        - name: from-build-pack-post-build
          steps:
            - command: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:$PREVIEW_VERSION
              dir: /workspace/source
              name: postbuild-post-build
        - name: from-build-pack-promote
          steps:
            - command: make preview
              dir: /workspace/source/charts/preview
              name: promote-make-preview
            - command: jx preview --app $APP_NAME --dir ../..
              dir: /workspace/source/charts/preview
              name: promote-jx-preview
    release:
      pipeline:
        options:
          containerOptions:
            env:
            - name: DOCKER_CONFIG
              value: /home/jenkins/.docker/
            - name: DOCKER_REGISTRY
              valueFrom:
                configMapKeyRef:
                  key: docker.registry
                  name: jenkins-x-docker-registry
            - name: GIT_AUTHOR_EMAIL
              value: jenkins-x@googlegroups.com
            - name: GIT_AUTHOR_NAME
              value: jenkins-x-bot
            - name: GIT_COMMITTER_EMAIL
              value: jenkins-x@googlegroups.com
            - name: GIT_COMMITTER_NAME
              value: jenkins-x-bot
            - name: JENKINS_URL
              value: http://jenkins:8080
            - name: MAVEN_OPTS
              value: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
            - name: XDG_CONFIG_HOME
              value: /home/jenkins
            name: ""
            resources:
              limits:
                cpu: "1"
                memory: 1Gi
              requests:
                cpu: 400m
                memory: 512Mi
            securityContext:
              privileged: true
            volumeMounts:
            - mountPath: /home/jenkins
              name: workspace-volume
            - mountPath: /var/run/docker.sock
              name: docker-daemon
            - mountPath: /root/.m2/
              name: volume-0
            - mountPath: /home/jenkins/.docker
              name: volume-1
            - mountPath: /home/jenkins/.gnupg
              name: volume-2
          volumes:
          - emptyDir: {}
            name: workspace-volume
          - hostPath:
              path: /var/run/docker.sock
            name: docker-daemon
          - name: volume-0
            secret:
              secretName: jenkins-maven-settings
          - name: volume-1
            secret:
              secretName: jenkins-docker-cfg
          - name: volume-2
            secret:
              secretName: jenkins-release-gpg
        agent:
          image: maven
        stages:
        - name: from-build-pack-setup
          steps:
            - command: jx step git credentials
              dir: /workspace/source
              name: setup-jx-git-credentials
        - name: from-build-pack-build
          steps:
            - command: mvn clean deploy
              dir: /workspace/source
              name: build-mvn-deploy
            - command: skaffold version
              dir: /workspace/source
              name: build-skaffold-version
            - command: /kaniko/executor --cache=true --cache-dir=/workspace --context=/workspace/source
                --dockerfile=/workspace/source/Dockerfile --destination=gcr.io/sap-cpe-cloudpot-dev/cloud-s4-sdk-book:${inputs.params.version}
                --cache-repo=gcr.io/sap-cpe-cloudpot-dev/cache
              dir: /workspace/source
              image: gcr.io/kaniko-project/executor:9912ccbf8d22bbafbf971124600fbb0b13b9cbd6
              name: build-container-build
            - command: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:${VERSION}
              dir: /workspace/source
              name: build-post-build
        - name: from-build-pack-promote
          steps:
            - command: jx step changelog --version v${VERSION}
              dir: /workspace/source/charts/cloud-s4-sdk-book
              name: promote-changelog
            - command: jx step helm release
              dir: /workspace/source/charts/cloud-s4-sdk-book
              name: promote-helm-release
            - command: jx promote -b --all-auto --timeout 1h --version ${VERSION}
              dir: /workspace/source/charts/cloud-s4-sdk-book
              name: promote-jx-promote
      setVersion:
        steps:
        - image: maven
          steps:
          - comment: so we can retrieve the version in later steps
            name: next-version
            command: echo \$(jx-release-version) > VERSION
          - name: set-version
            command: mvn versions:set -DnewVersion=\$(cat VERSION)
          - name: tag-version
            command: jx step tag --version \$(cat VERSION)
```
