### ISSUE TITLE
jx boot cherry-pick errors with latest boot-config and CLI

### ISSUE THREAD

**Issue by tomfrenken** [jenkins-x/jx#6580]
### Summary 
When running `jx boot` or `jx boot -r <requirementsfile>`
with the latest CLI and boot-config, you always receive cherry-pick erros,
they look like this:
```
Setting upstream to https://github.com/tomfrenken/environment-jx-eval-01-dev

Attempting to cherry pick commits that were on master but not yet pushed
error: handle dev environment repository: error updating dev environment for environment-jx-eval-01-dev: forking and pulling https://github.com/tomfrenken/environment-jx-eval-01-dev.git: Unable to cherry-pick 441da5a38736289e9a280593f55a1c47f8ea6798: git output: The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git cherry-pick --skip'
On branch master
Your branch and 'origin/master' have diverged,
and have 1 and 368 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

You are currently cherry-picking commit 441da5a.

Untracked files:
	env/parameters.yaml

nothing added to commit but untracked files present: failed to run 'git cherry-pick 441da5a38736289e9a280593f55a1c47f8ea6798' command in directory '/Users/i519840/Code/jx_related_repos/boot-configs/jenkins-x-boot-config', output: 'The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git cherry-pick --skip'
On branch master
Your branch and 'origin/master' have diverged,
and have 1 and 368 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

You are currently cherry-picking commit 441da5a.

Untracked files:
	env/parameters.yaml

nothing added to commit but untracked files present'
error: failed to interpret pipeline file /Users/i519840/Code/jx_related_repos/boot-configs/jenkins-x-boot-config/jenkins-x.yml: failed to run '/bin/sh -c jx step verify env' command in directory '/Users/i519840/Code/jx_related_repos/boot-configs/jenkins-x-boot-config', output: ''
```
This doesn't happen if I manually clone the repository before, so whatever logic you add when there isn't a clone in place is most likely causing this behaviour.

And yes, I did delete the dev/staging/production repositories before I ran jx boot.

### Steps to reproduce the behavior
Run `jx boot` without any boot-config

### Jx version

The output of `jx version` is:

```
jx                 2.0.1142
Kubernetes cluster v1.13.11-gke.14
kubectl            v1.17.1
helm client        Client: v2.16.1+gbbdfe5e
git                2.25.0
Operating System   Mac OS X 10.15.2 build 19C57
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Operating system / Environment
Mac OS X 10.15.2 build 19C57

**Comment by tomfrenken** [comment]
Most likely related to #6498

**Comment by hferentschik** [comment]
Wonder whether this would help - https://github.com/jenkins-x/jx/pull/6572

Note, this PR does still do the cherry-picking which is conceptually the wrong thing to do in this situation, but it does address some other issues and I think in many cases it should work now. 

Moving forward we have to move away from cherry-picking.

**Comment by hferentschik** [comment]
That said, what do you have specified in your `jx-requirements.yml` for the version stream? Are you using master? Or do you have a fixed version set? You should set a fixed version.

**Comment by tomfrenken** [comment]
Well if I run `jx boot` without anything it's just the default values I suppose,
when I run `jx boot -r <file>` the file looks like this:

```yaml
cluster:
  clusterName: ""
  environmentGitOwner: ""
  environmentGitPublic: false
  project: ""
  provider: gke
  zone: ""
gitops: true
environments:
- key: dev
- key: staging
- key: production
ingress:
  domain: ""
  externalDNS: false
  tls:
    email: ""
    enabled: false
    production: false
kaniko: true
secretStorage: local
storage:
  logs:
    enabled: true
    url: ""
  reports:
    enabled: true
    url: ""
  repository:
    enabled: true
    url: ""
  backup:
    enabled: true
    url: ""
versionStream:
  ref: "master"
  url: https://github.com/jenkins-x/jenkins-x-versions.git
webhook: prow
```
