### ISSUE TITLE
Dev pipeline fails on fresh jx boot install using bitbucketserver

### ISSUE THREAD

**Issue by RoVernekar** [jenkins-x/jx#6617]
### Summary 

The pipeline for the dev environment fails on a fresh `jx boot` install using `bitbucketserver` because the `sourcerepository` url is not properly set. The staging and production environments appear to work fine.

### Steps to reproduce the behavior

1. Run `jx boot` with a similar `jx-requirements.yml`:

    ```yaml
    cluster:
      clusterName: foo
      environmentGitOwner: jx
      environmentGitPublic: false
      gitKind: bitbucketserver
      gitName: bs
      gitServer: https://bitbucket.foo.com
      provider: kubernetes
    gitops: true
    environments:
    - key: dev
    - key: staging
    - key: production
    ingress:
      domain: foo.com
      externalDNS: true
      tls:
        email: ""
        enabled: false
        production: false
    kaniko: true
    secretStorage: local
    storage:
      logs:
        enabled: false
        url: ""
      reports:
        enabled: false
        url: ""
      repository:
        enabled: false
        url: ""
    versionStream:
      ref: "master"
      url: https://github.com/jenkins-x/jenkins-x-versions.git
    webhook: lighthouse
    ```

1. Observe that the url is missing for the dev environment sourcerepository

    ```bash
    >> kubectl get sr -o custom-columns=NAME:.metadata.name,URL:.spec.url,HTTP_CLONE_URL:.spec.httpCloneURL
    NAME                            URL                                                               HTTP_CLONE_URL
    jx-environment-foo-dev          <none>                                                            <none>
    jx-environment-foo-production   https://bitbucket.foo.com/scm/jx/environment-foo-production.git   https://bitbucket.foo.com/scm/jx/environment-foo-production.git
    jx-environment-foo-staging      https://bitbucket.foo.com/scm/jx/environment-foo-staging.git      https://bitbucket.foo.com/scm/jx/environment-foo-staging.git
    ```

1. Start dev pipeline
    ```bash
    jx start pipeline jx/environment-foo-dev/master
    ```

### Expected behavior

The dev pipeline should complete successfully.

### Actual behavior

The dev pipeline fails with the following logs:
```
Showing logs for build jx/environment-foo-dev/master #1 stage meta-pipeline and container step-git-source-meta-jx-environment-foo-msh8p
{"level":"warn","ts":1580138244.0669072,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-jx-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"error","ts":1580138244.153411,"logger":"fallback-logger","caller":"git/git.go:40","msg":"Error running git [fetch --depth=1 --recurse-submodules=yes origin master]: exit status 128\nfatal: repository 'https://bitbucket.foo.com/jx/environment-foo-dev.git/' not found\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\t/Users/abayer/go/src/github.com/tektoncd/pipeline/pkg/git/git.go:40\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\t/Users/abayer/go/src/github.com/tektoncd/pipeline/pkg/git/git.go:91\nmain.main\n\t/Users/abayer/go/src/github.com/tektoncd/pipeline/cmd/git-init/main.go:39\nruntime.main\n\t/usr/local/Cellar/go/1.12.4/libexec/src/runtime/proc.go:200"}
{"level":"error","ts":1580138244.227308,"logger":"fallback-logger","caller":"git/git.go:40","msg":"Error running git [pull --recurse-submodules=yes origin]: exit status 1\nfatal: repository 'https://bitbucket.foo.com/jx/environment-foo-dev.git/' not found\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\t/Users/abayer/go/src/github.com/tektoncd/pipeline/pkg/git/git.go:40\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\t/Users/abayer/go/src/github.com/tektoncd/pipeline/pkg/git/git.go:94\nmain.main\n\t/Users/abayer/go/src/github.com/tektoncd/pipeline/cmd/git-init/main.go:39\nruntime.main\n\t/usr/local/Cellar/go/1.12.4/libexec/src/runtime/proc.go:200"}
{"level":"warn","ts":1580138244.227361,"logger":"fallback-logger","caller":"git/git.go:95","msg":"Failed to pull origin : exit status 1"}
{"level":"error","ts":1580138244.229768,"logger":"fallback-logger","caller":"git/git.go:40","msg":"Error running git [checkout master]: exit status 1\nerror: pathspec 'master' did not match any file(s) known to git\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\t/Users/abayer/go/src/github.com/tektoncd/pipeline/pkg/git/git.go:40\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\t/Users/abayer/go/src/github.com/tektoncd/pipeline/pkg/git/git.go:97\nmain.main\n\t/Users/abayer/go/src/github.com/tektoncd/pipeline/cmd/git-init/main.go:39\nruntime.main\n\t/usr/local/Cellar/go/1.12.4/libexec/src/runtime/proc.go:200"}
{"level":"fatal","ts":1580138244.229831,"logger":"fallback-logger","caller":"git-init/main.go:40","msg":"Error fetching git repository: exit status 1","stacktrace":"main.main\n\t/Users/abayer/go/src/github.com/tektoncd/pipeline/cmd/git-init/main.go:40\nruntime.main\n\t/usr/local/Cellar/go/1.12.4/libexec/src/runtime/proc.go:200"}

Pipeline failed on stage 'meta-pipeline' : container 'step-git-source-meta-jx-environment-foo-msh8p'. The execution of the pipeline has stopped.
```

The git url in the error message appears to be missing `/scm/`.
Expected: `https://bitbucket.foo.com/scm/jx/environment-foo-dev.git/`
Actual: `https://bitbucket.foo.com/jx/environment-foo-dev.git/`

Manually editing the `sourcerepository` for the dev environment and adding the `spec.url` and `.spec.httpCloneURL` fields seems to fix the error and allows the dev pipeline to complete successfully.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1152
Kubernetes cluster v1.14.9
kubectl            v1.14.8
helm client        Client: v2.16.1+gbbdfe5e
git                2.21.0 (Apple Git-122.2)
Operating System   Mac OS X 10.15.2 build 19C57
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

On prem cluster created via Rancher.
