### ISSUE TITLE
bug: overriding `env` variables in buildpacks doesn't work

### ISSUE THREAD

**Issue by tomfrenken** [jenkins-x/jx#6668]
### Summary 
When you extend a buildpack and want to add/override `env` variables,
it doesn't work when used to build a new buildpack, as seen here:

```yaml
extends:
  file: ../maven/pipeline.yaml
pipelineConfig:
  env:
    - name: _JAVA_OPTIONS
      value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx1024m
```

however, when used the exact same way, it is working when extending a buildpack to write a new pipeline inside of a project, like this:

```yaml
buildPack: <buildpack>
buildPackGitURL: <url>
pipelineConfig:
  env:
  - name: _JAVA_OPTIONS
    value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true
      -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4
      -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx1024m
```

I suppose this is not by design and am looking forward to the fix.

### Jx version

The output of `jx version` is:

```
jx                 2.0.1173
Kubernetes cluster v1.13.11-gke.23
kubectl            v1.17.2
helm client        Client: v2.16.1+gbbdfe5e
git                2.25.0
Operating System   Mac OS X 10.15.3 build 19D76
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins
