### ISSUE TITLE
`jx add app jx-app-jenkins` w/ Bitbucket uses user as dev env owner, not organization

### ISSUE THREAD

**Issue by huytn12-test** [jenkins-x/jx#6688]
### Summary 
I've successfully installed Jenkins X with Bitbucket Cloud on GKE. However, when I tried to install Jenkins X UI using either one of these commands: `jx add app jx-app-ui` or `jx add app jx-app-jenkins`, I received a `404 Not Found` error from jx. I think Jx refers to incorrect username when making calls to Bitbucket servers. This issue will affect the `jx add app` functionality for those who use Bitbucket cloud because Jx can not update the git repo.

Instead of `shipwire`/environment-security-alpha-cluster-dev where shipwire is the organization git name, jx refers to `shipops`/environment-security-alpha-cluster-dev which is the username of git username.

Error:

> error: adding app jx-app-jenkins version  with alias  using gitops: creating pr for jx-app-jenkins: creating pull request with arguments Title: Add jx-app-jenkins 0.0.15; Body: Add app jx-app-jenkins 0.0.15; Head: add-app-jx-app-jenkins-0.0.15; Base: master; Labels: ; Git Repo: : Status: 404 Not Found, Body: {"type": "error", "error": {"message": "Repository shipops/environment-security-alpha-cluster-dev not found"}}

### Steps to reproduce the behavior
jx-requirements.yml
```
autoUpdate:
  enabled: false
  schedule: ""
bootConfigURL: https://github.com/jenkins-x/jenkins-x-boot-config.git
cluster:
  clusterName: security-alpha-cluster
  devEnvApprovers:
  - jsonhn
  environmentGitOwner: shipwire
  gitKind: bitbucketcloud
  gitName: bs
  gitServer: https://bitbucket.org
  namespace: jx
  project: shipwire-eng-core-dev
  provider: gke
  registry: gcr.io
  zone: us-central1-a
environments:
- ingress:
    domain: 35.226.96.160.nip.io
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  key: dev
  repository: environment-security-alpha-cluster-dev
- ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: ""
    tls:
      email: ""
      enabled: false
      production: false
  key: staging
  repository: environment-security-alpha-cluster-staging
- ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: ""
    tls:
      email: ""
      enabled: false
      production: false
  key: production
  repository: environment-security-alpha-cluster-production
gitops: true
ingress:
  domain: 35.226.96.160.nip.io
  externalDNS: false
  namespaceSubDomain: -jx.
  tls:
    email: ""
    enabled: false
    production: false
kaniko: true
repository: nexus
secretStorage: local
storage:
  backup:
    enabled: false
    url: ""
  logs:
    enabled: false
    url: ""
  reports:
    enabled: false
    url: ""
  repository:
    enabled: false
    url: ""
vault: {}
velero:
  schedule: ""
  ttl: ""
versionStream:
  ref: v1.0.335
  url: https://github.com/jenkins-x/jenkins-x-versions.git
webhook: lighthouse
```

### Expected behavior
Successfully install Jenkins X UI

### Actual behavior
Received 404 Not Found

### Jx version

The output of `jx version` is:

```
jx                 2.0.1177
Kubernetes cluster v1.13.11-gke.14
kubectl            v1.16.2
helm client        Client: v2.16.1+gbbdfe5e
git                2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.6 build 18G95
```

### Jenkins type

- [x ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GKE using Web console

### Operating system / Environment

MacOS
