### ISSUE TITLE
Gitlab import fails: unable to create pull request / Invalid path

### ISSUE THREAD

**Issue by wuestkamp** [jenkins-x/jx#6719]
Trying to do:

```
jx import --url URL
```

Getting this error:

```
error: failed to create Pull Request on the development environment git repository https://gitlab.com/XXX/environment-mouseprairie-dev.git: unable to create pull request: creating git provider for https://gitlab.com: Invalid path  could not determine organisation and repository name
```

jx envs:
```
NAME       LABEL       KIND        PROMOTE NAMESPACE     ORDER CLUSTER SOURCE                                                               REF    PR
dev        Development Development Never   jx            0             https://gitlab.com/XXX/environment-mouseprairie-dev.git        master 
staging    Staging     Permanent   Auto    jx-staging    100           https://gitlab.com/XXX/environment-mouseprairie-staging.git    master 
production Production  Permanent   Manual  jx-production 200           https://gitlab.com/XXX/environment-mouseprairie-production.git master 
```

### Jx version
```
jx                 2.0.1187
Kubernetes cluster v1.13.11-gke.23
kubectl            v1.16.1
helm client        Client: v2.16.1+gbbdfe5e
git                2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.4 build 18E226
```

**Comment by oonyeje-bside** [comment]
I also get this error when running jx import using bitbucketcloud 

`jx import`

## JX Version
`jx                 2.0.1187
Kubernetes cluster v1.15.9
kubectl            v1.16.3
helm client        Client: v2.12.3+geecf22f
git                2.25.0
Operating System   Ubuntu 16.04.6 LTS`

Instead of trying to create the pr at https://bitbucket.org/organization/environment-cluster-dev.git, it attempts to create it at https://bitbucket.org/jx-git-pipeline-user/environment-cluster-dev.git

**Comment by AndreasKnapp1812** [comment]
Same here with github:

```
error: failed to create Pull Request on the development environment git repository https://github.com/org/environment-mycluster-dev.git: unable to create pull request: creating git provider for https://github.com: Invalid path  could not determine organisation and repository name
```

I tried with several jx versions from `2.0.1173` up to `2.0.1194`.

**Comment by AndreasKnapp1812** [comment]
Seems like there is a bug wheen cloning the repo with ssh: https://kubernetes.slack.com/archives/C9MBGQJRH/p1581718972084700

**Comment by AndreasKnapp1812** [comment]
Hm, I am facing this issue again, although having the repo cloned with https.

**Comment by jalonsoa** [comment]
Hi !
can you review your ~/.jx/gitAuth.yaml file ? Yo must have a kind entry for all servers that you have in this yaml file. For example:

```
servers:
- currentuser: gitlab-group
  kind: gitlab
  name: mygitlab.com
  url: https://mygitlab.com
  users:
  - apitoken: myusertoken
    bearertoken: ""
    username: myuser
```

If you don't have the kind entry (and the default instalattion don't create it) the jx command thinks that your git server is a github and use this git provider in many requests

**Comment by AndreasKnapp1812** [comment]
Hi @jalonsoa, I am using github and still get this error on `jx import --no-draft` command:

```
error: failed to create Pull Request on the development environment git repository https://github.com/myorg/environment-mycluster-dev.git: unable to create pull request: creating git provider for https://github.com: Invalid path  could not determine organisation and repository name
```

I do have a `kind` entry in my gitAuth.yaml:

```yaml
currentserver: https://github.com
defaultusername: AndreasKnapp1812
pipelineserver: https://github.com
pipelineusername: AndreasKnapp1812
servers:
- currentuser: AndreasKnapp1812
  kind: github
  name: github.com
  url: https://github.com
  users:
  - apitoken: ********************
    bearertoken: ""
    username: AndreasKnapp1812
```

I've learned that it works having the repo cloned with http instead of ssh. Is there any missing configuration such that I get this working with ssh as well?
