### ISSUE TITLE
cannot override a step's image without copy/pasting the command string

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#6739]
I was trying to override the image of a named step in a build pack using the following `jenkins-x.yml` file - something that sounds pretty useful to me.

```yaml
buildPack: jenkinsfilerunner
buildPackGitURL: https://github.com/jstrachan/jenkins-x-kubernetes.git
pipelineConfig:
  pipelines:
    overrides:
      - name: run
        type: replace
        step:
          name: run
          image: jenkins4eval/jenkinsfile-runner:1.0-beta-11
```
the above fails with

```
error: failed to create effective pipeline for pull request: validation failed for Pipeline: expected exactly one, got neither: stages[0].parallel, stages[0].stages, stages[0].steps
```

However if I copy/paste the `command:` from the build pack in there t works:

```yaml
buildPack: jenkinsfilerunner
buildPackGitURL: https://github.com/jstrachan/jenkins-x-kubernetes.git
pipelineConfig:
  pipelines:
    overrides:
      - name: run
        type: replace
        step:
          name: run
          command: /app/bin/jenkinsfile-runner-launcher -w /app/jenkins -p /usr/share/jenkins/ref/plugins -f /workspace/source --runWorkspace /workspace/build
          image: jenkins4eval/jenkinsfile-runner:1.0-beta-11
```

I'm guessing its overzealous validation of the override steps? It might be nice to only specify some values in the override steps. e.g. just override the command and not any of the other values (image/agent etc?) and effectively override field-by-field for non-empty stuff?
