### ISSUE TITLE
AKZ AZBLOB Issues in jx-requirements.yml EnsureBucketIsCreated not implemented for LegacyBucketProvider

### ISSUE THREAD

**Issue by michaeljohnbennett** [jenkins-x/jx#6837]
@chrismellard BTW we're in the process of moving to [jx boot](https://jenkins-x.io/getting-started/boot/) as our strategic way to install/configure/upgrade/edit Jenkins X installation, storage, networking, ingress/TLS/DNS and whatnot so if you're interested in getting storage/vault working for AKS I'd maybe start there.

with boot you can specify the URLs of the storage locations for logs in your `jx-requirements.yml`. I've just polished the docs around that here: https://jenkins-x.io/getting-started/boot/#storage

I think if you specify the `azblob://mybucket` URLs for logs in your `jx-requirements.yml` file it might actually work on AKS :) 

But it would be nice to add an AKS implementation of this interface: https://github.com/jenkins-x/jx/blob/36cec2384739d1e9f0116d51306841d838a7c3c8/pkg/cloud/factory/factory.go#L14 so that we can lazily create AKS buckets and verify they exist etc Usually if the user enables long term storage on GKE we let folks enter a bucket name to create and if not lazily create one etc. Would be nice to have a similar UX on AKS toto.

_Originally posted by @jstrachan in https://github.com/jenkins-x/jx/issues/703#issuecomment-513696307_

I can't see this working in 2.0.1212.

When we get to verify we get this error:
```
Verifying Storage...
error: failed to ensure the bucket URL azblob://xxx.blob.core.windows.net/logs is created: EnsureBucketIsCreated not implemented for LegacyBucketProvider
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step verify preinstall --provider-values-dir="kubeProviders"' command in directory '.', output: ''
```

```
Verifying the CLI packages using version stream URL: https://github.com/jenkins-x/jenkins-x-versions.git and git ref: v1.0.362
using version 2.0.1212 of jx
CLI packages kubectl, git, helm seem to be setup correctly
NAME               VERSION
jx                 2.0.1212
Kubernetes cluster v1.15.7
kubectl            v1.16.3
helm client        v2.16.3+g1ee0254
git                2.21.0 (Apple Git-120)
```

This happens when running `jx boot`

**Comment by michaeljohnbennett** [comment]
We have disable devops in the requirements and the storage part looks like this: 

```
storage:
  backup:
    enabled: true
    url: azblob://xxx.blob.core.windows.net/backup/
  logs:
    enabled: true
    url: azblob://xxx.blob.core.windows.net/logs/
  reports:
    enabled: true
    url: azblob://xxx.blob.core.windows.net/reports/
  repository:
    enabled: true
    url: azblob://xxx.blob.core.windows.net/repistory/
vault: {}
````
