### ISSUE TITLE
PipelineActivity reports wrong status for a tekton taskrun

### ISSUE THREAD

**Issue by vbehar** [jenkins-x/jx#6838]
### Summary 

In the JX UI I can see all my builds as successful, and then when I come back a few hours later, some of them are marked as "failed". On the last 12 builds, it happened to 5 of them.
I tracked it down to the matching PipelineActivity having a wrong status for a tekton taskrun.

### Steps to reproduce the behavior

run a few successful build, ensure they are marked as successful (either on the pipelineactivities or in the UI), and come back a few hours later

### Expected behavior

the previous builds that were successful should still be marked as successful

### Actual behavior

some builds that were successful are now marked as failed.

In the pipelineactivity I have:

```
metadata:
  labels:
    owner: dailymotion
    repository: leo-jx-env
    branch: master
    context: promotion
    build: "30"
spec:
  pipeline: dailymotion/leo-jx-env/master
  startedTimestamp: "2020-02-27T10:47:34Z"
  status: Failed
  steps:
  - kind: Stage
    stage:
      completedTimestamp: "2020-02-27T10:48:13Z"
      name: meta pipeline
      startedTimestamp: "2020-02-27T10:47:34Z"
      status: Succeeded
  - kind: Stage
    stage:
      completedTimestamp: "2020-02-27T10:52:25Z"
      name: release
      startedTimestamp: "2020-02-27T10:48:28Z"
      status: Succeeded
  - kind: Stage
    stage:
      completedTimestamp: "2020-02-27T10:53:17Z"
      name: leo addons installation
      startedTimestamp: "2020-02-27T10:52:44Z"
      status: NotExecuted
      steps:
      - completedTimestamp: "2020-02-27T10:52:44Z"
        name: Credential Initializer 7tdwx
        startedTimestamp: "2020-02-27T10:52:44Z"
        status: Succeeded
      - completedTimestamp: "2020-02-27T10:52:45Z"
        name: Working Dir Initializer 8hpgj
        startedTimestamp: "2020-02-27T10:52:44Z"
        status: Succeeded
      - completedTimestamp: "2020-02-27T10:52:46Z"
        name: Place Tools
        startedTimestamp: "2020-02-27T10:52:45Z"
        status: Succeeded
      - completedTimestamp: "2020-02-27T10:52:50Z"
        name: Create Dir Workspace 46fgl
        startedTimestamp: "2020-02-27T10:52:46Z"
        status: Succeeded
      - completedTimestamp: "2020-02-27T10:52:51Z"
        name: Source Copy Workspace Pfswl
        startedTimestamp: "2020-02-27T10:52:50Z"
        status: Succeeded
      - completedTimestamp: "2020-02-27T10:53:17Z"
        name: Helmfile Apply
        startedTimestamp: "2020-02-27T10:52:51Z"
        status: Succeeded
```

You can see that the last stage ("leo addons installation) is `NotExecuted` while all its steps are successful.

the corresponding pipelinerun:

```
metadata:
  labels:
    owner: dailymotion
    repository: leo-jx-env
    branch: master
    context: promotion
    build: "30"
status:
  completionTime: "2020-02-27T10:53:18Z"
  conditions:
  - lastTransitionTime: "2020-02-27T10:53:18Z"
    message: All Tasks have completed executing
    reason: Succeeded
    status: "True"
    type: Succeeded
  startTime: "2020-02-27T10:48:13Z"
  taskRuns:
    dailymotion-leo-jx-env-master-p-7nsz2-30-leo-addons-insta-z96p6:
      pipelineTaskName: leo-addons-installation
      status:
        completionTime: "2020-02-27T10:53:18Z"
        conditions:
        - lastTransitionTime: "2020-02-27T10:53:18Z"
          message: All Steps have completed executing
          reason: Succeeded
          status: "True"
          type: Succeeded
        podName: dailymotion-leo-jx-env-master-p-7nsz2-30-leo-addons-insta-z96p6-pod-bbd80d
        startTime: "2020-02-27T10:52:26Z"
        steps:
        - container: step-helmfile-apply
          name: helmfile-apply
          terminated:
            exitCode: 0
            finishedAt: "2020-02-27T10:53:17Z"
            reason: Completed
            startedAt: "2020-02-27T10:52:48Z"
        - container: step-create-dir-workspace-46fgl
          name: create-dir-workspace-46fgl
          terminated:
            exitCode: 0
            finishedAt: "2020-02-27T10:52:50Z"
            reason: Completed
            startedAt: "2020-02-27T10:52:47Z"
        - container: step-source-copy-workspace-pfswl
          name: source-copy-workspace-pfswl
          terminated:
            exitCode: 0
            finishedAt: "2020-02-27T10:52:51Z"
            reason: Completed
            startedAt: "2020-02-27T10:52:48Z"
```

as you can see, the same stage/task ("leo-addons-installation") is marked as successful.

in the controllerbuild logs, I can see (for a different build):

```
{"level":"info","msg":"Build dailymotion-leo-jx-env-master-31 Succeeded","name":"dailymotion-leo-jx-env-master-31","pipelineRunInfo":"dailymotion-leo-jx-env-master-31",...,"status":"Succeeded","time":"2020-02-28T08:56:05Z"}
{"level":"warning","msg":"No PipelineRunInfo created for PipelineRun dailymotion-leo-jx-env-pr-35-pr-kqmhf-1: %!s(\u003cnil\u003e)","time":"2020-02-28T08:56:05Z"}
{"level":"info","msg":"Build dailymotion-leo-jx-env-master-31 Failed","name":"dailymotion-leo-jx-env-master-31","pipelineRunInfo":"dailymotion-leo-jx-env-master-31",...,"status":"Failed","time":"2020-02-28T09:00:09Z"}
```

I'm now running in the controllerbuild in debug mode to try to get more logs if I can reproduce it - it seems to happen randomly.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1192+cjxd.7
Kubernetes cluster v1.15.7-gke.23
kubectl            v1.15.7
helm client        Client: v2.14.3+g0e7f3b6
git                2.24.0
Operating System   Mac OS X 10.12.6 build 16G2136
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GKE

### Operating system / Environment

MacOS
