### ISSUE TITLE
env variables in overridden step are ignored

### ISSUE THREAD

**Issue by yelhouti** [jenkins-x/jx#6845]
### Summary 
I 'm trying to add env variables in a specific step:

### Steps to reproduce the behavior
```
buildPack: gradle
pipelineConfig:
  pipelines:
    overrides:
      - stage: build # add -PnodeInstall to install npm
        name: gradle-build
        type: replace
        steps:
          - name: gradle-build
            env:
              - name: KEYCLOAK_AUTH_SERVER_URL
                value: https://auth.jx.<org>.com/auth
              - name: KEYCLOAK_USERNAME
                value: keycloak
              - name: KEYCLOAK_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: jenkins-x-keycloak-http
                    key: password
            command: ./gradlew clean build -Pprod -PnodeInstall --no-daemon
```

### Expected behavior
env variables should be added to the step's container

### Actual behavior
env variables missing

### Jx version

The output of `jx version` is:

```
2.0.1221
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

Kubespray
