### ISSUE TITLE
"containerOptions" to increase the memory of the builder pods is ignored

### ISSUE THREAD

**Issue by hervelemeur** [jenkins-x/jx#6846]
### Summary 
I've added a `containerOptions` section to my pipeline to increase the memory available for the builder pods to be able to build an Angular app, but it wasn't taken in account, I had to duplicate it in each pipelines.

### Steps to reproduce the behavior
I have an Angular frontend build requiring more memory (if not I've got a "JavaScript heap out of memory" error), so I'm increasing the memory with:
`export NODE_OPTIONS=--max_old_space_size=2048 && ng build`
But now the builder pod is killed, as seen in the build log:

> > export NODE_OPTIONS=--max_old_space_size=2048 && ng build
> sh: line 1:    23 Killed                  ng build
> npm ERR! code ELIFECYCLE
> npm ERR! errno 137
> npm ERR! myproject@2.1.1 build-k8s: `export NODE_OPTIONS=--max_old_space_size=2048 && ng build`
> npm ERR! Exit status 137
> npm ERR!
> npm ERR! Failed at the myproject@2.1.1 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I've tried to increase the builder memory by adding this at the beginning of the frontend jenkins-x.yaml, but no luck:
```
buildPack: javascript
pipelineConfig:
  containerOptions:
    resources:
      requests:
        cpu: 1000m
        memory: 4096Mi
      limits:
        cpu: 1000m
        memory: 8172Mi
```

I had to duplicate the section in each pipeline overrides:
```
buildPack: javascript
pipelineConfig:
  pipelines:
    overrides:
    - pipeline: pullRequest
      containerOptions:
        resources:
          requests:
            cpu: 1000m
            memory: 4096Mi
          limits:
            cpu: 1000m
            memory: 8172Mi
       # [...]
    - pipeline: release
      containerOptions:
        resources:
          requests:
            cpu: 1000m
            memory: 4096Mi
          limits:
            cpu: 1000m
            memory: 8172Mi
       # [...]
```
### Expected behavior
The defined `containerOptions` is taken in account when declaring it at the beggining of the buildpack, without needing to duplicate it in each pipeline.
### Actual behavior
The defined `containerOptions` is not taken in account when declaring it at the beggining of the buildpack, needing to duplicate it in each pipeline.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1194
Kubernetes cluster v1.15.7
kubectl            v1.14.8
helm client        Client: v2.14.0+g05811b8
git                2.23.0.windows.1
Operating System   Windows 10 Enterprise 1709 build 16299
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

AKS, manually created.

### Operating system / Environment

Windows 10 Enterprise 1709 build 16299
