### ISSUE TITLE
Jx Boot fails to get ingress-controller

### ISSUE THREAD

**Issue by Touseefyousuf** [jenkins-x/jx#6863]
### Summary 
Jx Boot fails to get ingress-controller

```yaml
- ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: ""
    tls:
email: ""
enabled: false
production: false
```

### Actual behavior

Fails to get the ingress service

### Jx version

The output of `jx version` is:
```
Verifying the CLI packages using version stream URL: https://github.com/jenkins-x/jen
kins-x-versions.git and git ref: v1.0.374
using version 2.0.1225 of jx
CLI packages kubectl, git, helm seem to be setup correctly
NAME               VERSION
jx                 2.0.1225
Kubernetes cluster v1.14.9-eks-502bfb
kubectl            v1.14.0
git                2.23.1
```

```
STEP: create-install-values command: /bin/sh -c jx step create install values -b in d
ir: /home/ec2-user/jenkins-x-boot-config/env

Waiting to find the external host name of the ingress controller Service in namespace
 kube-system with name jxing-nginx-ingress-controller
No domain flag provided so using default  to generate Ingress rules
waiting for external Host on the ingress service jxing-nginx-ingress-controller in na
mespace kube-system ...
error: failed to discover the Ingress domain: getting a domain for ingress service ku
be-system/jxing-nginx-ingress-controller: Timed out after 5m0s, last error: %!s(<nil>
)
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx 
step create install values -b' command in directory 'env', output: ''
```

### Jenkins type

- Serverless Jenkins X Pipelines (Tekton + Prow)

### Operating system / Environment
ubuntu

**Comment by hferentschik** [comment]
Do you have your own domain or do you want to use _nip.io_ which is the default domain?

**Comment by Touseefyousuf** [comment]
i am using the default domain

**Comment by tommywo** [comment]
I had the same error. This are the errors in the service:
```
Error syncing load balancer: failed to ensure load balancer: Error creating load balancer: "AccessDenied: User: arn:aws:sts::XXXXXXX:assumed-role/tf-jx-XXXXXXX/XXXXXXX is not authorized to perform: ec2:DescribeAccountAttributes\n\tstatus code: 403, request id: XXXXXXX"

```
```
Error syncing load balancer: failed to ensure load balancer: Error creating load balancer: "AccessDenied: User: arn:aws:sts::XXXXXXX:assumed-role/tf-jx-XXXXXXX/XXXXXXX is not authorized to perform: ec2:DescribeInternetGateways\n\tstatus code: 403, request id: XXXXXXX"
```
I've added the permissions to eks role and jx boot passed.

**Comment by deanesmith** [comment]
@Touseefyousuf, did you leverage the jx Terraform script to provision your cluster?

**Comment by supermodo** [comment]
Same problem here.
I've created the cluster with Terraform and this is the jx-requirements.yml
```
autoUpdate:
  enabled: false
  schedule: ""
terraform: true
cluster:
  clusterName: "goat"
  provider: eks
  region: "us-east-1"
  environmentGitOwner: "supermodo"
  gitKind: gitlab
  gitName: gl
  gitServer: https://gitlab.com
gitops: true
environments:
  - key: dev
  - key: staging
  - key: production
ingress:
  domain: ""
  ignoreLoadBalancer: true
  externalDNS: true
  tls:
    email: ""
    enabled: false
    production: false
kaniko: true
secretStorage: vault
vault:
  aws:
    iamUserName: ""
    dynamoDBTable: "vault-unseal-goat-XXXXXXXX"
    dynamoDBRegion: "us-east-1"
    kmsKeyId: "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
    kmsRegion: "us-east-1"
    s3Bucket: "vault-unseal-goat-XXXXXXXXXXXXXXXXXXXXXXXXXX"
    s3Region: "us-east-1"
storage:
  logs:
    enabled: true
    url: s3://logs-goat-XXXXXXXXXXXXXXXXXXXXXXXXXX
  reports:
    enabled: true
    url: s3://reports-goat-XXXXXXXXXXXXXXXXXXXXXXXXXX
  repository:
    enabled: true
    url: s3://repository-goat-XXXXXXXXXXXXXXXXXXXXXXXXXX
versionStream:
  ref: master
  url: https://github.com/jenkins-x/jenkins-x-versions.git
webhook: lighthouse
```
then
```
$ mkdir prj
$ cd prj
$ jx boot -r ../jx-requirements.yml 
```
and this is the output
```
Creating boot config with defaults, as not in an existing boot directory with a git repository.
No Jenkins X pipeline file jenkins-x.yml or no jx boot requirements file jx-requirements.yml found. You are not running this command from inside a Jenkins X Boot git clone
To continue we will clone https://github.com/jenkins-x/jenkins-x-boot-config.git @ master to jenkins-x-boot-config
? Do you want to clone the Jenkins X Boot Git repository? Yes

Cloning https://github.com/jenkins-x/jenkins-x-boot-config.git @ master to jenkins-x-boot-config
Attempting to resolve version for boot config https://github.com/jenkins-x/jenkins-x-boot-config.git from https://github.com/jenkins-x/jenkins-x-versions.git
Booting Jenkins X
WARNING: failed to load ConfigMap jenkins-x-docker-registry in namespace jx: failed to get configmap jenkins-x-docker-registry in namespace jx, configmaps "jenkins-x-docker-registry" not found
WARNING: failed to load ConfigMap jenkins-x-docker-registry in namespace jx: failed to get configmap jenkins-x-docker-registry in namespace jx, configmaps "jenkins-x-docker-registry" not found

STEP: validate-git command: /bin/sh -c jx step git validate in dir: /Users/ROOT_TO_MY_FOLDER/jenkins-x-boot-config/env

Git configured for user: supermodo and email servizio@modotti.me

STEP: verify-preinstall command: /bin/sh -c jx step verify preinstall --provider-values-dir="kubeProviders" in dir: /Users/ROOT_TO_MY_FOLDER/jenkins-x-boot-config

? Comma-separated git provider usernames of approvers for development environment repository [? for h? Comma-separated git provider usernames of approvers for development environment repository supermodo
Locking version stream https://github.com/jenkins-x/jenkins-x-versions.git to release v1.0.471. Jenkins X will use this release rather than master to resolve all versions from now on.
writing the following to the OWNERS file for the development environment repository:
approvers:
- supermodo
reviewers:
- supermodo
The provided requirements file has 'strictPermissions' enabled but 'provider' is not Openshift.
This feature is only supported on Openshift
WARNING: Vault is enabled and TLS is not enabled. This means your secrets will be sent to and from your cluster in the clear. See https://jenkins-x.io/docs/getting-started/setup/boot/#ingress for more information
WARNING: TLS is not enabled so your webhooks will be called using HTTP. This means your webhook secret will be sent to your cluster in the clear. See https://jenkins-x.io/docs/getting-started/setup/boot/#ingress for more information
? Do you wish to continue? Yes

Verifying the kubernetes cluster before we try to boot Jenkins X in namespace: jx
WARNING: Lazy create of cloud resources is disabled
Verifying Ingress...

Using namespace 'jx' from context named 'arn:aws:eks:us-east-1:XXXXXXXXXXXX:cluster/goat' on server 'https://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.gr7.us-east-1.eks.amazonaws.com'.

Verifying the CLI packages using version stream URL: https://github.com/jenkins-x/jenkins-x-versions.git and git ref: v1.0.471
using version 2.1.45 of jx
CLI packages kubectl, git, helm seem to be setup correctly
NAME               VERSION
jx                 2.1.45
Kubernetes cluster v1.15.11-eks-af3caf
kubectl            v1.13.2
git                2.20.1

Verifying Storage...
WARNING: Your requirements have not enabled cloud storage for backup - we recommend enabling this for kubernetes provider eks
Storage configuration looks good

Helm installed and configured
Ensuring Helm chart repository https://storage.googleapis.com/chartmuseum.jenkins-x.io is configured
verified there is a ConfigMap config in namespace jx
verified there is a ConfigMap plugins in namespace jx
Cluster looks good, you are ready to 'jx boot' now!


STEP: install-jx-crds command: /bin/sh -c jx upgrade crd in dir: /Users/ROOT_TO_MY_FOLDER/jenkins-x-boot-config

Jenkins X CRDs upgraded with success

STEP: install-velero command: /bin/sh -c jx step helm apply --boot --remote --no-vault --name velero in dir: /Users/ROOT_TO_MY_FOLDER/jenkins-x-boot-config/systems/velero

Modified file /Users/ROOT_TO_MY_FOLDER/jenkins-x-boot-config/systems/velero/Chart.yaml to set the chart to version 1
lock cancelled because not running in tekton
Verifying the helm requirements versions in dir: . using version stream URL: https://github.com/jenkins-x/jenkins-x-versions.git and git ref: v1.0.471

STEP: install-velero-backups command: /bin/sh -c jx step helm apply --boot --remote --no-vault --name velero-backups in dir: /Users/ROOT_TO_MY_FOLDER/jenkins-x-boot-config/systems/velero-backups

Modified file /Users/ROOT_TO_MY_FOLDER/jenkins-x-boot-config/systems/velero-backups/Chart.yaml to set the chart to version 1
lock cancelled because not running in tekton
Ignoring templates/default-backup.yaml
No requirements file: /var/folders/b3/ty629jss00g9mjy5jz_yq3rr0000gn/T/jx-helm-apply-806100998/velero-backups/requirements.yaml so not checking for missing versions

STEP: install-nginx-controller command: /bin/sh -c jx step helm apply --boot --remote --no-vault --name jxing in dir: /Users/ROOT_TO_MY_FOLDER/jenkins-x-boot-config/systems/jxing

Modified file /Users/ROOT_TO_MY_FOLDER/jenkins-x-boot-config/systems/jxing/Chart.yaml to set the chart to version 1
lock cancelled because not running in tekton
Verifying the helm requirements versions in dir: . using version stream URL: https://github.com/jenkins-x/jenkins-x-versions.git and git ref: v1.0.471


STEP: create-install-values command: /bin/sh -c jx step create install values -b in dir: /Users/ROOT_TO_MY_FOLDER/jenkins-x-boot-config/env

Waiting to find the external host name of the ingress controller Service in namespace kube-system with name jxing-nginx-ingress-controller
No domain flag provided so using default  to generate Ingress rules
waiting for external Host on the ingress service jxing-nginx-ingress-controller in namespace kube-system ...
error: failed to discover the Ingress domain: getting a domain for ingress service kube-system/jxing-nginx-ingress-controller: Timed out after 5m0s, last error: %!s(<nil>)
error: failed to interpret pipeline file /Users/ROOT_TO_MY_FOLDER/jenkins-x-boot-config/jenkins-x.yml: failed to run '/bin/sh -c jx step create install values -b' command in directory '/Users/ROOT_TO_MY_FOLDER/jenkins-x-boot-config/env', output: ''
```
