### ISSUE TITLE
Promoting the same chart multiple times does not add multiple entries in requirements.yaml

### ISSUE THREAD

**Issue by RoVernekar** [jenkins-x/jx#6867]
### Summary 

If a chart is promoted to an environment multiple times with different aliases, only one entry will be added to `requirements.yaml`.

Any promote command after the first, will just rename the alias of the first entry for that chart.

### Steps to reproduce the behavior

1. Promote a chart to an environment
```
jx promote -f redis --env staging --alias redis-1
```

2. Observe that the dependency was added in `env/requirements.yaml` as expected
```
dependencies:
- alias: redis-1
  name: redis
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 10.5.6
```

3. Promote the same chart with a different alias
```
jx promote -f redis --env staging --alias redis-2
```

4. Observe that instead of adding a second entry to `env/requirements.yaml`, the first entry's alias was renamed to `redis-2`
```diff
dependencies:
- - alias: redis-1
+ - alias: redis-2
  name: redis
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 10.5.6
```

### Expected behavior

`env/requirements.yaml` should contain two dependencies:
```
dependencies:
- alias: redis-1
  name: redis
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 10.5.6
- alias: redis-2
  name: redis
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 10.5.6
```

### Actual behavior

`env/requirements.yaml` contains only one dependency:
```
dependencies:
- alias: redis-2
  name: redis
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 10.5.6
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1218
Kubernetes cluster v1.14.9
kubectl            v1.15.5
helm client        Client: v2.16.1+gbbdfe5e
git                2.21.0 (Apple Git-122.2)
Operating System   Mac OS X 10.15.2 build 19C57
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins
