### ISSUE TITLE
jx boot swallows jx-requirements.yml validation errors

### ISSUE THREAD

**Issue by joostvdg** [jenkins-x/jx#6936]
### Summary 

If you have syntax errors in `jx-requirements.yml`, they get swallowed and a generic error gets returned instead. This error obscures what is going wrong.

### Steps to reproduce the behavior

Make a syntax error in the `jx-requirements.yml` that is still valid YAML.
For example, add an additional field in the `environment.x.ingress.` such as below:

```yaml
- ingress:
    domain: staging.apps.ocp.kearos.net
    externalDNS: false
    namespaceSubDomain: ""
    tls:
      email: ""
      enabled: false
      production: false
  key: staging
  namespace: staging
  repository: env-staging
```

### Expected behavior

`jx boot` returning with an error, but logging the validation mistakes.

For example:

```bash
environments.1: Additional property namespace is not allowed
environments.2: Additional property namespace is not allowed)
```

### Actual behavior

```bash
error: unable to load jx-requirements.yml: jx-requirements.yml file not found
```

The culprit is the function `func LoadRequirementsConfig(dir string) (*RequirementsConfig, string, error) {}` in `config/install_requirements.go`.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1244
Kubernetes cluster v1.11.0+d4cacc0
kubectl            v1.16.7
git                2.21.0 (Apple Git-122.2)
Operating System   Mac OS X 10.15.3 build 19D76
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

OpenShift 3.11, how it was created -> https://joostvdg.github.io/openshift/rhos311-gcp-minimal/

### Operating system / Environment

Mac OS X 10.15.3 build 19D76
