### ISSUE TITLE
Discovery - Kubernetes 1.16 support

### ISSUE THREAD

**Issue by deanesmith** [jenkins-x/jx#6957]
### Summary 
As a result of major cloud provider's bumping default versions of Kubernetes to 1.16 (and beyond), it would be prudent to assess how much effort is required to formally support Jenkins-X on Kubernetes 1.16.  

A reasonable inventory of related open issues can be found here -
https://github.com/jenkins-x/jx/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%2Fkubernetes

The output of this task would be to establish how much effort is required for the additional support and to assess the risk and/or any upgrade nuances.

**Comment by ankitm123** [comment]
We could use [pluto](https://github.com/FairwindsOps/pluto) to find deprecated Kubernetes apiVersions in the codebase and helm releases (helm2 and helm3).

**Comment by ankitm123** [comment]
These are the versions of the charts that need to be updated in jenkins-x-platform to support kubernetes 1.16+ support (based on the error message I got after doing a `jx boot` on kubernetes 1.17.X cluster). 

- chartmuseum: 1.0.2 (https://github.com/helm/charts/pull/18123/files)
- docker-registry: 1.8.3 (https://github.com/helm/charts/pull/17454/files)
- heapster (this is deprecated, and should be replaced with metric-server): 2.4.0 (https://github.com/helm/charts/pull/17334/files)
- jenkins (Probably should be removed): - 

I will open a PR against the jenkins-x-platform. I will check if the other helm charts need to be updated as well.

**Comment by garethjevans** [comment]
Both helm 2 & 3 support a pretty decent set of built-in objects. e.g. https://v2.helm.sh/docs/chart_template_guide/#built-in-objects.  We should be able to use the `Capabilities` to determine if the api is present. e.g. `Capabilities.APIVersions.Has $version`.

Need to careful to do it for versions, rather than resources as it looks like that was only added in 2.15

**Comment by garethjevans** [comment]
@deanesmith do we have a view on what kubernetes versions we are attempting to support? v1.13 -v1.18?

**Comment by deanesmith** [comment]
@garethjevans any improvement on the current support level but v1.13-v1.16 is miminal I believe.  What do you think?

**Comment by ankitm123** [comment]
Should it not mirror what the cloud providers support? For example eks: https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#version-deprecation (Probably similar for gke and aks)
For people hosting their own kubernetes clusters, we need to document which versions we support, and what is our policy of deprecation. 
I like this suggestion: https://github.com/jenkins-x/jx/issues/7193#issuecomment-630302909, this seems to be consistent with the way we make it clear which versions of helm we support.

**Comment by vfarcic** [comment]
I just got the following error from `jx boot`.

```
...
unable to recognize "/var/folders/73/94ypm_917397bvg1y3f7phkc0000gn/T/helm-template-workdir-195790001/jenkins-x/output/namespaces/jx/env/charts/jenkins-x-platform/charts/chartmuseum/templates/part0-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
unable to recognize "/var/folders/73/94ypm_917397bvg1y3f7phkc0000gn/T/helm-template-workdir-195790001/jenkins-x/output/namespaces/jx/env/charts/jenkins-x-platform/charts/heapster/templates/part0-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"'
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step helm apply --boot --remote --name jenkins-x --provider-values-dir ../kubeProviders' command in directory 'env', output: ''
```

```bash
kubectl version --output yaml
```

```
clientVersion:
  buildDate: "2020-02-11T19:34:02Z"
  compiler: gc
  gitCommit: be3d344ed06bff7a4fc60656200a93c74f31f9a4
  gitTreeState: clean
  gitVersion: v1.16.7
  goVersion: go1.13.6
  major: "1"
  minor: "16"
  platform: darwin/amd64
serverVersion:
  buildDate: "2020-04-16T23:15:50Z"
  compiler: gc
  gitCommit: a17149e1a189050796ced469dbd78d380f2ed5ef
  gitTreeState: clean
  gitVersion: v1.16.9
  goVersion: go1.13.9
  major: "1"
  minor: "16"
  platform: linux/amd64
```
