### ISSUE TITLE
How to get jxui links into github pull requests?

### ISSUE THREAD

**Issue by hervelemeur** [jenkins-x/jx#6992]
### Summary 
Wanting to get build logs directly in the PR pages, I've added jxui to access these logs.
But :
1) jxui isn't exposed by default
2) tide is putting a deck.mydomain.org link instead of the jxui one
3) how can I specify a link to the concerned build and not the jxui homepage?

Details about these points:
1) I've managed to expose jxui interface by adding a custom ingress in the `jx`namespace:
````
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jxui-ingress-https
  namespace: jx
  annotations:
    # type of authentication
    nginx.ingress.kubernetes.io/auth-type: basic
    # name of the secret that contains the user/password definitions
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    # message to display with an appropriate context why the authentication is required
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
spec:
  tls:
  - hosts:
    - jxui.mydomain.org
    secretName: tls-mydomain
  rules:
    - host: jxui.mydomain.org
      http:
        paths:
        - backend:
            serviceName: jxui
            servicePort: 80
````

2) I've managed to replace the deck.mydomain.org link by jxui.mydomain.org with this command:
`kubectl edit cm config` and then replacing the value of `target_url`

How can I save this configuration in my boot repository?

3) After 2), the link "detail" provided by tide in the PR redirect to the homepage of jxui, but I'd like to be a redirection to the concerned build in jxui.

### Jx version

The output of `jx version` is:

```
jx                 2.0.1230
jenkins x platform 2.0.1296
Kubernetes cluster v1.15.3
kubectl            v1.17.3
helm client        2.16.3
git                2.21.1 (Apple Git-122.3)
Operating System   Mac OS X 10.15.3 build 19D76
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

AKS

### Other
Link to the Slack conversation: https://kubernetes.slack.com/archives/C9MBGQJRH/p1585583672195000

**Comment by dgozalo** [comment]
The workaround to manually configure `Plank` with lasting configuration is to either create a new `Scheduler` or modify one in the `dev` environment repository.

The default scheduler being created by Boot in your dev environment repository is: 

https://github.com/jenkins-x-charts/jxboot-resources/blob/master/jxboot-resources/templates/default-scheduler.yaml

You'd need to add an attachment to this scheduler at the end like:
```
  attachments:
  - name: jobURLPrefix
    urls:
    - '<YOUR_UI_URL>/teams'
  - name: reportTemplate
    urls:
    - '{{`{{if eq .Spec.Type "presubmit"}}[View all Builds for this Pull Request](<YOUR_UI_URL>/teams/{{.Spec.Namespace}}/projects/{{.Spec.Refs.Org}}/{{.Spec.Refs.Repo}}/PR-{{(index .Spec.Refs.Pulls 0).Number}}) {{else if eq .Spec.Type "batch"}} Run "jx get build log --owner {{.Spec.Refs.Org}} --repo {{.Spec.Refs.Repo}} --branch batch" whilst connected to the cluster. UI support coming soon. {{end}}`}}'
  - name: jobURLTemplate
    urls:
    - '{{`{{if eq .Spec.Type "presubmit"}}<YOUR_UI_URL>/teams/{{.Spec.Namespace}}/projects/{{.Spec.Refs.Org}}/{{.Spec.Refs.Repo}}/PR-{{(index .Spec.Refs.Pulls 0).Number}}/{{.Status.BuildID}}{{else if eq .Spec.Type "postsubmit"}}<YOUR_UI_URL>/teams/{{.Spec.Namespace}}/projects/{{.Spec.Refs.Org}}/{{.Spec.Refs.Repo}}/{{.Spec.Refs.BaseRef}}/{{.Status.BuildID}}{{end}}`}}'
```
