### ISSUE TITLE
Errors while trying to use locally deployed Gitlab with Jenkins-X

### ISSUE THREAD

**Issue by mpwaldhorst** [jenkins-x/jx#704]
I was trying out Jenkins-X to investigate use with a locally hosted Gitlab server.
For this I was following the guide on http://jenkins-x.io/developing/git/.
When trying to use the `jx create git token` command as described on http://jenkins-x.io/developing/git/

I received the following error:
```
Failed to create GitService with name gitlab: namespaces "jx" not found
```

After this I tried editing the `.jx/gitAuth.yaml` file and copied the way github credentials are stored like this:
```
servers:
- url: https://gitlab.server.url.com/
  users:
    - username: myUserName
      apitoken: 'gitlabAccessToken'
      bearer: ""
  name: gitlab
  kind: gitlab
  currentuser: "myUserName"
defaultusername: ""
currentserver: https://gitlab.server.url.com/
```

After this I tried running `jx create cluster minikube`.
I was asked to select a organisation, the only option I received was the username I had provided in the `gitAuth.yaml` file.
After selecting this organisation I received the following error:
```
Creating repository myUserName/environment-armfeather-staging
Creating git repository myUserName/environment-armfeather-staging
error creating cluster POST https://gitlab.com/api/v4/projects: 401 {message: 401 Unauthorized}
```

The command seems to try to post to the gitlab.com servers instead of the local servers.

I hope this helps you guys.
