### ISSUE TITLE
Fail to push to Container registry, EKS

### ISSUE THREAD

**Issue by babadofar** [jenkins-x/jx#7072]
### Symptom 

All builds fail to push docker container registry

    error checking push permissions -- make sure you entered the correct tag name, and that you 
    are authenticated correctly, and try again: checking push permission for 
    "X.dkr.ecr.eu-west-1.amazonaws.com/X-X/X:0.0.0-SNAPSHOT-PR-111-2": unsupported status 
     code 401; body: Not Authorized

### Cause
This is due to a missing policy for `ecr` on the role attached to the tekton-bot service account.
### Remedy
It got it working through adding policy `ecr:*` to the `CFNTektonBotPolicy` manually. It should be added to the policy defined in jx boot config

```
Description: 'Template to generate the necessary IAM Policies for Jenkins-X EKS support '
Resources:
  CFNJenkinsXPolicies:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Join [ "-", [ CFNTektonBotPolicy, Ref: PoliciesSuffixParameter] ]
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - cloudformation:ListStacks
          - cloudformation:DescribeStacks
          - cloudformation:CreateStack
          - cloudformation:DeleteStack
          - eks:*
          - s3:*
          - ecr:*
          - iam:DetachRolePolicy
          - iam:GetPolicy
          - iam:CreatePolicy
          - iam:DeleteRole
          - iam:GetOpenIDConnectProvider
          Resource: "*"
``` 

https://github.com/jenkins-x/jenkins-x-boot-config/blob/master/kubeProviders/eks/templates/jenkinsx-policies.yml

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1285
Kubernetes cluster v1.15.10-eks-bac369
kubectl            v1.16.2
helm client        2.14.3
git                2.18.0
Operating System   Mac OS X 10.14.6 build 18G3020
```
