### ISSUE TITLE
SSO for jxui

### ISSUE THREAD

**Issue by gazal-k** [jenkins-x/jx#7077]
### Summary 

Unable to configure SSO for jxui

### Steps to reproduce the behavior

1. Install [dex](https://github.com/jenkins-x/dex/) with values like:

```yaml
connectors:
  github:
    config:
      clientID: {myClientId}
      clientSecret: {myClientSecret}
      orgs:
      - {myorg}
domain: dex.{domain}
```

2. Install [sso-operator](https://github.com/jenkins-x/sso-operator/) with values:

```yaml
dex:
  grpcHost: dex.dex
```

3. Install jxui with values like:

```yaml
jxRequirements:
...
secrets:
...
sso:
  create: true
  oidcIssuerUrl: https://dex.{domain}
  domain: {{ .Values.jxRequirements.ingress.domain }}
  certIssuerName: "letsencrypt-prod"
  connector: github
```
### Expected behavior

jxui can be used on the exposed ingress in "read-write" mode (non single user)

### Actual behavior

- The sso-operator creates the sso-jxui deployment
- The ingress gets created
- Navigating to the jxui url does lead to oauth2 with github as expected
- But the callback to jxui results in a broken blank page, the browser console and the jxui frontend container both log:
```
"GET /api/v1/kubeql HTTP/1.1" 500
```

Seems to me like some resources are perhaps missing.

Also tried to set `.Values.rbac.jxuiRole.create` to true, but that doesn't solve the problem either.

### Jx version

The output of `jx version` is:
`jxl version`
```
NAME               VERSION
jxl                0.0.181
Kubernetes cluster v1.15.11-eks-af3caf
kubectl            v1.17.3
helm client        3.1.2
git                2.25.2
Operating System   "Fedora release 31 (Thirty One)"
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

EKS 1.15 with eksctl
### Operating system / Environment

Operating System   "Fedora release 31 (Thirty One)"
