### ISSUE TITLE
no matches for kind "Deployment" in version "apps/v1beta2" 

### ISSUE THREAD

**Issue by zzguang520** [jenkins-x/jx#7116]
### Summary 
 jx boot --helm-log=9
Attempting to resolve version for boot config https://github.com/jenkins-x/jenkins-x-boot-config from https://github.com/jenkins-x/jenkins-x-versions.git
Current HEAD v1.0.84 in . is not an ancestor of v1.0.83, the boot config version from the version stream.
Proceeding with current HEAD.
Booting Jenkins X

STEP: validate-git command: /bin/sh -c jx step git validate in dir: /root/jx-install/jenkins-x-boot-config-dev/env

Git configured for user: zzguang520 and email zzguang520@sina.com

STEP: verify-preinstall command: /bin/sh -c jx step verify preinstall --provider-values-dir="kubeProviders" in dir: /root/jx-install/jenkins-x-boot-config-dev

jx boot has only been validated on GKE and EKS, we'd love feedback and contributions for other Kubernetes providers
? Continue execution anyway? Yes

writing the following to the OWNERS file for the development environment repository:
approvers:
- zzguang520
reviewers:
- zzguang520
WARNING: Vault is enabled and TLS is not enabled. This means your secrets will be sent to and from your cluster in the clear. See https://jenkins-x.io/docs/getting-started/setup/boot/#ingress for more information
WARNING: TLS is not enabled so your webhooks will be called using HTTP. This means your webhook secret will be sent to your cluster in the clear. See https://jenkins-x.io/docs/getting-started/setup/boot/#ingress for more information
? Do you wish to continue? Yes

Verifying the kubernetes cluster before we try to boot Jenkins X in namespace: jx
Trying to lazily create any missing resources to get the current cluster ready to boot Jenkins X
Verifying Ingress...

Using namespace 'jx' from context named 'kubernetes-admin@kubernetes' on server 'https://master.iocc-test.test.com:6443'.

Verifying the CLI packages using version stream URL: https://github.com/jenkins-x/jenkins-x-versions.git and git ref: v1.0.434
using version 2.1.10 of jx
CLI packages kubectl, git, helm seem to be setup correctly
NAME               VERSION
jx                 2.1.10
jenkins x platform 2.0.2171
Kubernetes cluster v1.18.2
kubectl            v1.16.9
git                2.18.4

Verifying Storage...
Storage configuration looks good

Helm installed and configured
Ensuring Helm chart repository https://storage.googleapis.com/chartmuseum.jenkins-x.io is configured
Cluster looks good, you are ready to 'jx boot' now!

STEP: install-jx-crds command: /bin/sh -c jx upgrade crd in dir: /root/jx-install/jenkins-x-boot-config-dev

Jenkins X CRDs upgraded with success

STEP: install-velero command: /bin/sh -c jx step helm apply --boot --remote --no-vault --name velero in dir: /root/jx-install/jenkins-x-boot-config-dev/systems/velero

Modified file /root/jx-install/jenkins-x-boot-config-dev/systems/velero/Chart.yaml to set the chart to version 1
lock cancelled because not running in tekton
Verifying the helm requirements versions in dir: . using version stream URL: https://github.com/jenkins-x/jenkins-x-versions.git and git ref: v1.0.434

STEP: install-velero-backups command: /bin/sh -c jx step helm apply --boot --remote --no-vault --name velero-backups in dir: /root/jx-install/jenkins-x-boot-config-dev/systems/velero-backups

Modified file /root/jx-install/jenkins-x-boot-config-dev/systems/velero-backups/Chart.yaml to set the chart to version 1
lock cancelled because not running in tekton
Ignoring templates/default-backup.yaml
No requirements file: /tmp/jx-helm-apply-270026003/velero-backups/requirements.yaml so not checking for missing versions

STEP: install-nginx-controller command: /bin/sh -c jx step helm apply --boot --remote --no-vault --name jxing in dir: /root/jx-install/jenkins-x-boot-config-dev/systems/jxing

Modified file /root/jx-install/jenkins-x-boot-config-dev/systems/jxing/Chart.yaml to set the chart to version 1
lock cancelled because not running in tekton
Verifying the helm requirements versions in dir: . using version stream URL: https://github.com/jenkins-x/jenkins-x-versions.git and git ref: v1.0.434

STEP: create-install-values command: /bin/sh -c jx step create install values -b in dir: /root/jx-install/jenkins-x-boot-config-dev/env

STEP: install-external-dns command: /bin/sh -c jx step helm apply --boot --remote --no-vault --name exdns in dir: /root/jx-install/jenkins-x-boot-config-dev/systems/external-dns

Modified file /root/jx-install/jenkins-x-boot-config-dev/systems/external-dns/Chart.yaml to set the chart to version 1
lock cancelled because not running in tekton
Verifying the helm requirements versions in dir: . using version stream URL: https://github.com/jenkins-x/jenkins-x-versions.git and git ref: v1.0.434

STEP: install-cert-manager-crds command: /bin/sh -c kubectl apply --wait --validate=false -f https://raw.githubusercontent.com/jetstack/cert-manager/release-0.11/deploy/manifests/00-crds.yaml in dir: /root/jx-install/jenkins-x-boot-config-dev

customresourcedefinition.apiextensions.k8s.io/challenges.acme.cert-manager.io configured
customresourcedefinition.apiextensions.k8s.io/orders.acme.cert-manager.io configured
customresourcedefinition.apiextensions.k8s.io/certificaterequests.cert-manager.io configured
customresourcedefinition.apiextensions.k8s.io/certificates.cert-manager.io configured
customresourcedefinition.apiextensions.k8s.io/clusterissuers.cert-manager.io configured
customresourcedefinition.apiextensions.k8s.io/issuers.cert-manager.io configured

STEP: install-cert-manager command: /bin/sh -c jx step helm apply --boot --remote --no-vault --name cm in dir: /root/jx-install/jenkins-x-boot-config-dev/systems/cm

Modified file /root/jx-install/jenkins-x-boot-config-dev/systems/cm/Chart.yaml to set the chart to version 1
lock cancelled because not running in tekton
Verifying the helm requirements versions in dir: . using version stream URL: https://github.com/jenkins-x/jenkins-x-versions.git and git ref: v1.0.434

STEP: install-acme-issuer-and-certificate command: /bin/sh -c jx step helm apply --boot --remote --no-vault --name acme in dir: /root/jx-install/jenkins-x-boot-config-dev/systems/acme

Modified file /root/jx-install/jenkins-x-boot-config-dev/systems/acme/Chart.yaml to set the chart to version 1
lock cancelled because not running in tekton
Ignoring templates/cert-manager-prod-certificate.yaml
Ignoring templates/cert-manager-prod-issuer.yaml
Ignoring templates/cert-manager-staging-certificate.yaml
Ignoring templates/cert-manager-staging-issuer.yaml
No requirements file: /tmp/jx-helm-apply-308721369/acme/requirements.yaml so not checking for missing versions

STEP: install-vault command: /bin/sh -c jx step boot vault --provider-values-dir ../../kubeProviders in dir: /root/jx-install/jenkins-x-boot-config-dev/systems/vault

Installing vault-operator operator with helm values: [image.repository=banzaicloud/vault-operator image.tag=0.5.3]
error: unable to install Vault operator: unable to install vault operator: failed to run 'kubectl apply --recursive -f /tmp/helm-template-workdir-021020237/vault-operator/output/namespaces/jx -l jenkins.io/chart-release=vault-operator --namespace jx --validate=false' command in directory '', output: 'customresourcedefinition.apiextensions.k8s.io/vaults.vault.banzaicloud.com unchanged
clusterrole.rbac.authorization.k8s.io/vault-operator unchanged
clusterrolebinding.rbac.authorization.k8s.io/vault-operator unchanged
serviceaccount/vault-operator unchanged
service/vault-operator unchanged
error: unable to recognize "/tmp/helm-template-workdir-021020237/vault-operator/output/namespaces/jx/vault-operator/templates/part0-deployment.yaml": no matches for kind "Deployment" in version "apps/v1beta2"'
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step boot vault --provider-values-dir ../../kubeProviders' command in directory 'systems/vault', output: ''
### Steps to reproduce the behavior
1.git clone https://github.com/jenkins-x/jenkins-x-boot-config.git jenkins-x-boot-config-dev
2.modifying the jx-requirements.yml file
3.execute the command "jx boot"
### Expected behavior
jx boot successful
### Actual behavior
failed: no matches for kind "Deployment" in version "apps/v1beta2"
### Jx version

The output of `jx version` is:
```
NAME               VERSION
jx                 2.1.10
jenkins x platform 2.0.2171
Kubernetes cluster v1.18.2
kubectl            v1.16.9
helm client        2.16.6
git                2.18.4
Operating System   "Red Hat Enterprise Linux Workstation release 7.7 (Maipo)"


verifying packages
```

### Kubernetes cluster

install manually for Basic Kubernetes cluster 
```
[root@oc7778463706 jenkins-x-boot-config-dev]# kubectl get node
NAME                       STATUS   ROLES    AGE   VERSION
master.iocc-test.test.com   Ready    master   14d   v1.18.2
node1.iocc-test.test.com    Ready    <none>   14d   v1.18.2
node2.iocc-test.test.com    Ready    <none>   14d   v1.18.2
```

### Operating system / Environment
Redhat 7.7

**Comment by zzguang520** [comment]
```
[root@oc7778463706 jenkins-x-boot-config-dev]# kubectl api-versions
acme.cert-manager.io/v1alpha2
admissionregistration.k8s.io/v1
admissionregistration.k8s.io/v1beta1
apiextensions.k8s.io/v1
apiextensions.k8s.io/v1beta1
apiregistration.k8s.io/v1
apiregistration.k8s.io/v1beta1
apps/v1
authentication.k8s.io/v1
authentication.k8s.io/v1beta1
authorization.k8s.io/v1
authorization.k8s.io/v1beta1
autoscaling/v1
autoscaling/v2beta1
autoscaling/v2beta2
batch/v1
batch/v1beta1
cert-manager.io/v1alpha2
certificates.k8s.io/v1beta1
coordination.k8s.io/v1
coordination.k8s.io/v1beta1
discovery.k8s.io/v1beta1
events.k8s.io/v1beta1
extensions/v1beta1
jenkins.io/v1
networking.k8s.io/v1
networking.k8s.io/v1beta1
node.k8s.io/v1beta1
policy/v1beta1
rbac.authorization.k8s.io/v1
rbac.authorization.k8s.io/v1beta1
scheduling.k8s.io/v1
scheduling.k8s.io/v1beta1
storage.k8s.io/v1
storage.k8s.io/v1beta1
v1
vault.banzaicloud.com/v1alpha1
```

**Comment by zzguang520** [comment]
```
[root@master ~]# cat /etc/kubernetes/manifests/kube-apiserver.yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubeadm.kubernetes.io/kube-apiserver.advertise-address.endpoint: 192.168.160.58:6443
  creationTimestamp: null
  labels:
    component: kube-apiserver
    tier: control-plane
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-apiserver
    - --advertise-address=192.168.160.58
    - --allow-privileged=true
    - --authorization-mode=Node,RBAC
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --enable-admission-plugins=NodeRestriction
    - --enable-bootstrap-token-auth=true
    - --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt
    - --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt
    - --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key
    - --etcd-servers=https://127.0.0.1:2379
    - --insecure-port=0
    - --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt
    - --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt
    - --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key
    - --requestheader-allowed-names=front-proxy-client
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --requestheader-extra-headers-prefix=X-Remote-Extra-
    - --requestheader-group-headers=X-Remote-Group
    - --requestheader-username-headers=X-Remote-User
    - --secure-port=6443
    - --service-account-key-file=/etc/kubernetes/pki/sa.pub
    - --service-cluster-ip-range=10.96.0.0/12
    - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
    - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
	- --runtime-config=apps/v1beta2=true
    image: k8s.gcr.io/kube-apiserver:v1.18.2
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 192.168.160.58
        path: /healthz
        port: 6443
        scheme: HTTPS
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-apiserver
    resources:
      requests:
        cpu: 250m
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
    - mountPath: /etc/pki
      name: etc-pki
      readOnly: true
    - mountPath: /etc/kubernetes/pki
      name: k8s-certs
      readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
  - hostPath:
      path: /etc/pki
      type: DirectoryOrCreate
    name: etc-pki
  - hostPath:
      path: /etc/kubernetes/pki
      type: DirectoryOrCreate
    name: k8s-certs
status: {}
[root@master ~]#
```
