### ISSUE TITLE
Unable to change docker registry when using Boot + GKE

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx#7148]
Currently, it is not possible to use a non-default Docker registry when using GKE. One can specify the registry during initial boot, but then the secret/login will not be set up properly. Also, it is not possible to change the registry afterwards. One can change the registry host in the jx-requirements.yml, but the Docker credentials will always default to the GKE defaults. 

The problem is partly _kubeProviders/gke/values.tmpl.yaml_ in the boot config which does not take into account a non default registry:

```yml
jenkins-x-platform:
  PipelineSecrets:

    # lets enable GCR docker builds
    DockerConfig: |-
      {
          "credHelpers": {
              "gcr.io": "gcr",
              "us.gcr.io": "gcr",
              "eu.gcr.io": "gcr",
              "asia.gcr.io": "gcr",
              "staging-k8s.gcr.io": "gcr"
          }
      }

docker-registry:
{{- if eq .Requirements.webhook "jenkins" }}
  enabled: true
{{- else }}
  enabled: false
{{- end }}
```

We need something similar to the OpenShift setup _kubeProviders/openshift/values.tmpl.yaml_:

```yml
jenkins-x-platform:
  PipelineSecrets:
{{- if eq .Parameters.enableDocker true }}
    DockerConfig: |-
      {
        "auths":{
          {{ .Parameters.docker.url | quote }}:
            {
              "auth": {{ printf "%s:%s" .Parameters.docker.username .Parameters.docker.password | b64enc | quote}},
              "email": {{ .Parameters.docker.email | quote}}
            }
        }
      }
{{- else}}
    DockerConfig: ""
{{- end}}
```

On top of that we need to handle the case that the user wants to change the registry after an initial boot w/ the default registry. In this case, the required Vault secret needs to be created as well.
