### ISSUE TITLE
Lack of documentation on pipelines - maven builder out of memory

### ISSUE THREAD

**Issue by gcontini** [jenkins-x/jx#7167]
### Summary 
I have quite a large project maven project that is being refactored.  The standard maven builder goes out of memory. 

The doucmentation is not clear where do i have to change the builder (`containerOptions`) parameters. If i follow the [pipeline reference](https://jenkins-x.io/docs/reference/pipeline-syntax-reference/) i end up to override the whole pipeline... 
Can somebody prepare better examples of common extension cases?

**Comment by babadofar** [comment]
I had the same problem, fixed by adding a pipelineconfig section to the jenkins-x.yml file in the project.
```
buildPack: maven-java11
pipelineConfig:
  env:
    - name: MAVEN_OPTS
      value: -Xms256m -Xmx2048m -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
```
