### ISSUE TITLE
add a `jx dev go|maven|node` command

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#718]
It would good to to spin up a dev pod, in cluster, using a jenkins x builder image and exec into the pod so folks can leverage the cloud for development.  Then the os, builds and language version and are all the same as when the apps are built, released and run.  This also means folks that have restricted machines or low resources can leverage more of the cloud.

Also @jstrachan has mentioned before about being able to rsync a local filesystem into a pod, so folks can hack in their favourite IDE yet builds happen on the cloud.

Perhaps to start with we have go, maven and node helm chart, install these and use the existing `jx rsh` to exec into the pod?

This is a sample golang dev deployment yaml that also mounts the docker socket, we'd probably wanna use skaffold instead mind.
```
apiVersion: extensions/v1beta1
kind: Deployment
  name: go
spec:
  replicas: 1
  selector:
    matchLabels:
      run: go
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: go
    spec:
      containers:
      - command:
        - sleep
        - infinity
        image: jenkinsxio/builder-go:0.0.191
        imagePullPolicy: IfNotPresent
        name: go
        resources:
          limits:
            cpu: "2"
            memory: 2046Mi
          requests:
            cpu: 1500m
            memory: 1Gi
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-socket
      volumes:
      - hostPath:
          path: /var/run/docker.sock
        name: docker-socket
```
