### ISSUE TITLE
Setting up postsubmit pipeline on non-default context

### ISSUE THREAD

**Issue by axsaucedo** [jenkins-x/jx#7182]
We have a pipeline that is configured to only execute on branches of the form "v*" which we are using to trigger releases. However we would like this pipeline to use a different context, and pick up the actual jenkins x pipleine from a script other than the default `jenkins-x.yml` file in the top level directory. 

With pre-submits, when the context and name is changed, this allows for a pipeline specific file to be used, for example if we'd have a presubmit with the context `integration` then the respective file would be `jenkins-x-integration.yml`.

How can we configure a postsubmit to also use a custom jenkins-x file, is this supported at the moment, or does it have to always be that one?

Currently the post submit is configured as follows:
```
      SeldonIO/seldon-core:
      - agent: tekton
        branches:
        - master
        context: ""
        name: release
      - agent: tekton
        branches:
        - v*
        context: production
        name: production
```

What we want to achieve is that only the `jenkins-x.yml` file is triggered in the master branch, and only the `jenkins-x-production.yml` is triggered in the `v<version>` branches.
