### ISSUE TITLE
$ORG is not exposed when overriding postBuild Step in Jenkins X Pipeline

### ISSUE THREAD

**Issue by sharepointoscar** [jenkins-x/jx#7189]
### Summary 
I am trying to completely override the **postBuild** step and do some stuff with the image that was built prior to this step.

It appears the **$ORG** environment variable is not exposed like others such as **$DOCKER_REGISTRY** and **$APP_NAME** and even **$PREVIEW_VERSION**
### Expected behavior
Simply override the pipeline step as follows:

```yaml
buildPack: javascript
pipelineConfig:
  env:
  - name: JENKINS_X_DOCKER_REGISTRY_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        key: docker.registry
        name: jenkins-x-docker-registry
  - name: JENKINS_X_DOCKER_REGISTRY_SERVICE_PORT
    value: "80"
  pipelines:
    pullRequest:
      postBuild:
        replace: true
        steps:
        - command: echo ============================== start replacing postBuild ====================================
          name: anchore-starting-postbuild
        - command: echo ============================== $DOCKER_REGISTRY/$ORG/$APP_NAME:$PREVIEW_VERSION ==============================
          name: anchore-outpout-image-path
        - command: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:$PREVIEW_VERSION
          dir: /workspace/source
          image: nodejs
          name: postbuild-post-build
        - command: echo ============================== start anchore image scan  ====================================
        - command: curl -s https://ci-tools.anchore.io/inline_scan-v0.6.0 | bash -s -- -r -p $DOCKER_REGISTRY/$ORG/$APP_NAME:$PREVIEW_VERSION
          name: anchore-image-scan
        - command: echo ============================== end anchore image scan ====================================
          name: anchore-end-postbuild  
```
### Actual behavior
The image path is incorrect, as it does not include the value of $ORG which in this case, would be the Google Project as part of the path.

```bash
Showing logs for build jenkins-oscar/skiapp/pr-20 #15 pr-build stage from-build-pack and container step-postbuild-anchore-image-scan
Pulling image -- gcr.io//skiapp:0.0.0-SNAPSHOT-PR-20-15
invalid reference format

WARNING - Please pull remote image, or build/tag all local images before attempting analysis again


	ERROR - no local docker images specified in script input: bash gcr.io//skiapp:0.0.0-SNAPSHOT-PR-20-15
```

## Pod Environment Variables available (based on me checking)
```yaml
   env:
    - name: HOME
      value: /builder/home
    - name: APP_NAME
      value: skiapp
    - name: BRANCH_NAME
      value: PR-20
    - name: BUILD_ID
    - name: BUILD_NUMBER
      value: "15"
    - name: JOB_NAME
      value: jenkins-oscar/skiapp/PR-20
    - name: JOB_SPEC
      value: '{"type":"presubmit","job":"pr-build","refs":{"org":"jenkins-oscar","repo":"skiapp","base_ref":"master","base_sha":"2f7d10fb451befa1e51a8a1714c248bda730deaa","pulls":[{"number":20,"author":"sharepointoscar","sha":"943b0ea6c03359dc67111b6abc5821382fe5e951"}]}}'
    - name: JOB_TYPE
      value: presubmit
    - name: PIPELINE_CONTEXT
      value: pr-build
    - name: PIPELINE_KIND
      value: pullrequest
    - name: PROW_JOB_ID
    - name: PULL_BASE_REF
      value: master
    - name: PULL_BASE_SHA
      value: 2f7d10fb451befa1e51a8a1714c248bda730deaa
    - name: PULL_NUMBER
      value: "20"
    - name: PULL_PULL_SHA
      value: 943b0ea6c03359dc67111b6abc5821382fe5e951
    - name: PULL_REFS
      value: master:2f7d10fb451befa1e51a8a1714c248bda730deaa,20:943b0ea6c03359dc67111b6abc5821382fe5e951
    - name: REPO_NAME
      value: skiapp
    - name: REPO_OWNER
      value: jenkins-oscar
    - name: SOURCE_URL
      value: https://github.com/jenkins-oscar/skiapp.git
```
### Jx version

The output of `jx version` is:

```
➜ jx version
NAME               VERSION
jx                 2.0.1245+cjxd.8
Kubernetes cluster v1.14.10-gke.27
kubectl            v1.15.0
helm client        2.14.3
git                2.21.0
Operating System   Mac OS X 10.14.6 build 18G3020
```

### Kubernetes cluster

I am running GKE.
