### ISSUE TITLE
restrict the preview environment creation to pull-requests with github labels

### ISSUE THREAD

**Issue by bkempe** [jenkins-x/jx#7225]
### Summary 
Feature request:
It would be useful to have _manual_ creation of preview environments from pull requests, e.g. triggered via GitHub labels or ChatOps commands, i.e. without having to rely on the `jx` CLI.

### Current workaround

Reading GitHub label "preview"
```
  pipelines:
    overrides:
      - pipeline: pullRequest
        stage: promote
        name: jx-preview
        type: replace
        step:
          sh: |
            if jx step pr labels --pr ${PULL_NUMBER} | grep -q 'JX_PR_LABELS_PREVIEW'; then
              jx preview --app $APP_NAME --dir ../..
            fi
```

But this seems generally useful. Ideally, one could pass different PR labels to be used as enabled helm tags. Right now this would only work by creating a values.yaml with the tags before the above `jx preview` command.
