### ISSUE TITLE
jx boot fails

### ISSUE THREAD

**Issue by meyerandreas** [jenkins-x/jx#7239]
### Summary 

jx boot fails

### Actual behavior

```
Modified file /home/jenkins/jenkins-x-boot-config/systems/jx-auth/Chart.yaml to set the chart to version 1
lock cancelled because not running in tekton
Ignoring templates/jx-auth-configmap.yaml
No requirements file: /tmp/jx-helm-apply-979861903/jx-auth/requirements.yaml so not checking for missing versions

STEP: install-jenkins-x command: /bin/sh -c jx step helm apply --boot --remote --name jenkins-x --provider-values-dir ../kubeProviders in dir: /home/jenkins/jenkins-x-boot-config/env

Modified file /home/jenkins/jenkins-x-boot-config/env/Chart.yaml to set the chart to version 1
lock cancelled because not running in tekton
error: generating values.yaml for tree from /tmp/jx-helm-apply-572582845/env: failed to execute Secrets template: /tmp/jx-helm-apply-572582845/env/jenkins-x-platform/values.tmpl.yaml: template: values.tmpl.yaml:9:92: executing "values.tmpl.yaml" at <hashPassword>: wrong type for value; expected string; got float64
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step helm apply --boot --remote --name jenkins-x --provider-values-dir ../kubeProviders' command in directory 'env', output: ''
```

### Jx version

The output of `jx version` is:

```
jenkins@jedoxnbKSDsLjkE:~$ jx version
WARNING: Failed to find helm installs: running helm list --all --namespace jx: failed to run 'helm list --all --namespace jx' command in directory '', output: 'Error: could not find tiller'
NAME               VERSION
jx                 2.1.24
Kubernetes cluster v1.15.11
kubectl            v1.16.8
git                2.17.1
Operating System   Ubuntu 18.04.2 LTS
```

### Kubernetes cluster

aks kubernetes created by azure webgui 

[jx-requirements_yaml.txt](https://github.com/jenkins-x/jx/files/4687960/jx-requirements_yaml.txt)
[parameters_yaml.txt](https://github.com/jenkins-x/jx/files/4687961/parameters_yaml.txt)

**Comment by hferentschik** [comment]
Could you provide a bit more context? What type of cluster are you using and how do you create it? What is the error in `jx boot`?

**Comment by hferentschik** [comment]
for reference, the requirements file:

```yaml
autoUpdate:
  enabled: false
  schedule: ""
bootConfigURL: https://github.com/jenkins-x/jenkins-x-boot-config
cluster:
  clusterName: bmaks001
  devEnvApprovers:
  - erwinzeiter
  environmentGitOwner: erwinzeiter
  gitKind: github
  gitName: github
  gitServer: https://github.com
  namespace: jx
  provider: kubernetes
  registry: https://bmacr001.azurecr.io
environments:
- ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: ""
    tls:
      email: ""
      enabled: false
      production: false
  key: dev
  repository: environment-bmaks001-dev
- ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: ""
    tls:
      email: ""
      enabled: false
      production: false
  key: staging
  repository: environment-bmaks001-staging
- ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: ""
    tls:
      email: ""
      enabled: false
      production: false
  key: production
  repository: environment-bmaks001-production
gitops: true
ingress:
  domain: 51.138.14.166.nip.io
  externalDNS: false
  namespaceSubDomain: -jx.
  tls:
    email: ""
    enabled: false
    production: false
kaniko: true
repository: nexus
secretStorage: local
storage:
  backup:
    enabled: false
    url: ""
  logs:
    enabled: false
    url: ""
  reports:
    enabled: false
    url: ""
  repository:
    enabled: false
    url: ""
vault: {}
velero:
  schedule: ""
  ttl: ""
versionStream:
  ref: v1.0.473
  url: https://github.com/jenkins-x/jenkins-x-versions.git
webhook: lighthouse
```
