### ISSUE TITLE
`jx import` does not create `charts` directory

### ISSUE THREAD

**Issue by stepanselyuk** [jenkins-x/jx#7258]
### Summary 

I used `jx import` to import a GitHub repo (with Dockerfile already in the repo). 
Used command: 
```
jx import --url https://github.com/orgname/reponame --pack docker-helm
```
Well, I've run it a few times before I figured out the CICD user need to have admin rights on the repo. And I did not get what difference between `docker-helm` and `docker` pack - better to have some documentation regarding it.

The import process created files `OWNERS`, `OWNERS_ALIASES`, `jenkins-x.yml`, `skaffold.yaml`, but `charts` directory has not been added. In `skaffold.yaml` path contains `charts` mentioned:

```
deploy:
    helm:
      releases:
      - name: test-project-for-cicd
        chartPath: charts/test-project-for-cicd
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}'
          image.tag: '{{.DIGEST_HEX}}'

```

Is there a way to create the `charts` directory (by using some `jx` command)?

### Expected behavior

`charts` directory with default templates will be created among other files.

### Actual behavior

`charts` directory not created.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.1.45
Kubernetes cluster v1.15.11
kubectl            v1.13.2
helm client        2.12.2
git                2.25.1
Operating System   Ubuntu 20.04 LTS
```

### Kubernetes cluster

Ubuntu 20.04, Microk8s with enabled addons: `storage, rbac, dns, ingress`

### Operating system / Environment

Ubuntu 20.04
