### ISSUE TITLE
jx boot fails if storage specified as git repo in jx-requirements

### ISSUE THREAD

**Issue by stepanselyuk** [jenkins-x/jx#7262]
### Summary 

error: failed to ensure the bucket URL https://github.com/myorg/jx-vanessa-storage-logs.git is created: EnsureBucketIsCreated not implemented for LegacyBucketProvider
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step verify preinstall --provider-values-dir="kubeProviders"' command in directory '.', output: ''

According to this page `https://jenkins-x.io/commands/jx_edit_storage/` I can set storages after install, but I don't see it has an effect (repositories still empty, the user has admin rights on them, gh-pages branches created)

### Steps to reproduce the behavior

```
storage:
  backup:
    enabled: false
    url: ""
  logs:
    enabled: true
    url: https://github.com/myorg/jx-vanessa-storage-logs.git
  reports:
    enabled: false
    url: ""
  repository:
    enabled: false
    url: ""
```

### Expected behavior

It's working

### Actual behavior

It fails

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.1.45
Kubernetes cluster v1.15.11
kubectl            v1.13.2
helm client        2.12.2
git                2.25.1
Operating System   Ubuntu 20.04 LTS
```

### Kubernetes cluster

MicroK8s on Ubuntu 20.04

### Operating system / Environment

Ubuntu 20.04
