### ISSUE TITLE
 allow GetRequirementsConfigFromTeamSettings to be less restrictive validating settings

### ISSUE THREAD

**Issue by romainverduci** [jenkins-x/jx#7288]
### Summary 
In case there is a change in the team settings, we want some tolerance in the validation to not fail when there is a new field which does not impact existing ones for example.

This has been done in https://github.com/jenkins-x/jx/pull/7249 already so we just want to extand this behaviour in the GetRequirementsConfigFromTeamSettings method.

Concrete issue happening:
- There was a field added in the team settings in this PR: https://github.com/jenkins-x/jx/pull/7172
- It made import / quickstart failing because of:
```
error getting Requirements from TeamSettings to determine if in GitHub app mode: validation failuresi in requirements from team settings: (root): additional property buildPacks is not allowed
```
It looks like the validation failure comes from this method: https://github.com/jenkins-x/jx/blob/7ae7aac6e2af35b30cbe02193871f61d8169f835/pkg/config/install_requirements.go#L629

Adding a field in team settings should not fail this validation.

**Comment by hferentschik** [comment]
@romainverduci, can you provide the jx-requirements.yml as stored in the team settings? Which version of `jx` were you using at that stage?

**Comment by romainverduci** [comment]
Here is the jx-requirements.yml from the dev env repo:
```
autoUpdate:
  enabled: true
  schedule: 0 0 * * *
bootConfigURL: https://github.com/cloudbees/arcalos-boot-config.git
buildPacks:
  buildPackLibrary: {}
cluster:
  azure: {}
  chartRepository: http://bucketrepo/bucketrepo/charts/
  clusterName: elfperidot
  environmentGitOwner: core-platform-test-org
  environmentGitPublic: true
  externalDNSSAName: elfperidot-dn
  gitKind: github
  gitName: github
  gitPublic: true
  gitServer: https://github.com
  gke:
    projectNumber: "893173526554"
  kanikoSAName: elfperidot-ko
  namespace: jx
  project: cbjx-elfperidot
  provider: gke
  registry: gcr.io
  vaultName: elfperidot
  vaultSAName: elfperidot-vt
  zone: us-central1-c
environments:
- ingress:
    cloud_dns_secret_name: external-dns-gcp-sa
    domain: cbjx-elfperidot.play-jxaas.live
    domainIssuerURL: https://jx-tenant-service-jx.mgmt.play-jxaas.live
    externalDNS: true
    namespaceSubDomain: -jx.
    tls:
      email: jenkins-x@cloudbees.com
      enabled: true
      production: false
  key: dev
  repository: environment-elfperidot-dev
- ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: ""
    tls:
      email: ""
      enabled: false
      production: false
  key: staging
  repository: environment-elfperidot-staging
- ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: ""
    tls:
      email: ""
      enabled: false
      production: false
  key: production
  repository: environment-elfperidot-production
githubApp:
  enabled: true
  schedule: 0 0 * * *
  url: https://lighthouse-githubapp-jx.mgmt.play-jxaas.live
gitops: true
ingress:
  cloud_dns_secret_name: external-dns-gcp-sa
  domain: cbjx-elfperidot.play-jxaas.live
  domainIssuerURL: https://jx-tenant-service-jx.mgmt.play-jxaas.live
  externalDNS: true
  namespaceSubDomain: -jx.
  tls:
    email: jenkins-x@cloudbees.com
    enabled: true
    production: false
kaniko: true
repository: bucketrepo
secretStorage: vault
storage:
  backup:
    enabled: true
    url: gs://cbjx-elfperidot-backup
  logs:
    enabled: true
    url: gs://cbjx-elfperidot-lts
  reports:
    enabled: false
    url: ""
  repository:
    enabled: true
    url: gs://cbjx-elfperidot-repository
vault:
  aws: {}
  bucket: cbjx-elfperidot-vault
  key: elfperidot-52a3c7bf51e0-crypto-key
  keyring: elfperidot-52a3c7bf51e0-keyring
  name: elfperidot
  serviceAccount: elfperidot-vt
velero:
  namespace: velero
  schedule: ""
  serviceAccount: elfperidot-vo
  ttl: ""
versionStream:
  ref: v0.0.466
  url: https://github.com/cloudbees/arcalos-jenkins-x-versions.git
webhook: lighthouse
```

So there is a buildPack entry.
The version of jx used to create the quickstart is `v2.1.42` which does not contain the new field to validate so that's why the validation is failing.
