### ISSUE TITLE
Installation on kops-based cluster on AWS fails. Kops v1.9.0, RBAC enabled

### ISSUE THREAD

**Issue by kalbasit** [jenkins-x/jx#730]
When I run `jx install --provider=aws`, I get the following error:

```shell
$ jx install --provider=aws
Context "k8s-v1.us-west-1.k8s.example.com" modified.
Did not set exposeController Config Domain
? No existing ingress controller found in the kube-system namespace, shall we install one? Yes
Error: release jxing failed: namespaces "kube-system" is forbidden: User "system:serviceaccount:kube-system:default" cannot get namespaces in the namespace "kube-system"
Error: Command failed  helm install --name jxing stable/nginx-ingress --namespace kube-system --set rbac.create=true
Error: release jxing failed: namespaces "kube-system" is forbidden: User "system:serviceaccount:kube-system:default" cannot get namespaces in the namespace "kube-system"
Error: Command failed  helm install --name jxing stable/nginx-ingress --namespace kube-system --set rbac.create=true
Error: release jxing failed: namespaces "kube-system" is forbidden: User "system:serviceaccount:kube-system:default" cannot get namespaces in the namespace "kube-system"
Error: Command failed  helm install --name jxing stable/nginx-ingress --namespace kube-system --set rbac.create=true
Error: release jxing failed: namespaces "kube-system" is forbidden: User "system:serviceaccount:kube-system:default" cannot get namespaces in the namespace "kube-system"
Error: Command failed  helm install --name jxing stable/nginx-ingress --namespace kube-system --set rbac.create=true
ingress init failed: deployments.extensions "jxing-nginx-ingress-controller" not found
error: deployments.extensions "jxing-nginx-ingress-controller" not found
```

There's a similar report in #483, @arun-gupta said it worked for him after enabling RBAC, but it is already enabled for me. Here's my cluster config:

```yaml
//
//   WARNING: Do not use a '--full' cluster specification to define a Kubernetes installation.
//   You may experience unexpected behavior and other bugs.  Use only the required elements
//   and any modifications that you require.
//
//   Use the following command to retrieve only the required elements:
//   $ kops get cluster -o yaml
//

apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-04-26T17:33:29Z
  name: k8s-v1.us-west-1.k8s.example.com
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  clusterDNSDomain: cluster.local
  configBase: s3://example-infra/kops-state/k8s-v1.us-west-1.k8s.example.com
  configStore: s3://example-infra/kops-state/k8s-v1.us-west-1.k8s.example.com
  dnsZone: ZYK887MVM9N63
  docker:
    bridge: ""
    ipMasq: false
    ipTables: false
    logDriver: json-file
    logLevel: warn
    logOpt:
    - max-size=10m
    - max-file=5
    storage: overlay,aufs
    version: 17.03.2
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-west-1a
      name: a
    image: gcr.io/google_containers/etcd:2.2.1
    name: main
    version: 2.2.1
  - etcdMembers:
    - instanceGroup: master-us-west-1a
      name: a
    image: gcr.io/google_containers/etcd:2.2.1
    name: events
    version: 2.2.1
  hooks:
  - manifest: |
      Type=oneshot
      ExecStart=/usr/bin/docker run --net host quay.io/sergioballesteros/check-aws-tags
      ExecStartPost=/bin/systemctl restart kubelet.service
    name: ensure-aws-tags.service
    requires:
    - docker.service
    roles:
    - Node
  iam:
    allowContainerRegistry: true
    legacy: false
  keyStore: s3://example-infra/kops-state/k8s-v1.us-west-1.k8s.example.com/pki
  kubeAPIServer:
    address: 127.0.0.1
    admissionControl:
    - Initializers
    - NamespaceLifecycle
    - LimitRanger
    - ServiceAccount
    - PersistentVolumeLabel
    - DefaultStorageClass
    - DefaultTolerationSeconds
    - MutatingAdmissionWebhook
    - ValidatingAdmissionWebhook
    - NodeRestriction
    - ResourceQuota
    allowPrivileged: true
    anonymousAuth: false
    apiServerCount: 1
    authorizationMode: RBAC
    cloudProvider: aws
    etcdQuorumRead: false
    etcdServers:
    - http://127.0.0.1:4001
    etcdServersOverrides:
    - /events#http://127.0.0.1:4002
    image: gcr.io/google_containers/kube-apiserver:v1.9.3
    insecurePort: 8080
    kubeletPreferredAddressTypes:
    - InternalIP
    - Hostname
    - ExternalIP
    logLevel: 2
    requestheaderAllowedNames:
    - aggregator
    requestheaderExtraHeaderPrefixes:
    - X-Remote-Extra-
    requestheaderGroupHeaders:
    - X-Remote-Group
    requestheaderUsernameHeaders:
    - X-Remote-User
    securePort: 443
    serviceClusterIPRange: 100.64.0.0/13
    storageBackend: etcd2
  kubeControllerManager:
    allocateNodeCIDRs: true
    attachDetachReconcileSyncPeriod: 1m0s
    cloudProvider: aws
    clusterCIDR: 100.96.0.0/11
    clusterName: k8s-v1.us-west-1.k8s.example.com
    configureCloudRoutes: true
    image: gcr.io/google_containers/kube-controller-manager:v1.9.3
    leaderElection:
      leaderElect: true
    logLevel: 2
    useServiceAccountCredentials: true
  kubeDNS:
    cacheMaxConcurrent: 150
    cacheMaxSize: 1000
    domain: cluster.local
    replicas: 2
    serverIP: 100.64.0.10
  kubeProxy:
    clusterCIDR: 100.96.0.0/11
    cpuRequest: 100m
    hostnameOverride: '@aws'
    image: gcr.io/google_containers/kube-proxy:v1.9.3
    logLevel: 2
  kubeScheduler:
    image: gcr.io/google_containers/kube-scheduler:v1.9.3
    leaderElection:
      leaderElect: true
    logLevel: 2
  kubelet:
    allowPrivileged: true
    cgroupRoot: /
    cloudProvider: aws
    clusterDNS: 100.64.0.10
    clusterDomain: cluster.local
    enableDebuggingHandlers: true
    evictionHard: memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
    featureGates:
      ExperimentalCriticalPodAnnotation: "true"
    hostnameOverride: '@aws'
    kubeconfigPath: /var/lib/kubelet/kubeconfig
    logLevel: 2
    networkPluginMTU: 9001
    networkPluginName: kubenet
    nonMasqueradeCIDR: 100.64.0.0/10
    podInfraContainerImage: gcr.io/google_containers/pause-amd64:3.0
    podManifestPath: /etc/kubernetes/manifests
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.9.3
  masterInternalName: api.internal.k8s-v1.us-west-1.k8s.example.com
  masterKubelet:
    allowPrivileged: true
    cgroupRoot: /
    cloudProvider: aws
    clusterDNS: 100.64.0.10
    clusterDomain: cluster.local
    enableDebuggingHandlers: true
    evictionHard: memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
    featureGates:
      ExperimentalCriticalPodAnnotation: "true"
    hostnameOverride: '@aws'
    kubeconfigPath: /var/lib/kubelet/kubeconfig
    logLevel: 2
    networkPluginMTU: 9001
    networkPluginName: kubenet
    nonMasqueradeCIDR: 100.64.0.0/10
    podInfraContainerImage: gcr.io/google_containers/pause-amd64:3.0
    podManifestPath: /etc/kubernetes/manifests
    registerSchedulable: false
  masterPublicName: api.k8s-v1.us-west-1.k8s.example.com
  networkCIDR: 172.22.0.0/16
  networkID: vpc-cac35aad
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  secretStore: s3://example-infra/kops-state/k8s-v1.us-west-1.k8s.example.com/secrets
  serviceClusterIPRange: 100.64.0.0/13
  sshAccess:
  - 172.22.0.0/16
  subnets:
  - cidr: 172.22.32.0/19
    name: us-west-1a
    type: Public
    zone: us-west-1a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
```

**Comment by jstrachan** [comment]
it looks like your user doesn't have karma to query kube-system. I wonder if you could try a user account thats beefier roles on that cluster? e.g. `cluster-admin` maybe?

**Comment by kalbasit** [comment]
@jstrachan how can I do that?

**Comment by jstrachan** [comment]
ask whoever created the cluster to give you a user account with `cluster-admin` or grant you that role - or make your own cluster so you have enough karma

**Comment by kalbasit** [comment]
@jstrachan I'm the one who created the cluster and I only have one user, the `admin` user.

**Comment by kalbasit** [comment]
@jstrachan here's the KUBECONFIG that kops has created, when the cluster was created.

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: https://api.k8s-v1.us-west-1.k8s.example.com
  name: k8s-v1.us-west-1.k8s.example.com
contexts:
- context:
    cluster: k8s-v1.us-west-1.k8s.example.com
    user: k8s-v1.us-west-1.k8s.example.com
  name: k8s-v1.us-west-1.k8s.example.com
current-context: k8s-v1.us-west-1.k8s.example.com
kind: Config
preferences: {}
users:
- name: k8s-v1.us-west-1.k8s.example.com
  user:
    as-user-extra: {}
    client-certificate-data: ...
    client-key-data: ...
    password: ...
    username: admin
- name: k8s-v1.us-west-1.k8s.example.com-basic-auth
  user:
    as-user-extra: {}
    password: ...
    username: admin
```
