### ISSUE TITLE
JenkinsX Install using jx boot

### ISSUE THREAD

**Issue by 2020testuser** [jenkins-x/jx#7305]
Hi,
I've been trying to get JenkinsX installed in an on-prem Kubernetes cluster. I tried to modify the jx-requirements.yaml to get JenkinsX install successful. But, no luck so far.

If anyone got JenkinsX insalled successfully in on-prem Kubernetes, could you please share the install steps and jx-requirements.yaml (with sensitive info. replaced with dummy values)?
Thanks,

**Comment by havenqi** [comment]
Try this, jx successfully installed
```
autoUpdate:
  enabled: false
  schedule: ""
bootConfigURL: https://github.com/xxx/jenkins-x-boot-config
cluster:
  clusterName: tf-jx-evolving-x
  devEnvApprovers:
  - xxx
  environmentGitOwner: My-org
  gitKind: github
  gitName: github
  gitServer: https://github.com
  namespace: jx
  provider: eks
  region: us-east-1
  registry: .dkr.ecr.us-east-1.amazonaws.com
environments:
- ingress:
    domain: 0.0.0.0.nip.io
    externalDNS: false
    ignoreLoadBalancer: true
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  key: dev
  repository: environment-tf-jx-evolving-x-dev
- ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: ""
    tls:
      email: ""
      enabled: false
      production: false
  key: staging
  repository: environment-tf-jx-evolving-x-staging
- ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: ""
    tls:
      email: ""
      enabled: false
      production: false
  key: production
  repository: environment-tf-jx-evolving-x-production
gitops: true
ingress:
  domain: 0.0.0.0.nip.io
  externalDNS: false
  ignoreLoadBalancer: true
  namespaceSubDomain: -jx.
  tls:
    email: ""
    enabled: false
    production: false
kaniko: true
repository: nexus
secretStorage: vault
storage:
  backup:
    enabled: false
    url: ""
  logs:
    enabled: true
    url: s3://logs-tf-jx-evolving-x-x
  reports:
    enabled: true
    url: s3://reports-tf-jx-evolving-x-x
  repository:
    enabled: true
    url: s3://repository-tf-jx-evolving-x-x
terraform: true
vault:
  aws:
    dynamoDBRegion: us-east-1
    dynamoDBTable: vault-unseal-tf-jx-evolving-x-x
    kmsKeyId: 189bd97d-x-4873-8d82-x
    kmsRegion: us-east-1
    s3Bucket: vault-unseal-tf-jx-evolving-x-x
    s3Region: us-east-1
velero:
  schedule: ""
  ttl: ""
versionStream:
  ref: v1.0.492
  url: https://github.com/jenkins-x/jenkins-x-versions.git
webhook: lighthouse

```
