### ISSUE TITLE
regression: `jx step next-version --semantic-release` throwing error

### ISSUE THREAD

**Issue by haysclark** [jenkins-x/jx#7321]
### Summary 
Javascript builds error when using a custom `next-version` step that utilized the `--semantic-release` argument. Previous functionally supported the following custom step `sh: jx step next-version --semantic-release --filename package.json --tag`, which would modify 'package.json' using semantic release versioning.

### Steps to reproduce the behavior
- create a basic `javascript` project (I'm using React quick start)
- modify projects `jenkins-x.yaml` (see example below)
- commit work and watch Jenkins build

> jenkins-x.yaml example
```
buildPack: javascript
pipelineConfig:
  pipelines:
    release:
      setVersion:
        replace: true
        steps:
          - name: next-version
            sh: jx step next-version --semantic-release --filename package.json --tag
            comment: set the version number in package.json using semantic-release and create a new release tag
```

### Expected behavior
Build should not error and the following files are expected to be updated:
- `charts/PROJECT-NAME/Chart.yaml`
- `charts/PROJECT-NAME/values.yaml`
- 'package.json'

### Actual behavior
Build throws an error and fails.

> Build error output
```
Showing logs for build meta-mycompany-hopeful-ha-8d5qc-135 stage meta-pipeline and container step-create-tekton-crds
running command: ** step next-version --semantic-release --filename package.json --tag
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1c746b1]
goroutine 1 [running]:
github.com/Masterminds/semver.(*Version).String(0x0, 0x0, 0xc000765020)
	/workspace/go/pkg/mod/github.com/!masterminds/semver@v1.4.2/version.go:113 +0x51
github.com/jenkins-x/**/v2/pkg/cmd/step.(*StepNextVersionOptions).Run(0xc00004c850, 0x0, 0x0)
	/workspace/source/pkg/cmd/step/step_next_version.go:125 +0x238
github.com/jenkins-x/**/v2/pkg/cmd/step.NewCmdStepNextVersion.func1(0xc000655180, 0xc00026ca00, 0x0, 0x4)
	/workspace/source/pkg/cmd/step/step_next_version.go:91 +0x71
github.com/spf13/cobra.(*Command).execute(0xc000655180, 0xc00026c9c0, 0x4, 0x4, 0xc000655180, 0xc00026c9c0)
	/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xc000300000, 0xc00088d340, 0x51f4620, 0xc0000b4000)
	/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/jenkins-x/**/v2/cmd/**/app.Run(0x0, 0x0, 0x0, 0x3e8c880, 0xc00009c058)
	/workspace/source/cmd/**/app/**.go:19 +0x159
main.main()
	/workspace/source/cmd/**/**.go:11 +0x32
error: failed to set the version on release pipelines: failed to run '/bin/sh -c ** step next-version --semantic-release --filename package.json --tag' command in directory '/workspace/source', output: ''
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.1.62
Kubernetes cluster v1.15.9-gke.24
kubectl            v1.15.11-dispatcher
helm client        2.16.1
git                2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.13.6 build 17G13035
```

### Kubernetes cluster

GTK with `jx boot`

### Operating system / Environment

Mac OS X 10.13.6 build 17G13035
