### ISSUE TITLE
Custom Jenkins Servers and Kubernetes Version v1.17.1

### ISSUE THREAD

**Issue by jbyibm** [jenkins-x/jx#7346]
### Summary 

I'm trying to evaluate Jenkins X and Custom Jenkins under OpenShift 4.4.5 using CRC. I'm facing issues that I can resolve manually. But my main question is:

- What is the status of Custom Jenkins under Jenkins X it is something that will be maintained in the future ?

### Steps to reproduce the behavior

On OpenShift CRC version 4.4.5 Kubernetes Version v1.17.1 the adding  Custom Jenkins into   Jenkins X  failed.

### Expected behavior

No failure

### Actual behavior
`jx boot`:  

- I have a failure with the creation of the pod `jenkins-x-controllerbuild`.  I have to modify the deployment of `jenkins-x-controllerbuild`. This is an already know issue we need to add a volume.
````
...
            - name: XDG_CONFIG_HOME
              value: /home/jenkins
...

            - name: HOME
              value: /home/jenkins
          volumeMounts:
            - name: jenkinshome
              mountPath: /home/jenkins 
...
      schedulerName: default-scheduler
...

      volumes:
        - name: jenkinshome
          emptyDir: {}
````

`jx add app jenkins`:
- It does not support Kubernetes cluster v1.17.1. Here the failure. 
  >error: unable to recognize "/tmp/helm-template-workdir-702148675/jenkins-x/output/namespaces/jx/env/charts/jx-app-jenkins/charts/jenkins/templates/part0-jenkins-master-deployment.yaml": no matches for kind "Deployment" in version "apps/v1beta1"'

- I can bypass using recommendations here: https://github.com/jenkins-x/jx/issues/6957#issuecomment-635528161

Redo `jx add app jenkins`:
- The job `jenkins-x-jenkinstokenjob`just failed with this log.
   > error: creating Jenkins Auth configuration: mkdir /.jx: permission denied 
- I can bypass by replacing the image ` image: "jenkinsxio/jx:1.3.965"`in the  job `jenkins-x-jenkinstokenjob` by `image: 'gcr.io/jenkinsxio/builder-jx:2.1.65-696'`

Redo `jx add app jenkins`:
- The job `jenkins-x-jenkinstokenjob`just failed with this log.
   > DEBUG: Finding service url for jenkins-x in namespace jx
DEBUG: Couldn't find service url, attempting to look up via ingress
DEBUG: Unable to finding ingress for jenkins-x in namespace jx - err ingresses.extensions "jenkins-x" is forbidden: User "system:serviceaccount:jx:jenkins-x-jenkinstokenjob" cannot get resource "ingresses" in API group "extensions" in the namespace "jx"
error: creating Jenkins Auth configuration: unable to find external URL of service jenkins-x in namespace jx
- I can bypass by adding this in `part0-clusterrole.yaml`
```
- apiGroups:
  - ""
  - "extensions" <---------------
  resources:
  - namespaces
  - ingresses <----------------
  verbs:
  - get
  - list
  - watch

```

Redo `jx add app jenkins`:

- The job `jenkins-x-jenkinstokenjob`just failed with this log. 
  > DEBUG: Finding service url for jenkins-x in namespace jx
DEBUG: Couldn't find service url, attempting to look up via ingress
DEBUG: Unable to finding ingress for jenkins-x in namespace jx - err ingresses.extensions "jenkins-x" not found
error: creating Jenkins Auth configuration: unable to find external URL of service jenkins-x in namespace jx
- I can bypass by adding this Ingress
```
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  annotations:
    jenkins.io/chart: env
  name: jenkins-x
  namespace: jx
  labels:
    jenkins.io/chart-release: jenkins-x
    jenkins.io/namespace: jx
    jenkins.io/version: '1'
spec:
  rules:
    - host: jenkins-x-jx.apps-crc.testing
      http:
        paths:
          - backend:
              serviceName: jenkins-x
              servicePort: 8080
```

At this stage I can deal with my Custom Jenkins

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.1.67
Kubernetes cluster v1.17.1
kubectl            v1.13.2
helm client        2.12.2
git                2.25.0
Operating System   "Red Hat Enterprise Linux Workstation release 7.7 (Maipo)"

```

### Diagnostic information

The output of `jx diagnose --show=version` is:

```
Running in namespace: jx

Jenkins X Version:
NAME               VERSION
jx                 2.1.67
Kubernetes cluster v1.17.1
kubectl            v1.13.2
helm client        2.12.2
git                2.25.0
Operating System   "Red Hat Enterprise Linux Workstation release 7.7 (Maipo)"


verifying packages

Please visit https://jenkins-x.io/faq/issues/ for any known issues.

Finished printing diagnostic information.

```

### Kubernetes cluster
Kubernetes Version v1.17.1 on OpenShift CRC version 4.4.5

### Operating system / Environment
Operating System "Red Hat Enterprise Linux Workstation release 7.7 (Maipo)"
