### ISSUE TITLE
jx boot expects 40 char access token - gitlab generates 20char token 

### ISSUE THREAD

**Issue by ramanNarasimhan77** [jenkins-x/jx#7358]
### Summary 
Trying to setup jenkins-x using jx boot in a on-prem kubernetes cluster. Installation fails when I enter my api token as jx expects 40 char token

### Steps to reproduce the behavior
Generate an api token from gitlab. It is 20char long. Use it in jx boot 

#### jx-requirements.yml snippet 
```
cluster:
  clusterName: <myCluster>
  devEnvApprovers:
  - <myUserId>
  environmentGitOwner: <myUserId>
  gitKind: gitlab
  gitName: gitlab
  gitServer: https://gitlab.<enterprise-domain>.com
  namespace: jx
  provider: kubernetes
```

#### Error
```
? Pipeline bot Git token
X Sorry, your reply was invalid: value is too short. Min length is 40
```

### Expected behavior
jx accepts the api key

### Actual behavior
jx errors out as it expects 40 char token

### Jx version

The output of `jx version` is:

```
Version        2.1.69
Commit         db7c4e1
Build date     2020-06-16T12:57:09Z
Go version     1.13.8
Git tree state clean
```

### Diagnostic information

The output of `jx diagnose --show=version` is:

```
jx diagnose --show=version
Flag --show has been deprecated, use jx diagnose <object> instead. This will be removed on July 1, 2020
Running in namespace: jx
Version        2.1.69
Commit         db7c4e1
Build date     2020-06-16T12:57:09Z
Go version     1.13.8
Git tree state clean
NAME                          VERSION
Kubernetes cluster            v1.15.9
kubectl (installed in JX_BIN) v1.13.2
git                           2.24.1
Operating System              Mac OS X 10.15.5 build 19F101

Please visit https://jenkins-x.io/faq/issues/ for any known issues.

Finished printing diagnostic information.
```

### Kubernetes cluster
On-premise k8s cluster

### Operating system / Environment

macOS Catalina
