### ISSUE TITLE
PostgreSQL Helm Chart Fails in Promotion Pipeline

### ISSUE THREAD

**Issue by kbd4hire** [jenkins-x/jx#7396]
### Summary 
After adding the the Helm chart to `env/requirements.yml` of the dev environment. The PR promotion build passes, but after merging the PR, the pipeline fails with an error.

Issue created per discussion [here](https://kubernetes.slack.com/archives/C9MBGQJRH/p1593038096307600).
### Steps to reproduce the behavior
* Start in the dev environement git repository for the cluster
* Create a branch off of master
* Add the chart to `env/requiremnts.yml`
```
dependencies:
- name: jxboot-resources
  repository: http://chartmuseum.jenkins-x.io
- alias: tekton
  name: tekton
  repository: http://chartmuseum.jenkins-x.io
- alias: prow
  condition: prow.enabled
  name: prow
  repository: http://chartmuseum.jenkins-x.io
- alias: lighthouse
  condition: lighthouse.enabled
  name: lighthouse
  repository: http://chartmuseum.jenkins-x.io
- alias: bucketrepo
  condition: bucketrepo.enabled
  name: bucketrepo
  repository: http://chartmuseum.jenkins-x.io
- name: jenkins-x-platform
  repository: http://chartmuseum.jenkins-x.io
#- condition: chartmuseum.enabled
#  name: chartmuseum
#  repository: http://chartmuseum.jenkins-x.io
# *** NEW CHART***
- name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 8.10.7
```
* Commit, push, create PR
* Wait for promotion build to succeed
* Merge the PR to master
### Expected behavior
Default installation of PostgreSQL deployed in the jx namespace
### Actual behavior
The `master` promotion pipeline fails on step `step-install-jenkins-x` with an error:
```
error: unable to recognize "/tmp/helm-template-workdir-147749916/jenkins-x/output/namespaces/**/env/charts/postgresql/templates/part0-statefulset.yaml": no matches for kind "StatefulSet" in version "apps/v1beta2"'

Pipeline failed on stage 'release' : container 'step-install-jenkins-x'. The execution of the pipeline has stopped.
```
### Jx version

The output of `jx version` is:

```
Version        2.1.73
Commit         ae4e9ac
Build date     2020-06-18T13:56:36Z
Go version     1.13.8
Git tree state clean
```

### Diagnostic information

The output of `jx diagnose --show=version` is:

```
Flag --show has been deprecated, use jx diagnose <object> instead. This will be removed on July 1, 2020
Running in namespace: jx
Version        2.1.73
Commit         ae4e9ac
Build date     2020-06-18T13:56:36Z
Go version     1.13.8
Git tree state clean
NAME                          VERSION
Kubernetes cluster            v1.16.8-eks-e16311
kubectl (installed in JX_BIN) v1.16.8-eks-e16311
helm client                   2.12.2
git                           2.17.1
Operating System              Ubuntu 18.04.4 LTS

Please visit https://jenkins-x.io/faq/issues/ for any known issues.

Finished printing diagnostic information.
```

### Kubernetes cluster

AWS EKS cluster using JenkinsX Terraform module
### Operating system / Environment

Ubuntu Linux 18.04
