### ISSUE TITLE
jx create quickstart node-http fails in "Build Container Build"

### ISSUE THREAD

**Issue by fakoe** [jenkins-x/jx#7397]
### Summary 
When executing jx create quickstart -> node-http, the pipeline stops at "Build Container Build" and fails.
I'm using a local minikube kubernetes cluster with a non default docker registry set to https://index.docker.io/v1/

Now, before I get the "We don't support minikube anymore" answer again, please let me say this:
Jx boot ran without ANY problems (looking good). It setup the git repositories and everything.
I don't think that minikube is responsible for this error. Maybe the local installation vs the cloud and me using docker hub instead a default cloud registry, yes. BUT, when you recommend the default docker hub url to me, when I select yes on using a non default registry, then this should work, right?

I followed your recommendations on https://jenkins-x.io/docs/reference/components/docker-registry/#using-docker-hub and recreated the jenkins-docker-cfg, pointing to my .docker/config.json file after I logged into docker (Side note: I also used the same credentials, when I was asked by jx boot, so the config.json file hasn't changed). I re-ran the pipeline after recreating the cfg with the exact same outcome (see "Error" below).

As you can see below, my parameters.yaml, jx-requirements and my kubernetes/values.tmp.yaml are looking like you recommend them to look.

**Now, what I suspect:**
When you look at the Error, the push permission fails for "docker.io/lobster-jx/node-http:0.0.1" aswell as pull, since it claims, that I'm unauthorized.
My actual docker hub username is **lobsterjx** and NOT **lobster-jx** (that is my git user)
lobster-jx isn't my repositories' name either.

I tried multible ways to push a hello-world image to my docker account. 
All of them worked when I used **lobsterjx** and all of them failed when I used **lobster-jx**:

```
docker push docker.io/lobsterjx/hello-world
docker push lobsterjx/hello-world
docker push lobsterjx/my-repository:hello-world
```

So, I'm assuming, that my github username or my pipeline username is switched with my docker hub username somewhere along the pipeline, since all the docker pushes and pulls in the error-log are with **lobster-jx**

**Can you tell me how I can update my settings, so that the pipeline pushes as lobsterjx and not as lobster-jx?**

### Error

```
Showing logs for build lobster-jx/node-http/master #2 stage from-build-pack and container step-build-container-build
E0625 14:20:38.224511       9 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "docker.io/lobster-jx/node-http:0.0.1": POST https://index.docker.io/v2/lobster-jx/node-http/blobs/uploads/: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:lobster-jx/node-http Type:repository] map[Action:push Class: Name:lobster-jx/node-http Type:repository]]

Pipeline failed on stage 'from-build-pack' : container 'step-build-container-build'. The execution of the pipeline has stopped.
```

### Steps to reproduce the behavior

- Setup local kubernetes cluster on Ubuntu 18.04
- Fork and clone jenkins-x-boot
- run jx boot
- Non default docker registry: https://index.docker.io/v1/
- Enter docker user and password
- finish installation
- jx create quickstart -> node-http
- Enter git credentials, create API-token, ...
- jx get build logs

### Expected behavior

pipeline finishes 

### Actual behavior

pipeline fails and stopps.

### Settings in "jx-requirements.yaml"

```
cluster:
  clusterName: minikube
  devEnvApprovers:
  - lobster-jx
  environmentGitOwner: lobster-jx
  gitKind: github
  gitName: github
  gitServer: https://github.com
  namespace: jx
  provider: kubernetes
  registry: docker.io
```

### Settings in "env/parameters.yaml"

```
adminUser:
  password: local:minikube/adminUser:password
  username: xxx
docker:
  email: xxx@xxx.com
  password: local:minikube/docker:password
  url: https://index.docker.io/v1/
  username: lobsterjx
enableDocker: true
pipelineUser:
  email: xxx@xxx.com
  token: local:minikube/pipelineUser:token
  username: lobster-jx
prow:
  hmacToken: local:minikube/prow:hmacToken
```

### Settings in "kubeProviders/kubernetes/values.tmpl.yaml"

```
# Override configuration from https://github.com/jenkins-x/jenkins-x-platform/blob/master/jenkins-x-platform/values.yaml
jenkins-x-platform:
  PipelineSecrets:

{{- if eq .Parameters.enableDocker true }}
    DockerConfig: |-
      {
        "auths":{
          {{ .Parameters.docker.url | quote }}:
            {
              "auth": {{ printf "%s:%s" .Parameters.docker.username .Parameters.docker.password | b64enc | quote}},
              "email": {{ .Parameters.docker.email | quote}}
            }
        }
      }
{{- end}}
```
