### ISSUE TITLE
jxui can't set auth.type=none

### ISSUE THREAD

**Issue by gazal-k** [jenkins-x/jx#7401]
### Summary

Trying to set `auth.type=none` with `jxui` still references `jx-basic-auth` volume in `Deployment`

### Steps to reproduce the behavior

```sh
helm repo add jenkins-x https://storage.googleapis.com/chartmuseum.jenkins-x.io
helm upgrade --install jxui jenkins-x/jxui --set auth.type=none
```

### Expected behavior

jxui chart is installed.

### Actual behavior

If `Secret` `jx-basic-auth` is not present, jxui installaation fails
`Error: release jxui failed, and has been uninstalled due to atomic being set: timed out waiting for the condition`

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jxl                0.0.181
Kubernetes cluster v1.16.8-eks-e16311
kubectl            v1.18.4
helm client        3.2.3
git                2.26.2
Operating System   "Fedora release 32 (Thirty Two)"
```

### Diagnostic information

The output of `jx diagnose version` is:

```
Running in namespace: jx
ERROR: Unable to get the Jenkins X Version
error: Command failed 'jx version --no-version-check': FATAL: Your current helm version v3 is not supported. Please downgrade to helm v2. exit status 1
```

### Kubernetes cluster

AWS EKS 1.16 created using eksctl

### Kubectl version
The output of `kubectl version --client` is:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-18T17:02:08Z", GoVersion:"go1.13.12", Compiler:"gc", Platform:"linux/amd64"}

```

### Operating system / Environment

Operating System   "Fedora release 32 (Thirty Two)"

**Comment by gazal-k** [comment]
`templates/deployment.yaml` has:

```yaml
          {{- if eq (include "jxui.auth.type" .) "basic" }}
          volumeMounts:
          - name: jx-basic-auth
            mountPath: /etc/nginx/auth
            readOnly: true
          {{- end }}
      volumes:
      {{- if (include "jxui.auth.type" .) "basic" }}
      - name: jx-basic-auth
        secret:
          secretName: jx-basic-auth
          items:
          - key: auth
            path: htpasswd
      {{- end }}
```

I think, just adding `eq` in the condition for volume should do the trick
