### ISSUE TITLE
using --semantic-release to determine next version is unreliable

### ISSUE THREAD

**Issue by garethjevans** [jenkins-x/jx#7415]
### Summary 

Semantic release fails with latest JX.

```
Showing logs for build garethjevans-test-semantic-version-golang-http-master-3 stage meta-pipeline and container step-create-tekton-crds
running command: jx step next-version --semantic-release --tag
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1c749f1]
goroutine 1 [running]:
github.com/Masterminds/semver.(*Version).String(0x0, 0x0, 0xc00087a120)
	/workspace/go/pkg/mod/github.com/!masterminds/semver@v1.4.2/version.go:113 +0x51
github.com/jenkins-x/jx/v2/pkg/cmd/step.(*StepNextVersionOptions).Run(0xc0005d6a80, 0x0, 0x0)
	/workspace/source/pkg/cmd/step/step_next_version.go:125 +0x238
github.com/jenkins-x/jx/v2/pkg/cmd/step.NewCmdStepNextVersion.func1(0xc000770a00, 0xc00081d8e0, 0x0, 0x2)
	/workspace/source/pkg/cmd/step/step_next_version.go:91 +0x71
github.com/spf13/cobra.(*Command).execute(0xc000770a00, 0xc00081d8c0, 0x2, 0x2, 0xc000770a00, 0xc00081d8c0)
	/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xc000320f00, 0xc00058f640, 0x51f7dc0, 0xc0000d0000)
	/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/jenkins-x/**/v2/cmd/**/app.Run(0x0, 0x0, 0x0, 0x3e8ea40, 0xc0000b4058)
	/workspace/source/cmd/jx/app/jx.go:19 +0x159
main.main()
	/workspace/source/cmd/jx/jx.go:11 +0x32
error: failed to set the version on release pipelines: failed to run '/bin/sh -c jx step next-version --semantic-release --tag' command in directory '/workspace/source', output: ''
Pipeline failed on stage 'meta-pipeline' : container 'step-create-tekton-crds'. The execution of the pipeline has stopped.
```

Pipeline is configured with 

```
buildPack: go
pipelineConfig:
  pipelines:
    release:
      setVersion:
        replace: true
        steps:
          - name: next-version
            sh: jx step next-version --semantic-release --tag
            comment: set the version number using semantic-release and create a new release tag
```
