### ISSUE TITLE
external docker registry caching not enabled

### ISSUE THREAD

**Issue by patrickleet** [jenkins-x/jx#7423]
### Summary 

When using an external Docker registry, there is no caching of builds.

`jx step syntax effective` results in 

```
        - args:
            - --cache=true
            - --cache-dir=/workspace
            - --context=/workspace/source
            - --dockerfile=/workspace/source/Dockerfile
            - --destination=docker.io/pathnsf/nsf-pathway-app:${inputs.params.version}
            - --cache-repo=docker.io/todo/cache
            - --skip-tls-verify-registry=docker.io
            command: /kaniko/executor
            dir: /workspace/source
            image: gcr.io/kaniko-project/executor:v0.22.0
            name: build-container-build
```

Notice the cache repo is `- --cache-repo=docker.io/todo/cache`

When using GKE the result is

```
          - args:
            - --cache=true
            - --cache-dir=/workspace
            - --context=/workspace/source
            - --dockerfile=/workspace/source/Dockerfile
            - --destination=gcr.io/cldntventr/www:${inputs.params.version}
            - --cache-repo=gcr.io/cldntventr/cache
            command: /kaniko/executor
            dir: /workspace/source
            image: gcr.io/kaniko-project/executor:v0.22.0
            name: build-container-build
```

### Steps to reproduce the behavior

Configure jx to use external docker registry `docker.io` for Docker Hub 

### Expected behavior

Caching is used for builds

### Actual behavior

Organization name is "todo"

### Jx version

The output of `jx version` is:

```
Version        2.1.95
Commit         b486665
Build date     2020-07-02T10:28:34Z
Go version     1.13.8
Git tree state clean
```

### Diagnostic information

The output of `jx diagnose version` is:

```
Running in namespace: jx
Version        2.1.95
Commit         b486665
Build date     2020-07-02T10:28:34Z
Go version     1.13.8
Git tree state clean
NAME                          VERSION
Kubernetes cluster            v1.15.11-eks-af3caf
kubectl (installed in JX_BIN) v1.13.2
helm client                   2.12.2
git                           2.24.3 (Apple Git-128)
Operating System              Mac OS X 10.15.5 build 19F101

Please visit https://jenkins-x.io/faq/issues/ for any known issues.

Finished printing diagnostic information.
```

### Kubernetes cluster

JX Terraform EKS + jx boot

### Kubectl version
The output of `kubectl version --client` is:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}
```

### Operating system / Environment

MacOS
