### ISSUE TITLE
The containerOptions resources doesn't work for resource requests

### ISSUE THREAD

**Issue by axsaucedo** [jenkins-x/jx#7464]
### Summary 

When creating a pipeline with a stage that contains an options.containerOptions.resources.requests attribute with resources and requirements, when looking at the resulting pods, the `step-<pipeline-step-name>` pod spec, it only has the limits set, but the resources are all set to zero. This means that it's not possible to set resources and limits to pipelines. 

### Steps to reproduce the behavior

Create a pipeline with the format:
```
buildPack: none
pipelineConfig:
  pipelines:
    pullRequest:
      pipeline:
        agent:
          image: ...
        options:
          containerOptions:
            resources:
              requests:
                cpu: 6
                memory: 2000Mi
                ephimeral-storage: "4GI"
              limits:
                cpi: 6
                memory: 2000Mi
                ephimeral-storage: "4Gi"
...    
```

The resulting pod would have:
```
            resources:
              requests:
                cpu: 6
                memory: 2000Mi
                ephimeral-storage: "4GI"
              limits:
                cpi: "0"
                memory: "0"
                ephimeral-storage: "0"
```

### Expected behavior

For the resources to be set as per the containerOverride.

### Actual behavior

The resources are all set to zero for the pod that runs the job.

### Jx version

The output of `jx version` is:

```
Version        2.1.95
Commit         b486665
Build date     2020-07-02T10:28:34Z
Go version     1.13.8
Git tree state clean
```

### Diagnostic information

The output of `jx diagnose version` is:

```
Running in namespace: jx
Version        2.1.95
Commit         b486665
Build date     2020-07-02T10:28:34Z
Go version     1.13.8
Git tree state clean
NAME                          VERSION
Kubernetes cluster            v1.14.10-gke.36
kubectl (installed in JX_BIN) v1.16.6-beta.0
helm client                   2.12.2
git                           2.17.1
Operating System              Ubuntu 18.04.3 LTS

Please visit https://jenkins-x.io/faq/issues/ for any known issues.

Finished printing diagnostic information.
```

### Kubernetes cluster

Gcloud cluster 
```
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.36", GitCommit:"34a615f32e9a0c9e97cdb9f749adb392758349a6", GitTreeState:"clean", BuildDate:"2020-04-06T16:33:17Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

### Kubectl version
The output of `kubectl version --client` is:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:47:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

### Operating system / Environment

linux ubuntu 18.04

[Ref https://github.com/SeldonIO/seldon-core/issues/2175]
