### ISSUE TITLE
Pipeline retry is not fully supported

### ISSUE THREAD

**Issue by vbehar** [jenkins-x/jx#7469]
### Summary 

If you set the `retry` field on a pipeline's stage, in case of step failure Tekton will retry the step, and if the 2nd execution is successful, it will mark the taskrun as successful. But jx will keep the pipelineactivity in failed state.

### Steps to reproduce the behavior

in your pipeline:

```
stages:
- options:
  retry: 2
  steps: [...]
```

and have a step that will fail the first execution, but succeed the 2nd time

### Expected behavior

the failed step should be retried, and if successful, the pipeline's result should be a success

### Actual behavior

- the failed step is retried: tekton will create a new pod to re-run the whole stage/task, using the same taskrun
- when the 2nd execution is successful, the taskrun status is marked as successful:
```
status:
  completionTime: "2020-07-24T13:47:16Z"
  conditions:
  - lastTransitionTime: "2020-07-24T13:47:16Z"
    message: All Steps have completed executing
    reason: Succeeded
    status: "True"
    type: Succeeded
  podName: xyz-pr-16-lint-pzwrp-4-lint-txk52-pod-bdd564
  retriesStatus:
  - completionTime: "2020-07-24T13:45:20Z"
    conditions:
    - lastTransitionTime: "2020-07-24T13:45:20Z"
      message: '"step-golangci-lint" exited with code 4 (image: "docker-pullable://golangci/golangci-lint@sha256:cdf058c42d3f992b481495752b5e3c5d73bacfe1e19dd65489c6002bec53e78f");
        for logs run: kubectl -n jx logs xyz-pr-16-lint-pzwrp-4-lint-txk52-pod-e90b78
        -c step-golangci-lint'
      reason: Failed
      status: "False"
      type: Succeeded
```
- the pipelinerun is marked as successful too
```
status:
  completionTime: "2020-07-24T13:47:16Z"
  conditions:
  - lastTransitionTime: "2020-07-24T13:47:16Z"
    message: All Tasks have completed executing
    reason: Succeeded
    status: "True"
    type: Succeeded
```
- but the pipelineactivity is marked as failed:
```
spec:
  status: Failed
  steps:
  - kind: Stage
    stage:
      completedTimestamp: "2020-07-24T13:45:19Z"
      name: lint
      startedTimestamp: "2020-07-24T13:43:34Z"
      status: Failed
      steps:
      - completedTimestamp: "2020-07-24T13:45:19Z"
        name: Golangci Lint
        startedTimestamp: "2020-07-24T13:44:17Z"
        status: Failed
```

as you can see, it seems like the controllerbuild saw the result of the first execution, but didn't saw the result of the second.

the result is that the `retry` option is useless for the moment, because we need to manually rerun the whole pipeline in case of failure

### Jx version

The output of `jx version` is:

```
Version        2.1.78+cjxd.11
Commit         e9838a161
Build date     2020-06-23T02:02:04Z
Go version     1.13.8
Git tree state clean
```

### Diagnostic information

The output of `jx diagnose version` is:

```
Running in namespace: jx
Version        2.1.78+cjxd.11
Commit         e9838a161
Build date     2020-06-23T02:02:04Z
Go version     1.13.8
Git tree state clean
NAME                          VERSION
Kubernetes cluster            v1.15.11-gke.15
kubectl (installed in JX_BIN) v1.15.11
helm client                   2.14.3
git                           2.27.0
Operating System              Mac OS X 10.15.5 build 19F101
```

### Kubernetes cluster

GKE cluster

### Kubectl version
The output of `kubectl version --client` is:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:08:59Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"darwin/amd64"}
```
