### ISSUE TITLE
semver-aware auto-update configuration

### ISSUE THREAD

**Issue by vbehar** [jenkins-x/jx#7492]
With the announcement to stop releasing CJXD https://jenkins-x.io/blog/2020/07/29/cjxdtoupstreamjxtofuture/ users are left with the difficult question of "when to upgrade jx". With CJXD it was easy: every month.
But now there are releases every day, and all releases are "patch" releases - jx rarely has "feature" releases. So it requires a lot of time and effort to go through the releases notes, and take decisions on when to upgrade and when to skip versions. Unless you have a guy dedicated to JX management in your team - which is often not the case.

But if the JX releases were more "semver-compliant", with feature releases when there are new features, and keeping patch releases for fixes, it would help users decide when to upgrade.

And we could even go 1 step further, and make JX auto-update feature aware of this, for example by having multiple auto-update configurations. I'm thinking about something like (in the `jx-requirements.yaml`):

```
autoUpdates:
  patches:
    enabled: true
    autoMerge: true # or autoApply
    schedule: "..."
  minor:
    enabled: true
    autoMerge: false
    schedule: "..."
  major:
    enabled: true
    autoMerge: false
    schedule: "..."
```

this way we could have automatically applied patches (it would automatically merge these PRs), but keep the features on a manual-apply workflow.

anyway at least having more feature releases would already be very helpful!
