### ISSUE TITLE
Pipeline creation in jx fails with "failed to create Pull Request on the development environment git repository" error

### ISSUE THREAD

**Issue by reddybhavaniprasad** [jenkins-x/jx#7540]
### Summary
I am trying to create a pipeline for a repository in Jenkins-x using "jx import" command but it fails with an error "error: failed to create Pull Request on the development environment git repository"

### Steps to reproduce the behavior
Install Jenkins-x in openshift-3.11 and try to create a pipeline for a repository.

**jx-requirements.yaml:**
```
autoUpdate:
  enabled: false
  schedule: ""
bootConfigURL: https://github.com/jenkins-x/jenkins-x-boot-config.git
cluster:
  clusterName: cic-60
  devEnvApprovers:
  - automation
  environmentGitOwner: cic-60
  gitKind: bitbucketserver
  gitName: bs
  gitServer: http://rtx-swtl-git.fnc.net.local
  namespace: jx
  provider: openshift
  registry: docker-registry.default.svc:5000
environments:
- ingress:
    domain: 172.29.35.81.nip.io
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  key: dev
  repository: environment-cic-60-dev
- ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: ""
    tls:
      email: ""
      enabled: false
      production: false
  key: staging
  repository: environment-cic-60-staging
- ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: ""
    tls:
      email: ""
      enabled: false
      production: false
  key: production
  repository: environment-cic-60-production
gitops: true
ingress:
  domain: 172.29.35.81.nip.io
  externalDNS: false
  namespaceSubDomain: -jx.
  tls:
    email: ""
    enabled: false
    production: false
kaniko: true
repository: nexus
secretStorage: local
storage:
  backup:
    enabled: false
    url: ""
  logs:
    enabled: false
    url: ""
  reports:
    enabled: false
    url: ""
  repository:
    enabled: false
    url: ""
vault: {}
velero:
  schedule: ""
  ttl: ""
versionStream:
  ref: v1.0.562
  url: https://github.com/jenkins-x/jenkins-x-versions.git
webhook: lighthouse
```

### Expected behavior
Jenkins-x should create a pipeline for the repository.

### Actual behavior
It is failing with "error: failed to create Pull Request on the development environment git repository" error. 

Error log:
```
[centos@master ~]$ jx import --url http://rtx-swtl-git.fnc.net.local/scm/cic-60/user-interface.git --no-draft=True
? Do you wish to use automation as the Git user name: Yes
Cloned Git repository from http://automation:MzI1ODg1NjA1NTk4OqjiP9N3lr4iHt9L5rofdaWMqsgW@rtx-swtl-git.fnc.net.local/scm/cic-60/user-interface.git
? Would you like to define a different preview namespace? No
Pushed Git repository to http://automation:MzI1ODg1NjA1NTk4OqjiP9N3lr4iHt9L5rofdaWMqsgW@rtx-swtl-git.fnc.net.local/scm/cic-60/user-interface.git
WARNING: Already has a webhook registered for http://hook-jx.172.29.35.81.nip.io/hook
error: failed to create Pull Request on the development environment git repository http://rtx-swtl-git.fnc.net.local/scm/cic-60/environment-cic-60-dev.git: unable to create pull request: creating git provider for https://rtx-swtl-git.fnc.net.local/scm/cic-60/user-interface.git: no Git service resource found with URL 'https://rtx-swtl-git.fnc.net.local' in namespace jx
```

The repository for which jx is trying to create a pull request is proper "http://rtx-swtl-git.fnc.net.local/scm/cic-60/environment-cic-60-dev.git" but jx is failing to create a pull request for it.

Pods under jx namespace:
```
NAME                                           READY     STATUS             RESTARTS   AGE
jenkins-x-chartmuseum-5687695d57-pp994         1/1       Running            0          15h
jenkins-x-controllerbuild-78b4b56695-mg2vs     1/1       Running            0          15h
jenkins-x-controllerrole-765cf99bdb-swshp      1/1       Running            0          15h
jenkins-x-docker-registry-5bcd587565-rhd7q     1/1       Running            0          12h
jenkins-x-gcactivities-1598326200-zjwpj        0/1       Completed          0          53m
jenkins-x-gcactivities-1598328000-f95sr        0/1       Completed          0          23m
jenkins-x-gcpods-1598326200-k6zxg              0/1       Completed          0          53m
jenkins-x-gcpods-1598328000-dqsqn              0/1       Completed          0          23m
jenkins-x-gcpreviews-1598324400-mdp59          0/1       Completed          0          1h
jenkins-x-nexus-c7dcb47c7-fh7kx                1/1       Running            0          15h
lighthouse-foghorn-654c868bc8-d5w57            1/1       Running            0          15h
lighthouse-gc-jobs-1598324400-lh7v5            0/1       Completed          0          1h
lighthouse-gc-jobs-1598326200-dd8c9            0/1       Completed          0          53m
lighthouse-gc-jobs-1598328000-7wmf6            0/1       Completed          0          23m
lighthouse-jx-controller-6c9b8994bd-qt6tc      1/1       Running            0          15h
lighthouse-keeper-7c6fd9466f-gdjjt             1/1       Running            0          15h
lighthouse-webhooks-56668dc58b-4c52j           1/1       Running            0          15h
lighthouse-webhooks-56668dc58b-8dh27           1/1       Running            0          15h
tekton-pipelines-controller-76c8c8dd78-llj4c   1/1       Running            0          9h
tiller-7ddfd45c57-rwtt9                        1/1       Running            0          15h

```

### Jx version

The output of `jx version` is:

```
Version        2.1.127
Commit         4bc05a9
Build date     2020-08-05T20:34:57Z
Go version     1.13.8
Git tree state clean
```

### Diagnostic information

The output of `jx diagnose version` is:

```
Running in namespace: jx
Version        2.1.127
Commit         4bc05a9
Build date     2020-08-05T20:34:57Z
Go version     1.13.8
Git tree state clean
NAME                          VERSION
Kubernetes cluster            v1.11.0+d4cacc0
kubectl (installed in JX_BIN) v1.16.6-beta.0
helm client                   2.16.9
git                           2.24.1
Operating System              "CentOS Linux release 7.8.2003 (Core)"

Please visit https://jenkins-x.io/faq/issues/ for any known issues.

Finished printing diagnostic information.
```

### Kubernetes cluster

OPENSHIFT - 3.11

### Kubectl version
The output of `kubectl version --client` is:

```
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-10-15T09:45:30Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```

### Operating system / Environment
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
