### ISSUE TITLE
'jx boot' warning - no jx boot requirements file jx-requirements.yml found

### ISSUE THREAD

**Issue by gregberns** [jenkins-x/jx#7553]
### Summary

When I run `jx boot --requirements jx-requirements.yml` and a `jx-requirements.yml` file exists in the current directory I get a message: "No Jenkins X pipeline file jenkins-x.yml or no jx boot requirements file jx-requirements.yml found."

The `jx-requirements.yml` file was created from the `jenkins-x / terraform-azurerm-jx` project.

NOTE: This is my first time using JenkinsX. I think I've reviewed all the docs, but may be I missed something.

### Steps to reproduce the behavior

* Create the cluster with the  `jenkins-x / terraform-azurerm-jx` Terraform project
* Run `az aks get-credentials` with the output from `terraform output connect`
* Run `kubectl get nodes` to ensure connected

```bash
terraform output jx_requirements > ../new-dir/jx-requirements.yml
cd ../new-dir/jx-requirements.yml
ls
# see jx-requirements.yml exists
jx boot --requirements jx-requirements.yml
```

Contents of `jx-requirements.yml` (with several things redacted)

```
autoUpdate:
  enabled: false
  schedule: ""
cluster:
  clusterName: appdevwestus2
  devEnvApprovers:
  - <approver>
  environmentGitOwner: <owner>
  gitKind: github
  gitName: github
  gitServer: https://github.com
  namespace: jx
  provider: aks
  registry: devwestus2.azurecr.io
environments:
- ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: ""
    tls:
      email: ""
      enabled: false
      production: false
  key: dev
  repository: environment-<repo>-dev
- ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: ""
    tls:
      email: ""
      enabled: false
      production: false
  key: staging
  repository: environment-<repo>-staging
- ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: ""
    tls:
      email: ""
      enabled: false
      production: false
  key: production
  repository: environment-<repo>-production
gitops: true
ingress:
  domain: <domain>.
  externalDNS: false
  ignoreLoadBalancer: true
  namespaceSubDomain: -jx.
  tls:
    email: ""
    enabled: false
    production: true
kaniko: true
repository: nexus
secretStorage: vault
storage:
  backup:
    enabled: false
    url: ""
  logs:
    enabled: false
    url: ""
  reports:
    enabled: false
    url: ""
  repository:
    enabled: false
    url: ""
terraform: true
vault: {}
velero:
  schedule: ""
  ttl: ""
versionStream:
  ref: v1.0.571
  url: https://github.com/jenkins-x/jenkins-x-versions.git
webhook: lighthouse

```

### Expected behavior

This is my first time trying to set up JenkinsX - but I'd expect that `jx boot` would use my `jx-requirements.yml` file to create the local resources, but from the message it cannot find that file.

I would also hope that if a git repo is getting cloned that some how the `jx-requirements.yml` file I provided would be used - not the default one in the repo.

### Actual behavior

* A message is shown that the `jx-requirements.yml` doesn't exist in the current dirrectory (I also tried `./jx-requirements.yml`)
* A message is raised to create a git repo
* If you select 'Y', the repo is cloned to `jenkins-x-boot-config` and the `jx-requirements.yml` in the repo is used to bootstrap, which obviously fails.

```bash
$ ls
OWNERS              README.md           jx-requirements.yml
$ git init
Initialized empty Git repository in /Users/gb/github/issaonline/gitops-k8s-dev/.git/
$ jx boot --requirements jx-requirements.yml
Creating boot config with defaults, as not in an existing boot directory with a git repository.
No Jenkins X pipeline file jenkins-x.yml or no jx boot requirements file jx-requirements.yml found. You are not running this command from inside a Jenkins X Boot git clone
To continue we will clone https://github.com/jenkins-x/jenkins-x-boot-config.git @ master to jenkins-x-boot-config
? Do you want to clone the Jenkins X Boot Git repository? [? for help] (Y/n) 

Cloning https://github.com/jenkins-x/jenkins-x-boot-config.git @ master to jenkins-x-boot-config
Attempting to resolve version for boot config https://github.com/jenkins-x/jenkins-x-boot-config.git from https://github.com/jenkins-x/jenkins-x-versions.git
WARNING: when attempting to load team settings. the server could not find the requested resource (get environments.jenkins.io)
WARNING: It seems you're passing a requirements file to cluster which has already been provisioned.
WARNING: We recommend you update the jx-requirements.yml file at {  }, using the updates provided within your local jx-requirements.yml file.
error: loading from provided requirements file: attempting to boot cluster using a requirements file which is possibly stale
```

### Jx version

The output of `jx version` is:

```
Version        2.1.127
Commit         4bc05a9
Build date     2020-08-05T20:34:57Z
Go version     1.13.8
Git tree state clean
```

### Diagnostic information

The output of `jx diagnose version` is:

```
Running in namespace: default
WARNING: Failed to retrieve team settings: failed to setup the dev environment for namespace 'default': the server could not find the requested resource (post environments.jenkins.io) - falling back to default settings...
WARNING: Failed to find helm installs: running helm list --all --namespace default: failed to run 'helm list --all --namespace default' command in directory '', output: 'Error: could not find tiller'
Version        2.1.127
Commit         4bc05a9
Build date     2020-08-05T20:34:57Z
Go version     1.13.8
Git tree state clean
NAME                          VERSION
Kubernetes cluster            v1.15.11
kubectl (installed in JX_BIN) v1.16.6-beta.0
git                           2.28.0
Operating System              Mac OS X 10.15.6 build 19G73

Please visit https://jenkins-x.io/faq/issues/ for any known issues.

Finished printing diagnostic information.
```

### Kubernetes cluster

AKS + using the `jenkins-x / terraform-azurerm-jx` project.

### Kubectl version
The output of `kubectl version --client` is:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
```

### Operating system / Environment

MacOS 10.15.6
