### ISSUE TITLE
`jx step next-version` is not compatible with Helm 3

### ISSUE THREAD

**Issue by vbehar** [jenkins-x/jx#7564]
### Summary

When using the `jx step next-version` command with the `--filename` flag pointing to a Chart.yaml file, all the lines starting with `version` have their values replaced - which is an issue when using Helm 3, because the chart's dependencies are declared in the Chart.yaml file, resulting in all dependencies having the same version as the main chart.

### Steps to reproduce the behavior

- Uses an Helm3 Chart with the following Chart.yaml:

```
apiVersion: v2
name: test
version: 0.0.1-SNAPSHOT
dependencies:
- name: some-chart
  version: 2.0.0
  repository: https://repo.example.com/
```

- run `jx step next-version --dir=charts/${APP_NAME} --filename=Chart.yaml --tag`

### Expected behavior

Only the "main" `version` field should have changed - the dependency version should not

```
apiVersion: v2
name: test
version: 1.2.3
dependencies:
- name: some-chart
  version: 2.0.0
  repository: https://repo.example.com/
```

### Actual behavior

Both the "main" and the dependency `version` fields have changed

```
apiVersion: v2
name: test
version: 1.2.3
dependencies:
- name: some-chart
  version: 1.2.3
  repository: https://repo.example.com/
```
