### ISSUE TITLE
Failing on : jx step helm release 

### ISSUE THREAD

**Issue by hoaitang** [jenkins-x/jx#7597]
### Summary
We are having the jx cluster running fine, suddently, the "jx step helm release" start failing with error below:

error: failed to build dependencies for chart from directory '.': failed to add chart repositories: 
failed to add the Helm repository with URL 'https://storage.googleapis.com/chartmuseum.jenkins-x.io': 
failed to add the repository 'storage.googleapis.com' with URL 'https://storage.googleapis.com/chartmuseum.jenkins-x.io':
failed to run 'helm repo add storage.googleapis.com https://storage.googleapis.com/chartmuseum.jenkins-x.io' 
command in directory '.', output: 'Error: Couldn't load repositories file (/tekton/home/.helm/repository/repositories.yaml).

If you have any inside , please advice, 
Much appreciate

**Comment by PuckOut** [comment]
same here

**Comment by vilbert** [comment]
same here, any solution?

**Comment by pod2metra** [comment]
Same story.

**Comment by aure-olli** [comment]
Got the same problem.

The helm repo https://storage.googleapis.com/chartmuseum.jenkins-x.io is now dead, should now use https://charts.helm.sh/stable
This is the case in the lastest `helm`, but the `helm` used in Jenkins-X docker images is highly outdated.
```
docker run gcr.io/jenkinsxio/builder-go:2.1.150-769 helm version
> Client: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}

docker run gcr.io/jenkinsxio/builder-go:2.1.150-769 helm init --help | grep 'stable-repo-url'
>       --stable-repo-url string            URL for stable repository (default "https://kubernetes-charts.storage.googleapis.com")
```

There are 2 ways to fix that:
- the most obvious one is to update the helm2 version used in all the images
- can also set `jx` to force the repo https://charts.helm.sh/stable with the option `--stable-repo-url https://charts.helm.sh/stable` in `HelmCli.Init`: https://github.com/jenkins-x/jx/blob/master/pkg/helm/helm_cli.go#L148
```golang
args = append(args, "--stable-repo-url", "https://charts.helm.sh/stable")
```

In the meanwhile, I'll create my own docker images to make it work.

**Comment by aure-olli** [comment]
OK apparently the `helm` version of the image doesn't matter because it's downloaded again.
The version is hardcoded here: https://github.com/jenkins-x/jx/blob/master/pkg/packages/packages.go#L32
And yes, it means that helm made a critical change without backward compatibility in only one change ...

**Comment by pod2metra** [comment]
@aure-olli can you post a code snippet about new release or share more info about fix?

**Comment by aure-olli** [comment]
OK got it to work on my cluster

Build a new jx
```bash
git clone https://github.com/jenkins-x/jx
cd jx
nano +32 pkg/packages/packages.go # const Helm2Version = "2.17.0"
make build
cd ..
```
Download the last helm
```bash
wget https://get.helm.sh/helm-v2.17.0-linux-amd64.tar.gz
tar -xvzf helm-v2.17.0-linux-amd64.tar.gz
```
Create a new image
```bash
echo 'FROM gcr.io/jenkinsxio/builder-go:2.1.150-769
COPY linux-amd64/helm /home/jenkins/.jx/bin/helm
COPY linux-amd64/helm /usr/bin/helm
COPY jx/build/jx /usr/bin/jx' > Dockerfile
docker build . -t builder-go:helm-v2.17.0 $DOCKER_REPO/builder-go:helm-v2.17.0
docker push $DOCKER_REPO/builder-go:helm-v2.17.0
```
Then use that `$DOCKER_REPO/builder-go:helm-v2.17.0` image wherever you need it.

I don't know if all those steps are necessary, but at least they work.

**Comment by pod2metra** [comment]
All my attempts to make this action work on python or nodejs iamges are failed. 
`/bin/sh: /usr/bin/jx: cannot execute binary file` on `setup-jx-git-credentials` step

**Comment by pod2metra** [comment]
I found how to resolve that.

`make build` should be changed to `make linux` and `COPY jx/build/jx /usr/bin/jx` to `COPY jx/build/linux/jx /usr/bin/jx`

**Comment by pod2metra** [comment]
@aure-olli may be you know where possible to setup image for env building? I reset image value in configmap jenkins-x-pod-template-go but on env building step it still use old go image `gcr.io/jenkinsxio/builder-go:2.1.150-769`

**Comment by pod2metra** [comment]
I found solution. To set image for your env You should overwrite agent in each env repo jenkins-x.yaml. 
```
env:
- name: DEPLOY_NAMESPACE
  value: jx-staging
pipelineConfig:
  agent:
    image: <path to your image>
  env:
  - name: DEPLOY_NAMESPACE
    value: jx-staging
  pipelines: {}
```

**Comment by aure-olli** [comment]
Those are currently the fixes I had to perform (with `$DOCKER_REPO` being your docker repo, `gcr.io/my-project` on GCE):

__dev environment:__

In `jenkins-x.yaml`, replace every
```yaml
image: builder-go
```
by
```yaml
image: $DOCKER_REPO/builder-go:helm-v2.17.0
```

__Other environments:__

Add in `jenkins-x.yaml`
```yaml
pipelineConfig:
  agent:
    image: $DOCKER_REPO/builder-go:helm-v2.17.0
    label: jenkins-go
````
Make sure that `env/Chart.yaml` starts with
```yaml
apiVersion: v1
```

__For applications preview__

Add in `jenkins-x.yaml`
```yaml
pipelineConfig:
  pipelines:
    overrides:
    - pipeline: pullRequest
      stage: promote
      name: make-preview
      steps:
      - command: make preview
        dir: /workspace/source/charts/preview
        image: $DOCKER_REPO/builder-go:helm-v2.17.0
        name: make-preview
```

That's all I've detected right now, but may be more usage of helm to fix.
