### ISSUE TITLE
jx boot is not able to found eks cluster name

### ISSUE THREAD

**Issue by Guss4241** [jenkins-x/jx#7620]
### Summary 

jx boot is not able to found eks cluster name

### Steps to reproduce the behavior

configure kubectl to use your own cluster
install `jx` tool
launch `jx boot`
get the jx-boot repo

edit jx-requirement.yml to set provider to eks
launch jx boot again answer initial quesiton

### Expected behavior

get jx installed on the cluster

### Actual behavior

error during `jx boot` command

```
Enabling IRSA for cluster consoneoekscluster associating the IAM Open ID Connect provider
[ℹ]  eksctl version 0.37.0
[ℹ]  using region eu-west-1
Error: unable to fetch cluster status to determine operability: unable to describe cluster control plane: ResourceNotFoundException: No cluster found for name: consoneoekscluster.
{
  RespMetadata: {
    StatusCode: 404,
    RequestID: "6b4c44ee-b36e-422f-a86e-13c961b6664c"
  },
  Message_: "No cluster found for name: consoneoekscluster."
}
error: error enabling IRSA in cluster: there was a porblem enabling IRSA in the cluster: there was a problem calling eksctl with the provided args: failed to run 'eksctl utils associate-iam-oidc-provider --cluster consoneoekscluster --region eu-west-1 --approve' command in directory '', output: ''
```

### Jx version

The output of `jx version` is:

```
Version 2.1.155
```

sample of my kube config:
```
clusters:
- cluster:
    certificate-authority-data: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX>
    server: https://XXXXXXXXXXXXXXXXXXXX.gr7.eu-west-1.eks.amazonaws.com
  name: arn:aws:eks:eu-west-1:XXXXXXXXXXXXX:cluster/ConsoneoEksCluster
contexts:
- context:
    cluster: arn:aws:eks:eu-west-1:XXXXXXXXXXX:cluster/ConsoneoEksCluster
    namespace: jx
    user: arn:aws:eks:eu-west-1:XXXXXXXXXXX:cluster/ConsoneoEksCluster
  name: arn:aws:eks:eu-west-1:XXXXXXXXXXX:cluster/ConsoneoEksCluster
current-context: arn:aws:eks:eu-west-1:XXXXXXXXXX:cluster/ConsoneoEksCluster
kind: Config
preferences: {}
users:
- name: arn:aws:eks:eu-west-1:XXXXXXXXXXX:cluster/ConsoneoEksCluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - eu-west-1
      - eks
      - get-token
      - --cluster-name
      - ConsoneoEksCluster
      command: aws
      env: null
```

feel free to ask some questions if you need more infrmation.
