### ISSUE TITLE
jx3 multicluster: error with chartmuseum repository

### ISSUE THREAD

**Issue by dicolasi** [jenkins-x/jx#7623]
### Summary

Whenever I got a promotion from dev to stage and production, the repository `dev2` is added:

```
repositories:
- name: dev
  url: https://chartmuseum.dev.property.xyz
- name: dev2
  url: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
releases:
```

This would cause an error in stage and production environments since dev2 it is not reachable. 

### Steps to reproduce the behavior

3 clusters (eks-vault):
  - dev with jx3  related chart
  - stage with only git-operator
  - prod with only git operator

### Expected behavior

Dev2 it is not added, but dev would be used as default chart.

### Actual behavior

Dev2 is added causing the following to happen: 

```
- chart: dev2/data-outcode-stats-service
  version: 1.0.22
  name: data-outcode-stats-service
  values:
  - jx-values.yaml

```
Which will result in a error in jx-boot (repo unreachable).

### Jx version

The output of `jx version` is:

```
version: 3.1.251
```
