### ISSUE TITLE
Secret fails to be created in helmfile release.

### ISSUE THREAD

**Issue by Hmr-ramzi** [jenkins-x/jx#7661]
Hello,

I am currently using version 3.1.353. I am using jx with helmfile. The helmfile includes a release similar to the following:

```
repositories:
- name: incubator
  url: https://charts.helm.sh/incubator
- chart: incubator/raw
  name: ingress-secret
  values:
  - resources:
    - apiVersion: v1
      data:
        tls.crt: #base64-encrypted-value
        key.crt: #base64-encrypted-value
      kind: Secret
      metadata:
        name: credentials
      type: kubernetes.io/tls
```
I am using the git-jx-operator and the job gets completed. However, I see this error in the logs:
`
jx secret populate --source filesystem --secret-namespace jx-vault                                                                                                         Error: failed to populate secrets: failed to save properties key: tls.key properties: tls.key on ExternalSecret credentials: failed to create Secret credentials in namespace xxx: Secret "credentials" is invalid: data[tls.crt]: Required value`

What could possibly be the issue? Is this a bug?
