### ISSUE TITLE
Using {{ .Values.x.y }} from within a helmfile.yaml

### ISSUE THREAD

**Issue by Hmr-ramzi** [jenkins-x/jx#7666]
I am currently trying to import a values.yaml file (along with the autogenerated jx-values.yaml) and use directly in the helmfile:

For exampe:
```
custom-values.yaml 
secret:
  crt: #VALUE_BASE64
  key: #VALUE_BASE64
```

```
filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
    - custom-values.yaml
namespace: xxx
repositories:
- name: incubator
  url: https://charts.helm.sh/incubator
releases:
- chart: incubator/raw
  name: secret
  namespace: xxx
  values:
  - resources:
    - apiVersion: v1
      data:
        tls.crt: {{ .Values.secret.crt }}
        tls.key: {{ .Values.secret.key }}
      kind: Secret
      metadata:
        name: credential
        namespace: xxx
      type: kubernetes.io/tls
```
Unfortunately, somehow the custom-values.yaml somehow does not get recognised and I end up having templating error (map key not found). I tried the templating locally on my machine with the same command in the makefile.mk and the templating worked fine on the same helmfile version used on the boot job. Anyidea what might be the issue ?

**Comment by jstrachan** [comment]
this is something thats a little confusing with `helmfile` - the `environments` section's values yaml files are only used to render `values.yaml.gotmpl` files; they are not passed into helm.

So try add the `custom-values.yaml` into the `values:` section of your release:

```yaml
filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: xxx
repositories:
- name: incubator
  url: https://charts.helm.sh/incubator
releases:
- chart: incubator/raw
  name: secret
  namespace: xxx
  values:
  - custom-values.yaml
  - resources:
    - apiVersion: v1
      data:
        tls.crt: {{ .Values.secret.crt }}
        tls.key: {{ .Values.secret.key }}
      kind: Secret
      metadata:
        name: credential
        namespace: xxx
      type: kubernetes.io/tls
```

**Comment by Hmr-ramzi** [comment]
Thanks @jstrachan for your reply. The problem there if we use this approach our setup won't be environment dependent. Meaning that for example we use different values for our releases for different environments:

For example:

```
environments:
  default:
    values:
    - jx-values.yaml
  development:
    values:
    - jx-values.yaml
  staging:
    values:
    - jx-values.yaml
```

So this work around won't allow us to provide different values for different environments. Any other suggestion?
