### ISSUE TITLE
Cannot install jx operator in existing kubernetes cluster 

### ISSUE THREAD

**Issue by hichamov** [jenkins-x/jx#7679]
I'm working on deploying JX in an existing kubernetes cluster:

Env: All VMs are hosted in AWS

K8s: Created using Kubespray

Git Source: Bitbucket server hosted in a VM (AWS)

jx-requirements file:

```
apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: jxdemo
    gitKind: bitbucketserver
    gitName: bbc
    gitServer: "http://XXXXXXXXXXXX.compute.amazonaws.com:7990/scm/jxdem/jxdemo.git"
    provider: kubernetes
    registry: docker.io
  environments:
  - key: dev
  ingress:
    domain: "XXXXXXXXXXX.compute.amazonaws.com:30417"
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
```

Command:

jx admin operator --username XXXXXX --token XXXXXX

Expected result:

Operator deployed

Current result:

```
jx gitops git setup
generated Git credentials file: /workspace/xdg_config/git/credentials with username: XXX email:
jx gitops apply
found last commit message: new commit
make regen-phase-1
make[1]: Entering directory '/workspace/source'
jx gitops git setup
generated Git credentials file: /workspace/xdg_config/git/credentials with username: XXX email:
Already up to date.
jx gitops requirements merge
there is no ConfigMap terraform-jx-requirements in namespace default so no need to merge requirements
jx gitops requirements resolve -n
WARNING: no email in secret jx-boot in namespace jx-git-operator
modified the pipeline user in /workspace/source/jx-requirements.yml
no resolve logic for kubernetes provider kubernetes
jx gitops repository create
file does not exist: .jx/gitops/source-config.yaml so not defaulting any SourceConfig resources
jx gitops repository resolve --source-dir config-root/namespaces
jx gitops jenkins jobs
the source config file .jx/gitops/source-config.yaml does not exist
jx secret convert edit
Error: .jx/secret/mapping/secret-mappings.yaml file not found
Usage:
  jx-secret convert edit [flags]

Examples:
  # edits the local 'secret-mappings.yaml' file
  jx-secret secretsmapping edit --gcp-project-id foo --cluster-name

Flags:
      --dir string   base directory containing '.jx/secret/mapping/secret-mappings.yaml' file
  -h, --help         help for edit

make[1]: Leaving directory '/workspace/source'
make[1]: *** [versionStream/src/Makefile.mk:113: fetch] Error 1
error: failed to regenerate: failed to regenerate phase 1: failed to run 'make regen-phase-1' command in directory '.', output: ''
make: *** [versionStream/src/Makefile.mk:240: regen-check] Error 1
boot Job pod jx-boot-a1735000-46bb-45e5-8d20-bf7f0e90ff5b-wxtn5 has Failed

```
