### ISSUE TITLE
"jx admin operator" takes too long time ( It's been two days and it's not over yet )

### ISSUE THREAD

**Issue by dhkim0225** [jenkins-x/jx#7761]
I'm following https://jenkins-x.io/v3/admin/platforms/on-premise/#getting-started

"jx admin operator" takes too long time.  
It's been two days and it's not over yet.  
Please let me know any guessing cause.

#### ENVIRONMENT
```
[irteamsu@cgpudev-ocr006.cvision jx_gitops_test2]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.12", GitCommit:"7cd5e9086de8ae25d6a1514d0c87bac67ca4a481", GitTreeState:"clean", BuildDate:"2020-11-12T09:11:15Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

```
[irteamsu@cgpudev-ocr006.cvision jx_gitops_test2]$ sudo jx version
version: 3.1.353
```

```
[irteamsu@cgpudev-ocr006.cvision jx_gitops_test2]$ kubectl get ns
NAME                   STATUS   AGE
argocd                 Active   151d
default                Active   152d
jx-git-operator        Active   2d17h
kube-node-lease        Active   152d
kube-public            Active   152d
kube-system            Active   152d
kubernetes-dashboard   Active   151d
```

```
[irteamsu@cgpudev-ocr006.cvision jx_gitops_test2]$ cat jx-requirements.yml 
apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://oss.navercorp.com
    provider: kubernetes
    registry: ghcr.io
  environments:
  - key: dev
  - key: staging
  - key: production
  ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
```

#### RUNNING COMMAND
```
sudo jx admin operator --username dong-hyun --token $MYTOKEN
```
#### OUTPUT
```
git clone URL is https://oss.navercorp.com/dong-hyun/jx_gitops_test2.git
now verifying we have a valid git username and token so that we can clone the git repository inside kubernetes...
git username is dong-hyun for URL https://oss.navercorp.com/dong-hyun/jx_gitops_test2.git and we have a valid password
running command:

/root/.jx3/plugins/bin/helm-3.5.4 upgrade --install \
    --set url=https://oss.navercorp.com/dong-hyun/jx_gitops_test2.git \
    --set username=dong-hyun \
    --set password=**** --namespace jx-git-operator --create-namespace jxgo jx3/jx-git-operator

waiting for the Git Operator to be ready in namespace jx-git-operator...
pod jx-git-operator-546884d7c9-jjkbw has status Ready
the Git Operator is running in pod jx-git-operator-546884d7c9-jjkbw

waiting for boot Job pod with selector app=jx-boot in namespace jx-git-operator...
```
