### ISSUE TITLE
Lighthouse errors while installing JenkinsX3

### ISSUE THREAD

**Issue by nathanwong91** [jenkins-x/jx#7782]
I'm trying to install jx3 on an AWS EKS cluster but not via Terraform so I've been following the `on-prem` installation guide.
My template repo is 
```
https://github.com/jx3-gitops-repositories/jx3-kubernetes/
```
and this is my jx-requirements
```
apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
    clusterName: cluster-dev-1
    devEnvApprovers:
    - person
    environmentGitOwner: serviceaccount
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: kubernetes
    registry: ghcr.io
  environments:
  - key: dev
  - key: staging
  - key: production
  ingress:
    domain: "jx.domainthing"
    externalDNS: false
    namespaceSubDomain: -jx3.
    tls:
      email: ""
      enabled: false
      production: false
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
```
I've deployed the jx-git-operator via the helm chart 
The job pods seem to fail with the following error
```
jx gitops scheduler
error: failed to generate lighthouse configuration: No source repository resources were found
make[1]: Leaving directory '/workspace/source'
make[1]: *** [versionStream/src/Makefile.mk:100: gitops-scheduler] Error 1
error: failed to regenerate: failed to regenerate phase 1: failed to run 'make regen-phase-1' command in directory '.', output: ''
make: *** [versionStream/src/Makefile.mk:240: regen-check] Error 1
```
I've tried changing the `webhook` to jenkins/something other than lighthouse and tried changing `production` to true. All of which produce the same error message.
