### ISSUE TITLE
Connect docker sock from builder image

### ISSUE THREAD

**Issue by maiakhoa** [jenkins-x/jx#7951]
I would like to import Jenkinsfile project to JenkinsX 3, I created a new Jenkins server successful. But when I run docker build command from Jenkinsfile, it's throwing 

`Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

How can I set up to connect docker sock inside builder images.

Thanks!

**Comment by ankitm123** [comment]
Is this still an issue? I would recommend not to use docker socket, as you would have no upgrade path to kubernetes 1.22, which removed support for docker socket.
```
One thing to note: If you are relying on the underlying docker socket (/var/run/docker.sock) as part of a workflow within your cluster today, moving to a different runtime will break your ability to use it. This pattern is often called Docker in Docker. There are lots of options out there for this specific use case including things like kaniko, img, and buildah.
```
Source: https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/

IIRC, you were able to build and push images to ECR using kaniko, so I am going to close this issue.

If you still need access to docker socket, you can do this:

```
tasks:
    - name: XXX-pr
      resources: {}
      taskSpec:
        metadata: {}
        volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
            type: Socket
.....

```

and then in the step you need access to the docker daemon, you can volume mount is as follows:
```
volumeMounts:
          - name: docker-socket
            mountPath: /var/run/docker.sock
```
