### ISSUE TITLE
Indicate errors in configuration when importing a project

### ISSUE THREAD

**Issue by Shiti** [jenkins-x/jx#7970]
I had a typo in the `triggers.yaml` file. The name of the source for pullrequest file was incorrect. 
```yaml
apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  presubmits:
    - name: pr
      context: "pr"
      always_run: true
      optional: false
      source: "pull-request.yaml"  # This should have been pullrequest.yaml
```

I was able to import the project using the `jx import` command but the tests were not running on creating pull requests. It took sometime to figure out why. 

It will be helpful if the `jx import` command gave a warning or error message. One temporary solution I can think of is adding a note in docs to execute `jx pipeline lint` or something similar before doing import.
