### ISSUE TITLE
linting checks pass even if exported structs do not have any comments

### ISSUE THREAD

**Issue by ankitm123** [jenkins-x/jx#8037]
Not sure what the error is, but lint passes in the CI and locally even if exported structs dont have comments.
Most probably, it's an issue with the golangci yaml config we use.

Also we use revive instead of golint (which is deprecated), may be some setting in revive needs to be enabled?

If we check the goreport card, we can see the issues: https://goreportcard.com/report/github.com/jenkins-x/jx#golint

**Comment by sgmac** [comment]
@ankitm123 I'd like to work on this. /assign

**Comment by sgmac** [comment]
Hi @ankitm123  I've been looking into this for a while. I agree that `revive` and that's the way to go, however both `golint` and `revive` return and exit code 0 even with warnings. I think this should be implemented from the CI/CD pipeline. For instance in this branch:

```
 jx git:ISSUE-8037-fix-linting ● [^._.^]ﾉ彡ミ
$ revive  ./... | wc -l
18
```
It's true you can configure revive for **golanci-cli**


```yaml
linters-settings:
  revive:
      ignore-generated-header: false
      severity: warning
      confidence: 0
      rules:
        - name: exported
```

What would you suggest next?
