### ISSUE TITLE
gcjobs failin

### ISSUE THREAD

**Issue by TarekAS** [jenkins-x/jx#8062]
Hi,

I'm facing the following error on `jx-gcjobs`. The pods are terminating with the log:
```
error: jobs.batch is forbidden: User "system:serviceaccount:jx:jx-gcjobs" cannot list resource "jobs" in API group "batch" in the namespace "jx-git-operator"
```

This is on a newly created cluster (on EKS). Everything else is working as expected.

**Comment by ankitm123** [comment]
This is getting fixed here: https://github.com/jenkins-x-charts/jxboot-helmfile-resources/pull/412

**Comment by robertgartman** [comment]
Having the same issue blocking deploy of Jenkins X (jx v3.2.262) on GKE.

**Comment by nicolaerosia** [comment]
any update?

**Comment by mow20** [comment]
We're having the same issue. As a workaround, you can create another Role with the same permisssions in the jx-git-operator namespace, and the use a RoleBinding to the main gcjobs SA. (I'm attaching the new Role and binding we used to fix the issue)
[jx-gcjobs.zip](https://github.com/jenkins-x/jx/files/8580953/jx-gcjobs.zip)

**Comment by chrislovecnm** [comment]
@ankitm123 I am seeing that the jx-gcjobs-cronjob is running in the jx namespace and I think we want the job to run in the jx-git-operator namespace

```yaml
"jx-gcjobs-cronjob.yaml" 45L, 1256C                                                                                                                                                                                                                           32,17         All
# Source: jxboot-helmfile-resources/templates/jx-gcjobs-cronjob.yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: jx-gcjobs
  namespace: "jx"
  annotations:
    meta.helm.sh/release-name: 'jxboot-helmfile-resources'
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  schedule: "0/30 */3 * * *"
  startingDeadlineSeconds: 4000
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: gcjobs
            release: jxboot-helmfile-resources
        spec:
          restartPolicy: Never
          serviceAccountName: jx-gcjobs
          containers:
            - name: gcjobs
              command: [jx]
              args:
                - gitops
                - gc
                - jobs
                - --namespace
                - jx-git-operator
              imagePullPolicy: IfNotPresent
              image: "ghcr.io/jenkins-x/jx-boot:3.2.308"
              env:
                - name: JX_LOG_FORMAT
                  value: json
                - name: JX_LOG_LEVEL
                  value: info
                - name: PIPELINE_KIND
                  value: dummy
              resources: {}
```

The job, serviceaccount, role, and rolebinding are all being set to the `jx` namespace for some reason and not the default namespace, even-though we have:

https://github.com/jenkins-x-charts/jxboot-helmfile-resources/blob/966b5375ce94b631185f496db6bfa69476245c48/charts/jxboot-helmfile-resources/values.yaml#L133-L143
