### ISSUE TITLE
jx project quickstart is giving an error error: failed to validate options: failed to find the dev Environment: the server could not find the requested resource (get environments.jenkins.io)

### ISSUE THREAD

**Issue by outjoker** [jenkins-x/jx#8074]
I have used https://jenkins-x.io/v3/admin/platforms/eks/ 
to create an EKS cluster using terraform which is created succesfully (terraform is installed on my workstation) 

I have then installed jx from https://jenkins-x.io/v3/admin/setup/jx3/  (on my workstation where terraform is installed) 

jx version command gives the following output to me. 

`balasrinivas:~$ jx version
version: 3.2.253
balasrinivas:~$ 
`

upon running **jx project**

`balasrinivas:jx3-eks-vault$ jx project
? Which kind of project you want to create:  Create new application from a Quickstart
error: failed to validate options: failed to find the dev Environment: the server could not find the requested resource (get environments.jenkins.io)
balasrinivas:jx3-eks-vault$ 
`

**Comment by outjoker** [comment]
since the jx namespace was not automatically present, i  tried to create it from the octant UI manually and then i tried to get into it 

jx ns jx.

**Comment by outjoker** [comment]
following are the logs from jx git operator 

`balasrinivas:jx3-terraform-eks$ jx admin log
waiting for the Git Operator to be ready in namespace jx-git-operator...
pod jx-git-operator-7bc44fc4c-z8scb has status Running

WARNING: the git operator pod has failed but will restart
to view the log of the failed git operator pod run: kubectl logs -n jx-git-operator jx-git-operator-7bc44fc4c-z8scb


`balasrinivas:jx3-terraform-eks$ kubectl logs -n jx-git-operator jx-git-operator-7bc44fc4c-z8scb
no custom git initialisation scripts
using poll duration 20s
polling repository jx-boot in namespace jx-git-operator with git URL https://github.kyndryl.net/bavanapa/jx3-terraform-eks
cloning repository jx-boot to /tmp/jx-git-operator-182720635/jx-boot
repository jx-boot has latest commit sha 3594e1373152281cd2e9d3d49eefdc7d586f81fc
about to create a new job for name jx-boot and sha 3594e1373152281cd2e9d3d49eefdc7d586f81fc
ERROR: failed to poll repository jx-boot in namespace jx-git-operator: failed to launch job for jx-boot: repository jx-boot does not have a Job file: /tmp/jx-git-operator-182720635/jx-boot/.jx/git-operator/job.yaml
balasrinivas:jx3-terraform-eks$ `

**Comment by ankitm123** [comment]
Did u generate the cluster git repo from jx3-eks-vault?
Very weird that ur missing the job.yaml file, it's here: https://github.com/jx3-gitops-repositories/jx3-eks-vault/blob/main/versionStream/git-operator/job.yaml
Check: https://jenkins-x.io/v3/admin/platforms/eks/#eks--terraform--vaultasm--github

**Comment by outjoker** [comment]
Hi @ankitm123 thanks for responding.
yes i do see this file 
![image](https://user-images.githubusercontent.com/10362809/155137473-7d8993e3-b311-4c50-81fd-8d0124936538.png)

i have generated the repo based on the [jx3-gitops-repositories/jx3-eks-vault](https://github.com/jx3-gitops-repositories/jx3-eks-vault)

**Comment by ankitm123** [comment]
Can u past ur main.tf file? Did u provide the repo as an input to the module using `jx_git_url`?

**Comment by outjoker** [comment]
main.tf 

`provider "aws" {
  region  = var.region
  profile = var.profile
}

module "eks-jx" {
  source               = "github.com/jenkins-x/terraform-aws-eks-jx?ref=v1.18.9"
  cluster_version      = var.cluster_version
  cluster_name         = var.cluster_name
  region               = var.region
  vault_user           = var.vault_user
  is_jx2               = false
  jx_git_url           = var.jx_git_url
  jx_bot_username      = var.jx_bot_username
  jx_bot_token         = var.jx_bot_token
  force_destroy        = var.force_destroy
  nginx_chart_version  = var.nginx_chart_version
  install_kuberhealthy = var.install_kuberhealthy
}
`

but i have declared the variable in variables.tf and gave the default value over there which is in the same level as main.tf 

![image](https://user-images.githubusercontent.com/10362809/155138479-e4868118-9f65-46d2-be0b-ee4ca0a3bb05.png)

**Comment by ankitm123** [comment]
I see, it's because of the non-standard github server url imo. I assume ur using github enterprise.
Take a look here: https://jenkins-x.io/v3/admin/setup/config/git/#github-enterprise

Check ur jx-requirements.yml file in the cluster git repo (https://github.com/jx3-gitops-repositories/jx3-eks-vault/blob/main/jx-requirements.yml), and change the gitserver key to point to `https://github.kyndryl.net`. Once done, push a commit directly to master/main branch. Check this page on why you should push directly to master: https://jenkins-x.io/v3/admin/troubleshooting/install/ (basically to re-generate secrets as your first boot job failed)

**Comment by outjoker** [comment]
@ankitm123 thanks for pointing out the changes, i have committed them to master of jx3-eks-vault. Do i need to trigger something else now?

**Comment by ankitm123** [comment]
No, check the logs using `jx admin logs`. That should tell u if the job has failed/succeeded.

**Comment by outjoker** [comment]
these are the logs 

`balasrinivas:jx3-terraform-eks$ jx admin logs
waiting for the Git Operator to be ready in namespace jx-git-operator...
pod jx-git-operator-7bc44fc4c-z8scb has status Ready
the Git Operator is running in pod jx-git-operator-7bc44fc4c-z8scb

waiting for boot Job pod with selector app=jx-boot in namespace jx-git-operator...
`

**Comment by outjoker** [comment]
On the octant UI these are the snaps 
![image](https://user-images.githubusercontent.com/10362809/155141934-bc7fe7b3-b664-4ead-884a-0f1f75c3ca8a.png)
![image](https://user-images.githubusercontent.com/10362809/155141990-71555583-23af-40f7-a744-4626cd47d7a7.png)

**Comment by outjoker** [comment]
which means in the variable i shouldn't be passing the 
variable "jx_git_url" {
  description = "URL for the Jenins X cluster git repository"
  type        = string
  default     = "https://github.kyndryl.net/bavanapa/jx3-terraform-eks"
}

but https://github.kyndryl.net/bavanapa/jx3-eks-vault right?? 
i see i have to run terraform apply again, can you kindly let me know if  there is any other alternative to update jx_git_url configuration

**Comment by outjoker** [comment]
@ankitm123 thanks for pointing out. I am able to create the project using jx project quickstart from the CLI , however 
after the repo is created and synchronized back to the cluster , while viewing the pipeline activity for the new repo that got created , i see the following issue 

I have run 
`jx get build logs`

which failed at the end while promoting to stage, following are the logs 

`Showing logs for build bavanapa/golang-http/master #1 release stage from-build-pack and container step-check-registry
sourcing .jx/variables.sh
verifying the container registry is setup
WARNING: no $GIT_SECRET_MOUNT_PATH environment variable set
about to run: git clone https://github.kyndryl.net/bavanapa/jx3-eks-vault.git /tmp/jx-git-423624897 in dir /tmp
Cloning into '/tmp/jx-git-423624897'...
verifying that container registry 882410330966.dkr.ecr.us-east-1.amazonaws.com with organisation bavanapa and app name golang-http has an ECR associated with it
loading config with AWS region: 'us-east-1'
Let's ensure that we have an ECR repository for the image bavanapa/golang-http
Created ECR repository: 882410330966.dkr.ecr.us-east-1.amazonaws.com/bavanapa/golang-http
Put ECR repository lifecycle policy: {}

Showing logs for build bavanapa/golang-http/master #1 release stage from-build-pack and container step-build-container-build
Error: unknown command "ver=manual-kyndryl-manual-kyndryl" for "executor"
Run 'executor --help' for usage.

Pipeline failed on stage 'from-build-pack' : container 'step-build-container-build'. The execution of the pipeline has stopped.
balasrinivas:jx3-terraform-eks$`

can you kindly let me know if there could  be any issue as i am using gihub enterprise.

**Comment by outjoker** [comment]
@ankitm123 no i haven't touched/changed anything with respect to `step-build-container-build`  step 
can you kindly shed more light on this please?

**Comment by ankitm123** [comment]
Which quickstart are u using? Can you post ur pipeline files? (both the pullrequest and release yaml file)

**Comment by outjoker** [comment]
sure, actually i have used both nodejs-http and golang-http, and got the same issue for both but the current one is for golang-http though

release.yaml 

`apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/environment/release.yaml@versionStream
          name: ""
          resources:
            requests:
              cpu: 0.1
              memory: 128Mi
            limits:
              cpu: 400m
              memory: 256Mi
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
          name: ""
          resources: {}
        - name: admin-log
          resources: {}
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
`


pullrequest.yaml 

`apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/environment/pullrequest.yaml@versionStream
          name: ""
          resources:
            requests:
              cpu: 0.1
              memory: 128Mi
            limits:
              cpu: 400m
              memory: 512Mi
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-env-pr.yaml@versionStream
          resources: {}
        - name: make-pr
          resources: {}
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}`

**Comment by ankitm123** [comment]
can u format it, hard to read it like this ...

**Comment by outjoker** [comment]
sorry my bad @ankitm123 . done!

**Comment by ankitm123** [comment]
I dont think this is from the quickstart, this seems to be what u have in the cluster git repo: https://github.com/jenkins-x/jx3-pipeline-catalog/tree/master/tasks/environment.

When u did a quickstart, it should have created and pushed a new git repo, can u paste the pr and release pipelines for those? They would have files from the go task I believe: https://github.com/jenkins-x/jx3-pipeline-catalog/tree/master/tasks/go

**Comment by outjoker** [comment]
okay these are the corresponding files from the repo that got created. 
pullrequest.yaml

```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/go/pullrequest.yaml@versionStream
          name: ""
          resources:
            requests:
              cpu: 400m
              memory: 600Mi
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
          name: ""
          resources: {}
        - name: jx-variables
          resources: {}
        - name: build-make-linux
          resources: {}
        - name: check-registry
          resources: {}
        - name: build-container-build
          resources: {}
        - name: promote-jx-preview
          resources: {}
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
```

release.yaml 

```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/go/release.yaml@versionStream
          name: ""
          resources:
            requests:
              cpu: 400m
              memory: 600Mi
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
          name: ""
          resources: {}
        - name: next-version
          resources: {}
        - name: jx-variables
          resources: {}
        - name: build-make-build
          resources: {}
        - name: check-registry
          resources: {}
        - name: build-container-build
          resources: {}
        - name: promote-changelog
          resources: {}
        - name: promote-helm-release
          resources: {}
        - name: promote-jx-promote
          resources: {}
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
```
