### ISSUE TITLE
JX Slack integration is not working with nested repos (GitLab)

### ISSUE THREAD

**Issue by svilenvul** [jenkins-x/jx#8303]
Currently we don't see only the notifications in Slack. Can you tell us if you need to do smt additionally there to support Slack notifications for GitLab nested Projects?
We configured Slack with a token according to the guide https://jenkins-x.io/v3/develop/ui/slack/ and we still don't see any slack notifications.
JX Slack pod is showing in the logs that configuration is missing,

```

│ no slack configuration for our-company-our-group-protection-microservices-dp-ms-legalagreement-main-10                                                                                                     │
│ no slack configuration for our-company-our-group-protection-microservices-dp-ms-legalagreement-main-10                                                                                                     │
│ no slack configuration for our-company-our-group-protection-microservices-dp-ms-legalagreement-main-10                                                                                                     │
│ no slack configuration for our-company-our-group-protection-microservices-dp-ms-legalagreement-main-10                                                                                                     │
│ no slack configuration for our-company-our-group-protection-microservices-dp-ms-legalagreement-main-10                                                                                                     │
│ no slack configuration for our-company-our-group-protection-microservices-dp-ms-legalagreement-main-10                                                                                                     │
│ no slack configuration for our-company-our-group-protection-microservices-dp-ms-legalagreement-main-10                                                                                                     │
│ no slack configuration for our-company-our-group-protection-microservices-dp-ms-legalagreement-main-10                                                                                                     │
│ no slack configuration for our-company-our-group-protection-microservices-dp-ms-legalagreement-main-10                                                                                                     │
│ no slack configuration for our-company-our-group-protection-microservices-dp-ms-legalagreement-main-10                                                                                                     │
│ no slack configuration for our-company-our-group-protection-microservices-dp-ms-legalagreement-main-10                                                                                                     │
│ no slack configuration for our-company-our-group-protection-microservices-dp-ms-legalagreement-main-10                                                                                                     │
│ no slack configuration for our-company-our-group-protection-microservices-dp-ms-legalagreement-main-10 
```

We are using a default configuration in .jx/gitops/source-config.yaml

```
apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SourceConfig
metadata:
  creationTimestamp: null
spec:
  groups:
  - owner: our-group-cicd-platform
    provider: https://gitlab.our-group.com/
    providerKind: gitlab
    repositories:
    - name: java-project-example
    scheduler: in-repo
  - owner: our-company
    provider: https://gitlab.our-group.com/
    providerKind: gitlab
    repositories:
    - name: our-group-data-protection/microservices/dp-ms-legalagreement
    - name: our-group-mscr/library/our-group-mscr-library
    - name: our-group-mscr/template/our-group-mscr-charts
    - name: our-group-notification/microservices/tn-ms-phonenumber-verification
    - name: our-groupid/microservices/tiam-ms-profile
    scheduler: in-repo
  slack:
    channel: '#builds'
    kind: failureOrNextSuccess
    pipeline: all
```

PS tested with jx-slack version 0.1.3.

cc @ankitm123
