### ISSUE TITLE
JX cluster `verify` jobs failing with 404 when using GitHub pages for charts

### ISSUE THREAD

**Issue by haysclark** [jenkins-x/jx#8333]
### Summary

It appears that build times for GitHub pages have increased recently, which has exposed a race condition for folks using [GitHub pages for charts](https://jenkins-x.io/v3/develop/faq/config/registries/#how-do-i-switch-to-github-pages-for-charts).

### Steps to reproduce the behavior

Have a JX cluster setup to use [GitHub pages for charts](https://jenkins-x.io/v3/develop/faq/config/registries/#how-do-i-switch-to-github-pages-for-charts). Trigger a `release` in any project so that a new chart will be added to GitHub pages and a PR will be opened on the dev cluster repo. 

### Expected behavior

Ideally, the logic that handles deploying the chart would wait until the chart manager has finished deploying any content.

### Actual behavior

If it takes longer than ~1m 17s for GitHub to generate and deploy the GitHub page, the `verify` job will fail.

### Jx version
The output of jx version is:
```
version: 3.4.12
shaCommit: 845b21dd2c9ccadd3ac899ab7ad67bfbe0a87f1b
buildDate: Thu Aug 25 12:30:51 UTC 2022
goVersion: 1.17.9
branch: main
gitTreeState: clean
```

### kubectl version
The output of `kubectl version --short` is:
```
Client Version: v1.24.2
Kustomize Version: v4.5.4
Server Version: v1.22.11-gke.400
```

### Jenkins type
 Serverless Jenkins X Pipelines (Tekton + Prow)

### Kubernetes cluster
GKE

### Operating system / Environment
MacOS

**Comment by haysclark** [comment]
For the past 5 months, I've been getting around the issue by adding a `sleep 30` step to my cluster-repo's pull-request Pipeline. See the code below.

While this "fix" has been pretty effective, there have been sporadic PR failures when the GitHub page generation takes a tiny bit too long and the `verify` job fails because the Chart isn't available yet. Additionally, this workaround is rather lame because the `sleep 30` runs a second time when the _regeneration_ step runs.

## Workaround

> ⚠️ This is a hacky fix that is treating the symptom, not the root cause.

```yaml
# .lighthouse/jenkins-x/pullrequest.yaml 
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata: # kpt-merge: /pullrequest
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/environment/pullrequest.yaml@versionStream
          name: ""
          resources:
            # override limits for all containers here
            limits:
              cpu: 400m
              memory: 512Mi
          workingDir: /workspace/source
        steps:
        - image: odise/busybox-curl
          name: chart-repo-pause-for-30s
          resources: {}
          script: |
            #!/bin/sh
            echo
            echo "pausing for 30 seconds..."
            echo "(a work-around to give the GitHub charts pages time to re-build it's HTML content.)"
            sleep 30
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-env-pr.yaml@versionStream
          resources: {}
        - name: make-pr
          resources:
            # override requests for the pod here
            requests:
              cpu: 0.1
              memory: 128Mi
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
```
