### ISSUE TITLE
Cluster observability not exposing ingress with External DNS and TLS

### ISSUE THREAD

**Issue by gonzalochief** [jenkins-x/jx#8344]
I installed Jenkins X following the instructions and got a cluster running with the following configuration:
Kubernetes Version: 1.21
Cloud environment: AWS
Secret Manager: AWS SM
External DNS: using the native JX3 configuration
Cert-manager: Install the cert-manager using the regular manifest method as per the documentation from [cert-manager.io](https://cert-manager.io/docs/installation/kubectl/)

When installing the observability layer usin JX v3 documentation, i get the deployment up, but the External DNS service does not create the DNS annotations, nor setup the ELB for the ingress to expose grafana's web application; which makes the development incomplete, as it fails to provide the full capabilities offered by the observability system.
**Errors:**
1. The external DNS service does not create the grafana dns records for exposing grafana through the ingress, which gets created
2. Cert-manager does not set up tls configuration for grafana's ingress

The chart is configured under the jx-observability namespace with the following helmfile.yaml:
```
filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-observability
repositories:
- name: jxgh
  url: https://jenkins-x-charts.github.io/repo
- name: grafana
  url: https://grafana.github.io/helm-charts
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
releases:
- chart: jxgh/grafana-dashboard
  version: 0.2.2
  name: grafana-dashboard
  values:
  - ../../versionStream/charts/jxgh/grafana-dashboard/values.yaml.gotmpl
  - jx-values.yaml
- chart: grafana/loki
  version: 2.5.0
  name: loki
  values:
  - ../../versionStream/charts/grafana/loki/values.yaml
  - jx-values.yaml
- chart: grafana/promtail
  version: 3.5.0
  name: promtail
  values:
  - ../../versionStream/charts/grafana/promtail/values.yaml
  - jx-values.yaml
- chart: grafana/tempo
  version: 0.6.8
  name: tempo
  values:
  - ../../versionStream/charts/grafana/tempo/values.yaml
  - jx-values.yaml
- chart: grafana/grafana
  version: 6.17.4
  name: grafana
  values:
  - ../../versionStream/charts/grafana/grafana/values.yaml.gotmpl
  - jx-values.yaml
- chart: prometheus-community/prometheus
  version: 13.6.0
  name: prometheus
  values:
  - ../../versionStream/charts/prometheus-community/prometheus/values.yaml
  - jx-values.yaml
templates: {}
renderedvalues: {}
```
