### ISSUE TITLE
support pulling Jenkins X images from other than dockerhub

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#940]
```
jx install --docker-registry fooio
```
For folks that have issues pulling from dockerhub i.e. in China with the great firewall

When someone specifies this flag we could generate a new helm values.yaml that overrides every docker image registry.  I.e. something like this:

```
nexus:
  image:
    repository: fooio/nexus
chartmuseum
  image:
    repository: fooio/chartmuseum
jenkins:
  Agent:
    PodTemplates:
      Maven:
        Containers:
          Maven:
            Image: fooio/builder-maven:0.0.255
```
