### ISSUE TITLE
/home/jenkins/git/credentials file is empty 

### ISSUE THREAD

**Issue by bobclarke** [jenkins-x/jx#957]
Hello,
I appear to be having the same problem as issue 626 (https://github.com/jenkins-x/jx/issues/626) in that the make tag stop fails because git credentials are not available.

For me, it appears that the jx step git credentials step in my Jenkinsfile is producing a null output. 

By placing sh "cat /home/jenkins/git/credentials" in my Jenkins directly after the jx step git credentials step file I can see that this file is empty.

This being the case I wonder if you could tell me from where the jx step git credentials step derives the credential information. I thought it might be from ~/.jx/gitAuth.yaml however mine appears to be correct - I've pasted it below (without my token of course :) ) 

```
servers:
- url: https://github.com
  users:
  - username: bobclarke
    apitoken: my token goes here 
    bearertoken: ""
  name: GitHub
  kind: github
  currentuser: my username here 
defaultusername: my username here
currentserver: https://github.com
```

I understand that previously a secret was mounted (jenkins-git-credential into the ephemeral pod that gets created as part of the pipeline run) but this is no longer used.

I've updated accordingly and I'm on the latest version of jx client and server components.

Any help much appreciated

**Comment by jstrachan** [comment]
the `jx step git credentials` should be loading all the `Secret` resources in the current namespace which look like `jx-pipeline-git-*`. I wonder what the output of `kubectl get secret` looks like in your `jx` namespace?

e.g. my github secret looks like this:
```yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: jx-pipeline-git-github-github
  annotations:
    jenkins.io/credentials-description: API Token for acccessing https://github.com
      git service inside pipelines
    jenkins.io/name: GitHub
    jenkins.io/url: https://github.com
  labels:
    jenkins.io/created-by: jx
    jenkins.io/credentials-type: usernamePassword
    jenkins.io/kind: git
    jenkins.io/service-kind: github
  namespace: jx
data:
...
```
